In [1]:
!pip install librecommender

Requirement already satisfied: librecommender in d:\anaconda\lib\site-packages (1.5.1)
Requirement already satisfied: gensim>=4.0.0 in d:\anaconda\lib\site-packages (from librecommender) (4.3.3)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from librecommender) (4.66.4)
Requirement already satisfied: smart-open>=1.8.1 in d:\anaconda\lib\site-packages (from gensim>=4.0.0->librecommender) (7.0.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in d:\anaconda\lib\site-packages (from gensim>=4.0.0->librecommender) (1.10.1)
Requirement already satisfied: numpy<2.0,>=1.18.5 in d:\anaconda\lib\site-packages (from gensim>=4.0.0->librecommender) (1.24.3)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm->librecommender) (0.4.6)
Requirement already satisfied: wrapt in d:\anaconda\lib\site-packages (from smart-open>=1.8.1->gensim>=4.0.0->librecommender) (1.14.1)

In [1]:
import pandas as pd
from libreco.data import DatasetPure
from libreco.algorithms import TwoTower

WARNING:tensorflow:From D:\Anaconda\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [2]:
# train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_traindata_movielens.csv')
# val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_valdata_movielens.csv')
# test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_testdata_movielens.csv')
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_train_movielens.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_val_movielens.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_test_movielens.csv')
movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')
users = pd.read_csv('processed_dataset/MovieLens-1M/users/users_movielens.csv')

In [3]:
# Merge train_ratings with movies based on item_id
combined_data = pd.merge(train_ratings, movies, how='left', left_on='item_id', right_on='item_id')

# Merge the result with users based on user_id
combined_data = pd.merge(combined_data, users, how='left', on='user_id')

# Display the first few rows of the combined dataframe
combined_data.head()

,user_id,item_id,rating,timestamp,title,genres,year,gender,age,occupation,zip_code
0,1,3186,4,978300019,"Girl, Interrupted",Drama,1999,Female,Under 18,K-12 student,48067
1,1,1022,5,978300055,Cinderella,"Animation, Children's, Musical",1950,Female,Under 18,K-12 student,48067
2,1,1721,4,978300055,Titanic,"Drama, Romance",1997,Female,Under 18,K-12 student,48067
3,1,1270,5,978300055,Back to the Future,"Comedy, Sci-Fi",1985,Female,Under 18,K-12 student,48067
4,1,2340,3,978300103,Meet Joe Black,Romance,1998,Female,Under 18,K-12 student,48067

In [20]:
users

      user_id  gender          age              occupation zip_code
0           1  Female     Teenager            K-12 student    48067
1           2    Male        Elder           self-employed    70072
2           3    Male        Adult               scientist    55117
3           4    Male  Older Adult    executive/managerial    02460
4           5    Male        Adult                  writer    55455
...       ...     ...          ...                     ...      ...
6035     6036  Female        Adult               scientist    32603
6036     6037  Female  Older Adult       academic/educator    76006
6037     6038  Female        Elder       academic/educator    14706
6038     6039  Female  Older Adult  other or not specified    01060
6039     6040    Male        Adult      doctor/health care    11106

[6040 rows x 5 columns]

In [4]:
# items = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/books_data_with_new_id.csv')
# # movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens.csv')
#
# train_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/binarized/amazon_books_ratings_train_fixed_binarized.csv')
# val_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/binarized/amazon_books_ratings_val_fixed_binarized.csv')
# test_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/binarized/amazon_books_ratings_test_fixed_binarized.csv')
#
# # train_ratings = pd.read_csv('./processed_dataset/Amazon-Beauty/20 interactions/amazon_beauty_ratings_train.csv')
# # val_ratings = pd.read_csv('./processed_dataset/Amazon-Beauty/20 interactions/amazon_beauty_ratings_val.csv')
# # test_ratings = pd.read_csv('./processed_dataset/Amazon-Beauty/20 interactions/amazon_beauty_ratings_test.csv')
#
# # movies = pd.read_csv('./processed_dataset/Amazon-Beauty/amazon_beauty_reviews_meta_modified.csv')

In [13]:
train_ratings

        user_id  item_id  rating  timestamp
0             1     3186       4  978300019
1             1     1022       5  978300055
2             1     1721       4  978300055
3             1     1270       5  978300055
4             1     2340       3  978300103
...         ...      ...     ...        ...
797753     6040     2612       5  960971797
797754     6040     2303       5  960971857
797755     6040     3504       4  960971857
797756     6040     1449       3  960971857
797757     6040     3334       5  960971875

[797758 rows x 4 columns]

In [4]:
# Rename columns to match the expected format
combined_data.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
val_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
test_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)

# train_ratings.rename(columns={'user_id': 'user', 'parent_asin': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
# val_ratings.rename(columns={'user_id': 'user', 'parent_asin': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
# test_ratings.rename(columns={'user_id': 'user', 'parent_asin': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)

# Ensure the columns are in the correct order
# combined_data = combined_data[['user', 'item', 'label', 'time']]
val_ratings = val_ratings[['user', 'item', 'label', 'time']]
test_ratings = test_ratings[['user', 'item', 'label', 'time']]

In [5]:
train_data, data_info = DatasetPure.build_trainset(train_ratings)
eval_data = DatasetPure.build_evalset(val_ratings)
test_data = DatasetPure.build_testset(test_ratings)
print(data_info)  # n_users: 5894, n_items: 3253, data sparsity: 0.4172 %

ValueError: 'user', 'item' must be the first two columns of the data

In [18]:
train_ratings

        user  item  label       time
0          1  3186      4  978300019
1          1  1022      5  978300055
2          1  1721      4  978300055
3          1  1270      5  978300055
4          1  2340      3  978300103
...      ...   ...    ...        ...
797753  6040  2612      5  960971797
797754  6040  2303      5  960971857
797755  6040  3504      4  960971857
797756  6040  1449      3  960971857
797757  6040  3334      5  960971875

[797758 rows x 4 columns]

In [42]:
combined_data

,user,item,label,time,title,genres,year,gender,age,occupation,zip_code
0,1,3186,4,978300019,"Girl, Interrupted",Drama,1999,Female,Under 18,K-12 student,48067
1,1,1022,5,978300055,Cinderella,"Animation, Children's, Musical",1950,Female,Under 18,K-12 student,48067
2,1,1721,4,978300055,Titanic,"Drama, Romance",1997,Female,Under 18,K-12 student,48067
3,1,1270,5,978300055,Back to the Future,"Comedy, Sci-Fi",1985,Female,Under 18,K-12 student,48067
4,1,2340,3,978300103,Meet Joe Black,Romance,1998,Female,Under 18,K-12 student,48067
...,...,...,...,...,...,...,...,...,...,...,...
797753,6040,2612,5,960971797,Mildred Pierce,Drama,1945,Male,25-34,doctor/health care,11106
797754,6040,2303,5,960971857,Nashville,"Drama, Musical",1975,Male,25-34,doctor/health care,11106
797755,6040,3504,4,960971857,Network,"Comedy, Drama",1976,Male,25-34,doctor/health care,11106
797756,6040,1449,3,960971857,Waiting for Guffman,Comedy,1996,Male,25-34,doctor/health care,11106
797757,6040,3334,5,960971875,Key Largo,"Crime, Drama, Film-Noir, Thriller",1948,Male,25-34,doctor/health care,11106

In [6]:
from libreco.data import DatasetFeat

sparse_col = ["gender", "occupation", "genres"]
dense_col = ["age"]
user_col = ["gender", "occupation"]
item_col = ["genres"]
train_data, data_info = DatasetFeat.build_trainset(combined_data, user_col, item_col, sparse_col)

In [52]:
train_data

In [9]:
train_ratings

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
0,0,192634,2808945,B000NWR0W6,and ladies of the club,A3RTKL9KB8KLID,Stan Vernooy,1,854150400
1,1,192637,2144019,B000MVVYNO,Bethlehem Road,A3RTKL9KB8KLID,Stan Vernooy,1,862358400
2,2,195879,2520883,B000HEV3WS,"HERCULES, MY SHIPMATE",A3TEH90X39WC8F,"Stuart W. Mirsky ""swm""",1,863308800
3,3,195797,2196179,B0007E212E,"Hercules, My Shipmate",A3TEH90X39WC8F,"Stuart W. Mirsky ""swm""",1,863308800
4,4,238620,346828,B000KISQC6,"Guns, Germs, and Steel: The Fates of Human Soc...",AMGVCPHMT1DWE,Gregory N. Hullender,1,865468800
...,...,...,...,...,...,...,...,...,...
262291,262291,96431,1558301,1593355548,Wuthering Heights,A2DKTZMMG3JHN4,K. Burns,1,1362268800
262292,262292,96428,1343379,1569602093,Wuthering Heights.,A2DKTZMMG3JHN4,K. Burns,1,1362268800
262293,262293,96420,861842,1593355548,Wuthering Heights,A2DKTZMMG3JHN4,K. Burns,1,1362268800
262294,262294,103760,2616778,1844560333,Pride and Prejudice,A2GDT5QQSFZD14,Joy Hilda Handley,1,1362268800
262295,262295,103763,637896,8188280046,Pride & Prejudice (Classic Library),A2GDT5QQSFZD14,Joy Hilda Handley,1,1362268800

In [7]:
# from librecommender import TwoTowerModel

# Initialize the Two-Tower model with some default parameters
twoTower = TwoTower(
    "ranking",
    data_info,
    loss_type="softmax",
    embed_size=384,
    norm_embed=False,
    use_correction=True,
    temperature=0.1,
    # lr=0.00001,
    ssl_pattern=None,
    n_epochs=5# options: "rfm", "rfm-complementary", "cfm"
)
twoTower.fit(train_data, neg_sampling=True)

Training start time: 2024-09-07 13:09:32
WARNING:tensorflow:From D:\Anaconda\lib\site-packages\keras\layers\normalization\batch_normalization.py:562: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

D:\Anaconda\lib\site-packages\libreco\layers\dense.py:31: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  net = tf.layers.batch_normalization(net, training=is_training)
2024-09-07 13:09:32,301 - WARNING - From D:\Anaconda\lib\site-packages\keras\layers\normalization\batch_normalization.py:562: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
D:\Anaconda\lib\site-packages\libreco\layers\dense.py:34: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  net = tf_dense(units, reuse=reuse_layer, name=layer_name)(net)
D:\Anaconda\lib\site-packages\libreco\layers\dense.py:39: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  net = tf.layers.batch_normalization(net, training=is_training)

total params: 4,124,736 | embedding params: 3,853,888 | network params: 270,848

train: 100%|██████████| 3117/3117 [01:07<00:00, 45.94it/s]

Epoch 1 elapsed: 67.849s

train: 100%|██████████| 3117/3117 [01:07<00:00, 45.97it/s]

Epoch 2 elapsed: 67.807s

train: 100%|██████████| 3117/3117 [01:07<00:00, 46.04it/s]

Epoch 3 elapsed: 67.706s

train: 100%|██████████| 3117/3117 [01:07<00:00, 46.08it/s]

Epoch 4 elapsed: 67.640s

train: 100%|██████████| 3117/3117 [01:08<00:00, 45.80it/s]

Epoch 5 elapsed: 68.056s

In [10]:
train_ratings = train_ratings.sort_values(by='time')
val_ratings = val_ratings.sort_values(by='time')
test_ratings = test_ratings.sort_values(by='time')

In [11]:
test_ratings

                 user        item  label        time
0       AZUNT3QP2CWTL  B000G167FA      1          -1
1      A3VVDE8I22IAJA  B0006D9LII      1   868492800
2      A3AZ4O4I9S4668  B000NKUH32      1   869270400
3      A319KYEIAZ3SON  B000Q1RMUE      1   869702400
4      A3SOB0CMUBK6XJ  B0006BV6RY      1   871084800
...               ...         ...    ...         ...
36021   A67VT05EV5EOF  B0006D1ZKU      1  1362009600
36023   A67VT05EV5EOF  B000CPSU9G      1  1362009600
36025  A2GDT5QQSFZD14  1593355548      1  1362268800
36024  A2GDT5QQSFZD14  1844560333      1  1362268800
36026  A2GDT5QQSFZD14  014013168X      1  1362268800

[36027 rows x 4 columns]

In [15]:
unique_users = test_ratings['user'].unique()
print(len(unique_users))

6318

In [8]:
import numpy as np
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count

def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0

def evaluate_user_cf_model(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []
    iteration_counter = 0

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user_id'] == user]['item_id'].values

        # Get items the user has not seen
        # unseen_items = np.setdiff1d(all_items, seen_items)

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values

        y_score = [1 if item in test_items else 0 for item in recommended_items]
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)
        iteration_counter += 1

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))

    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
        'Recall@{}'.format(k): avg_recall,
        'MRR@{}'.format(k): avg_mrr,
    }

# all_items = movies['item_id'].unique()
all_items = movies['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model(twoTower, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(twoTower, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_15180\475019146.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.6484233919835904, 'Recall@5': 0.02629877032515778, 'MRR@5': 0.1159630242825607}
{'NDCG@10': 0.5306438707687063, 'Recall@10': 0.047738373445594444, 'MRR@10': 0.13133816882161253}

In [ ]:
lr def - emb 384 - norm emb {'NDCG@5': 0.6426314631194139, 'Recall@5': 0.027864656922610115, 'MRR@5': 0.11494205298013245}
lr -5 - emb 384 - norm emb {'NDCG@5': 0.6304724368014266, 'Recall@5': 0.022220923684936302, 'MRR@5': 0.10701158940397351}

In [17]:
def evaluate_user_cf_model(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user'] == user]['item'].values

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values
        labels = user_test_data['label'].values


        y_score = [
            user_test_data[user_test_data['item'] == item]['label'].values[0] if item in test_items else 0
            for item in recommended_items
        ]

        # y_score = [
        #     user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 2.5
        #     for item in recommended_items
        # ]

        ndcg = ndcg_at_k(y_score, k)
        # recall = recall_at_k(labels, k)

        ndcg_scores.append(ndcg)
        # recall_scores.append(recall)
        # print(user)
    # avg_ndcg = np.nanmean(ndcg_scores)
    # avg_recall = np.nanmean(recall_scores)
    avg_ndcg = np.nanmean(ndcg_scores)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))
    # avg_recall = np.mean(np.nan_to_num(recall_scores, nan=0.0))
    return {
        'NDCG@{}'.format(k): avg_ndcg,
        # 'Recall@{}'.format(k): avg_recall
    }

# all_items = movies['item_id'].unique()
all_items = items['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model(user_cf, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(user_cf, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_9344\611941998.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.726869975750975}
{'NDCG@10': 0.6625759494461073}

In [ ]:
{'NDCG@5': 0.7482504128365846}
{'NDCG@10': 0.6943043653737456}

In [20]:
import numpy as np
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def evaluate_user_cf_model2(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user_id'] == user]['item_id'].values

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values
        labels = user_test_data['label'].values


        # y_score = [
        #     user_test_data[user_test_data['item'] == item]['label'].values[0] if item in test_items else 0
        #     for item in recommended_items
        # ]

        y_score = [
            user_test_data[user_test_data['item'] == item]['label'].values[0] if item in test_items else 2.5
            for item in recommended_items
        ]

        ndcg = ndcg_at_k(y_score, k)
        # recall = recall_at_k(labels, k)

        ndcg_scores.append(ndcg)
        # recall_scores.append(recall)
        # print(user)
    # avg_ndcg = np.nanmean(ndcg_scores)
    # avg_recall = np.nanmean(recall_scores)
    avg_ndcg = np.nanmean(ndcg_scores)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))
    # avg_recall = np.mean(np.nan_to_num(recall_scores, nan=0.0))
    return {
        'NDCG@{}'.format(k): avg_ndcg,
        # 'Recall@{}'.format(k): avg_recall
    }

all_items = movies['item_id'].unique()
# all_items = items['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model2(model, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model2(model, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

{'NDCG@5': 0.9851303919961455}
{'NDCG@10': 0.9763072208531596}

In [ ]:
{'NDCG@5': 0.986232785657715}
{'NDCG@10': 0.9843870995527803}

In [22]:
def evaluate_user_cf_model2(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user_id'] == user]['item_id'].values

        # Get items the user has not seen
        # unseen_items = np.setdiff1d(all_items, seen_items)

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values
        # labels = user_test_data['label'].values


        # y_score = [1 if item in test_items else 0 for item in recommended_items]
        y_score = [
            1 if (item in test_items and user_test_data[user_test_data['item'] == item]['label'].values[0] == 1) else 0
            for item in recommended_items
        ]
        ndcg = ndcg_at_k(y_score, k)
        # recall = recall_at_k(labels, k)

        ndcg_scores.append(ndcg)
        # recall_scores.append(recall)
        # print(user)
    # avg_ndcg = np.nanmean(ndcg_scores)
    # avg_recall = np.nanmean(recall_scores)
    avg_ndcg = np.nanmean(ndcg_scores)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))
    # avg_recall = np.mean(np.nan_to_num(recall_scores, nan=0.0))
    return {
        'NDCG@{}'.format(k): avg_ndcg,
        # 'Recall@{}'.format(k): avg_recall
    }

all_items = movies['item_id'].unique()
# all_items = items['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model2(model, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model2(model, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_12276\2488232951.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.6114072368658541}
{'NDCG@10': 0.4761238955210694}