In [1]:
!pip install librecommender

Requirement already satisfied: librecommender in d:\anaconda\lib\site-packages (1.5.1)
Requirement already satisfied: gensim>=4.0.0 in d:\anaconda\lib\site-packages (from librecommender) (4.3.3)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from librecommender) (4.66.4)
Requirement already satisfied: smart-open>=1.8.1 in d:\anaconda\lib\site-packages (from gensim>=4.0.0->librecommender) (7.0.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in d:\anaconda\lib\site-packages (from gensim>=4.0.0->librecommender) (1.10.1)
Requirement already satisfied: numpy<2.0,>=1.18.5 in d:\anaconda\lib\site-packages (from gensim>=4.0.0->librecommender) (1.24.3)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm->librecommender) (0.4.6)
Requirement already satisfied: wrapt in d:\anaconda\lib\site-packages (from smart-open>=1.8.1->gensim>=4.0.0->librecommender) (1.14.1)

In [1]:
import pandas as pd
from libreco.data import DatasetPure
from libreco.algorithms import UserCF

WARNING:tensorflow:From D:\Anaconda\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

D:\Anaconda\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

In [2]:
# train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_traindata_movielens.csv')
# val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_valdata_movielens.csv')
# test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_testdata_movielens.csv')
# train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_train_movielens.csv')
# val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_val_movielens.csv')
# test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_test_movielens.csv')
# movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens.csv')

In [3]:
items = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/books_data_with_new_id.csv')
# movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens.csv')

train_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_train_filtered_fixed.csv')
val_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_val_filtered_fixed.csv')
test_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_test_filtered_fixed.csv')

# train_ratings = pd.read_csv('./processed_dataset/Amazon-Beauty/20 interactions/amazon_beauty_ratings_train.csv')
# val_ratings = pd.read_csv('./processed_dataset/Amazon-Beauty/20 interactions/amazon_beauty_ratings_val.csv')
# test_ratings = pd.read_csv('./processed_dataset/Amazon-Beauty/20 interactions/amazon_beauty_ratings_test.csv')

# movies = pd.read_csv('./processed_dataset/Amazon-Beauty/amazon_beauty_reviews_meta_modified.csv')

In [4]:
train_ratings

,Unnamed: 0.1,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
0,192634,2808945,B000NWR0W6,and ladies of the club,A3RTKL9KB8KLID,Stan Vernooy,5.0,854150400
1,192637,2144019,B000MVVYNO,Bethlehem Road,A3RTKL9KB8KLID,Stan Vernooy,4.0,862358400
2,195879,2520883,B000HEV3WS,"HERCULES, MY SHIPMATE",A3TEH90X39WC8F,"Stuart W. Mirsky ""swm""",5.0,863308800
3,195797,2196179,B0007E212E,"Hercules, My Shipmate",A3TEH90X39WC8F,"Stuart W. Mirsky ""swm""",5.0,863308800
4,238620,346828,B000KISQC6,"Guns, Germs, and Steel: The Fates of Human Soc...",AMGVCPHMT1DWE,Gregory N. Hullender,5.0,865468800
...,...,...,...,...,...,...,...,...
262291,96431,1558301,1593355548,Wuthering Heights,A2DKTZMMG3JHN4,K. Burns,4.0,1362268800
262292,96428,1343379,1569602093,Wuthering Heights.,A2DKTZMMG3JHN4,K. Burns,4.0,1362268800
262293,96420,861842,1593355548,Wuthering Heights,A2DKTZMMG3JHN4,K. Burns,4.0,1362268800
262294,103760,2616778,1844560333,Pride and Prejudice,A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800
262295,103763,637896,8188280046,Pride & Prejudice (Classic Library),A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800

In [5]:
# Rename columns to match the expected format
train_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
val_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
test_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)

# train_ratings.rename(columns={'user_id': 'user', 'parent_asin': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
# val_ratings.rename(columns={'user_id': 'user', 'parent_asin': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
# test_ratings.rename(columns={'user_id': 'user', 'parent_asin': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)

# Ensure the columns are in the correct order
train_ratings = train_ratings[['user', 'item', 'label', 'time']]
val_ratings = val_ratings[['user', 'item', 'label', 'time']]
test_ratings = test_ratings[['user', 'item', 'label', 'time']]

In [6]:
train_data, data_info = DatasetPure.build_trainset(train_ratings)
eval_data = DatasetPure.build_evalset(val_ratings)
test_data = DatasetPure.build_testset(test_ratings)
print(data_info)  # n_users: 5894, n_items: 3253, data sparsity: 0.4172 %

n_users: 6318, n_items: 45862, data density: 0.0905 %

In [7]:
train_ratings = train_ratings.sort_values(by='time')
val_ratings = val_ratings.sort_values(by='time')
test_ratings = test_ratings.sort_values(by='time')

In [8]:
test_ratings

                 user        item  label        time
0       AZUNT3QP2CWTL  B000G167FA    5.0          -1
1      A3VVDE8I22IAJA  B0006D9LII    5.0   868492800
2      A3AZ4O4I9S4668  B000NKUH32    4.0   869270400
3      A319KYEIAZ3SON  B000Q1RMUE    5.0   869702400
4      A3SOB0CMUBK6XJ  B0006BV6RY    5.0   871084800
...               ...         ...    ...         ...
36021   A67VT05EV5EOF  B0006D1ZKU    5.0  1362009600
36023   A67VT05EV5EOF  B000CPSU9G    5.0  1362009600
36025  A2GDT5QQSFZD14  1593355548    5.0  1362268800
36024  A2GDT5QQSFZD14  1844560333    5.0  1362268800
36026  A2GDT5QQSFZD14  014013168X    5.0  1362268800

[36027 rows x 4 columns]

In [9]:
user_cf = UserCF(task="ranking", data_info=data_info, k_sim=1, sim_type="cosine", mode='invert')

In [10]:
# Training the model
user_cf.fit(train_data, verbose=2, eval_data=eval_data, k=5, metrics=["loss", "roc_auc", "precision", "recall", "ndcg"], neg_sampling=True)

Training start time: 2024-08-23 04:12:10
Final block size and num: (6318, 1)
sim_matrix elapsed: 0.414s
sim_matrix, shape: (6318, 6318), num_elements: 4289274, density: 10.7454 %

top_k: 100%|██████████| 6318/6318 [00:00<00:00, 6748.20it/s]
eval_pointwise:  12%|█▎        | 1/8 [00:00<00:01,  6.64it/s]

Detect 353 unknown interaction(s), position: [2064, 7186, 7188, 1048, 30, 4134, 1066, 3116, 6190, 1074, 7218, 4150, 2110, 4160, 4162, 4164, 3142, 1096, 2122, 5200, 4088, 4188, 1120, 5216, 7264, 6244, 104, 3176, 106, 3180, 3182, 1140, 126, 1154, 7300, 6278, 7306, 140, 2188, 1164, 4242, 4246, 5278, 6306, 4262, 6310, 2216, 6312, 170, 5286, 3244, 3248, 180, 7350, 186, 7354, 188, 4284, 2238, 7360, 2244, 4292, 4294, 6340, 7372, 2256, 6352, 5332, 4314, 7386, 4318, 3294, 8186, 6372, 7396, 3304, 7400, 3310, 242, 6388, 5368, 5370, 4352, 262, 3342, 4370, 6418, 7444, 280, 5402, 3362, 7458, 3368, 304, 7472, 2354, 7480, 2362, 6460, 5438, 4416, 5442, 326, 1356, 6482, 4436, 344, 2392, 6490, 2398, 7520, 1388, 366, 7536, 3456, 4492, 2450, 2454, 408, 3480, 4506, 3482, 7578, 2462, 7582, 6562, 7588, 6566, 3494, 424, 426, 3498, 6572, 5546, 430, 7596, 2480, 3510, 2490, 2496, 7616, 6594, 5572, 7622, 4554, 5580, 462, 1488, 5584, 468, 6612, 470, 2520, 2522, 3546, 6626, 2532, 2534, 4582, 5608, 7658, 4590, 7670, 2556, 508, 3580, 2560, 7684, 6662, 4616, 526, 2576, 2578, 2580, 6680, 7708, 5662, 2594, 6690, 2596, 7718, 1576, 4650, 6698, 6700, 1580, 2606, 7728, 6718, 4676, 3656, 4682, 3658, 588, 4686, 3668, 6742, 3670, 5718, 4702, 3678, 4706, 5732, 6760, 6762, 2674, 4722, 628, 6770, 634, 2682, 5754, 7804, 1662, 6790, 3722, 5776, 2706, 1684, 6806, 1686, 4760, 670, 2720, 6818, 6820, 7844, 4774, 5798, 680, 7846, 7850, 2732, 7854, 6832, 3764, 6838, 7868, 7872, 6850, 5828, 1734, 3784, 2762, 720, 3796, 5844, 6876, 4830, 6878, 3806, 1760, 4834, 7914, 4844, 4852, 3840, 4866, 6914, 6918, 6920, 7944, 4878, 4884, 6934, 4890, 4892, 2850, 7972, 2856, 816, 6960, 7990, 4920, 4926, 5952, 834, 838, 842, 3916, 6990, 1876, 6998, 7000, 1882, 3932, 2910, 5990, 8038, 4968, 1896, 5994, 5996, 878, 1902, 8048, 882, 3956, 6004, 8052, 2938, 3962, 6012, 8060, 2942, 896, 3968, 4996, 3972, 6020, 6024, 1938, 6034, 5012, 7060, 8084, 1942, 3998, 7074, 8100, 1966, 946, 6072, 954, 956, 3004, 7104, 1984, 1986, 6084, 8132, 1992, 4040, 5068, 8140, 7122, 2002, 4050, 2012, 990, 6114, 8162, 3046, 7142, 6120, 3052, 4078, 8174, 7156, 4084, 6134, 7160, 3066]
No common interaction or similar neighbor for user 4585 and item 15235, proceed with default prediction
No common interaction or similar neighbor for user 4585 and item 29325, proceed with default prediction
No common interaction or similar neighbor for user 4669 and item 44311, proceed with default prediction
No common interaction or similar neighbor for user 4669 and item 1147, proceed with default prediction
No common interaction or similar neighbor for user 4628 and item 37115, proceed with default prediction
No common interaction or similar neighbor for user 4628 and item 12613, proceed with default prediction
Detect 342 unknown interaction(s), position: [2, 12, 5132, 4110, 22, 26, 7200, 38, 5158, 2092, 6188, 2096, 3120, 7232, 1094, 2124, 7244, 4174, 6222, 6224, 3152, 5208, 2138, 5214, 2144, 1120, 98, 7264, 7266, 1124, 4200, 6248, 6250, 1130, 2156, 1132, 110, 1134, 2160, 6256, 6260, 7284, 6264, 3196, 126, 2178, 3206, 7306, 7310, 3216, 1172, 3220, 4246, 1174, 4248, 1180, 5276, 3236, 7334, 172, 5292, 3248, 2228, 1204, 4280, 6330, 2236, 1212, 2244, 5316, 5320, 6346, 3274, 4300, 7372, 1230, 3280, 5328, 3292, 5340, 5342, 2272, 2278, 3302, 4336, 2294, 6390, 248, 6394, 7422, 6402, 1282, 3334, 4360, 1290, 6412, 7438, 1298, 5394, 5396, 1302, 3350, 5400, 282, 1312, 2338, 1316, 2342, 1332, 7480, 7486, 326, 1350, 3406, 2384, 338, 2386, 3410, 6492, 5468, 1374, 5472, 354, 1380, 358, 6504, 1384, 1388, 4462, 1390, 370, 2418, 1394, 374, 5494, 3450, 5508, 392, 5512, 5514, 4492, 5516, 3472, 4498, 5526, 3488, 2474, 4524, 5548, 2478, 7596, 6578, 436, 6580, 3528, 5584, 5588, 4566, 6616, 5596, 2526, 3550, 4576, 7646, 3552, 7654, 4584, 2538, 4586, 7662, 496, 5626, 1530, 3582, 1540, 3588, 7686, 6676, 6680, 2594, 4642, 1572, 2598, 7718, 2600, 2602, 4650, 4652, 4662, 1590, 7734, 1594, 7738, 1596, 7744, 582, 2632, 3656, 588, 5708, 6744, 604, 1628, 4702, 1630, 3678, 7774, 612, 4708, 6756, 7780, 1638, 7782, 7790, 3696, 3698, 4724, 630, 6774, 4738, 1666, 3716, 5764, 6792, 6798, 656, 2704, 4762, 6810, 2716, 3742, 4770, 2732, 6832, 3762, 6836, 5812, 7866, 7870, 712, 2762, 3788, 718, 3796, 7892, 6872, 732, 4830, 5856, 6882, 6886, 746, 6890, 748, 5866, 1772, 5870, 7920, 3832, 2810, 6906, 5882, 5884, 2814, 5886, 2816, 3842, 6916, 780, 6924, 7952, 3860, 7956, 2838, 1818, 1824, 3884, 7984, 4914, 3892, 5940, 3896, 4926, 3902, 5952, 2882, 1858, 2884, 5956, 1864, 2892, 846, 850, 5970, 8018, 858, 1888, 2916, 4964, 5988, 3942, 2924, 2928, 888, 1916, 3964, 3968, 7044, 2950, 2952, 7050, 3980, 5006, 1938, 5016, 3994, 8090, 2972, 1948, 1952, 6048, 6056, 5034, 4012, 7088, 2994, 4020, 1974, 5048, 4042, 8138, 7118, 4050, 7124, 988, 7146, 3056, 7154, 6130, 7162, 5116, 1022]

eval_pointwise:  38%|███▊      | 3/8 [00:00<00:00,  6.52it/s]

Detect 380 unknown interaction(s), position: [7168, 4098, 6148, 7172, 4102, 6152, 5130, 1036, 2066, 4118, 5142, 2078, 6174, 7206, 3116, 5164, 7222, 1084, 4162, 6214, 6222, 1102, 4178, 1108, 3156, 88, 4088, 1116, 94, 4196, 6248, 1128, 2154, 1130, 1134, 3184, 2162, 5236, 7286, 4216, 6264, 4220, 5244, 6270, 3198, 3210, 4238, 2196, 4244, 4248, 7322, 4252, 3228, 5276, 7324, 3232, 6306, 1186, 170, 4268, 6140, 3246, 5296, 4274, 3250, 4276, 3254, 184, 1216, 6338, 3266, 6340, 5316, 7364, 7368, 4298, 2254, 208, 210, 6354, 7380, 7382, 6366, 4320, 6368, 7392, 2278, 1256, 8188, 4334, 7412, 246, 1272, 4350, 2304, 2306, 260, 2312, 6408, 5392, 1298, 7446, 5400, 3354, 286, 3360, 1316, 3364, 6438, 3376, 5426, 6454, 314, 2366, 4414, 6464, 7486, 4418, 6468, 6474, 6480, 338, 2386, 4436, 7510, 6492, 1376, 7524, 4454, 1392, 2418, 4468, 6516, 4470, 7542, 1400, 1402, 7548, 6526, 6528, 1408, 6530, 3460, 3462, 7560, 6538, 6540, 400, 5526, 6552, 3480, 3484, 5536, 3492, 5542, 6568, 1450, 7594, 1452, 7596, 7600, 4532, 3508, 2486, 4534, 5564, 7612, 6590, 7616, 454, 456, 3530, 5578, 462, 7630, 7632, 3540, 6616, 6618, 482, 6628, 3556, 4582, 3560, 6634, 1514, 2540, 7658, 7660, 5616, 4598, 504, 3576, 1528, 2558, 510, 3594, 7690, 7692, 2576, 3600, 3604, 534, 536, 6682, 5658, 7706, 3612, 542, 6688, 7712, 550, 5678, 3632, 5680, 4658, 7738, 5694, 576, 5696, 4676, 6734, 6738, 7764, 2648, 7768, 2650, 6746, 6752, 3682, 4712, 618, 2666, 6762, 3692, 6766, 2674, 4734, 1664, 6786, 5762, 5764, 646, 4748, 658, 3734, 668, 674, 5796, 1702, 680, 2728, 682, 3752, 6828, 4782, 1710, 4784, 3758, 4788, 6838, 3770, 7868, 6846, 706, 5828, 720, 1744, 4818, 6870, 730, 7898, 7902, 7904, 3810, 4838, 4844, 1790, 7940, 2828, 6930, 2840, 5914, 3868, 4896, 6944, 2850, 2852, 7974, 5928, 1836, 7980, 7982, 5936, 4914, 3890, 6964, 7986, 1846, 6968, 2874, 6976, 1856, 5952, 5956, 8004, 2886, 842, 2894, 1874, 5970, 4948, 1878, 3928, 5976, 5978, 7006, 7008, 866, 3940, 878, 2926, 1902, 4980, 3958, 7034, 3962, 6018, 1924, 5002, 5004, 8076, 3982, 6032, 5010, 916, 3990, 1946, 7070, 5024, 4000, 930, 4002, 936, 940, 942, 7086, 954, 7100, 5054, 6080, 6086, 5064, 1996, 974, 976, 6096, 982, 2006, 6102, 5084, 4062, 6110, 994, 996, 5094, 2022, 3048, 1002, 8172, 8174, 3056, 1010, 3060, 7156, 5110, 5112, 3066, 2044, 7166]
Detect 543 unknown interaction(s), position: [4096, 6144, 10, 6164, 2072, 26, 6174, 4128, 6176, 4130, 6182, 42, 6188, 2098, 4146, 4148, 6198, 4152, 2106, 60, 62, 64, 2116, 2122, 2128, 4176, 6230, 88, 2136, 4186, 6232, 6234, 4196, 4198, 6258, 4216, 6264, 2170, 4220, 2174, 6272, 130, 4230, 6278, 136, 2184, 2186, 6282, 4240, 6290, 6294, 6300, 2208, 6304, 4262, 174, 4270, 2224, 6330, 6336, 6344, 2250, 4304, 6352, 210, 4306, 6354, 4310, 4312, 218, 4318, 2272, 6368, 6370, 2276, 230, 4326, 4334, 240, 244, 4346, 2314, 2320, 4372, 6426, 6428, 4388, 4390, 2346, 2350, 304, 310, 2358, 2360, 4408, 2362, 6456, 2364, 318, 4418, 4422, 2374, 2376, 4426, 334, 6478, 354, 2402, 4450, 2406, 6502, 6506, 6510, 6514, 6524, 4478, 2438, 6534, 392, 4492, 6542, 400, 402, 404, 6548, 408, 4508, 6560, 422, 4522, 6570, 2476, 430, 432, 2480, 6576, 4532, 448, 6592, 6600, 460, 2512, 2516, 6616, 474, 6618, 2526, 6626, 484, 490, 6636, 494, 6638, 6644, 6654, 2564, 518, 4616, 6664, 4628, 4642, 6696, 554, 2610, 4664, 6716, 574, 4672, 6720, 2638, 4692, 2648, 2660, 2662, 618, 2670, 2672, 6768, 632, 6776, 634, 4732, 6784, 6786, 6796, 654, 6798, 656, 660, 4762, 672, 674, 2724, 4776, 4782, 2742, 6838, 696, 4802, 2758, 4808, 6858, 4812, 2766, 728, 6872, 2782, 2794, 6890, 2796, 4846, 754, 756, 6900, 2806, 6916, 2826, 784, 6928, 788, 2836, 4892, 800, 2848, 6948, 4904, 4908, 6956, 6958, 6960, 6962, 820, 6966, 4922, 2880, 836, 838, 2888, 4938, 4940, 2902, 2910, 7018, 7020, 878, 4990, 4998, 7046, 5000, 906, 7052, 7054, 7066, 2976, 932, 5032, 940, 7096, 3002, 5050, 958, 7102, 7118, 5074, 3030, 5080, 5088, 7152, 5110, 1018, 3070, 1024, 5120, 1028, 1030, 3082, 5136, 5142, 1052, 5148, 3102, 7206, 1066, 1070, 7218, 5172, 7222, 1080, 5184, 3138, 3140, 3142, 1098, 1106, 3154, 1108, 7254, 7256, 1116, 3164, 7260, 7262, 7270, 3176, 3182, 1136, 1146, 7298, 5256, 7304, 1172, 7318, 5280, 7328, 1188, 1192, 7336, 1194, 7344, 5298, 1212, 1214, 7362, 3270, 5326, 5330, 7380, 3286, 7388, 3294, 5344, 7394, 1260, 3308, 7410, 5364, 7414, 3322, 5378, 5384, 7438, 7442, 5400, 7448, 3354, 3356, 1316, 3374, 1332, 1348, 1350, 3410, 7508, 5464, 7512, 5468, 1374, 5476, 7524, 5480, 1386, 3434, 5482, 3440, 3446, 1402, 5502, 3456, 7556, 5514, 7564, 3470, 1426, 3474, 5522, 1430, 7580, 3486, 1442, 7588, 1446, 3498, 3500, 3506, 7602, 5556, 1462, 7606, 1464, 7608, 5564, 5574, 5582, 1488, 5584, 3540, 1498, 1508, 7652, 3558, 5608, 7660, 5618, 7666, 3572, 5620, 7670, 5626, 7674, 3588, 7686, 5642, 7692, 7696, 7698, 1560, 5656, 3610, 7706, 7710, 7728, 5684, 7736, 1594, 7738, 7742, 7750, 1610, 7754, 3660, 3668, 7768, 1626, 5722, 7772, 1640, 5746, 7798, 7812, 5776, 7824, 3732, 7830, 5790, 1700, 7850, 5810, 5816, 7866, 5820, 1726, 7872, 1752, 5848, 7900, 5860, 1766, 5862, 1768, 7912, 5868, 1774, 5870, 1780, 1784, 3838, 5886, 5894, 7942, 1808, 3856, 1812, 5908, 3866, 5914, 7962, 1826, 3876, 5930, 7978, 7980, 1842, 1846, 7990, 7992, 5952, 1858, 3906, 5958, 1864, 3912, 5960, 3916, 3918, 8026, 8032, 8034, 5992, 5994, 8044, 5998, 6000, 1908, 3956, 6004, 8058, 1920, 8066, 8076, 1934, 6034, 8084, 6040, 8088, 8090, 4000, 6054, 8106, 6062, 8118, 4024, 1978, 6076, 8124, 8126, 1986, 6082, 4040, 6094, 4048, 6096, 4050, 6098, 4056, 2012, 4060, 8158, 6114, 6116, 8166, 8170, 4090, 8188]

eval_pointwise:  62%|██████▎   | 5/8 [00:00<00:00,  6.61it/s]

Detect 454 unknown interaction(s), position: [2, 4098, 1030, 7174, 4104, 1032, 10, 2058, 3080, 1042, 2072, 2074, 2076, 4124, 7200, 4132, 5156, 1062, 7206, 7208, 42, 1066, 7210, 46, 48, 4148, 7220, 1080, 4154, 3130, 4156, 3132, 3134, 6214, 74, 7246, 5204, 7254, 88, 2136, 4088, 2140, 1116, 3166, 98, 5218, 7266, 5220, 7270, 1128, 6250, 2156, 5228, 1134, 6258, 5242, 6268, 126, 1154, 5252, 4234, 7310, 4244, 152, 2200, 156, 7326, 4256, 1184, 164, 3236, 5286, 4264, 7336, 4276, 1204, 2232, 2234, 7358, 4288, 1216, 200, 5322, 1230, 7374, 4304, 6352, 210, 1242, 3290, 220, 6366, 1246, 1248, 4322, 5348, 7396, 6374, 3304, 234, 4332, 1266, 244, 250, 3322, 252, 4352, 1280, 3328, 7428, 264, 1292, 3342, 6418, 5394, 3350, 2330, 4378, 2332, 4380, 286, 6428, 2338, 292, 4388, 4390, 1316, 298, 2346, 4396, 304, 7472, 306, 3388, 1342, 322, 5446, 4424, 4426, 7498, 332, 2388, 4440, 6488, 1368, 2396, 1372, 5468, 6498, 1380, 358, 5486, 1400, 378, 6522, 1408, 386, 3458, 4484, 392, 3466, 7562, 4492, 4496, 3472, 2450, 5522, 4500, 2458, 3482, 6556, 3488, 4514, 5538, 2470, 4524, 6574, 1454, 7598, 3504, 1458, 3506, 7604, 446, 4542, 3520, 1476, 2502, 7622, 2510, 2514, 7634, 4564, 7636, 5592, 5594, 4572, 6620, 1500, 1504, 5602, 6628, 2534, 2538, 6644, 5620, 1526, 504, 6648, 1536, 2562, 3586, 516, 5640, 2572, 1552, 3600, 4626, 5650, 7698, 3604, 2582, 5652, 536, 6680, 538, 540, 1564, 6686, 3612, 1570, 4644, 1572, 552, 3624, 2602, 5672, 1580, 5684, 4662, 1590, 4664, 1592, 6718, 1598, 4672, 5696, 2626, 580, 582, 6726, 4680, 1606, 5702, 3656, 4684, 3668, 5728, 6754, 2660, 4708, 4710, 1636, 5736, 1642, 5738, 1644, 5740, 624, 2674, 3698, 1654, 3702, 5752, 5754, 6780, 5756, 7806, 640, 2688, 3712, 3714, 2692, 5766, 648, 6794, 2700, 1678, 2706, 6804, 3734, 5782, 666, 7836, 6814, 3742, 4768, 678, 2726, 5800, 7848, 694, 6840, 4798, 5822, 2752, 3776, 706, 2754, 1732, 4810, 1738, 720, 3792, 722, 724, 7892, 5848, 2778, 7898, 5852, 1760, 3810, 5858, 7906, 2790, 746, 4844, 7916, 750, 752, 2800, 1778, 7922, 758, 1782, 2808, 5884, 7932, 7934, 6912, 3846, 7944, 6922, 5900, 782, 5902, 2832, 6930, 3862, 7958, 5918, 7968, 802, 1826, 2858, 1834, 4908, 6956, 7978, 7980, 1842, 820, 2868, 4918, 828, 7998, 832, 4930, 8002, 4934, 844, 3922, 852, 4948, 854, 6996, 6998, 7002, 860, 7004, 3932, 1888, 8034, 7012, 1892, 3940, 3942, 8040, 7018, 1898, 3946, 8044, 8046, 884, 8052, 886, 4982, 7030, 3958, 6014, 8062, 7040, 3970, 8068, 912, 5008, 5010, 5012, 8084, 1942, 6040, 924, 5020, 926, 8092, 7072, 8094, 8100, 1960, 8104, 1962, 8106, 948, 1974, 7096, 8120, 6078, 6080, 7112, 972, 5070, 976, 4048, 980, 2006, 7128, 6104, 6108, 2014, 4062, 992, 5088, 7142, 6120, 3050, 7150, 2030, 8176, 4082, 4084, 4086, 8184, 2044]
Detect 414 unknown interaction(s), position: [1030, 10, 3082, 12, 2060, 4108, 16, 1040, 18, 3088, 7184, 26, 4124, 7196, 3102, 2082, 4130, 5154, 7202, 2086, 2088, 1064, 2090, 6186, 2094, 7214, 1072, 2098, 60, 64, 4162, 3144, 1098, 5196, 78, 7246, 1104, 6226, 1106, 6228, 1114, 3162, 6236, 1116, 3164, 3166, 5218, 2154, 1130, 5226, 5228, 3182, 5234, 6266, 2172, 128, 4224, 6272, 3200, 5248, 1154, 2182, 3204, 7302, 4244, 3220, 5268, 4248, 3224, 158, 2210, 4258, 2214, 174, 6320, 5298, 6324, 3254, 7352, 192, 196, 6342, 1224, 4298, 5322, 6348, 3280, 5328, 4312, 218, 6362, 2268, 5338, 6368, 7392, 6370, 1250, 2278, 5352, 2282, 4330, 6380, 1264, 242, 248, 5374, 7428, 4358, 6406, 2312, 5382, 7434, 3340, 270, 2320, 1302, 5402, 7452, 4382, 7454, 292, 4388, 6438, 1320, 5416, 4394, 1324, 1326, 4400, 5426, 7478, 2360, 4418, 4420, 1348, 2374, 7492, 3402, 3406, 1360, 2388, 2392, 3416, 2394, 6490, 3418, 352, 1382, 6510, 4464, 2420, 6518, 4474, 5500, 6526, 4480, 5504, 388, 4488, 6536, 396, 4496, 7570, 2454, 3484, 7588, 4518, 1452, 4528, 2488, 6584, 2492, 1468, 2494, 3516, 5568, 6594, 7618, 5572, 7624, 7630, 6616, 1498, 5594, 476, 4572, 7644, 4576, 3554, 2536, 4586, 1518, 2546, 1522, 2548, 4602, 2554, 4604, 508, 4606, 3578, 5630, 514, 2562, 2564, 3588, 2566, 4614, 6664, 7686, 2572, 3598, 6672, 5648, 3602, 6680, 3608, 4634, 3610, 540, 4636, 1566, 544, 6688, 1576, 6698, 6702, 4656, 6704, 5682, 4662, 4664, 1592, 4666, 1594, 574, 6718, 6720, 3648, 3654, 5702, 5704, 6736, 1616, 3672, 6746, 5724, 3682, 6758, 616, 1640, 7784, 2676, 630, 1656, 7802, 2684, 3708, 4734, 3710, 2690, 4738, 2692, 5766, 3728, 5780, 664, 5784, 668, 672, 5792, 674, 5798, 4780, 5804, 2736, 3760, 1716, 2742, 1722, 7868, 1726, 5822, 704, 706, 5826, 6852, 4806, 1736, 716, 4812, 718, 2768, 2774, 1750, 728, 732, 7900, 734, 6880, 738, 4834, 6886, 7910, 4844, 6892, 3820, 5868, 2800, 1778, 7928, 7930, 764, 3838, 7936, 3846, 4876, 3856, 4888, 7966, 4896, 2850, 804, 1828, 1830, 1836, 6958, 1840, 6962, 5938, 4916, 6964, 7988, 5950, 7998, 4928, 8000, 2882, 1860, 5956, 3910, 4938, 4940, 8016, 1878, 5978, 860, 3932, 1886, 3934, 5984, 866, 1892, 4966, 5990, 874, 2922, 2924, 7018, 2926, 7022, 3946, 1900, 7026, 1902, 4980, 7028, 1904, 8052, 2946, 3974, 904, 2952, 2954, 2962, 3986, 2966, 3992, 8088, 6042, 8096, 7074, 7080, 6056, 8104, 5036, 2990, 4016, 946, 3000, 7096, 8122, 3008, 5056, 6084, 1992, 7118, 1998, 4046, 5076, 7126, 3034, 4060, 4064, 8162, 996, 3048, 5098, 5102, 5104, 4080, 7156, 1014, 7164]

eval_pointwise:  88%|████████▊ | 7/8 [00:01<00:00,  6.56it/s]

Detect 337 unknown interaction(s), position: [2054, 6152, 7176, 5132, 7190, 6180, 4134, 3112, 2096, 6192, 2100, 58, 3130, 7228, 5184, 3142, 2120, 3146, 6222, 7246, 6234, 92, 5216, 5218, 102, 4198, 4200, 5224, 1130, 3178, 5236, 124, 128, 1154, 5250, 134, 4230, 4232, 138, 4234, 2194, 3226, 2204, 7328, 7330, 5284, 6318, 6142, 3258, 7354, 2236, 5314, 3268, 5316, 6344, 2252, 7372, 6350, 4308, 5332, 4312, 2272, 6372, 1254, 7402, 242, 2290, 1266, 3316, 1272, 250, 5370, 2300, 5372, 254, 3326, 256, 7422, 3328, 2308, 1284, 1286, 4360, 5384, 4362, 270, 7438, 6416, 2334, 4384, 1312, 1316, 7460, 5414, 1320, 1322, 5420, 302, 7470, 306, 7484, 6466, 3398, 4424, 2382, 7502, 4438, 3414, 7520, 356, 6502, 370, 6516, 7540, 2422, 3448, 1404, 384, 7554, 2436, 3460, 4486, 5510, 5512, 1418, 7572, 1432, 2458, 6556, 4510, 2464, 4514, 2468, 7592, 1454, 432, 4534, 5558, 1468, 2494, 1470, 6594, 6602, 2508, 5582, 3544, 7644, 7646, 7650, 2532, 5612, 7662, 4592, 1520, 7664, 1522, 5620, 4600, 1530, 7676, 512, 5632, 7682, 3590, 5640, 528, 7696, 2582, 2584, 7704, 1566, 3614, 3616, 548, 4646, 6696, 3624, 6700, 1580, 4658, 6706, 6708, 3634, 5684, 3638, 3640, 1594, 3642, 3648, 2626, 6722, 3656, 7752, 590, 4692, 4700, 1638, 4722, 6776, 5760, 7808, 1666, 6796, 6798, 1678, 5774, 3728, 2706, 7826, 6804, 7830, 2712, 6814, 4778, 2732, 1708, 3756, 7856, 4786, 3762, 692, 4790, 7862, 1722, 2754, 4802, 4806, 6854, 3782, 1738, 3792, 7888, 722, 3796, 7900, 2782, 3806, 5854, 2790, 5870, 754, 5876, 6904, 3832, 3834, 7936, 4870, 2828, 6924, 2830, 6926, 2832, 7952, 1812, 4886, 1814, 2844, 1820, 5916, 3876, 4902, 6950, 4906, 814, 3886, 3892, 3896, 5946, 3900, 830, 1854, 5950, 4932, 6982, 1862, 844, 1868, 848, 2900, 6996, 2904, 8032, 1890, 8036, 2918, 1896, 2922, 4970, 7018, 8042, 1900, 1906, 3958, 888, 4986, 3962, 892, 896, 2948, 2952, 6028, 3986, 7060, 2970, 2972, 2974, 2976, 7074, 4004, 6054, 1960, 4008, 938, 7082, 940, 2994, 5044, 8116, 8118, 1976, 3010, 3012, 3016, 1994, 3020, 4046, 8150, 2012, 4062, 5092, 7142, 1000, 3050, 2028, 2030, 6130, 7166]
Detect 308 unknown interaction(s), position: [4100, 1032, 6154, 4108, 14, 1044, 2074, 4122, 7198, 6190, 4146, 5172, 54, 3126, 3132, 2116, 3142, 6220, 2126, 4178, 86, 1110, 5206, 6236, 2148, 4196, 2150, 1130, 2156, 3180, 112, 3186, 5234, 2164, 1142, 1144, 4218, 130, 2180, 6278, 1158, 5254, 4240, 2196, 2206, 2208, 5280, 162, 168, 6312, 5288, 6326, 3254, 2232, 4280, 188, 190, 6336, 1216, 196, 200, 202, 2250, 6346, 5324, 6352, 3280, 218, 4320, 5344, 3300, 230, 6374, 232, 2280, 1254, 3304, 5354, 1262, 1266, 5364, 3318, 5370, 2302, 5376, 2314, 268, 4370, 6422, 4378, 6428, 7452, 2334, 7454, 4386, 6434, 1314, 1316, 294, 4390, 7460, 3368, 2350, 306, 2360, 6456, 1338, 1346, 5446, 1356, 4434, 7506, 4438, 5482, 1390, 3440, 1394, 3444, 378, 4474, 4476, 7548, 4478, 2434, 388, 3468, 1422, 5518, 400, 2448, 3486, 4520, 3498, 434, 6578, 2484, 7604, 3510, 1464, 2494, 3518, 454, 4550, 3530, 3532, 5584, 2520, 3544, 500, 3572, 4604, 4608, 7680, 3588, 7684, 1548, 528, 4624, 1552, 536, 4632, 7706, 6688, 3618, 6692, 2602, 558, 4654, 2608, 1588, 2614, 4662, 568, 7736, 570, 7738, 5692, 3646, 5694, 3648, 578, 4680, 588, 4688, 6738, 1626, 3674, 606, 3678, 2662, 6760, 7786, 4716, 4720, 2676, 7798, 5758, 4736, 1666, 646, 4744, 652, 4748, 3724, 4756, 664, 666, 3738, 3744, 1698, 678, 5800, 2730, 2740, 1716, 3768, 4798, 720, 5844, 4824, 4832, 740, 2798, 4846, 4848, 7918, 5874, 4856, 3834, 6910, 3840, 7942, 3848, 5896, 2826, 5898, 2832, 1810, 1814, 3862, 2840, 5914, 802, 7974, 6954, 816, 4920, 2874, 4922, 1852, 1854, 5956, 838, 2896, 4946, 3926, 3930, 3936, 868, 1894, 3942, 876, 3952, 3954, 3956, 4982, 890, 4992, 7040, 7042, 908, 914, 1944, 6046, 7074, 2980, 5030, 4006, 940, 1966, 6064, 1970, 5044, 950, 5048, 1976, 3006, 960, 3008, 4046, 3026, 2002, 2004, 7128, 6104, 4058, 990, 2016, 2018, 4068, 998, 4070, 2026, 4074, 1008, 5104, 2032, 7166]

eval_pointwise: 100%|██████████| 8/8 [00:01<00:00,  6.48it/s]
eval_listwise: 100%|██████████| 6318/6318 [00:01<00:00, 6213.17it/s]

	 eval log_loss: 16.7935
	 eval roc_auc: 0.5357
	 eval precision@5: 0.0469
	 eval recall@5: 0.0637
	 eval ndcg@5: 0.1502
==============================

In [11]:
from libreco.evaluation import evaluate

# Evaluate the model on the test data with the specified metrics
evaluation_results = evaluate(
    model=user_cf,
    data=test_data,
    neg_sampling=True,
    metrics=["loss", "roc_auc", "precision", "recall", "ndcg"]
)

# Print the evaluation results
for metric, value in evaluation_results.items():
    print(f"{metric}: {value}")

eval_pointwise:   0%|          | 0/9 [00:00<?, ?it/s]

Detect 310 unknown interaction(s), position: [0, 2, 1026, 2052, 6148, 6154, 7180, 6162, 22, 7194, 2076, 4126, 1054, 3102, 5158, 7212, 56, 5176, 7228, 3136, 7236, 6214, 5190, 2120, 7240, 2122, 4170, 80, 3154, 4182, 1114, 4188, 7282, 5242, 2172, 4222, 4224, 4228, 6278, 3212, 4246, 5118, 4256, 6304, 3234, 7332, 4266, 7338, 4274, 7350, 6328, 7352, 1218, 3266, 5314, 2246, 6342, 7376, 7166, 7382, 3290, 3298, 4332, 6384, 6388, 1278, 3326, 4368, 6416, 1300, 4374, 6422, 5398, 6430, 6432, 4390, 298, 6446, 1328, 7472, 1334, 3384, 5432, 4412, 6460, 6462, 3392, 3400, 7504, 4434, 2394, 6490, 5466, 5476, 2406, 1382, 2410, 2412, 6508, 2414, 2418, 2424, 3448, 3450, 4478, 3456, 3464, 2442, 5514, 6540, 6542, 7570, 3474, 5522, 6550, 408, 4504, 4508, 414, 6558, 7582, 1442, 3498, 5548, 2480, 6576, 3504, 7600, 3508, 2486, 440, 3512, 5560, 2492, 6590, 3518, 6594, 456, 2518, 472, 2532, 486, 3558, 2536, 3560, 7656, 1516, 494, 7670, 1530, 1532, 1534, 5636, 6662, 7690, 6668, 1548, 1550, 2578, 1556, 2584, 7704, 538, 4636, 2592, 4640, 1574, 4652, 3628, 2610, 6706, 572, 2624, 6730, 2640, 6736, 6738, 5712, 4692, 7766, 7768, 7774, 2658, 1636, 7780, 6758, 7786, 6764, 2670, 4718, 7790, 7802, 4734, 1664, 1670, 656, 3734, 4762, 6818, 3748, 7846, 4778, 1712, 6838, 1718, 2744, 6840, 5814, 7864, 7868, 2750, 5834, 6860, 3792, 5842, 1748, 6870, 4824, 3802, 7900, 734, 6878, 7908, 1776, 7922, 756, 7924, 7932, 3838, 6912, 1812, 1816, 2848, 4900, 6954, 2862, 6960, 5938, 1844, 6966, 4918, 1846, 1848, 2874, 4924, 1854, 4934, 3910, 6986, 3914, 2894, 852, 3930, 7006, 3938, 2924, 5998, 6002, 7028, 3956, 7030, 7032, 7034, 3962, 3964, 3966, 2944, 3968, 2946, 4994, 7044, 1928, 7050, 5002, 5006, 5008, 3984, 7058, 3986, 2964, 7060, 5014, 8086, 2968, 3992, 4002, 7078, 4006, 2984, 8104, 7094, 4022, 1976, 4028, 8128, 1988, 1992, 1994, 976, 3034, 5082, 3036, 5094, 1002, 8172, 5110, 4086, 3066, 3068, 1022]

eval_pointwise:  11%|█         | 1/9 [00:00<00:01,  6.39it/s]

Detect 330 unknown interaction(s), position: [3072, 1028, 8, 26, 4122, 2076, 1058, 2088, 4136, 1066, 3114, 44, 3116, 2096, 4146, 1074, 6196, 4156, 6206, 3134, 6210, 3138, 4164, 6212, 74, 4170, 5194, 2128, 7254, 4184, 94, 98, 3170, 4204, 4206, 1134, 112, 7282, 4212, 6262, 3194, 7292, 5246, 3202, 1158, 142, 3216, 6294, 1176, 5282, 166, 6314, 1194, 172, 6316, 3254, 5312, 3266, 7364, 6344, 6348, 3278, 6352, 3280, 4310, 7382, 3288, 2268, 4316, 1244, 226, 232, 7404, 240, 6384, 242, 7408, 248, 4354, 6404, 2312, 270, 6426, 2332, 1310, 1314, 4390, 4394, 302, 3378, 308, 4404, 6454, 4406, 312, 3382, 314, 4410, 6458, 6460, 318, 3388, 3392, 322, 2388, 2390, 3414, 1370, 3418, 1374, 2400, 6496, 7526, 3432, 3434, 5484, 2418, 1396, 5502, 2434, 2446, 3474, 7570, 7572, 6552, 7578, 412, 2462, 416, 7586, 4516, 7588, 2476, 5554, 438, 5560, 4538, 5562, 2492, 3516, 446, 1470, 5568, 7616, 2502, 5576, 7624, 6604, 1486, 5582, 1490, 7636, 1494, 4578, 1514, 492, 7664, 2546, 4596, 5624, 6650, 3578, 2556, 1538, 6660, 6664, 7688, 1564, 5664, 4642, 3618, 6692, 7714, 5672, 2602, 2606, 3630, 6704, 4660, 6708, 1588, 3636, 6712, 580, 1606, 1620, 2646, 3670, 602, 4702, 4706, 3682, 612, 616, 2670, 1646, 6770, 3698, 5746, 3700, 632, 636, 4734, 3710, 2688, 7806, 7808, 1666, 5766, 7816, 656, 3734, 664, 5784, 666, 6812, 7836, 4768, 1696, 3744, 5792, 4772, 3748, 2726, 4782, 2738, 692, 5814, 6842, 2754, 7874, 2756, 3782, 716, 4812, 1744, 3792, 2770, 6866, 5840, 7890, 1750, 728, 2776, 3800, 2788, 3812, 7912, 746, 4842, 5866, 6896, 754, 6898, 2804, 1778, 3832, 7952, 2834, 7954, 2838, 4886, 7958, 7960, 6942, 802, 2850, 2854, 2868, 822, 826, 8006, 4936, 8010, 6992, 3920, 5972, 8022, 1884, 2912, 1888, 4962, 3936, 1890, 8034, 8040, 4970, 7018, 5994, 8044, 2926, 1908, 886, 2936, 7032, 1912, 8056, 6010, 7038, 3968, 4996, 3974, 5002, 2956, 8078, 1942, 1960, 8104, 938, 940, 6062, 7090, 2996, 950, 5046, 3000, 4028, 1982, 3008, 1988, 968, 1994, 4048, 2008, 998, 1002, 7146, 5102, 2034, 7160]

eval_pointwise:  22%|██▏       | 2/9 [00:00<00:01,  6.44it/s]

Detect 382 unknown interaction(s), position: [4096, 2, 8, 2058, 7186, 4116, 4118, 24, 28, 3104, 4134, 1064, 7208, 5162, 3116, 5164, 6192, 1072, 5172, 7220, 56, 7226, 1086, 6208, 1090, 5188, 5190, 7242, 5198, 6228, 1108, 2136, 3162, 5212, 5214, 96, 5216, 5218, 4196, 104, 106, 4202, 2156, 110, 5234, 116, 3194, 124, 2174, 6280, 138, 7314, 148, 6300, 3228, 6306, 6308, 3236, 1190, 7334, 172, 4268, 4270, 6318, 2224, 1196, 3244, 3252, 3262, 4288, 5312, 2246, 2248, 4296, 7370, 206, 6352, 216, 6366, 2274, 6374, 3302, 4328, 5352, 234, 7400, 1260, 240, 1264, 2290, 6386, 1266, 2296, 7422, 1280, 1286, 6410, 274, 282, 6432, 4386, 2340, 5414, 4392, 6446, 7470, 2354, 2358, 316, 3392, 322, 324, 326, 7496, 7500, 5454, 3410, 1372, 6494, 1374, 354, 358, 5480, 362, 4460, 5484, 6510, 1390, 4464, 372, 5496, 1404, 384, 1408, 3460, 5510, 3464, 396, 6540, 404, 6548, 1430, 5528, 4510, 6560, 7592, 7594, 6572, 1456, 4532, 4534, 6588, 7612, 448, 6592, 7618, 1476, 7626, 5582, 2512, 7638, 4572, 3548, 7646, 7648, 3566, 6640, 3568, 500, 6644, 5620, 4604, 2556, 3582, 2560, 6656, 514, 5632, 2568, 1544, 2572, 4622, 4626, 2580, 7706, 540, 1564, 2590, 7708, 5664, 7718, 7720, 1578, 1580, 5678, 2608, 3632, 1588, 570, 3644, 4672, 6724, 584, 7756, 4686, 2640, 4688, 594, 3666, 7766, 4696, 3672, 3680, 1638, 1640, 618, 4714, 7788, 7790, 4722, 6774, 7798, 4728, 1656, 5754, 3712, 3716, 1670, 3718, 1672, 1674, 4748, 3728, 5778, 6804, 7828, 7830, 5784, 7834, 5792, 674, 6820, 5798, 2730, 4778, 1708, 5804, 5806, 7854, 692, 3766, 2744, 3774, 7872, 6850, 4804, 4806, 5830, 712, 1738, 718, 6864, 728, 1752, 5850, 736, 1760, 2786, 4836, 1768, 2794, 6892, 6894, 3824, 4850, 7924, 2806, 4854, 2808, 5882, 2814, 5886, 2816, 7940, 5898, 5902, 784, 3858, 5912, 1818, 3868, 7964, 4902, 812, 6956, 1840, 6964, 1848, 5950, 1856, 4932, 3914, 8012, 6990, 1870, 5966, 4946, 1874, 6996, 3926, 7000, 8028, 4958, 7010, 3944, 3946, 2924, 4972, 2926, 4974, 7022, 6000, 4990, 6014, 4994, 6018, 8068, 908, 3980, 5006, 5008, 3984, 5014, 3990, 5016, 7068, 7070, 7072, 4000, 7074, 8096, 6050, 934, 7078, 936, 5032, 5036, 1970, 5046, 8120, 7098, 7100, 1980, 7102, 1982, 3008, 6078, 8128, 3016, 5064, 7118, 1998, 6094, 4048, 980, 5076, 3030, 988, 2014, 4062, 992, 994, 998, 3046, 5094, 7150, 8176, 4082, 3060, 6132, 2042, 5116]

eval_pointwise:  33%|███▎      | 3/9 [00:00<00:00,  6.30it/s]

Detect 457 unknown interaction(s), position: [5122, 3080, 7176, 3086, 1040, 7184, 3092, 4118, 5144, 4126, 2082, 7202, 5158, 4136, 5168, 5170, 6196, 6198, 1078, 56, 4158, 6206, 7230, 1090, 2118, 4166, 3142, 2122, 5200, 4180, 86, 4182, 4184, 3158, 5210, 7258, 2142, 2144, 2146, 6246, 6248, 4202, 1130, 7274, 1136, 4212, 7284, 2166, 3194, 5242, 3196, 128, 134, 4230, 136, 6280, 3206, 5256, 2188, 4236, 6286, 3210, 7312, 3220, 3222, 7320, 7322, 4254, 1188, 7332, 3238, 7336, 7338, 1196, 3244, 2222, 5294, 3248, 4274, 2228, 7348, 182, 3254, 4282, 2244, 3268, 2246, 7366, 1226, 2252, 2254, 208, 3280, 2258, 212, 2262, 1238, 218, 1242, 4316, 222, 4322, 1252, 4326, 5350, 232, 4328, 4334, 5358, 6384, 5360, 7410, 1272, 2298, 3322, 2300, 2304, 260, 7432, 1290, 5390, 2320, 4368, 7444, 3350, 5404, 2334, 2336, 1312, 2340, 5412, 296, 2346, 1324, 7468, 6446, 3374, 1328, 6450, 1330, 7474, 7478, 4408, 3384, 3386, 316, 6462, 3398, 4426, 336, 7504, 7506, 1366, 4440, 7512, 3418, 3426, 5474, 4458, 7530, 4464, 1394, 7540, 5498, 1406, 5502, 7550, 2434, 3458, 2436, 6532, 392, 2440, 1418, 3466, 1420, 3468, 398, 2446, 7562, 3476, 5524, 6550, 7574, 3480, 2460, 6560, 1446, 3496, 4522, 6570, 5546, 7594, 7596, 7600, 2482, 4530, 6578, 6580, 438, 6582, 3510, 442, 2494, 4542, 6592, 1470, 5574, 3528, 5576, 2506, 7624, 5580, 5592, 2524, 2526, 7648, 7650, 484, 6628, 4582, 5606, 7656, 1514, 1516, 5614, 7662, 1524, 3574, 5622, 4600, 504, 3576, 5624, 3578, 7674, 5628, 1532, 3586, 7684, 1542, 520, 4616, 522, 6664, 524, 5640, 7690, 4624, 6676, 3604, 536, 3608, 7706, 7710, 1568, 546, 3622, 554, 7726, 6704, 5684, 5686, 7734, 568, 5688, 4666, 7736, 4672, 5696, 4674, 5698, 1606, 5708, 7758, 5712, 2650, 5722, 7774, 5728, 5738, 2668, 5740, 5744, 626, 7794, 3702, 6776, 1658, 5756, 3712, 4738, 6786, 3714, 7814, 2698, 6794, 5770, 3728, 6804, 4758, 6806, 6808, 4762, 7838, 4768, 3752, 5800, 2730, 6832, 1716, 3766, 4798, 1728, 3776, 7872, 5830, 4808, 7880, 1738, 1740, 5836, 1744, 5840, 7888, 7896, 5850, 4834, 7908, 4838, 3816, 7912, 746, 4844, 754, 3828, 4854, 7930, 6908, 1788, 766, 5886, 6914, 6916, 4870, 1798, 2824, 5894, 6924, 7948, 2830, 3854, 3856, 7952, 1810, 4884, 796, 5918, 5920, 1828, 7972, 5926, 1832, 3880, 7976, 7978, 3884, 3892, 3896, 5948, 7996, 5952, 3906, 2884, 8008, 842, 6986, 3918, 2896, 6992, 1872, 8018, 1876, 1886, 3934, 8030, 4964, 7012, 3942, 2920, 4970, 7018, 876, 4972, 4974, 1906, 7028, 3956, 8052, 3958, 6010, 3966, 3974, 7050, 2956, 910, 2958, 3990, 5016, 3992, 6040, 5020, 926, 1954, 4004, 934, 7078, 6054, 1960, 2986, 4012, 5040, 4018, 6068, 5050, 4030, 960, 6082, 7110, 4038, 5064, 6086, 7114, 6088, 3024, 7120, 978, 7122, 5076, 4052, 5080, 6106, 6110, 8158, 7136, 4064, 3044, 7140, 8164, 8170, 3052, 7148, 6126, 6128, 4084, 6140, 7166]

eval_pointwise:  44%|████▍     | 4/9 [00:00<00:00,  6.22it/s]

Detect 498 unknown interaction(s), position: [0, 5122, 4, 4106, 2062, 4116, 28, 34, 36, 2084, 2086, 6182, 3114, 3116, 7214, 1074, 54, 60, 7230, 68, 5188, 70, 7236, 2124, 5196, 4176, 3152, 4180, 5206, 7260, 4192, 1120, 4194, 3168, 5220, 4200, 3176, 110, 2158, 1136, 2162, 6258, 5240, 122, 3194, 6268, 126, 6270, 1150, 7302, 140, 7308, 3214, 1168, 2194, 4242, 4246, 5270, 3224, 6298, 3226, 156, 5278, 1184, 164, 5284, 2214, 5286, 4268, 174, 2224, 5296, 6322, 2230, 1206, 2232, 1208, 1214, 192, 5316, 6342, 5318, 2248, 5322, 6348, 3276, 1232, 3280, 210, 4308, 7380, 5334, 6360, 2266, 2270, 5344, 4322, 1254, 2280, 1258, 7402, 2286, 240, 3312, 242, 6388, 2294, 6392, 7416, 2298, 4346, 6396, 7418, 1284, 3332, 7430, 6408, 2314, 5388, 1294, 3344, 6418, 1300, 3348, 4376, 6424, 3352, 6428, 2336, 1318, 296, 4392, 5418, 6444, 5422, 3376, 6452, 7476, 2360, 1338, 318, 1342, 3390, 1344, 322, 2370, 5442, 326, 328, 4424, 1354, 1358, 6482, 3410, 2388, 5458, 6486, 1364, 344, 4440, 2394, 1368, 3418, 7514, 1376, 6498, 3426, 2404, 7522, 358, 1380, 5478, 5480, 6510, 7534, 5488, 2418, 5490, 2422, 4470, 3446, 1400, 3450, 7546, 7548, 1406, 384, 3456, 388, 4488, 5512, 394, 7560, 1420, 1422, 4496, 2450, 404, 4500, 4502, 5526, 5528, 2458, 1434, 412, 5530, 1436, 2464, 1440, 7584, 4516, 424, 6568, 1452, 6574, 3504, 4530, 436, 1460, 3508, 3510, 6586, 5562, 1468, 4546, 454, 3526, 3528, 1482, 5580, 7630, 3536, 470, 6616, 5594, 2528, 1504, 4578, 3552, 5600, 492, 4592, 6640, 7664, 5618, 3572, 5620, 3576, 3586, 516, 1540, 2566, 3590, 6666, 3594, 2572, 6668, 3596, 7692, 3598, 1552, 530, 2578, 3600, 1554, 2582, 5648, 5652, 1560, 538, 7714, 548, 6692, 1572, 7716, 6696, 3622, 4650, 6698, 5670, 5672, 5676, 7732, 2620, 4670, 6720, 3648, 5696, 5698, 580, 6736, 7766, 604, 3678, 3680, 1634, 6756, 5732, 614, 1638, 5734, 4714, 5738, 5740, 5742, 2672, 6770, 1650, 7794, 7802, 1660, 1662, 7806, 2690, 1668, 3720, 4752, 658, 4754, 1682, 5780, 1688, 3738, 5786, 4764, 670, 4766, 1696, 6818, 1698, 2724, 7842, 2726, 7844, 7848, 5802, 4780, 7852, 5806, 690, 3762, 1716, 3764, 694, 2742, 696, 4792, 6838, 3768, 5816, 3776, 706, 3780, 4806, 6854, 3782, 714, 2762, 4812, 1744, 6868, 1748, 2774, 3796, 3800, 2778, 7898, 3806, 4832, 2788, 7908, 5866, 7914, 4848, 6896, 4850, 2806, 4854, 2812, 766, 7936, 4868, 2822, 3846, 776, 1800, 6922, 1804, 4880, 6930, 3858, 7954, 790, 6934, 2840, 2844, 4892, 6942, 3872, 4898, 7970, 4902, 808, 3880, 7976, 3892, 1846, 3894, 824, 2872, 4922, 1852, 1858, 1862, 840, 6988, 854, 2902, 2904, 6998, 1878, 8024, 8028, 4958, 7006, 2912, 7008, 2914, 3936, 1892, 1894, 3942, 872, 4968, 4970, 7016, 3946, 8042, 4974, 7022, 4978, 6002, 8052, 4982, 3958, 2936, 4984, 6008, 3964, 7038, 6016, 3970, 6018, 8072, 2954, 1934, 2964, 3988, 3990, 7066, 6042, 6050, 1964, 1966, 7096, 4024, 3006, 1982, 7104, 6080, 1986, 4034, 6082, 7110, 968, 7114, 3020, 5072, 7120, 5076, 986, 7130, 8154, 8158, 2018, 5092, 7142, 2022, 3050, 1006, 3054, 7154, 2034, 4084, 8180, 7158, 5114, 6140]

eval_pointwise:  56%|█████▌    | 5/9 [00:00<00:00,  6.18it/s]

Detect 403 unknown interaction(s), position: [2048, 2050, 4100, 6148, 4104, 5128, 10, 2060, 3086, 6160, 18, 7186, 1044, 22, 6168, 6170, 6172, 30, 6174, 34, 4130, 38, 7206, 7222, 66, 1092, 6214, 4168, 6218, 7244, 2128, 5202, 1108, 5204, 86, 88, 6232, 2138, 1112, 92, 5210, 1120, 2146, 104, 4200, 106, 3178, 112, 7280, 116, 6262, 3192, 6270, 1150, 3204, 1158, 4232, 1160, 3208, 146, 3218, 6136, 5278, 4256, 4260, 6308, 166, 7332, 3242, 2220, 6318, 1202, 6324, 1206, 4284, 6332, 3262, 192, 3266, 7362, 7364, 198, 4296, 4300, 2258, 3282, 4312, 220, 3292, 6366, 5342, 5344, 7392, 2274, 1250, 1258, 4336, 1264, 244, 2294, 7414, 1272, 3322, 6402, 3332, 5380, 262, 7428, 6410, 1290, 268, 4364, 3340, 5388, 6416, 7438, 1296, 5396, 2328, 4376, 1304, 5402, 6430, 288, 1316, 7464, 6442, 5420, 7470, 3378, 6452, 7482, 7484, 2366, 1342, 5448, 7496, 5450, 334, 5454, 2388, 3412, 7512, 346, 3420, 5470, 1376, 4450, 6500, 3432, 366, 372, 4468, 2422, 3444, 376, 7548, 1408, 3458, 1414, 1416, 6540, 1424, 1426, 3474, 1428, 5528, 7576, 6554, 6558, 3486, 7586, 2476, 4528, 3510, 5558, 4536, 7606, 4552, 5576, 1482, 5578, 5580, 480, 2534, 4582, 5610, 7658, 6636, 1516, 3566, 5614, 7664, 2546, 1526, 7672, 3578, 7680, 6658, 5634, 5640, 4624, 2580, 5652, 5656, 4636, 2590, 1566, 1580, 2608, 6704, 1584, 2612, 3638, 568, 2618, 5694, 2624, 5698, 7746, 4678, 5704, 2636, 2642, 5716, 4694, 5726, 7774, 1634, 4708, 2662, 618, 4720, 1648, 1650, 2676, 3700, 7796, 634, 5756, 6782, 2688, 1664, 6790, 4746, 5770, 6796, 3726, 3730, 1686, 5782, 1688, 4766, 6814, 2720, 1700, 6822, 3752, 4780, 7852, 4782, 7864, 7866, 5820, 6848, 4802, 3778, 3780, 712, 2762, 3786, 1740, 1742, 2768, 1744, 5840, 1746, 6870, 1750, 1752, 6874, 3802, 732, 4828, 6880, 1760, 5860, 2790, 2792, 6890, 7914, 4858, 5882, 2812, 766, 1792, 2822, 2826, 3850, 2832, 5904, 5906, 1812, 790, 4886, 2840, 6938, 3868, 7966, 2848, 1824, 2852, 4900, 2858, 7978, 2860, 1836, 4910, 5932, 2866, 3894, 2872, 4926, 5952, 5954, 8002, 4932, 6982, 3910, 1864, 8008, 2890, 1866, 8010, 1868, 5964, 8012, 4946, 5970, 3928, 8024, 8026, 1884, 1886, 8040, 4970, 1898, 8042, 882, 890, 8060, 896, 4994, 6018, 902, 2950, 904, 3976, 3978, 908, 3980, 7054, 1934, 5016, 8088, 5018, 1946, 5022, 4000, 7074, 8100, 5030, 936, 938, 5036, 6060, 6062, 8110, 2992, 4018, 5046, 6070, 8128, 8132, 5062, 7116, 2002, 7124, 2004, 6100, 2006, 4058, 3036, 6110, 2016, 5092, 998, 6118, 6120, 2026, 1014, 5112, 2042]

eval_pointwise:  67%|██████▋   | 6/9 [00:00<00:00,  6.09it/s]

Detect 380 unknown interaction(s), position: [0, 4096, 3072, 2058, 7178, 6158, 7182, 4116, 22, 28, 7196, 34, 1060, 40, 5160, 7210, 6188, 3116, 7214, 48, 50, 2100, 1076, 5172, 1088, 68, 3142, 1102, 3154, 84, 6230, 1110, 3158, 92, 4196, 102, 110, 6258, 118, 5242, 7292, 4222, 5250, 4228, 1156, 5258, 4236, 3220, 6294, 2200, 154, 7322, 4256, 6306, 5282, 4262, 7336, 3250, 7346, 4276, 3254, 6328, 3258, 2242, 3266, 5316, 1222, 7366, 3272, 5320, 204, 5324, 4306, 4308, 6356, 1236, 7382, 6360, 1240, 1246, 5342, 226, 6370, 1256, 7400, 4334, 7406, 2288, 4336, 6386, 3312, 4342, 4348, 1276, 5374, 1280, 3332, 2310, 3334, 2312, 5382, 5384, 7430, 5386, 4366, 5392, 1300, 7444, 2328, 3356, 286, 290, 5412, 2342, 4390, 296, 6440, 1320, 4398, 2352, 4402, 6450, 2360, 6458, 3392, 1348, 5444, 4422, 1354, 7498, 2384, 6480, 1366, 350, 4446, 4448, 1376, 2402, 3426, 2404, 3434, 2412, 5486, 7536, 5490, 7538, 1404, 5502, 3456, 3458, 6532, 3460, 3462, 5510, 4488, 7560, 394, 402, 404, 7572, 6550, 7574, 408, 2460, 1436, 416, 1440, 5538, 5540, 4518, 3494, 5548, 3506, 5556, 7606, 2488, 6586, 4540, 6588, 3516, 5564, 7614, 7616, 1474, 460, 1486, 464, 468, 7638, 7640, 2534, 3558, 494, 4594, 3570, 4596, 504, 5626, 2556, 5628, 4608, 5634, 3588, 2568, 5640, 532, 4630, 7702, 3608, 7710, 5664, 4644, 4646, 3624, 4650, 6700, 558, 2606, 6708, 570, 2626, 3652, 7748, 5704, 592, 3666, 4698, 1626, 604, 6748, 5726, 1632, 5730, 612, 2660, 6758, 7780, 7782, 1640, 5736, 5742, 1650, 2676, 1652, 2678, 7802, 4732, 7804, 2686, 1662, 2688, 2690, 2692, 2694, 4742, 3722, 3730, 7830, 666, 6816, 1696, 7842, 678, 1702, 680, 682, 6826, 7856, 6836, 7862, 698, 1726, 3776, 4802, 6850, 4806, 2760, 716, 3790, 3794, 2772, 2776, 3800, 2778, 5848, 1764, 7912, 758, 6904, 6906, 5884, 1794, 776, 3848, 7946, 2828, 5900, 7948, 5902, 784, 7950, 1820, 3868, 4894, 5920, 4898, 6946, 6964, 5940, 4924, 2882, 836, 8004, 4938, 6986, 5962, 2896, 2898, 1878, 2904, 3930, 8028, 862, 4960, 8038, 2920, 5994, 2924, 880, 3952, 882, 888, 2936, 8058, 4988, 7036, 4990, 8060, 896, 6020, 7048, 906, 912, 8080, 7064, 2970, 926, 6046, 8094, 930, 2980, 6056, 4012, 7096, 4032, 7106, 5062, 968, 7112, 4040, 4048, 6096, 4050, 982, 7126, 2006, 986, 988, 3038, 8160, 5090, 3044, 4070, 5098, 5108, 1014, 6136, 2042, 8188, 6142]

eval_pointwise:  78%|███████▊  | 7/9 [00:01<00:00,  6.02it/s]

Detect 368 unknown interaction(s), position: [1024, 1026, 2052, 4100, 2054, 5124, 8, 2058, 6154, 3086, 2078, 5150, 36, 6182, 1062, 2088, 7206, 5160, 1066, 4142, 1070, 7218, 54, 7224, 4154, 3134, 64, 6208, 5186, 2116, 2120, 6224, 3154, 1114, 1126, 6248, 1130, 2156, 6254, 6260, 6262, 1144, 3192, 3194, 3204, 3206, 4232, 3208, 4234, 6282, 5256, 4242, 6292, 4246, 1174, 1176, 3224, 7322, 5276, 7324, 4258, 5286, 2216, 5292, 6320, 6322, 2232, 1218, 4292, 7364, 4296, 1224, 1228, 1230, 6354, 2260, 3288, 6364, 5344, 6370, 6372, 1254, 6376, 238, 6382, 4340, 5364, 5368, 7422, 5376, 4354, 6406, 7432, 4374, 7446, 7448, 2334, 4382, 3358, 5408, 1314, 7462, 6446, 5424, 3378, 310, 5430, 7488, 7498, 332, 6478, 4436, 1364, 344, 2394, 1370, 5470, 7520, 7522, 3430, 7526, 360, 2410, 6508, 3438, 1392, 6518, 3446, 376, 2428, 6524, 3460, 5508, 6538, 5514, 4494, 7570, 2452, 1432, 412, 4514, 2468, 422, 7590, 2472, 1452, 430, 6574, 432, 434, 2484, 3508, 2486, 6582, 3510, 1466, 5564, 1470, 7614, 2504, 6606, 3538, 7634, 2516, 2522, 478, 7646, 7650, 7654, 7658, 4596, 5624, 3578, 508, 3582, 3584, 6658, 5634, 3588, 5636, 2566, 7684, 3598, 1552, 4630, 3612, 3614, 3616, 5664, 2600, 5674, 6700, 3630, 3632, 4668, 5694, 4672, 3652, 2636, 7760, 5714, 5716, 7764, 6744, 6756, 5732, 1638, 4718, 3694, 1648, 1650, 3700, 2678, 6782, 3712, 646, 6790, 1670, 6794, 652, 1676, 4752, 6800, 5778, 2710, 6808, 2714, 1690, 5786, 4766, 6814, 7838, 4770, 7842, 684, 4780, 2734, 1708, 5804, 3758, 7852, 1712, 694, 1720, 1724, 7868, 1726, 3774, 708, 1732, 4810, 7882, 2766, 4814, 2770, 3798, 6872, 6876, 5856, 3812, 1766, 7910, 3818, 5866, 748, 6892, 750, 2798, 752, 5874, 758, 6906, 1786, 768, 2822, 1800, 7946, 780, 7948, 2830, 784, 5914, 3876, 1830, 4904, 6952, 3880, 7976, 3882, 5930, 7986, 1844, 3892, 6966, 3894, 3906, 8004, 838, 6984, 1864, 3912, 1866, 8010, 1870, 8014, 5968, 4948, 1878, 5974, 8024, 860, 3932, 4962, 868, 872, 4976, 1904, 4978, 2932, 1908, 7034, 2940, 1916, 3964, 4996, 1924, 4998, 6026, 2964, 5014, 2968, 1944, 2974, 8094, 2976, 1952, 5026, 1954, 8098, 6052, 8106, 5038, 7086, 5044, 7092, 3002, 7098, 4028, 4030, 6080, 4040, 7114, 1996, 974, 2004, 4052, 4054, 2008, 2010, 5084, 996, 7140, 3046, 3048, 8174, 4080, 1014, 5110]

eval_pointwise:  89%|████████▉ | 8/9 [00:01<00:00,  6.11it/s]

Detect 198 unknown interaction(s), position: [1024, 8, 520, 1546, 6156, 14, 1556, 6170, 3102, 6174, 34, 2082, 1060, 4132, 1062, 5670, 552, 2600, 3112, 3626, 556, 2092, 558, 4136, 2610, 3122, 1588, 2100, 566, 2614, 3064, 4664, 3130, 4666, 2112, 3066, 68, 4166, 2120, 4170, 2124, 594, 596, 1624, 6232, 2654, 2144, 6240, 1634, 614, 2664, 4712, 1130, 4092, 2162, 2166, 4094, 2680, 4726, 4218, 1670, 6278, 1166, 144, 1170, 2200, 2202, 1180, 2204, 670, 4252, 1190, 2216, 2218, 172, 3756, 1198, 4270, 178, 2228, 2234, 2746, 1724, 190, 4286, 4290, 1220, 4296, 4814, 5330, 212, 5334, 6360, 1244, 5342, 4330, 240, 4850, 2294, 3832, 5882, 2812, 4348, 2816, 5890, 2308, 3844, 3334, 3846, 1288, 4362, 268, 2320, 280, 288, 2348, 4912, 830, 1856, 326, 1350, 328, 2886, 1868, 3404, 1872, 1878, 3414, 1368, 3416, 1370, 4440, 1884, 1886, 4446, 352, 6494, 1892, 6500, 358, 1894, 872, 3430, 2922, 1900, 6178, 2928, 884, 6008, 890, 3452, 2432, 386, 898, 1412, 5508, 1928, 2448, 3474, 1946, 5530, 1954, 3492, 2470, 4010, 4522, 1454, 2992, 6068, 2488, 6072, 3004, 1982, 1984, 1986, 1478, 6088, 1484, 5068, 462, 1998, 2000, 4564, 2016, 3042, 486, 6118, 2538, 6122, 1520, 500, 1524, 2038, 3062, 2552, 506, 3068, 2046]

eval_pointwise: 100%|██████████| 9/9 [00:01<00:00,  6.25it/s]
eval_listwise: 100%|██████████| 6318/6318 [00:00<00:00, 7094.45it/s]

loss: 16.606322667287863
roc_auc: 0.5411699302798277
precision: 0.031228236783792336
recall: 0.07843033651241647
ndcg: 0.18769990932548294

In [12]:
unique_users = test_ratings['user'].unique()
print(len(unique_users))

6318

In [13]:
import numpy as np
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count

def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0

def evaluate_user_cf_model(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []
    iteration_counter = 0

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user'] == user]['item'].values

        # Get items the user has not seen
        # unseen_items = np.setdiff1d(all_items, seen_items)

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values

        y_score = [1 if item in test_items else 0 for item in recommended_items]
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)
        iteration_counter += 1

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))

    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
        'Recall@{}'.format(k): avg_recall,
        'MRR@{}'.format(k): avg_mrr,
    }

# all_items = movies['item_id'].unique()
all_items = items['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model(user_cf, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(user_cf, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_35228\774034423.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.7494054887964802, 'Recall@5': 0.06428771155699957, 'MRR@5': 0.15456895642080826}
{'NDCG@10': 0.6936378254664127, 'Recall@10': 0.07446002238290779, 'MRR@10': 0.15927973489701885}

In [ ]:
{'NDCG@5': 0.7494054887964802, 'Recall@5': 0.06428771155699957, 'MRR@5': 0.15456895642080826}
{'NDCG@10': 0.6936378254664127, 'Recall@10': 0.07446002238290779, 'MRR@10': 0.15927973489701885}

In [14]:
def evaluate_user_cf_model(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user'] == user]['item'].values

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values
        labels = user_test_data['label'].values


        y_score = [
            user_test_data[user_test_data['item'] == item]['label'].values[0] if item in test_items else 0
            for item in recommended_items
        ]

        # y_score = [
        #     user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 2.5
        #     for item in recommended_items
        # ]

        ndcg = ndcg_at_k(y_score, k)
        # recall = recall_at_k(labels, k)

        ndcg_scores.append(ndcg)
        # recall_scores.append(recall)
        # print(user)
    # avg_ndcg = np.nanmean(ndcg_scores)
    # avg_recall = np.nanmean(recall_scores)
    avg_ndcg = np.nanmean(ndcg_scores)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))
    # avg_recall = np.mean(np.nan_to_num(recall_scores, nan=0.0))
    return {
        'NDCG@{}'.format(k): avg_ndcg,
        # 'Recall@{}'.format(k): avg_recall
    }

# all_items = movies['item_id'].unique()
all_items = items['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model(user_cf, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(user_cf, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_35228\774034423.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.7501314226752376}
{'NDCG@10': 0.6935999151129002}

In [ ]:
{'NDCG@5': 0.7482504128365846}
{'NDCG@10': 0.6943043653737456}

In [15]:
import numpy as np
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def evaluate_user_cf_model2(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user'] == user]['item'].values

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values
        labels = user_test_data['label'].values


        # y_score = [
        #     user_test_data[user_test_data['item'] == item]['label'].values[0] if item in test_items else 0
        #     for item in recommended_items
        # ]

        y_score = [
            user_test_data[user_test_data['item'] == item]['label'].values[0] if item in test_items else 2.5
            for item in recommended_items
        ]

        ndcg = ndcg_at_k(y_score, k)
        # recall = recall_at_k(labels, k)

        ndcg_scores.append(ndcg)
        # recall_scores.append(recall)
        # print(user)
    # avg_ndcg = np.nanmean(ndcg_scores)
    # avg_recall = np.nanmean(recall_scores)
    avg_ndcg = np.nanmean(ndcg_scores)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))
    # avg_recall = np.mean(np.nan_to_num(recall_scores, nan=0.0))
    return {
        'NDCG@{}'.format(k): avg_ndcg,
        # 'Recall@{}'.format(k): avg_recall
    }

# all_items = movies['item_id'].unique()
all_items = items['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model2(user_cf, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model2(user_cf, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

{'NDCG@5': 0.9860779305856874}
{'NDCG@10': 0.9843315701713524}

In [ ]:
{'NDCG@5': 0.986232785657715}
{'NDCG@10': 0.9843870995527803}

In [40]:
def evaluate_user_cf_model2(model, test_data, train_data, all_items, k):
    ndcg_scores = []
    recall_scores = []

    # Get unique users
    unique_users = test_data['user'].unique()

    for user in unique_users:
        # Get items the user has seen in the training data
        seen_items = train_data[train_data['user'] == user]['item'].values

        # Get items the user has not seen
        unseen_items = np.setdiff1d(all_items, seen_items)

        # Recommend items for the user using the model|
        recommended_items = model.recommend_user(user, n_rec=k, filter_consumed=True)
        recommended_items = recommended_items[user]
        user_test_data = test_data[test_data['user'] == user]
        test_items = user_test_data['item'].values
        labels = user_test_data['label'].values


        # y_score = [1 if item in test_items else 0 for item in recommended_items]
        y_score = [
            1 if (item in test_items and user_test_data[user_test_data['item'] == item]['label'].values[0] == 1) else 0
            for item in recommended_items
        ]
        ndcg = ndcg_at_k(y_score, k)
        # recall = recall_at_k(labels, k)

        ndcg_scores.append(ndcg)
        # recall_scores.append(recall)
        # print(user)
    # avg_ndcg = np.nanmean(ndcg_scores)
    # avg_recall = np.nanmean(recall_scores)
    avg_ndcg = np.nanmean(ndcg_scores)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))
    # avg_recall = np.mean(np.nan_to_num(recall_scores, nan=0.0))
    return {
        'NDCG@{}'.format(k): avg_ndcg,
        # 'Recall@{}'.format(k): avg_recall
    }

# all_items = movies['item_id'].unique()
all_items = items['parent_asin'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model2(user_cf, test_ratings, train_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model2(user_cf, test_ratings, train_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_2184\4081532848.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)
C:\Users\Hooman\AppData\Local\Temp\ipykernel_2184\2871655273.py:36: RuntimeWarning: Mean of empty slice
  avg_ndcg = np.nanmean(ndcg_scores)

{'NDCG@5': nan}
{'NDCG@10': nan}