In [1]:
import pandas as pd
from libreco.data import DatasetPure
from libreco.algorithms import UserCF

WARNING:tensorflow:From D:\Anaconda\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [1]:
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_traindata_movielens.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_valdata_movielens.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_testdata_movielens.csv')
# train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_train_movielens.csv')
# val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_val_movielens.csv')
# test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_test_movielens.csv')

movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')

NameError: name 'pd' is not defined

In [6]:
train_ratings

        user_id  item_id  rating  timestamp
0             1     3186       1  978300019
1             1     1022       1  978300055
2             1     1721       1  978300055
3             1     1270       1  978300055
4             1     2340       1  978300103
...         ...      ...     ...        ...
797753     6040     2612       1  960971797
797754     6040     2303       1  960971857
797755     6040     3504       1  960971857
797756     6040     1449       1  960971857
797757     6040     3334       1  960971875

[797758 rows x 4 columns]

In [7]:
train_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'},
                     inplace=True)
val_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
test_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'},
                    inplace=True)

In [8]:
train_data, data_info = DatasetPure.build_trainset(train_ratings)
eval_data = DatasetPure.build_evalset(val_ratings)
test_data = DatasetPure.build_testset(test_ratings)
print(data_info)  # n_users: 5894, n_items: 3253, data sparsity: 0.4172 %

n_users: 6040, n_items: 3667, data density: 3.6018 %

In [9]:
train_ratings = train_ratings.sort_values(by='time')
val_ratings = val_ratings.sort_values(by='time')
test_ratings = test_ratings.sort_values(by='time')

In [12]:
user_cf = UserCF(task="ranking", data_info=data_info, k_sim=10, sim_type="cosine", mode='invert')
# 200

In [13]:
# Training the model
user_cf.fit(train_data, verbose=2, eval_data=eval_data, k=5,
            metrics=["loss", "roc_auc", "precision", "recall", "ndcg"], neg_sampling=True)

Training start time: 2025-02-01 19:13:21
Final block size and num: (6040, 1)
sim_matrix elapsed: 3.407s
sim_matrix, shape: (6040, 6040), num_elements: 33103268, density: 90.7396 %

top_k: 100%|██████████| 6040/6040 [00:07<00:00, 817.65it/s]
eval_pointwise:   4%|▍         | 1/25 [00:00<00:04,  5.19it/s]

Detect 1 unknown interaction(s), position: [5602]
No common interaction or similar neighbor for user 0 and item 2344, proceed with default prediction
No common interaction or similar neighbor for user 0 and item 91, proceed with default prediction
No common interaction or similar neighbor for user 0 and item 818, proceed with default prediction
No common interaction or similar neighbor for user 0 and item 2456, proceed with default prediction
No common interaction or similar neighbor for user 0 and item 2700, proceed with default prediction
No common interaction or similar neighbor for user 1 and item 1605, proceed with default prediction

eval_pointwise:   8%|▊         | 2/25 [00:00<00:04,  5.23it/s]

Detect 1 unknown interaction(s), position: [5320]

eval_pointwise:  12%|█▏        | 3/25 [00:00<00:04,  5.22it/s]

Detect 2 unknown interaction(s), position: [6104, 4798]

eval_pointwise:  24%|██▍       | 6/25 [00:01<00:03,  5.37it/s]

Detect 4 unknown interaction(s), position: [7664, 3522, 7728, 7722]
Detect 1 unknown interaction(s), position: [4480]

eval_pointwise:  36%|███▌      | 9/25 [00:01<00:02,  5.42it/s]

Detect 1 unknown interaction(s), position: [6206]

eval_pointwise:  40%|████      | 10/25 [00:01<00:02,  5.32it/s]

Detect 1 unknown interaction(s), position: [4080]

eval_pointwise:  52%|█████▏    | 13/25 [00:02<00:02,  5.26it/s]

Detect 1 unknown interaction(s), position: [1426]

eval_pointwise:  64%|██████▍   | 16/25 [00:03<00:01,  5.34it/s]

Detect 1 unknown interaction(s), position: [4530]
Detect 2 unknown interaction(s), position: [8026, 7654]

eval_pointwise:  72%|███████▏  | 18/25 [00:03<00:01,  5.40it/s]

Detect 2 unknown interaction(s), position: [1280, 3058]

eval_pointwise:  88%|████████▊ | 22/25 [00:04<00:00,  5.26it/s]

Detect 1 unknown interaction(s), position: [3300]

eval_pointwise: 100%|██████████| 25/25 [00:04<00:00,  5.45it/s]
eval_listwise: 100%|██████████| 2997/2997 [00:18<00:00, 160.19it/s]

	 eval log_loss: 10.6527
	 eval roc_auc: 0.6278
	 eval precision@5: 0.0665
	 eval recall@5: 0.0445
	 eval ndcg@5: 0.1602
==============================

In [8]:
from libreco.evaluation import evaluate

# Evaluate the model on the test data with the specified metrics
evaluation_results = evaluate(
    model=user_cf,
    data=test_data,
    neg_sampling=True,
    metrics=["loss", "roc_auc", "precision", "recall", "ndcg"]
)

# Print the evaluation results
for metric, value in evaluation_results.items():
    print(f"{metric}: {value}")

eval_pointwise:   0%|          | 0/26 [00:00<?, ?it/s]

Detect 1 unknown interaction(s), position: [1344]

eval_pointwise:   8%|▊         | 2/26 [00:01<00:12,  1.89it/s]

Detect 2 unknown interaction(s), position: [1890, 812]

eval_pointwise:  19%|█▉        | 5/26 [00:02<00:10,  1.91it/s]

Detect 1 unknown interaction(s), position: [4572]

eval_pointwise:  23%|██▎       | 6/26 [00:03<00:10,  1.92it/s]

Detect 3 unknown interaction(s), position: [1016, 1362, 932]

eval_pointwise:  27%|██▋       | 7/26 [00:03<00:09,  1.92it/s]

Detect 2 unknown interaction(s), position: [4248, 5354]

eval_pointwise:  31%|███       | 8/26 [00:04<00:09,  1.92it/s]

Detect 4 unknown interaction(s), position: [1056, 8146, 796, 6824]

eval_pointwise:  38%|███▊      | 10/26 [00:05<00:08,  1.94it/s]

Detect 1 unknown interaction(s), position: [3668]

eval_pointwise:  42%|████▏     | 11/26 [00:05<00:07,  1.93it/s]

Detect 1 unknown interaction(s), position: [6100]

eval_pointwise:  50%|█████     | 13/26 [00:06<00:06,  1.89it/s]

Detect 2 unknown interaction(s), position: [2872, 4758]

eval_pointwise:  54%|█████▍    | 14/26 [00:07<00:06,  1.89it/s]

Detect 2 unknown interaction(s), position: [3552, 3450]

eval_pointwise:  65%|██████▌   | 17/26 [00:08<00:04,  1.91it/s]

Detect 9 unknown interaction(s), position: [4128, 3718, 7302, 3696, 4018, 3924, 3958, 3834, 4030]

eval_pointwise:  73%|███████▎  | 19/26 [00:09<00:03,  1.96it/s]

Detect 2 unknown interaction(s), position: [2312, 4330]

eval_pointwise:  77%|███████▋  | 20/26 [00:10<00:03,  1.96it/s]

Detect 1 unknown interaction(s), position: [862]

eval_pointwise:  85%|████████▍ | 22/26 [00:11<00:02,  1.89it/s]

Detect 2 unknown interaction(s), position: [4542, 886]

eval_pointwise:  88%|████████▊ | 23/26 [00:12<00:01,  1.91it/s]

Detect 2 unknown interaction(s), position: [4738, 4766]

eval_pointwise:  92%|█████████▏| 24/26 [00:12<00:01,  1.91it/s]

Detect 1 unknown interaction(s), position: [8184]

eval_pointwise: 100%|██████████| 26/26 [00:13<00:00,  1.98it/s]
eval_listwise:   9%|▊         | 262/3020 [00:36<06:27,  7.12it/s]

KeyboardInterrupt:

In [14]:
cf_recommendations = {}

# Assume unique_users is a list or array of all user IDs
for user in test_ratings['user'].unique():
    # Generate top N recommendations for the user using the Collaborative Filtering model
    recommended_items = user_cf.recommend_user(user, n_rec=5, filter_consumed=True)
    cf_recommendations[user] = recommended_items[user]  # Store the recommendations in the dictionary
cf_recommendations

KeyboardInterrupt:

In [43]:
movies

,item_id,title,genres,year,movie_features
0,1,Toy Story,"Animation, Children's, Comedy",1995,"[MOVIE_DETAIL] genres: Animation, Children's, ..."
1,2,Jumanji,"Adventure, Children's, Fantasy",1995,"[MOVIE_DETAIL] genres: Adventure, Children's, ..."
2,3,Grumpier Old Men,"Comedy, Romance",1995,"[MOVIE_DETAIL] genres: Comedy, Romance"
3,4,Waiting to Exhale,"Comedy, Drama",1995,"[MOVIE_DETAIL] genres: Comedy, Drama"
4,5,Father of the Bride Part II,Comedy,1995,[MOVIE_DETAIL] genres: Comedy
...,...,...,...,...,...
3878,3948,Meet the Parents,Comedy,2000,[MOVIE_DETAIL] genres: Comedy
3879,3949,Requiem for a Dream,Drama,2000,[MOVIE_DETAIL] genres: Drama
3880,3950,Tigerland,Drama,2000,[MOVIE_DETAIL] genres: Drama
3881,3951,Two Family House,Drama,2000,[MOVIE_DETAIL] genres: Drama
3882,3952,"Contender, The","Drama, Thriller",2000,"[MOVIE_DETAIL] genres: Drama, Thriller"

### Two-Tower Model

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
import pytorch_lightning as pl
from sentence_transformers import SentenceTransformer
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
from pytorch_lightning.callbacks import Callback
import pandas as pd
import pickle
from pytorch_lightning.callbacks import ModelCheckpoint

D:\Anaconda\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
D:\Anaconda\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(

In [12]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [13]:
full_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_full_movielens.csv')
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_train_movielens.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_val_movielens.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_test_movielens.csv')

movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')
users = pd.read_csv('processed_dataset/MovieLens-1M/users/users_movielens_modified.csv')

In [431]:
movies['movie_features'] = '[MOVIE_DETAIL] title: ' + movies['title'] + ' [SEP] genres: ' + movies['genres']
movies['movie_features']

0       [MOVIE_DETAIL] title: Toy Story (1995) [SEP] g...
1       [MOVIE_DETAIL] title: Jumanji (1995) [SEP] gen...
2       [MOVIE_DETAIL] title: Grumpier Old Men (1995) ...
3       [MOVIE_DETAIL] title: Waiting to Exhale (1995)...
4       [MOVIE_DETAIL] title: Father of the Bride Part...
                              ...
3878    [MOVIE_DETAIL] title: Meet the Parents (2000) ...
3879    [MOVIE_DETAIL] title: Requiem for a Dream (200...
3880    [MOVIE_DETAIL] title: Tigerland (2000) [SEP] g...
3881    [MOVIE_DETAIL] title: Two Family House (2000) ...
3882    [MOVIE_DETAIL] title: Contender, The (2000) [S...
Name: movie_features, Length: 3883, dtype: object

In [432]:
# Create a dictionary for fast lookup
movie_features_dict = movies.set_index('item_id')['movie_features'].to_dict()

# Create lists of user and item texts
item_texts = [movie_features_dict[movieId] for movieId in full_ratings['item_id'].unique()]

# Create a mapping from userId and movieId to indices
movie_id_to_idx = {movieId: idx for idx, movieId in enumerate(full_ratings['item_id'].unique())}

# Map userId and movieId in ratings_df to indices
train_ratings['movie_idx'] = train_ratings['item_id'].map(movie_id_to_idx)

# Map userId and movieId in ratings_val to indices
val_ratings['movie_idx'] = val_ratings['item_id'].map(movie_id_to_idx)

# Map userId and movieId in ratings_test to indices
test_ratings['movie_idx'] = test_ratings['item_id'].map(movie_id_to_idx)

# Extract user indices, item indices, and ratings
train_item_indices = torch.LongTensor(train_ratings['movie_idx'].values).to(device)
train_labels = torch.FloatTensor(train_ratings['rating'].values).to(device)

# Extract user indices, item indices, and ratings for validation
val_item_indices = torch.LongTensor(val_ratings['movie_idx'].values).to(device)
val_labels = torch.FloatTensor(val_ratings['rating'].values).to(device)

# Extract user indices, item indices, and ratings for test
test_item_indices = torch.LongTensor(test_ratings['movie_idx'].values).to(device)
test_labels = torch.FloatTensor(test_ratings['rating'].values).to(device)

In [16]:
class TwoTowerModel(pl.LightningModule):
    def __init__(self, user_model_name, item_model_name, embedding_size=384):
        super(TwoTowerModel, self).__init__()
        self.user_model = SentenceTransformer(user_model_name)
        self.item_model = SentenceTransformer(item_model_name)

        self.user_fc = nn.Linear(embedding_size, embedding_size)
        self.item_fc = nn.Linear(embedding_size, embedding_size)

        self.criterion = nn.MSELoss()
        self.epoch_losses = {'train_loss': [], 'val_loss': []}

    def forward(self, user_text, item_text):
        user_embedding = self.user_model.encode(user_text, convert_to_tensor=True).to(device)
        item_embedding = self.item_model.encode(item_text, convert_to_tensor=True).to(device)

        user_output = self.user_fc(user_embedding)
        item_output = self.item_fc(item_embedding)

        dot_product = torch.matmul(user_output.squeeze(), item_output.T)
        dot_product = 4 * torch.sigmoid(dot_product) + 1

        return dot_product

    def training_step(self, batch, batch_idx):
        users, items, ratings = batch

        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        users, items, ratings = batch

        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('val_loss', loss)
        return loss

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=1e-5)


class PrintLossesCallback(Callback):
    def on_train_epoch_end(self, trainer, pl_module):
        train_loss = trainer.callback_metrics.get('train_loss')
        if train_loss is not None:
            pl_module.epoch_losses['train_loss'].append(train_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Train Loss: {train_loss.item()}")

    def on_validation_epoch_end(self, trainer, pl_module):
        val_loss = trainer.callback_metrics.get('val_loss')
        if val_loss is not None:
            pl_module.epoch_losses['val_loss'].append(val_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Val Loss: {val_loss.item()}")

In [17]:
best_model_path = './lightning_logs/movies/paraphrase-MiniLM-L12-v2/not-binarized/history_5-epochs_lr-1e-5_(occu + gen ) (new format - only genre for movies) (with header tag)/checkpoints/epoch=4-step=62320.ckpt'
# best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L6-v2', item_model_name='paraphrase-MiniLM-L6-v2').to(device)
best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L12-v2',
                                                item_model_name='paraphrase-MiniLM-L12-v2').to(device)

D:\Anaconda\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
D:\Anaconda\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(

In [18]:
def generate_last_user_texts_with_history(users, movies, ratings):
    user_histories = {user_id: [] for user_id in users['user_id'].unique()}
    last_user_texts = {}

    # Convert relevant columns to dictionaries for faster access
    user_features_dict = users.set_index('user_id').to_dict('index')
    movie_titles_dict = movies.set_index('item_id')['genres'].to_dict()

    for _, row in ratings.iterrows():
        user_id = row['user_id']
        movie_id = row['item_id']

        # Get user features
        user = user_features_dict[user_id]
        user_features = f"[USER_PROFILE] occupation: {user['occupation']} [SEP] gender: {user['gender']}"

        # Append the user's history (only the last 3 movies)
        history_movies = [movie_titles_dict[mid] for mid in user_histories[user_id][-3:]]

        history_str = ", ".join(history_movies)

        if history_str:
            combined_features = f"{user_features} [SEP] genres: {history_str}"
        else:
            combined_features = f"{user_features}"

        # Update the dictionary to keep the last text for each user
        last_user_texts[user_id] = combined_features

        # Update the user history after generating combined features
        user_histories[user_id].append(movie_id)

    return last_user_texts


# Generate the last user texts for the validation data
val_last_user_texts = generate_last_user_texts_with_history(users, movies, val_ratings)

In [19]:
val_last_user_texts.get(5)

'[USER_PROFILE] occupation: writer [SEP] gender: Male [SEP] genres: Crime, Drama, Drama, Romance, Drama'

In [221]:
def get_top_n_items_with_history_unseen_items(model, userId, n):
    # Ensure the model is in evaluation mode
    model.eval()

    # Get the user text for the given userId
    user_text = val_last_user_texts[userId]
    # Encode the user text
    user_embedding = model.user_model.encode(user_text, convert_to_tensor=True).to(device)

    # Compute the scores (dot product between user embedding and each item embedding)
    user_output = model.user_fc(user_embedding).to(device)
    item_output = model.item_fc(full_items_embeddings).to(device)
    dot_product = torch.matmul(user_output, item_output.t()).squeeze()

    # Get items the user has seen in the training and validation data
    seen_items_train = train_ratings[train_ratings['user_id'] == userId]['item_id'].values
    seen_items_val = val_ratings[val_ratings['user_id'] == userId]['item_id'].values
    seen_items = set(np.concatenate((seen_items_train, seen_items_val)))

    # Get the top n + len(seen_items) item indices and their scores
    top_n_scores, top_n_indices = torch.topk(dot_product, n + len(seen_items))

    # Map indices back to item IDs
    top_n_item_ids = [list(movie_id_to_idx.keys())[list(movie_id_to_idx.values()).index(idx.item())] for idx in
                      top_n_indices]

    # Filter out seen items
    unseen_top_n_item_ids = [item for item in top_n_item_ids if item not in seen_items]
    # print(unseen_top_n_item_ids[:n])
    return unseen_top_n_item_ids[:n]

In [434]:
full_items_embeddings = torch.stack(
    [best_model.item_model.encode(item_text, convert_to_tensor=True) for item_text in item_texts]).to(device)

In [22]:
tt_recommendations = {}

for user in test_ratings['user_id'].unique():
    # Generate top N recommendations for the user using the Two-Tower model
    recommended_items = get_top_n_items_with_history_unseen_items(best_model, user, n=5)
    tt_recommendations[user] = recommended_items  # Store the recommendations in the dictionary

In [25]:
def rrf_score(ranks, k=4):
    return sum([1 / (k + rank) for rank in ranks])


def combine_recommendations_with_rrf(user_id, cf_recommendations, tt_recommendations, k=5):
    # Create a dictionary to hold the RRF scores
    combined_scores = {}

    # Assign ranks and calculate RRF scores from Collaborative Filtering recommendations
    for rank, item in enumerate(cf_recommendations[user_id], start=1):
        if item not in combined_scores:
            combined_scores[item] = rrf_score([rank], k)
        else:
            combined_scores[item] += rrf_score([rank], k)

    # Assign ranks and calculate RRF scores from Two-Tower recommendations
    for rank, item in enumerate(tt_recommendations[user_id], start=1):
        if item not in combined_scores:
            combined_scores[item] = rrf_score([rank], k)
        else:
            combined_scores[item] += rrf_score([rank], k)

    # Sort the items based on their RRF scores in descending order
    sorted_items = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)

    # Return the top N items
    return [item for item, score in sorted_items[:k]]

In [26]:
final_recommendations_without_weight = {}
for user_id in test_ratings['user_id'].unique():
    final_recommendations_without_weight[user_id] = combine_recommendations_with_rrf(user_id, cf_recommendations,
                                                                                     tt_recommendations, k=5)

# Now final_recommendations contains the combined top N recommendations for each user
final_recommendations_without_weight

{1: [1196, 922, 318, 2066, 1198],
 2: [527, 922, 260, 2066, 608],
 3: [2571, 922, 2028, 2066, 589],
 4: [1240, 3121, 858, 1153, 2571],
 5: [2396, 922, 527, 2066, 1265],
 6: [919, 922, 1307, 2066, 1197],
 7: [260, 3121, 1210, 1153, 1198],
 8: [318, 922, 593, 2066, 1617],
 9: [296, 922, 2997, 2066, 110],
 10: [260, 922, 1196, 2066, 2571],
 11: [296, 922, 2028, 2066, 527],
 12: [260, 1154, 1196, 1153, 318],
 13: [1240, 922, 733, 2066, 1200],
 14: [2716, 1154, 223, 1153, 2599],
 15: [589, 922, 608, 2066, 1],
 16: [2858, 922, 2706, 2066, 2716],
 17: [1580, 922, 1199, 2066, 2985],
 18: [2571, 922, 480, 2066, 1214],
 19: [589, 922, 480, 2066, 2916],
 20: [480, 1154, 1580, 1153, 593],
 21: [260, 1153, 1196, 1154, 3114],
 22: [260, 922, 1198, 2066, 356],
 23: [1270, 922, 1210, 2066, 1374],
 24: [1196, 922, 1198, 2066, 1265],
 25: [589, 922, 1240, 2066, 2916],
 26: [1210, 922, 2028, 2066, 260],
 27: [912, 746, 908, 2940, 1230],
 28: [2858, 922, 527, 2066, 858],
 29: [2028, 922, 1197, 2066, 2194],
 30: [1704, 922, 110, 2066, 2396],
 31: [1294, 922, 1278, 2066, 1079],
 32: [318, 922, 296, 2066, 527],
 33: [2028, 922, 1617, 2066, 1036],
 34: [1265, 922, 2797, 2066, 1394],
 35: [858, 922, 923, 2066, 260],
 36: [1198, 922, 318, 2066, 50],
 37: [39, 922, 1270, 2066, 1393],
 38: [597, 922, 1265, 2066, 11],
 39: [2762, 922, 2694, 2066, 1093],
 40: [260, 922, 480, 2066, 2028],
 41: [1198, 1154, 2571, 1153, 589],
 42: [1676, 922, 2028, 2066, 110],
 43: [2858, 1154, 2716, 1153, 2683],
 44: [1214, 922, 541, 2066, 1200],
 45: [356, 922, 2797, 2066, 260],
 46: [1387, 922, 1258, 2066, 1214],
 47: [2858, 3121, 2028, 1153, 1213],
 48: [2000, 922, 1214, 2066, 608],
 49: [260, 922, 1198, 2066, 110],
 50: [589, 922, 110, 2066, 3481],
 51: [2997, 922, 527, 2066, 2028],
 52: [2571, 922, 377, 2066, 3256],
 53: [1198, 2066, 1197, 746, 527],
 54: [1294, 922, 1270, 2066, 2858],
 55: [2858, 1154, 2028, 1153, 608],
 56: [1265, 922, 589, 2066, 356],
 57: [3481, 922, 589, 2066, 110],
 58: [50, 922, 1265, 2066, 924],
 59: [858, 922, 608, 2066, 527],
 60: [480, 922, 2571, 2066, 2916],
 61: [2858, 922, 3751, 2066, 3408],
 62: [527, 922, 1197, 2066, 1265],
 63: [2997, 922, 2355, 2066, 2710],
 64: [1196, 3121, 2571, 1153, 260],
 65: [589, 922, 457, 2066, 1210],
 66: [589, 1154, 1580, 1153, 2571],
 67: [858, 922, 912, 2066, 1193],
 68: [1079, 922, 1270, 2066, 1394],
 69: [608, 922, 318, 2066, 527],
 70: [2710, 922, 2502, 2066, 2762],
 71: [2858, 3380, 3578, 3121, 2706],
 72: [1265, 922, 1, 2066, 357],
 73: [260, 922, 1127, 2066, 1214],
 74: [2858, 922, 1213, 2066, 527],
 75: [260, 922, 1198, 2066, 1197],
 76: [527, 922, 2028, 2066, 2997],
 77: [223, 922, 2716, 2066, 2355],
 78: [1028, 922, 1197, 2066, 1580],
 79: [3578, 3121, 2858, 1153, 480],
 80: [318, 922, 2571, 2066, 2858],
 81: [858, 922, 923, 2066, 608],
 82: [2028, 922, 356, 2066, 1610],
 83: [2997, 922, 2706, 2066, 2599],
 84: [589, 3121, 1036, 1153, 858],
 85: [3753, 922, 3623, 2066, 2997],
 86: [2571, 922, 260, 2066, 1196],
 87: [1210, 922, 858, 2066, 1214],
 88: [2858, 922, 593, 2066, 919],
 89: [318, 3380, 593, 1153, 2858],
 90: [296, 922, 2571, 2066, 593],
 91: [1265, 922, 2858, 2066, 1270],
 92: [1196, 922, 260, 2066, 1210],
 93: [110, 922, 1374, 2066, 1527],
 94: [1214, 3121, 1387, 1153, 589],
 95: [2858, 922, 318, 2066, 593],
 96: [2858, 922, 1704, 2066, 1198],
 97: [908, 2066, 1230, 746, 608],
 98: [2858, 1153, 480, 3380, 110],
 99: [593, 922, 2571, 2066, 2762],
 100: [1240, 922, 589, 2066, 1036],
 101: [1291, 922, 110, 2066, 1610],
 102: [2762, 922, 2716, 2066, 223],
 103: [377, 922, 2628, 2066, 1196],
 104: [2716, 922, 1127, 2066, 2599],
 105: [1198, 922, 1240, 2066, 1036],
 106: [912, 922, 1197, 2066, 1265],
 107: [527, 922, 904, 2066, 2858],
 108: [589, 922, 110, 2066, 1580],
 109: [1197, 922, 1097, 2066, 1136],
 110: [2571, 922, 2028, 2066, 593],
 111: [608, 922, 2858, 2066, 1704],
 112: [260, 746, 2081, 2940, 1196],
 113: [110, 922, 1196, 2066, 2628],
 114: [594, 922, 260, 2066, 3114],
 115: [589, 922, 3753, 2066, 110],
 116: [2858, 922, 2716, 2066, 2762],
 117: [480, 922, 1127, 2066, 3527],
 118: [1240, 922, 1610, 2066, 2000],
 119: [1210, 922, 2081, 2066, 2858],
 120: [2028, 922, 1617, 2066, 912],
 121: [1240, 922, 589, 2066, 1200],
 122: [2571, 922, 1036, 2066, 110],
 123: [1265, 922, 1197, 2066, 1220],
 124: [318, 1154, 593, 1153, 608],
 125: [260, 922, 1198, 2066, 1196],
 126: [1196, 922, 1198, 2066, 2028],
 127: [2916, 922, 1198, 2066, 318],
 128: [480, 3380, 589, 1153, 110],
 129: [260, 922, 589, 2066, 457],
 130: [1197, 922, 1304, 2066, 1127],
 131: [1213, 922, 1196, 2066, 1394],
 132: [2791, 922, 2918, 2066, 1270],
 133: [608, 922, 1704, 2066, 2571],
 134: [2028, 922, 1610, 2066, 1196],
 135: [2997, 922, 2599, 2066, 3578],
 136: [1198, 2066, 296, 746, 593],
 137: [593, 922, 50, 2066, 380],
 138: [2028, 922, 527, 2066, 260],
 139: [2571, 922, 1240, 2066, 589],
 140: [1252, 922, 908, 2066, 910],
 141: [110, 2727, 589, 1153, 1580],
 142: [593, 922, 608, 2066, 527],
 143: [589, 922, 457, 2066, 480],
 144: [2762, 922, 2028, 2066, 110],
 145: [2355, 922, 2712, 2066, 2770],
 146: [750, 922, 1270, 2066, 1304],
 147: [2916, 922, 1240, 2066, 593],
 148: [1214, 922, 733, 2066, 2001],
 149: [2791, 922, 1291, 2066, 356],
 150: [50, 922, 1213, 2066, 858],
 151: [260, 922, 318, 2066, 1198],
 152: [2858, 1154, 1270, 1153, 1265],
 153: [2683, 3121, 223, 3380, 2997],
 154: [2706, 922, 223, 2066, 2580],
 155: [356, 922, 1, 2066, 2858],
 156: [39, 922, 1784, 2066, 587],
 157: [1036, 922, 1220, 2066, 296],
 158: [913, 1153, 1252, 1154, 858],
 159: [2716, 922, 2762, 2066, 2997],
 160: [589, 1153, 1196, 3380, 1580],
 161: [858, 922, 1193, 2066, 1230],
 162: [2571, 922, 1210, 2066, 1610],
 163: [318, 922, 1610, 2066, 527],
 164: [912, 3380, 260, 2727, 527],
 165: [2571, 922, 3471, 2066, 750],
 166: [318, 2066, 1197, 746, 858],
 167: [2858, 922, 3510, 2066, 3793],
 168: [1198, 3121, 1210, 3380, 858],
 169: [1210, 2066, 1580, 746, 2396],
 170: [924, 922, 1197, 2066, 2529],
 171: [2858, 2727, 608, 1153, 2028],
 172: [1252, 2727, 1617, 1153, 541],
 173: [1193, 746, 1304, 2940, 2028],
 174: [1198, 922, 1196, 2066, 2028],
 175: [608, 922, 50, 2066, 1270],
 176: [2791, 922, 1259, 2066, 3210],
 177: [2571, 922, 1214, 2066, 589],
 178: [1270, 922, 1097, 2066, 595],
 179: [260, 922, 1214, 2066, 480],
 180: [318, 922, 1213, 2066, 527],
 181: [260, 922, 589, 2066, 593],
 182: [2858, 922, 1923, 2066, 2571],
 183: [1617, 922, 912, 2066, 858],
 184: [260, 922, 1210, 2066, 1197],
 185: [2571, 922, 457, 2066, 733],
 186: [110, 922, 3114, 2066, 593],
 187: [527, 922, 2997, 2066, 3006],
 188: [2858, 922, 2997, 2066, 2716],
 189: [527, 3121, 296, 1153, 2571],
 190: [1198, 922, 1196, 2066, 318],
 191: [2683, 3380, 2028, 3121, 2997],
 192: [593, 922, 2028, 2066, 1],
 193: [858, 2066, 260, 746, 1230],
 194: [2858, 922, 2396, 2066, 1923],
 195: [2571, 922, 1200, 2066, 1291],
 196: [858, 922, 527, 2066, 318],
 197: [2858, 3121, 527, 1153, 608],
 198: [733, 922, 1127, 2066, 2406],
 199: [1196, 922, 1198, 2066, 2916],
 200: [2858, 3121, 223, 3380, 2716],
 201: [318, 922, 593, 2066, 1265],
 202: [1197, 922, 2762, 2066, 527],
 203: [2858, 922, 296, 2066, 608],
 204: [2000, 922, 2858, 2066, 296],
 205: [858, 922, 608, 2066, 2858],
 206: [589, 3121, 260, 1153, 1196],
 207: [589, 1154, 3578, 1153, 110],
 208: [858, 922, 2571, 2066, 1213],
 209: [2683, 1154, 2716, 1153, 2997],
 210: [2571, 922, 589, 2066, 2028],
 211: [589, 922, 2791, 2066, 110],
 212: [1196, 922, 2571, 2066, 260],
 213: [2858, 3121, 356, 1153, 2396],
 214: [2700, 922, 1517, 2066, 39],
 215: [2571, 922, 1196, 2066, 589],
 216: [260, 922, 1197, 2066, 1097],
 217: [1196, 3121, 2571, 1153, 260],
 218: [2858, 922, 2716, 2066, 2355],
 219: [3578, 922, 2997, 2066, 110],
 220: [1196, 922, 593, 2066, 260],
 221: [2858, 3121, 593, 3380, 608],
 222: [1270, 922, 1580, 2066, 2916],
 223: [110, 922, 260, 2066, 1240],
 224: [2396, 922, 260, 2066, 527],
 225: [1136, 2066, 1252, 746, 32],
 226: [1270, 3121, 1197, 1153, 1198],
 227: [2858, 3121, 2706, 1153, 2683],
 228: [589, 3380, 110, 3121, 1580],
 229: [593, 922, 2762, 2066, 2997],
 230: [1196, 922, 318, 2066, 1210],
 231: [2028, 922, 3471, 2066, 110],
 232: [223, 922, 1500, 2066, 1923],
 233: [1282, 922, 899, 2066, 1197],
 234: [2028, 3121, 593, 1153, 260],
 235: [593, 2066, 1278, 746, 111],
 236: [1240, 922, 858, 2066, 1270],
 237: [2571, 922, 2028, 2066, 110],
 238: [1193, 922, 527, 2066, 2858],
 239: [608, 922, 593, 2066, 318],
 240: [2916, 922, 2028, 2066, 457],
 241: [260, 922, 1210, 2066, 2529],
 242: [589, 922, 1197, 2066, 457],
 243: [2396, 922, 2997, 2066, 1270],
 244: [1196, 922, 2571, 2066, 1580],
 245: [1265, 2066, 1, 746, 1617],
 246: [1197, 3121, 2858, 1153, 260],
 247: [593, 3121, 2858, 1153, 608],
 248: [2028, 922, 1291, 2066, 1200],
 249: [1198, 922, 2028, 2066, 110],
 250: [589, 3121, 110, 1153, 1580],
 251: [1196, 922, 1197, 2066, 1210],
 252: [110, 922, 457, 2066, 2916],
 253: [608, 922, 527, 2066, 318],
 254: [260, 1154, 1258, 1153, 1196],
 255: [1210, 922, 1200, 2066, 480],
 256: [260, 922, 1214, 2066, 457],
 257: [318, 922, 50, 2066, 1610],
 258: [110, 922, 457, 2066, 593],
 259: [2858, 922, 527, 2066, 2571],
 260: [457, 922, 2000, 2066, 780],
 261: [296, 922, 593, 2066, 2571],
 262: [541, 922, 1270, 2066, 589],
 263: [1210, 922, 2571, 2066, 1580],
 264: [1270, 922, 1291, 2066, 2571],
 265: [260, 922, 1028, 2066, 1197],
 266: [858, 922, 593, 2066, 919],
 267: [2858, 922, 593, 2066, 1265],
 268: [356, 922, 2571, 2066, 2028],
 269: [2858, 3121, 2997, 1153, 608],
 270: [2028, 922, 1240, 2066, 589],
 271: [2028, 922, 1036, 2066, 2000],
 272: [2028, 922, 110, 2066, 1240],
 273: [110, 922, 480, 2066, 457],
 274: [2396, 922, 2599, 2066, 2580],
 275: [1198, 922, 2716, 2066, 1961],
 276: [589, 2727, 110, 1153, 1259],
 277: [2028, 3121, 2858, 1153, 318],
 278: [1994, 922, 1407, 2066, 1333],
 279: [2028, 922, 260, 2066, 1198],
 280: [1136, 922, 1304, 2066, 1278],
 281: [2858, 922, 318, 2066, 2997],
 282: [457, 3121, 589, 1153, 608],
 283: [1196, 3121, 1210, 1153, 2571],
 284: [1198, 922, 2571, 2066, 589],
 285: [608, 922, 2858, 2066, 593],
 286: [318, 922, 2028, 2066, 50],
 287: [608, 922, 1617, 2066, 2908],
 288: [589, 922, 457, 2066, 1214],
 289: [260, 922, 1214, 2066, 1617],
 290: [2028, 922, 1704, 2066, 2762],
 291: [260, 922, 908, 2066, 318],
 292: [480, 922, 1210, 2066, 1240],
 293: [296, 922, 1196, 2066, 2028],
 294: [2858, 922, 1265, 2066, 608],
 295: [2916, 922, 480, 2066, 2000],
 296: [260, 922, 1196, 2066, 1210],
 297: [50, 922, 589, 2066, 912],
 298: [589, 3121, 2791, 1153, 3578],
 299: [318, 922, 1617, 2066, 593],
 300: [260, 2066, 527, 746, 296],
 301: [858, 922, 1259, 2066, 1136],
 302: [1196, 922, 2858, 2066, 260],
 303: [318, 922, 593, 2066, 1617],
 304: [541, 3380, 1267, 3292, 922],
 305: [968, 922, 1347, 2066, 3476],
 306: [110, 922, 1196, 2066, 480],
 307: [923, 922, 913, 2066, 1230],
 308: [1136, 922, 110, 2066, 1259],
 309: [1196, 922, 593, 2066, 260],
 310: [318, 922, 2028, 2066, 1580],
 311: [1196, 3121, 260, 1153, 2028],
 312: [527, 922, 858, 2066, 2028],
 313: [480, 3380, 589, 1154, 110],
 314: [858, 922, 1196, 2066, 1198],
 315: [260, 3121, 1252, 1153, 913],
 316: [1240, 922, 1374, 2066, 3471],
 317: [1198, 3121, 1210, 1153, 858],
 318: [2858, 1153, 2997, 3380, 2683],
 319: [50, 922, 1, 2066, 1270],
 320: [589, 3121, 110, 1153, 2791],
 321: [2028, 922, 1198, 2066, 593],
 322: [1210, 922, 919, 2066, 858],
 323: [858, 922, 1198, 2066, 1210],
 324: [2028, 922, 480, 2066, 593],
 325: [356, 922, 1265, 2066, 2396],
 326: [527, 922, 1214, 2066, 2028],
 327: [923, 2066, 912, 746, 111],
 328: [733, 922, 1196, 2066, 1573],
 329: [110, 922, 2716, 2066, 858],
 330: [1196, 922, 318, 2066, 2858],
 331: [2571, 922, 110, 2066, 377],
 332: [2858, 922, 1704, 2066, 296],
 333: [260, 922, 908, 2066, 858],
 334: [912, 922, 1247, 2066, 1307],
 335: [260, 922, 1210, 2066, 2571],
 336: [924, 922, 1356, 2066, 32],
 337: [1196, 922, 260, 2066, 110],
 338: [110, 922, 1291, 2066, 608],
 339: [527, 922, 2858, 2066, 593],
 340: [1198, 2066, 908, 746, 899],
 341: [589, 1153, 1580, 1154, 1259],
 342: [1198, 922, 480, 2066, 2028],
 343: [589, 922, 1200, 2066, 1214],
 344: [2571, 922, 589, 2066, 1200],
 345: [608, 1154, 318, 1153, 1193],
 346: [260, 922, 1198, 2066, 539],
 347: [527, 922, 858, 2066, 2858],
 348: [260, 922, 2028, 2066, 858],
 349: [593, 922, 2858, 2066, 1387],
 350: [589, 922, 2028, 2066, 356],
 351: [1196, 922, 1210, 2066, 2858],
 352: [593, 922, 1265, 2066, 2028],
 353: [858, 1154, 2858, 1153, 593],
 354: [2683, 922, 2706, 2066, 223],
 355: [1198, 922, 50, 2066, 608],
 356: [1214, 1153, 1407, 3380, 1387],
 357: [1196, 922, 2571, 2066, 2858],
 358: [608, 922, 1210, 2066, 1214],
 359: [1240, 922, 1214, 2066, 1200],
 360: [260, 922, 1580, 2066, 1197],
 361: [589, 3121, 110, 3380, 1259],
 362: [1580, 922, 2916, 2066, 1210],
 363: [589, 922, 110, 2066, 1580],
 364: [2997, 3121, 2716, 1153, 2706],
 365: [356, 922, 597, 2066, 2671],
 366: [1196, 922, 858, 2066, 912],
 367: [2396, 3121, 912, 1153, 1307],
 368: [608, 922, 50, 2066, 47],
 369: [1270, 922, 1265, 2066, 2716],
 370: [1127, 922, 2502, 2066, 2770],
 371: [608, 922, 1196, 2066, 1617],
 372: [2916, 922, 1036, 2066, 356],
 373: [1196, 3121, 2571, 1153, 589],
 374: [260, 922, 1196, 2066, 1210],
 375: [318, 922, 2028, 2066, 296],
 376: [2959, 922, 2706, 2066, 2599],
 377: [1240, 922, 457, 2066, 593],
 378: [318, 922, 608, 2066, 296],
 379: [2396, 922, 1210, 2066, 357],
 380: [2918, 922, 1270, 2066, 1196],
 381: [260, 922, 541, 2066, 1206],
 382: [2396, 922, 2858, 2066, 357],
 383: [2716, 1153, 2599, 3380, 2706],
 384: [1196, 3121, 858, 1153, 1198],
 385: [1196, 922, 589, 2066, 1210],
 386: [223, 922, 593, 2066, 527],
 387: [1197, 922, 1270, 2066, 1],
 388: [1198, 922, 1196, 2066, 1307],
 389: [2028, 922, 527, 2066, 2858],
 390: [1321, 2066, 1278, 746, 260],
 391: [1252, 922, 3435, 2066, 1284],
 392: [593, 922, 2028, 2066, 1265],
 393: [608, 922, 1252, 2066, 1221],
 394: [2028, 922, 110, 2066, 1580],
 395: [2706, 2727, 2762, 1153, 2599],
 396: [1265, 922, 608, 2066, 1],
 397: [1210, 922, 110, 2066, 858],
 398: [1196, 922, 260, 2066, 608],
 399: [2683, 922, 2706, 2066, 2997],
 400: [1210, 922, 260, 2066, 318],
 401: [1196, 922, 260, 2066, 2571],
 402: [260, 922, 318, 2066, 858],
 403: [589, 922, 110, 2066, 1036],
 404: [296, 922, 2028, 2066, 50],
 405: [1270, 922, 1197, 2066, 2396],
 406: [1196, 922, 260, 2066, 593],
 407: [2858, 922, 260, 2066, 608],
 408: [1252, 922, 912, 2066, 260],
 409: [296, 922, 1270, 2066, 356],
 410: [2918, 922, 1270, 2066, 1],
 411: [919, 922, 296, 2066, 1617],
 412: [593, 922, 1210, 2066, 1617],
 413: [593, 922, 1704, 2066, 608],
 414: [260, 922, 527, 2066, 1198],
 415: [260, 922, 858, 2066, 1196],
 416: [2716, 922, 2706, 2066, 2683],
 417: [1196, 3380, 1198, 1153, 1210],
 418: [1196, 922, 260, 2066, 1210],
 419: [1198, 922, 1196, 2066, 1210],
 420: [1197, 922, 1214, 2066, 1136],
 421: [2571, 3121, 589, 1153, 2028],
 422: [589, 922, 924, 2066, 1097],
 423: [785, 922, 2605, 2066, 2396],
 424: [1220, 2066, 1580, 746, 3527],
 425: [1196, 922, 608, 2066, 1197],
 426: [480, 922, 1617, 2066, 2194],
 427: [2291, 3121, 3481, 1153, 1249],
 428: [608, 922, 2028, 2066, 296],
 429: [1198, 922, 593, 2066, 296],
 430: [357, 922, 1197, 2066, 1307],
 431: [589, 922, 1240, 2066, 541],
 432: [539, 922, 1393, 2066, 2671],
 433: [1265, 922, 2396, 2066, 1197],
 434: [858, 922, 1196, 2066, 1198],
 435: [2571, 922, 2028, 2066, 110],
 436: [1200, 922, 1, 2066, 1214],
 437: [260, 922, 1196, 2066, 1198],
 438: [1198, 922, 296, 2066, 1291],
 439: [593, 922, 527, 2066, 2571],
 440: [2571, 3121, 589, 1153, 457],
 441: [1210, 922, 1214, 2066, 3471],
 442: [527, 922, 1210, 2066, 1259],
 443: [2028, 922, 593, 2066, 2858],
 444: [858, 922, 260, 2066, 919],
 445: [924, 922, 2628, 2066, 2021],
 446: [2858, 2066, 608, 746, 318],
 447: [1196, 922, 1097, 2066, 1193],
 448: [2858, 2727, 2762, 1153, 2997],
 449: [1196, 922, 1210, 2066, 1278],
 450: [858, 922, 1196, 2066, 2858],
 451: [858, 922, 1247, 2066, 1219],
 452: [110, 922, 733, 2066, 648],
 453: [1197, 922, 593, 2066, 1265],
 454: [1197, 922, 1617, 2066, 2918],
 455: [912, 1154, 2028, 1153, 1210],
 456: [1214, 922, 2571, 2066, 2916],
 457: [1197, 922, 1265, 2066, 1291],
 458: [589, 922, 110, 2066, 2291],
 459: [2997, 922, 2716, 2066, 2355],
 460: [1197, 922, 2716, 2066, 3421],
 461: [260, 922, 589, 2066, 457],
 462: [1214, 922, 1200, 2066, 1610],
 463: [2396, 922, 3421, 2066, 1220],
 464: [593, 922, 318, 2066, 527],
 465: [2858, 922, 296, 2066, 1617],
 466: [2997, 922, 608, 2066, 2396],
 467: [2396, 922, 539, 2066, 1265],
 468: [1307, 3121, 357, 3380, 1247],
 469: [912, 922, 608, 2066, 1193],
 470: [1, 922, 2080, 2066, 260],
 471: [1196, 922, 2571, 2066, 750],
 472: [1270, 922, 1210, 2066, 1097],
 473: [260, 922, 2396, 2066, 914],
 474: [318, 922, 1923, 2066, 32],
 475: [1200, 922, 1374, 2066, 1036],
 476: [2571, 922, 1, 746, 110],
 477: [1214, 922, 1200, 2066, 592],
 478: [527, 922, 2028, 2066, 2762],
 479: [2028, 922, 589, 2066, 2571],
 480: [2762, 922, 356, 2066, 2916],
 481: [2028, 922, 1291, 2066, 457],
 482: [527, 922, 1387, 2066, 1136],
 483: [2858, 3121, 608, 1153, 2028],
 484: [2858, 922, 2716, 2066, 2959],
 485: [2997, 922, 1270, 2066, 2355],
 486: [2858, 922, 593, 2066, 608],
 487: [589, 922, 110, 2066, 2791],
 488: [1196, 1154, 2571, 1153, 1240],
 489: [260, 1154, 2858, 1153, 608],
 490: [1097, 922, 480, 2066, 1580],
 491: [260, 1154, 1196, 1153, 1198],
 492: [2683, 922, 2959, 2066, 2355],
 493: [2858, 922, 296, 2066, 1704],
 494: [1, 922, 356, 2066, 2716],
 495: [1198, 922, 1240, 2066, 1270],
 496: [2571, 922, 1210, 2066, 2628],
 497: [1196, 1154, 1198, 1153, 260],
 498: [858, 922, 923, 2066, 1193],
 499: [1265, 922, 1270, 2066, 2028],
 500: [260, 922, 1, 2066, 1210],
 501: [908, 922, 3753, 2066, 2160],
 502: [2858, 3380, 1265, 1154, 1],
 503: [2858, 3121, 1284, 1153, 858],
 504: [2858, 746, 1580, 2940, 2791],
 505: [1196, 922, 457, 2066, 1210],
 506: [2762, 922, 2502, 2066, 2336],
 507: [858, 922, 527, 2066, 608],
 508: [589, 922, 480, 2066, 2916],
 509: [608, 922, 50, 2066, 1270],
 510: [1240, 922, 541, 2066, 1527],
 511: [2858, 3121, 2355, 1153, 223],
 512: [593, 922, 2858, 2066, 2028],
 513: [1196, 922, 1198, 2066, 1214],
 514: [2716, 922, 2706, 2066, 3578],
 515: [2858, 922, 260, 2066, 1230],
 516: [2571, 922, 3471, 2066, 1198],
 517: [1784, 922, 1196, 2066, 1197],
 518: [858, 922, 1196, 2066, 260],
 519: [1270, 922, 2355, 2066, 1],
 520: [260, 922, 1196, 2066, 1198],
 521: [608, 922, 1196, 2066, 2028],
 522: [589, 922, 1374, 2066, 1127],
 523: [1197, 922, 1221, 2066, 589],
 524: [50, 922, 589, 2066, 480],
 525: [1196, 922, 2028, 2066, 912],
 526: [1214, 922, 1387, 2066, 457],
 527: [1197, 1154, 2858, 1153, 1259],
 528: [480, 922, 527, 2066, 2762],
 529: [1210, 922, 1036, 2066, 1304],
 530: [750, 922, 1199, 2066, 2628],
 531: [1196, 922, 480, 2066, 1198],
 532: [1200, 922, 1270, 2066, 924],
 533: [608, 922, 1270, 2066, 2916],
 534: [17, 922, 1393, 2066, 2858],
 535: [2858, 1153, 2355, 3380, 2683],
 536: [110, 922, 480, 2066, 2916],
 537: [858, 922, 527, 2066, 908],
 538: [1196, 922, 2028, 2066, 858],
 539: [1240, 922, 1036, 2066, 589],
 540: [2858, 922, 593, 2066, 50],
 541: [2571, 922, 2628, 2066, 919],
 542: [2791, 922, 1259, 2066, 3481],
 543: [1240, 922, 1127, 2066, 1527],
 544: [260, 922, 1270, 2066, 1197],
 545: [2706, 3380, 2959, 3121, 223],
 546: [1265, 922, 39, 2066, 1641],
 547: [1210, 922, 1270, 2066, 480],
 548: [1580, 922, 2160, 2066, 1258],
 549: [2858, 922, 2028, 2066, 1387],
 550: [1036, 922, 1610, 2066, 593],
 551: [608, 922, 858, 2066, 318],
 552: [1270, 922, 2858, 2066, 2791],
 553: [2997, 922, 1, 2066, 1641],
 554: [2997, 922, 2599, 2066, 2355],
 555: [2858, 922, 2997, 2066, 1196],
 556: [2396, 922, 1073, 2066, 2987],
 557: [2571, 922, 1206, 2066, 3175],
 558: [858, 922, 296, 2066, 1704],
 559: [608, 1153, 1617, 3380, 2858],
 560: [1291, 922, 1036, 2066, 2000],

In [27]:
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))


def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)


def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count


def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0


def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_ratings['user_id'].unique()

    for user in unique_users:
        # Get the recommended items for the user
        recommended_items = final_recommendations[user]

        # Get the actual items the user interacted with in the test set
        user_test_data = test_ratings[test_ratings['user_id'] == user]
        test_items = user_test_data['item_id'].values

        # Create a binary relevance score list (1 if item is in the test set, 0 otherwise)
        y_score = [1 if item in test_items else 0 for item in recommended_items]

        # Calculate the evaluation metrics
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        # Store the scores
        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # Compute average scores
    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
        'Recall@{}'.format(k): avg_recall,
        'MRR@{}'.format(k): avg_mrr,
    }


# Evaluate the final recommendations
eval_result = evaluate_final_recommendations(final_recommendations_without_weight, test_ratings, k=5)
print(eval_result)
# eval_result = evaluate_final_recommendations(final_recommendations, test_ratings, k=10)
# print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_6416\3447043275.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.6790345384772987, 'Recall@5': 0.019486311002615286, 'MRR@5': 0.10588024282560707}

In [28]:
def rrf_score(ranks, k=5):
    return sum([1 / (k + rank) for rank in ranks])

def combine_recommendations_with_rrf_with_weight(user_id, cf_recommendations, tt_recommendations, k=5, cf_weight=1,
                                                 tt_weight=4):
    # Create a dictionary to hold the RRF scores
    combined_scores = {}

    # Assign ranks and calculate weighted RRF scores from Collaborative Filtering recommendations
    for rank, item in enumerate(cf_recommendations[user_id], start=1):
        weighted_rank = rank * cf_weight  # Apply the weight to CF ranks
        if item not in combined_scores:
            combined_scores[item] = rrf_score([weighted_rank], k)
        else:
            combined_scores[item] += rrf_score([weighted_rank], k)

    # Assign ranks and calculate weighted RRF scores from Two-Tower recommendations
    for rank, item in enumerate(tt_recommendations[user_id], start=1):
        weighted_rank = rank * tt_weight  # Apply the weight to TT ranks
        if item not in combined_scores:
            combined_scores[item] = rrf_score([weighted_rank], k)
        else:
            combined_scores[item] += rrf_score([weighted_rank], k)

    # Sort the items based on their RRF scores in descending order
    sorted_items = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)

    # Return the top N items
    return [item for item, score in sorted_items[:k]]

In [29]:
final_recommendations_with_weight = {}
for user_id in test_ratings['user_id'].unique():
    final_recommendations_with_weight[user_id] = combine_recommendations_with_rrf_with_weight(user_id,
                                                                                              cf_recommendations,
                                                                                              tt_recommendations, k=5)

# Now final_recommendations contains the combined top N recommendations for each user
final_recommendations_with_weight

{1: [1196, 318, 1198, 1, 922],
 2: [527, 260, 608, 858, 922],
 3: [2571, 2028, 589, 2628, 922],
 4: [1240, 858, 2571, 589, 3121],
 5: [2396, 527, 1265, 1673, 922],
 6: [919, 1307, 1197, 356, 922],
 7: [260, 1210, 1198, 1240, 3121],
 8: [318, 593, 1617, 2762, 922],
 9: [296, 2997, 110, 2396, 922],
 10: [260, 1196, 2571, 1097, 922],
 11: [296, 2028, 527, 1617, 922],
 12: [260, 1196, 318, 2858, 1154],
 13: [1240, 733, 1200, 1036, 922],
 14: [2716, 223, 2599, 2683, 1154],
 15: [589, 608, 1, 377, 922],
 16: [2858, 2706, 2716, 1127, 922],
 17: [1580, 1199, 2985, 2968, 922],
 18: [2571, 480, 1214, 1270, 922],
 19: [589, 480, 2916, 2985, 922],
 20: [480, 1580, 593, 1196, 1154],
 21: [260, 1196, 3114, 2571, 1153],
 22: [260, 1198, 356, 2028, 922],
 23: [1270, 1210, 1374, 1197, 922],
 24: [1196, 1198, 1265, 2000, 922],
 25: [589, 1240, 2916, 3175, 922],
 26: [1210, 2028, 260, 110, 922],
 27: [912, 908, 1230, 1284, 746],
 28: [2858, 527, 858, 296, 922],
 29: [2028, 1197, 2194, 1201, 922],
 30: [1704, 110, 2396, 2997, 922],
 31: [1294, 1278, 1079, 2791, 922],
 32: [318, 296, 527, 2997, 922],
 33: [2028, 1617, 1036, 750, 922],
 34: [1265, 2797, 1394, 260, 922],
 35: [858, 923, 260, 1193, 922],
 36: [1198, 318, 50, 1036, 922],
 37: [39, 1270, 1393, 2858, 922],
 38: [597, 1265, 11, 2858, 922],
 39: [2762, 2694, 1093, 2541, 922],
 40: [260, 480, 2028, 1240, 922],
 41: [1198, 2571, 589, 2028, 1154],
 42: [1676, 2028, 110, 1199, 922],
 43: [2858, 2716, 2683, 2959, 1154],
 44: [1214, 541, 1200, 110, 922],
 45: [356, 2797, 260, 1079, 922],
 46: [1387, 1258, 1214, 2716, 922],
 47: [2858, 2028, 1213, 296, 3121],
 48: [2000, 1214, 608, 3471, 922],
 49: [260, 1198, 110, 1240, 922],
 50: [589, 110, 3481, 1259, 922],
 51: [2997, 527, 2028, 356, 922],
 52: [2571, 377, 3256, 1527, 922],
 53: [1198, 1197, 527, 110, 2066],
 54: [1294, 1270, 2858, 3421, 922],
 55: [2858, 2028, 608, 1617, 1154],
 56: [1265, 589, 356, 2959, 922],
 57: [3481, 589, 110, 1580, 922],
 58: [50, 1265, 924, 1, 922],
 59: [858, 608, 527, 1196, 922],
 60: [480, 2571, 2916, 589, 922],
 61: [2858, 3751, 3408, 3510, 922],
 62: [527, 1197, 1265, 1036, 922],
 63: [2997, 2355, 2710, 1127, 922],
 64: [1196, 2571, 260, 589, 3121],
 65: [589, 457, 1210, 110, 922],
 66: [589, 1580, 2571, 1259, 1154],
 67: [858, 912, 1193, 608, 922],
 68: [1079, 1270, 1394, 1, 922],
 69: [608, 318, 527, 1213, 922],
 70: [2710, 2502, 2762, 2712, 922],
 71: [2858, 3578, 2706, 589, 3380],
 72: [1265, 1, 357, 34, 922],
 73: [260, 1127, 1214, 648, 922],
 74: [2858, 1213, 527, 593, 922],
 75: [260, 1198, 1197, 2571, 922],
 76: [527, 2028, 2997, 110, 922],
 77: [223, 2716, 2355, 1127, 922],
 78: [1028, 1197, 1580, 595, 922],
 79: [3578, 2858, 480, 3753, 3121],
 80: [318, 2571, 2858, 1704, 922],
 81: [858, 923, 608, 1219, 922],
 82: [2028, 356, 1610, 50, 922],
 83: [2997, 2706, 2599, 2770, 922],
 84: [589, 1036, 858, 1387, 3121],
 85: [3753, 3623, 2997, 3751, 922],
 86: [2571, 260, 1196, 589, 922],
 87: [1210, 858, 1214, 1200, 922],
 88: [2858, 593, 919, 260, 922],
 89: [318, 593, 2858, 110, 3380],
 90: [296, 2571, 593, 589, 922],
 91: [1265, 2858, 1270, 1136, 922],
 92: [1196, 260, 1210, 2028, 922],
 93: [110, 1374, 1527, 2985, 922],
 94: [1214, 1387, 589, 1219, 3121],
 95: [2858, 318, 593, 296, 922],
 96: [2858, 1704, 1198, 50, 922],
 97: [908, 1230, 608, 1219, 2066],
 98: [2858, 480, 110, 1196, 1153],
 99: [593, 2571, 2762, 608, 922],
 100: [1240, 589, 1036, 1214, 922],
 101: [1291, 110, 1610, 2028, 922],
 102: [2762, 2716, 223, 2706, 922],
 103: [377, 2628, 1196, 3256, 922],
 104: [2716, 1127, 2599, 2694, 922],
 105: [1198, 1240, 1036, 110, 922],
 106: [912, 1197, 1265, 1247, 922],
 107: [527, 904, 2858, 1221, 922],
 108: [589, 110, 1580, 1259, 922],
 109: [1197, 1097, 1136, 2571, 922],
 110: [2571, 2028, 593, 318, 922],
 111: [608, 2858, 1704, 527, 922],
 112: [260, 2081, 1196, 1097, 746],
 113: [110, 1196, 2628, 1210, 922],
 114: [594, 260, 3114, 1196, 922],
 115: [589, 3753, 110, 1580, 922],
 116: [2858, 2716, 2762, 1196, 922],
 117: [480, 1127, 3527, 2985, 922],
 118: [1240, 1610, 2000, 1580, 922],
 119: [1210, 2081, 2858, 260, 922],
 120: [2028, 1617, 912, 919, 922],
 121: [1240, 589, 1200, 480, 922],
 122: [2571, 1036, 110, 1240, 922],
 123: [1265, 1197, 1220, 541, 922],
 124: [318, 593, 608, 2028, 1154],
 125: [260, 1198, 1196, 858, 922],
 126: [1196, 1198, 2028, 1240, 922],
 127: [2916, 1198, 318, 1610, 922],
 128: [480, 589, 110, 1259, 3380],
 129: [260, 589, 457, 110, 922],
 130: [1197, 1304, 1127, 2628, 922],
 131: [1213, 1196, 1394, 1221, 922],
 132: [2791, 2918, 1270, 2858, 922],
 133: [608, 1704, 2571, 110, 922],
 134: [2028, 1610, 1196, 1210, 922],
 135: [2997, 2599, 3578, 2712, 922],
 136: [1198, 296, 593, 527, 2066],
 137: [593, 50, 380, 780, 922],
 138: [2028, 527, 260, 2571, 922],
 139: [2571, 1240, 589, 1270, 922],
 140: [1252, 908, 910, 858, 922],
 141: [110, 589, 1580, 1259, 2727],
 142: [593, 608, 527, 1213, 922],
 143: [589, 457, 480, 1210, 922],
 144: [2762, 2028, 110, 318, 922],
 145: [2355, 2712, 2770, 3160, 922],
 146: [750, 1270, 1304, 593, 922],
 147: [2916, 1240, 593, 1200, 922],
 148: [1214, 733, 2001, 2947, 922],
 149: [2791, 1291, 356, 1193, 922],
 150: [50, 1213, 858, 1197, 922],
 151: [260, 318, 1198, 457, 922],
 152: [2858, 1270, 1265, 2918, 1154],
 153: [2683, 223, 2997, 2762, 3121],
 154: [2706, 223, 2580, 3160, 922],
 155: [356, 1, 2858, 1270, 922],
 156: [39, 1784, 587, 1580, 922],
 157: [1036, 1220, 296, 593, 922],
 158: [913, 1252, 858, 908, 1153],
 159: [2716, 2762, 2997, 223, 922],
 160: [589, 1196, 1580, 2571, 1153],
 161: [858, 1193, 1230, 50, 922],
 162: [2571, 1210, 1610, 1196, 922],
 163: [318, 1610, 527, 648, 922],
 164: [912, 260, 527, 2028, 3380],
 165: [2571, 3471, 750, 858, 922],
 166: [318, 1197, 858, 32, 2066],
 167: [2858, 3510, 3793, 3897, 922],
 168: [1198, 1210, 858, 1197, 3121],
 169: [1210, 1580, 2396, 1222, 2066],
 170: [924, 1197, 2529, 1374, 922],
 171: [2858, 608, 2028, 593, 2727],
 172: [1252, 1617, 541, 912, 2727],
 173: [1193, 1304, 2028, 1084, 746],
 174: [1198, 1196, 2028, 1200, 922],
 175: [608, 50, 1270, 858, 922],
 176: [2791, 1259, 3210, 1198, 922],
 177: [2571, 1214, 589, 1270, 922],
 178: [1270, 1097, 595, 2081, 922],
 179: [260, 1214, 480, 1580, 922],
 180: [318, 1213, 527, 858, 922],
 181: [260, 589, 593, 858, 922],
 182: [2858, 1923, 2571, 593, 922],
 183: [1617, 912, 858, 908, 922],
 184: [260, 1210, 1197, 1270, 922],
 185: [2571, 457, 733, 648, 922],
 186: [110, 3114, 593, 588, 922],
 187: [527, 2997, 3006, 32, 922],
 188: [2858, 2997, 2716, 2706, 922],
 189: [527, 296, 2571, 2997, 3121],
 190: [1198, 1196, 318, 1213, 922],
 191: [2683, 2028, 2997, 1270, 3380],
 192: [593, 2028, 1, 2762, 922],
 193: [858, 260, 1230, 1252, 2066],
 194: [2858, 2396, 1923, 1784, 922],
 195: [2571, 1200, 1291, 1610, 922],
 196: [858, 527, 318, 2028, 922],
 197: [2858, 527, 608, 2028, 3121],
 198: [733, 1127, 2406, 2858, 922],
 199: [1196, 1198, 2916, 1036, 922],
 200: [2858, 223, 2716, 2710, 3121],
 201: [318, 593, 1265, 356, 922],
 202: [1197, 2762, 527, 858, 922],
 203: [2858, 296, 608, 150, 922],
 204: [2000, 2858, 296, 2716, 922],
 205: [858, 608, 2858, 1617, 922],
 206: [589, 260, 1196, 1580, 3121],
 207: [589, 3578, 110, 1580, 1154],
 208: [858, 2571, 1213, 1210, 922],
 209: [2683, 2716, 2997, 223, 1154],
 210: [2571, 589, 2028, 457, 922],
 211: [589, 2791, 110, 1580, 922],
 212: [1196, 2571, 260, 1210, 922],
 213: [2858, 356, 2396, 1580, 3121],
 214: [2700, 1517, 39, 3253, 922],
 215: [2571, 1196, 589, 1580, 922],
 216: [260, 1197, 1097, 1221, 922],
 217: [1196, 2571, 260, 593, 3121],
 218: [2858, 2716, 2355, 2997, 922],
 219: [3578, 2997, 110, 2355, 922],
 220: [1196, 593, 260, 296, 922],
 221: [2858, 593, 608, 2571, 3121],
 222: [1270, 1580, 2916, 3527, 922],
 223: [110, 260, 1240, 1036, 922],
 224: [2396, 260, 527, 1198, 922],
 225: [1136, 1252, 32, 1288, 2066],
 226: [1270, 1197, 1198, 2716, 3121],
 227: [2858, 2706, 2683, 223, 3121],
 228: [589, 110, 1580, 2571, 3380],
 229: [593, 2762, 2997, 1617, 922],
 230: [1196, 318, 1210, 593, 922],
 231: [2028, 3471, 110, 924, 922],
 232: [223, 1500, 1923, 39, 922],
 233: [1282, 899, 1197, 1, 922],
 234: [2028, 593, 260, 2858, 3121],
 235: [593, 1278, 111, 1206, 2066],
 236: [1240, 858, 1270, 2858, 922],
 237: [2571, 2028, 110, 589, 922],
 238: [1193, 527, 2858, 912, 922],
 239: [608, 593, 318, 296, 922],
 240: [2916, 2028, 457, 1036, 922],
 241: [260, 1210, 2529, 2916, 922],
 242: [589, 1197, 457, 2916, 922],
 243: [2396, 2997, 1270, 1394, 922],
 244: [1196, 2571, 1580, 110, 922],
 245: [1265, 1, 1617, 2987, 2066],
 246: [1197, 2858, 260, 1196, 3121],
 247: [593, 2858, 608, 1704, 3121],
 248: [2028, 1291, 1200, 858, 922],
 249: [1198, 2028, 110, 1265, 922],
 250: [589, 110, 1580, 1259, 3121],
 251: [1196, 1197, 1210, 2571, 922],
 252: [110, 457, 2916, 1610, 922],
 253: [608, 527, 318, 2762, 922],
 254: [260, 1258, 1196, 1200, 1154],
 255: [1210, 1200, 480, 1270, 922],
 256: [260, 1214, 457, 1387, 922],
 257: [318, 50, 1610, 1617, 922],
 258: [110, 457, 593, 296, 922],
 259: [2858, 527, 2571, 2762, 922],
 260: [457, 2000, 780, 1200, 922],
 261: [296, 593, 2571, 50, 922],
 262: [541, 1270, 589, 1200, 922],
 263: [1210, 2571, 1580, 2028, 922],
 264: [1270, 1291, 2571, 1610, 922],
 265: [260, 1028, 1197, 1198, 922],
 266: [858, 593, 919, 2028, 922],
 267: [2858, 593, 1265, 457, 922],
 268: [356, 2571, 2028, 480, 922],
 269: [2858, 2997, 608, 593, 3121],
 270: [2028, 1240, 589, 1200, 922],
 271: [2028, 1036, 2000, 2916, 922],
 272: [2028, 110, 1240, 1036, 922],
 273: [110, 480, 457, 1270, 922],
 274: [2396, 2599, 2580, 2571, 922],
 275: [1198, 2716, 1961, 260, 922],
 276: [589, 110, 1259, 480, 2727],
 277: [2028, 2858, 318, 527, 3121],
 278: [1994, 1407, 1333, 260, 922],
 279: [2028, 260, 1198, 858, 922],
 280: [1136, 1304, 1278, 1270, 922],
 281: [2858, 318, 2997, 1213, 922],
 282: [457, 589, 608, 2028, 3121],
 283: [1196, 1210, 2571, 2028, 3121],
 284: [1198, 2571, 589, 1240, 922],
 285: [608, 2858, 593, 296, 922],
 286: [318, 2028, 50, 527, 922],
 287: [608, 1617, 2908, 2599, 922],
 288: [589, 457, 1214, 2028, 922],
 289: [260, 1214, 1617, 2028, 922],
 290: [2028, 1704, 2762, 296, 922],
 291: [260, 908, 318, 923, 922],
 292: [480, 1210, 1240, 1214, 922],
 293: [296, 1196, 2028, 858, 922],
 294: [2858, 1265, 608, 1641, 922],
 295: [2916, 480, 2000, 3175, 922],
 296: [260, 1196, 1210, 1214, 922],
 297: [50, 589, 912, 1387, 922],
 298: [589, 2791, 3578, 110, 3121],
 299: [318, 1617, 593, 527, 922],
 300: [260, 527, 296, 1097, 2066],
 301: [858, 1259, 1136, 2000, 922],
 302: [1196, 2858, 260, 1198, 922],
 303: [318, 593, 1617, 1213, 922],
 304: [541, 1267, 922, 2186, 3380],
 305: [968, 1347, 3476, 1196, 922],
 306: [110, 1196, 480, 356, 922],
 307: [923, 913, 1230, 260, 922],
 308: [1136, 110, 1259, 1610, 922],
 309: [1196, 593, 260, 296, 922],
 310: [318, 2028, 1580, 110, 922],
 311: [1196, 260, 2028, 1198, 3121],
 312: [527, 858, 2028, 1213, 922],
 313: [480, 589, 110, 3578, 3380],
 314: [858, 1196, 1198, 1221, 922],
 315: [260, 1252, 913, 1617, 3121],
 316: [1240, 1374, 3471, 1356, 922],
 317: [1198, 1210, 858, 1270, 3121],
 318: [2858, 2997, 2683, 913, 1153],
 319: [50, 1, 1270, 1197, 922],
 320: [589, 110, 2791, 1580, 3121],
 321: [2028, 1198, 593, 1270, 922],
 322: [1210, 919, 858, 527, 922],
 323: [858, 1198, 1210, 296, 922],
 324: [2028, 480, 593, 110, 922],
 325: [356, 1265, 2396, 539, 922],
 326: [527, 1214, 2028, 296, 922],
 327: [923, 912, 111, 1230, 2066],
 328: [733, 1196, 1573, 260, 922],
 329: [110, 2716, 858, 2918, 922],
 330: [1196, 318, 2858, 1193, 922],
 331: [2571, 110, 377, 1, 922],
 332: [2858, 1704, 296, 2396, 922],
 333: [260, 908, 858, 608, 922],
 334: [912, 1247, 1307, 969, 922],
 335: [260, 1210, 2571, 2028, 922],
 336: [924, 1356, 32, 1206, 922],
 337: [1196, 260, 110, 1584, 922],
 338: [110, 1291, 608, 296, 922],
 339: [527, 2858, 593, 1225, 922],
 340: [1198, 908, 899, 858, 2066],
 341: [589, 1580, 1259, 3481, 1153],
 342: [1198, 480, 2028, 1, 922],
 343: [589, 1200, 1214, 1527, 922],
 344: [2571, 589, 1200, 480, 922],
 345: [608, 318, 1193, 296, 1154],
 346: [260, 1198, 539, 1968, 922],
 347: [527, 858, 2858, 2396, 922],
 348: [260, 2028, 858, 969, 922],
 349: [593, 2858, 1387, 1270, 922],
 350: [589, 2028, 356, 110, 922],
 351: [1196, 1210, 2858, 858, 922],
 352: [593, 1265, 2028, 356, 922],
 353: [858, 2858, 593, 2028, 1154],
 354: [2683, 2706, 223, 3578, 922],
 355: [1198, 50, 608, 1704, 922],
 356: [1214, 1407, 1387, 2571, 1153],
 357: [1196, 2571, 2858, 589, 922],
 358: [608, 1210, 1214, 527, 922],
 359: [1240, 1214, 1200, 924, 922],
 360: [260, 1580, 1197, 2571, 922],
 361: [589, 110, 1259, 908, 3121],
 362: [1580, 2916, 1210, 1196, 922],
 363: [589, 110, 1580, 3578, 922],
 364: [2997, 2716, 2706, 2396, 3121],
 365: [356, 597, 2671, 587, 922],
 366: [1196, 858, 912, 1234, 922],
 367: [2396, 912, 1307, 1247, 3121],
 368: [608, 50, 47, 1682, 922],
 369: [1270, 1265, 2716, 2797, 922],
 370: [1127, 2502, 2770, 785, 922],
 371: [608, 1196, 1617, 593, 922],
 372: [2916, 1036, 356, 316, 922],
 373: [1196, 2571, 589, 1291, 3121],
 374: [260, 1196, 1210, 110, 922],
 375: [318, 2028, 296, 858, 922],
 376: [2959, 2706, 2599, 223, 922],
 377: [1240, 457, 593, 1221, 922],
 378: [318, 608, 296, 2396, 922],
 379: [2396, 1210, 357, 919, 922],
 380: [2918, 1270, 1196, 2599, 922],
 381: [260, 541, 1206, 3471, 922],
 382: [2396, 2858, 357, 356, 922],
 383: [2716, 2599, 2706, 2683, 1153],
 384: [1196, 858, 1198, 2028, 3121],
 385: [1196, 589, 1210, 110, 922],
 386: [223, 593, 527, 1196, 922],
 387: [1197, 1270, 1, 1196, 922],
 388: [1198, 1196, 1307, 1197, 922],
 389: [2028, 527, 2858, 356, 922],
 390: [1321, 1278, 260, 1196, 2066],
 391: [1252, 3435, 1284, 260, 922],
 392: [593, 2028, 1265, 1097, 922],
 393: [608, 1252, 1221, 912, 922],
 394: [2028, 110, 1580, 1610, 922],
 395: [2706, 2762, 2599, 1, 2727],
 396: [1265, 608, 1, 1394, 922],
 397: [1210, 110, 858, 1387, 922],
 398: [1196, 260, 608, 1270, 922],
 399: [2683, 2706, 2997, 1127, 922],
 400: [1210, 260, 318, 2858, 922],
 401: [1196, 260, 2571, 589, 922],
 402: [260, 318, 858, 1198, 922],
 403: [589, 110, 1036, 318, 922],
 404: [296, 2028, 50, 1193, 922],
 405: [1270, 1197, 2396, 3421, 922],
 406: [1196, 260, 593, 1197, 922],
 407: [2858, 260, 608, 593, 922],
 408: [1252, 912, 260, 2858, 922],
 409: [296, 1270, 356, 1221, 922],
 410: [2918, 1270, 1, 1196, 922],
 411: [919, 296, 1617, 908, 922],
 412: [593, 1210, 1617, 1240, 922],
 413: [593, 1704, 608, 296, 922],
 414: [260, 527, 1198, 858, 922],
 415: [260, 858, 1196, 1230, 922],
 416: [2716, 2706, 2683, 223, 922],
 417: [1196, 1198, 1210, 2355, 3380],
 418: [1196, 260, 1210, 2028, 922],
 419: [1198, 1196, 1210, 2571, 922],
 420: [1197, 1214, 1136, 2858, 922],
 421: [2571, 589, 2028, 110, 3121],
 422: [589, 924, 1097, 2916, 922],
 423: [785, 2605, 2396, 2699, 922],
 424: [1220, 1580, 3527, 32, 2066],
 425: [1196, 608, 1197, 1210, 922],
 426: [480, 1617, 2194, 3527, 922],
 427: [2291, 3481, 1249, 3753, 3121],
 428: [608, 2028, 296, 2571, 922],
 429: [1198, 593, 296, 1197, 922],
 430: [357, 1197, 1307, 1393, 922],
 431: [589, 1240, 541, 2916, 922],
 432: [539, 1393, 2671, 339, 922],
 433: [1265, 2396, 1197, 1307, 922],
 434: [858, 1196, 1198, 1193, 922],
 435: [2571, 2028, 110, 1214, 922],
 436: [1200, 1, 1214, 1127, 922],
 437: [260, 1196, 1198, 1210, 922],
 438: [1198, 296, 1291, 50, 922],
 439: [593, 527, 2571, 1270, 922],
 440: [2571, 589, 457, 480, 3121],
 441: [1210, 1214, 3471, 1200, 922],
 442: [527, 1210, 1259, 1, 922],
 443: [2028, 593, 2858, 1196, 922],
 444: [858, 260, 919, 923, 922],
 445: [924, 2628, 2021, 2640, 922],
 446: [2858, 608, 318, 527, 2066],
 447: [1196, 1097, 1193, 858, 922],
 448: [2858, 2762, 2997, 2706, 2727],
 449: [1196, 1210, 1278, 2571, 922],
 450: [858, 1196, 2858, 593, 922],
 451: [858, 1247, 1219, 1617, 922],
 452: [110, 733, 648, 1196, 922],
 453: [1197, 593, 1265, 110, 922],
 454: [1197, 1617, 2918, 1089, 922],
 455: [912, 2028, 1210, 1221, 1154],
 456: [1214, 2571, 2916, 1127, 922],
 457: [1197, 1265, 1291, 1136, 922],
 458: [589, 110, 2291, 3481, 922],
 459: [2997, 2716, 2355, 223, 922],
 460: [1197, 2716, 3421, 2858, 922],
 461: [260, 589, 457, 1610, 922],
 462: [1214, 1200, 1610, 2916, 922],
 463: [2396, 3421, 1220, 1196, 922],
 464: [593, 318, 527, 1617, 922],
 465: [2858, 296, 1617, 50, 922],
 466: [2997, 608, 2396, 1080, 922],
 467: [2396, 539, 1265, 318, 922],
 468: [1307, 357, 1247, 920, 3121],
 469: [912, 608, 1193, 2858, 922],
 470: [1, 2080, 260, 1270, 922],
 471: [1196, 2571, 750, 1206, 922],
 472: [1270, 1210, 1097, 1374, 922],
 473: [260, 2396, 914, 1947, 922],
 474: [318, 1923, 32, 457, 922],
 475: [1200, 1374, 1036, 1214, 922],
 476: [2571, 1, 110, 1127, 922],
 477: [1214, 1200, 592, 377, 922],
 478: [527, 2028, 2762, 858, 922],
 479: [2028, 589, 2571, 110, 922],
 480: [2762, 356, 2916, 1617, 922],
 481: [2028, 1291, 457, 1610, 922],
 482: [527, 1387, 1136, 2762, 922],
 483: [2858, 608, 2028, 260, 3121],
 484: [2858, 2716, 2959, 2355, 922],
 485: [2997, 1270, 2355, 1265, 922],
 486: [2858, 593, 608, 296, 922],
 487: [589, 110, 2791, 608, 922],
 488: [1196, 2571, 1240, 589, 1154],
 489: [260, 2858, 608, 318, 1154],
 490: [1097, 480, 1580, 919, 922],
 491: [260, 1196, 1198, 1210, 1154],
 492: [2683, 2959, 2355, 1127, 922],
 493: [2858, 296, 1704, 50, 922],
 494: [1, 356, 2716, 1265, 922],
 495: [1198, 1240, 1270, 2916, 922],
 496: [2571, 1210, 2628, 1200, 922],
 497: [1196, 1198, 260, 2571, 1154],
 498: [858, 923, 1193, 1219, 922],
 499: [1265, 1270, 2028, 608, 922],
 500: [260, 1, 1210, 1270, 922],
 501: [908, 3753, 2160, 3160, 922],
 502: [2858, 1265, 1, 2396, 3380],
 503: [2858, 1284, 858, 260, 3121],
 504: [2858, 1580, 2791, 2291, 746],
 505: [1196, 457, 1210, 1240, 922],
 506: [2762, 2502, 2336, 3175, 922],
 507: [858, 527, 608, 912, 922],
 508: [589, 480, 2916, 924, 922],
 509: [608, 50, 1270, 457, 922],
 510: [1240, 541, 1527, 1200, 922],
 511: [2858, 2355, 223, 2599, 3121],
 512: [593, 2858, 2028, 480, 922],
 513: [1196, 1198, 1214, 260, 922],
 514: [2716, 2706, 3578, 2599, 922],
 515: [2858, 260, 1230, 1213, 922],
 516: [2571, 3471, 1198, 1197, 922],
 517: [1784, 1196, 1197, 318, 922],
 518: [858, 1196, 260, 919, 922],
 519: [1270, 2355, 1, 11, 922],
 520: [260, 1196, 1198, 1210, 922],
 521: [608, 1196, 2028, 260, 922],
 522: [589, 1374, 1127, 2529, 922],
 523: [1197, 1221, 589, 1240, 922],
 524: [50, 589, 480, 1704, 922],
 525: [1196, 2028, 912, 1240, 922],
 526: [1214, 1387, 457, 1197, 922],
 527: [1197, 2858, 1259, 2791, 1154],
 528: [480, 527, 2762, 1198, 922],
 529: [1210, 1036, 1304, 318, 922],
 530: [750, 1199, 2628, 1253, 922],
 531: [1196, 480, 1198, 260, 922],
 532: [1200, 1270, 924, 3471, 922],
 533: [608, 1270, 2916, 1259, 922],
 534: [17, 1393, 2858, 1247, 922],
 535: [2858, 2355, 2683, 2762, 1153],
 536: [110, 480, 2916, 1580, 922],
 537: [858, 527, 908, 923, 922],
 538: [1196, 2028, 858, 1221, 922],
 539: [1240, 1036, 589, 1580, 922],
 540: [2858, 593, 50, 2028, 922],
 541: [2571, 2628, 919, 1240, 922],
 542: [2791, 1259, 3481, 2291, 922],
 543: [1240, 1127, 1527, 2858, 922],
 544: [260, 1270, 1197, 527, 922],
 545: [2706, 2959, 223, 2599, 3380],
 546: [1265, 39, 1641, 608, 922],
 547: [1210, 1270, 480, 924, 922],
 548: [1580, 2160, 1258, 1219, 922],
 549: [2858, 2028, 1387, 2987, 922],
 550: [1036, 1610, 593, 2762, 922],
 551: [608, 858, 318, 296, 922],
 552: [1270, 2858, 2791, 1196, 922],
 553: [2997, 1, 1641, 34, 922],
 554: [2997, 2599, 2355, 2710, 922],
 555: [2858, 2997, 1196, 2571, 922],
 556: [2396, 1073, 2987, 1580, 922],
 557: [2571, 1206, 3175, 2529, 922],
 558: [858, 296, 1704, 1270, 922],
 559: [608, 1617, 2858, 2571, 1153],
 560: [1291, 1036, 2000, 1197, 922],
 561: [3578, 2858, 3793, 2028, 922],
 562: [2571, 1036, 589, 1210, 922],
 563: [1198, 1197, 2028, 110, 922],
 564: [260, 858, 2028, 919, 922],
 565: [110, 1580, 908, 3160, 2727],
 566: [2716, 480, 1265, 2918, 922],

In [64]:
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count

def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0

def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_ratings['user_id'].unique()

    for user in unique_users:
        # Get the recommended items for the user
        recommended_items = final_recommendations[user]

        # Get the actual items the user interacted with in the test set
        user_test_data = test_ratings[test_ratings['user_id'] == user]
        test_items = user_test_data['item_id'].values

        # Create a binary relevance score list (1 if item is in the test set, 0 otherwise)
        y_score = [1 if item in test_items else 0 for item in recommended_items]

        # Calculate the evaluation metrics
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        # Store the scores
        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # Compute average scores
    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
        'Recall@{}'.format(k): avg_recall,
        'MRR@{}'.format(k): avg_mrr,
    }

# Evaluate the final recommendations
eval_result = evaluate_final_recommendations(final_recommendations_with_weight, test_ratings, k=5)
print(eval_result)
# eval_result = evaluate_final_recommendations(final_recommendations, test_ratings, k=10)
# print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_48048\3616414181.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.6971539766817687, 'Recall@5': 0.02525017748090077, 'MRR@5': 0.12717439293598232}

In [53]:
def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_ratings['user_id'].unique()

    for user in unique_users:
        # Get the recommended items for the user
        recommended_items = final_recommendations[user]

        # Get the actual items the user interacted with in the test set
        user_test_data = test_ratings[test_ratings['user_id'] == user]
        test_items = user_test_data['item_id'].values

        # Create a binary relevance score list (1 if item is in the test set, 0 otherwise)
        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 2.5
            for item in recommended_items
        ]
        # Calculate the evaluation metrics
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        # Store the scores
        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # Compute average scores
    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }


# Evaluate the final recommendations
eval_result = evaluate_final_recommendations(final_recommendations_with_weight, test_ratings, k=5)
print(eval_result)
# eval_result = evaluate_final_recommendations(final_recommendations, test_ratings, k=10)
# print(eval_result)

{'NDCG@5': 0.9864683233258414}

In [54]:
def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_ratings['user_id'].unique()

    for user in unique_users:
        # Get the recommended items for the user
        recommended_items = final_recommendations[user]

        # Get the actual items the user interacted with in the test set
        user_test_data = test_ratings[test_ratings['user_id'] == user]
        test_items = user_test_data['item_id'].values

        # Create a binary relevance score list (1 if item is in the test set, 0 otherwise)
        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 0
            for item in recommended_items
        ]
        # Calculate the evaluation metrics
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        # Store the scores
        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # Compute average scores
    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
    }


# Evaluate the final recommendations
eval_result = evaluate_final_recommendations(final_recommendations_with_weight, test_ratings, k=5)
print(eval_result)
# eval_result = evaluate_final_recommendations(final_recommendations, test_ratings, k=10)
# print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_48048\1029841768.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.6930541880009977}

## Gradio Visualization

In [437]:
import gradio as gr

In [446]:
def CFGenerator(user_id):
    k=10
    user_id = int(user_id)
    # Check if user_id exists in the users dataframe
    if user_id not in users["user_id"].values:
        return [f"User ID {user_id} does not exist in the database."]

    recommended_items = user_cf.recommend_user(user_id, n_rec=k, filter_consumed=True)
    movie_ids = recommended_items[user_id]
    movie_titles = []
    for movie_id in movie_ids:
        title_row = movies[movies["item_id"] == movie_id]
        if not title_row.empty:
            movie_titles.append(title_row["title"].values[0])
        else:
            movie_titles.append(f"Unknown Movie ID: {movie_id}")

    # Add ranks to the movie titles with proper newline formatting
    movie_titles_string = "\n".join([f"{i + 1}. {title}" for i, title in enumerate(movie_titles)])
    return movie_titles_string

In [447]:
def TTGenerator(input_data, input_method="User ID"):
    k=10
    try:
        if input_method == "User ID":
            # Validate user ID input
            try:
                user_id = int(input_data)
            except ValueError:
                return "Invalid User ID. Please enter a valid integer."

            # Generate recommendations using user ID
            movie_ids = get_top_n_items_with_history_unseen_items_gradio(
                best_model, user_id, n=k, input_type="userId"
            )

        elif input_method == "Manual Data Entry":
            # Validate user text input
            user_text = input_data.strip()
            if not user_text:
                return "No user data provided. Please enter valid user text."

            # Generate recommendations using manual user text
            movie_ids = get_top_n_items_with_history_unseen_items_gradio(
                best_model, user_text, n=k, input_type="userText"
            )

        else:
            return "Invalid input method. Please choose either 'User ID' or 'Manual Data Entry'."
        # Retrieve movie titles
        movie_titles = []
        for movie_id in movie_ids:
            title_row = movies[movies["item_id"] == movie_id]
            if not title_row.empty:
                movie_titles.append(title_row["title"].values[0])
            else:
                movie_titles.append(f"Unknown Movie ID: {movie_id}")

        # Add ranks to the movie titles with proper newline formatting
        movie_titles_string = "\n".join([f"{i + 1}. {title}" for i, title in enumerate(movie_titles)])
        return movie_titles_string

    except ValueError as e:
        return str(e)
    except Exception as e:
        return f"An error occurred: {str(e)}"

In [280]:
# TTGenerator(1, input_method="User ID")
# TTGenerator("f", input_method="Manual Data Entry")

1. Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)
2. Out of the Past (1947)
3. Force of Evil (1948)
4. Gilda (1946)
5. Big Combo, The (1955)

'1. Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)\n2. Out of the Past (1947)\n3. Force of Evil (1948)\n4. Gilda (1946)\n5. Big Combo, The (1955)'

In [440]:
def get_top_n_items_with_history_unseen_items_gradio(model, user_input, n, input_type="userId"):
    # Ensure the model is in evaluation mode
    model.eval()
    userId = 0
    if input_type == "userId":
        # Handle userId input
        try:
            userId = int(user_input)
        except ValueError:
            raise ValueError("Invalid userId. Please provide a valid integer.")

        if userId not in val_last_user_texts:
            raise ValueError(f"User ID {userId} does not exist in the database.")

        # Get the user text for the given userId
        user_text = val_last_user_texts[userId]
    elif input_type == "userText":
        # Handle userText input
        user_text = user_input.strip()
        if not user_text:
            raise ValueError("Invalid user text. Please provide non-empty text.")
    else:
        raise ValueError("Invalid input type. Must be 'userId' or 'userText'.")

    # Encode the user text
    user_embedding = model.user_model.encode(user_text, convert_to_tensor=True).to(device)
    # Compute the scores (dot product between user embedding and each item embedding)
    user_output = model.user_fc(user_embedding).to(device)
    item_output = model.item_fc(full_items_embeddings).to(device)
    dot_product = torch.matmul(user_output, item_output.t()).squeeze()

    if input_type == "userId":
        # Get items the user has seen in the training and validation data
        seen_items_train = train_ratings[train_ratings['user_id'] == userId]['item_id'].values
        seen_items_val = val_ratings[val_ratings['user_id'] == userId]['item_id'].values
        seen_items = set(np.concatenate((seen_items_train, seen_items_val)))

        # Get the top n + len(seen_items) item indices and their scores
        top_n_scores, top_n_indices = torch.topk(dot_product, n + len(seen_items))

        # Map indices back to item IDs
        top_n_item_ids = [list(movie_id_to_idx.keys())[list(movie_id_to_idx.values()).index(idx.item())] for idx in
                          top_n_indices]

        # Filter out seen items
        unseen_top_n_item_ids = [item for item in top_n_item_ids if item not in seen_items]

        return unseen_top_n_item_ids[:n]

    else:
        top_n_scores, top_n_indices = torch.topk(dot_product, n)
        top_n_item_ids = [list(movie_id_to_idx.keys())[list(movie_id_to_idx.values()).index(idx.item())] for idx in
                          top_n_indices]

        return top_n_item_ids[:n]

In [448]:
def rrf_score(ranks, k=10):
    return sum([1 / (k + rank) for rank in ranks])

def combine_recommendations_with_rrf_with_weight_for_gradio(user_id, k=10, cf_weight=1, tt_weight=4, input_method="userId"):
    # Dictionary to hold the RRF scores
    combined_scores = {}

    # If input is "userId", only use Two-Tower recommendations
    if input_method == "Manual Data Entry":
        tt_recommended_item = get_top_n_items_with_history_unseen_items_gradio(
            best_model, user_id, n=k, input_type="userText"
        )

        # Calculate RRF scores from Two-Tower recommendations
        for rank, item in enumerate(tt_recommended_item, start=1):
            weighted_rank = rank * tt_weight  # Apply the weight to TT ranks
            if item not in combined_scores:
                combined_scores[item] = rrf_score([weighted_rank], k)
            else:
                combined_scores[item] += rrf_score([weighted_rank], k)

    # If input is "User ID", combine CF and TT recommendations
    else:
        # Get Collaborative Filtering recommendations
        user_id = int(user_id)
        cf_recommended_items = user_cf.recommend_user(user_id, n_rec=k, filter_consumed=True)

        # Assign ranks and calculate weighted RRF scores from CF recommendations
        for rank, item in enumerate(cf_recommended_items[user_id], start=1):
            weighted_rank = rank * cf_weight  # Apply the weight to CF ranks
            if item not in combined_scores:
                combined_scores[item] = rrf_score([weighted_rank], k)
            else:
                combined_scores[item] += rrf_score([weighted_rank], k)

        # Get Two-Tower recommendations
        tt_recommended_item = get_top_n_items_with_history_unseen_items_gradio(
            best_model, user_id, n=k, input_type="userId"
        )
        # print(movieTitleOutput(tt_recommended_item))

        # Assign ranks and calculate weighted RRF scores from TT recommendations
        for rank, item in enumerate(tt_recommended_item, start=1):
            weighted_rank = rank * tt_weight  # Apply the weight to TT ranks
            if item not in combined_scores:
                combined_scores[item] = rrf_score([weighted_rank], k)
            else:
                combined_scores[item] += rrf_score([weighted_rank], k)

    # Sort the items based on their RRF scores in descending order
    sorted_items = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)

    # Retrieve the top N item IDs
    top_items = [item for item, score in sorted_items[:k]]

    # Get the movie titles for the top items
    movie_titles = []
    for movie_id in top_items:
        title_row = movies[movies["item_id"] == movie_id]
        if not title_row.empty:
            movie_titles.append(title_row["title"].values[0])
        else:
            movie_titles.append(f"Unknown Movie ID: {movie_id}")

    # Add ranks to the movie titles with proper newline formatting
    movie_titles_string = "\n".join([f"{i + 1}. {title}" for i, title in enumerate(movie_titles)])

    return movie_titles_string

In [369]:
tt_recommendations

{1: [922, 2066, 746, 2940, 3292],
 2: [922, 2066, 746, 2940, 3292],
 3: [922, 2066, 746, 2940, 3292],
 4: [3121, 1153, 3380, 2066, 3292],
 5: [922, 2066, 746, 2940, 3292],
 6: [922, 2066, 746, 2940, 3292],
 7: [3121, 1153, 3380, 3292, 1154],
 8: [922, 2066, 746, 2940, 3292],
 9: [922, 2066, 746, 2940, 3292],
 10: [922, 2066, 746, 2940, 3292],
 11: [922, 2066, 746, 2940, 3292],
 12: [1154, 1153, 3121, 3380, 2940],
 13: [922, 2066, 746, 2940, 3292],
 14: [1154, 1153, 3121, 3380, 2940],
 15: [922, 2066, 746, 2940, 3292],
 16: [922, 2066, 746, 2940, 3292],
 17: [922, 2066, 746, 2940, 3292],
 18: [922, 2066, 746, 2940, 3292],
 19: [922, 2066, 746, 2940, 3292],
 20: [1154, 1153, 3121, 3380, 2940],
 21: [1153, 1154, 3121, 2727, 3380],
 22: [922, 2066, 746, 2940, 3292],
 23: [922, 2066, 746, 2940, 3292],
 24: [922, 2066, 746, 2940, 3292],
 25: [922, 2066, 746, 2940, 3292],
 26: [922, 2066, 746, 2940, 3292],
 27: [746, 2940, 3292, 2727, 1154],
 28: [922, 2066, 746, 2940, 3292],
 29: [922, 2066, 746, 2940, 3292],
 30: [922, 2066, 746, 2940, 3292],
 31: [922, 2066, 746, 2940, 3292],
 32: [922, 2066, 746, 2940, 3292],
 33: [922, 2066, 746, 2940, 3292],
 34: [922, 2066, 746, 2940, 3292],
 35: [922, 2066, 746, 2940, 3292],
 36: [922, 2066, 746, 2940, 3292],
 37: [922, 2066, 746, 2940, 3292],
 38: [922, 2066, 746, 2940, 3292],
 39: [922, 2066, 746, 2940, 3292],
 40: [922, 2066, 746, 2940, 3292],
 41: [1154, 1153, 3121, 3380, 2940],
 42: [922, 2066, 746, 2940, 3292],
 43: [1154, 1153, 3121, 3380, 2940],
 44: [922, 2066, 746, 2940, 3292],
 45: [922, 2066, 746, 2940, 3292],
 46: [922, 2066, 746, 2940, 3292],
 47: [3121, 1153, 3380, 2066, 3292],
 48: [922, 2066, 746, 2940, 3292],
 49: [922, 2066, 746, 2940, 3292],
 50: [922, 2066, 746, 2940, 3292],
 51: [922, 2066, 746, 2940, 3292],
 52: [922, 2066, 746, 2940, 3292],
 53: [2066, 746, 2940, 3292, 2727],
 54: [922, 2066, 746, 2940, 3292],
 55: [1154, 1153, 3121, 3380, 2940],
 56: [922, 2066, 746, 2940, 3292],
 57: [922, 2066, 746, 2940, 3292],
 58: [922, 2066, 746, 2940, 3292],
 59: [922, 2066, 746, 2940, 3292],
 60: [922, 2066, 746, 2940, 3292],
 61: [922, 2066, 746, 2940, 3292],
 62: [922, 2066, 746, 3292, 2727],
 63: [922, 2066, 746, 2940, 3292],
 64: [3121, 1153, 3380, 3292, 1154],
 65: [922, 2066, 746, 2940, 3292],
 66: [1154, 1153, 3121, 3380, 2940],
 67: [922, 2066, 746, 2940, 3292],
 68: [922, 2066, 746, 2940, 3292],
 69: [922, 2066, 746, 2940, 3292],
 70: [922, 2066, 746, 2940, 3292],
 71: [3380, 3121, 1153, 2940, 2727],
 72: [922, 2066, 746, 2940, 3292],
 73: [922, 2066, 746, 2940, 3292],
 74: [922, 2066, 746, 2940, 3292],
 75: [922, 2066, 746, 2940, 3292],
 76: [922, 2066, 746, 2940, 3292],
 77: [922, 2066, 746, 2940, 3292],
 78: [922, 2066, 746, 2940, 3292],
 79: [3121, 1153, 3380, 3292, 1154],
 80: [922, 2066, 746, 2940, 3292],
 81: [922, 2066, 746, 2940, 3292],
 82: [922, 2066, 746, 2940, 3292],
 83: [922, 2066, 746, 2940, 3292],
 84: [3121, 1153, 3380, 3292, 1154],
 85: [922, 2066, 746, 2940, 3292],
 86: [922, 2066, 746, 2940, 3292],
 87: [922, 2066, 746, 2940, 3292],
 88: [922, 2066, 746, 2940, 3292],
 89: [3380, 1153, 3121, 2066, 3292],
 90: [922, 2066, 746, 2940, 3292],
 91: [922, 2066, 746, 2940, 3292],
 92: [922, 2066, 746, 2940, 3292],
 93: [922, 2066, 746, 2940, 3292],
 94: [3121, 1153, 3380, 2066, 3292],
 95: [922, 2066, 746, 2940, 3292],
 96: [922, 2066, 746, 2940, 3292],
 97: [2066, 746, 2940, 3292, 2727],
 98: [1153, 3380, 3121, 2066, 3292],
 99: [922, 2066, 746, 2940, 3292],
 100: [922, 2066, 746, 2940, 3292],
 101: [922, 2066, 746, 2940, 3292],
 102: [922, 2066, 746, 2940, 3292],
 103: [922, 2066, 746, 2940, 3292],
 104: [922, 2066, 746, 2940, 3292],
 105: [922, 2066, 746, 2940, 3292],
 106: [922, 2066, 746, 2940, 3292],
 107: [922, 2066, 746, 2940, 3292],
 108: [922, 2066, 746, 2940, 3292],
 109: [922, 2066, 746, 2940, 3292],
 110: [922, 2066, 746, 2940, 3292],
 111: [922, 2066, 746, 2940, 3292],
 112: [746, 2940, 3292, 2727, 1154],
 113: [922, 2066, 746, 2940, 3292],
 114: [922, 2066, 746, 2940, 3292],
 115: [922, 2066, 746, 2940, 3292],
 116: [922, 2066, 746, 2940, 3292],
 117: [922, 2066, 746, 2940, 3292],
 118: [922, 2066, 746, 2940, 3292],
 119: [922, 2066, 746, 2940, 3292],
 120: [922, 2066, 746, 2940, 3292],
 121: [922, 2066, 746, 2940, 3292],
 122: [922, 2066, 746, 2940, 3292],
 123: [922, 2066, 746, 2940, 3292],
 124: [1154, 1153, 3121, 3380, 2940],
 125: [922, 2066, 746, 2940, 3292],
 126: [922, 2066, 746, 2940, 3292],
 127: [922, 2066, 746, 2940, 3292],
 128: [3380, 1153, 3121, 2066, 3292],
 129: [922, 2066, 746, 2940, 3292],
 130: [922, 2066, 746, 2940, 3292],
 131: [922, 2066, 746, 2940, 3292],
 132: [922, 2066, 746, 2940, 3292],
 133: [922, 2066, 746, 2940, 3292],
 134: [922, 2066, 746, 2940, 3292],
 135: [922, 2066, 746, 2940, 3292],
 136: [2066, 746, 2940, 3292, 2727],
 137: [922, 2066, 746, 2940, 3292],
 138: [922, 2066, 746, 2940, 3292],
 139: [922, 2066, 746, 2940, 3292],
 140: [922, 2066, 746, 3292, 2727],
 141: [2727, 1153, 3121, 1154, 3380],
 142: [922, 2066, 746, 2940, 3292],
 143: [922, 2066, 746, 2940, 3292],
 144: [922, 2066, 746, 2940, 3292],
 145: [922, 2066, 746, 2940, 3292],
 146: [922, 2066, 746, 3292, 2727],
 147: [922, 2066, 746, 2940, 3292],
 148: [922, 2066, 746, 2940, 3292],
 149: [922, 2066, 746, 2940, 3292],
 150: [922, 2066, 746, 2940, 3292],
 151: [922, 2066, 746, 2940, 3292],
 152: [1154, 1153, 3121, 3380, 2940],
 153: [3121, 3380, 3292, 1153, 1154],
 154: [922, 2066, 746, 2940, 3292],
 155: [922, 2066, 746, 2940, 3292],
 156: [922, 2066, 746, 2940, 3292],
 157: [922, 2066, 746, 2940, 3292],
 158: [1153, 1154, 3121, 3380, 2940],
 159: [922, 2066, 746, 2940, 3292],
 160: [1153, 3380, 3121, 2066, 3292],
 161: [922, 2066, 746, 2940, 3292],
 162: [922, 2066, 746, 2940, 3292],
 163: [922, 2066, 746, 2940, 3292],
 164: [3380, 2727, 1153, 3292, 1154],
 165: [922, 2066, 746, 2940, 3292],
 166: [2066, 746, 2940, 3292, 2727],
 167: [922, 2066, 746, 2940, 3292],
 168: [3121, 3380, 3292, 1153, 1154],
 169: [2066, 746, 2940, 3292, 2727],
 170: [922, 2066, 746, 2940, 3292],
 171: [2727, 1153, 3121, 1154, 3380],
 172: [2727, 1153, 3121, 1154, 3380],
 173: [746, 2940, 3292, 2727, 1154],
 174: [922, 2066, 746, 2940, 3292],
 175: [922, 2066, 746, 2940, 3292],
 176: [922, 2066, 746, 2940, 3292],
 177: [922, 2066, 746, 2940, 3292],
 178: [922, 2066, 746, 2940, 3292],
 179: [922, 2066, 746, 2940, 3292],
 180: [922, 2066, 746, 2940, 3292],
 181: [922, 2066, 746, 2940, 3292],
 182: [922, 2066, 746, 2940, 3292],
 183: [922, 2066, 746, 2940, 3292],
 184: [922, 2066, 746, 2940, 3292],
 185: [922, 2066, 746, 2940, 3292],
 186: [922, 2066, 746, 2940, 3292],
 187: [922, 2066, 746, 2940, 3292],
 188: [922, 2066, 746, 2940, 3292],
 189: [3121, 1153, 3380, 3292, 1154],
 190: [922, 2066, 746, 2940, 3292],
 191: [3380, 3121, 1153, 2940, 2727],
 192: [922, 2066, 746, 2940, 3292],
 193: [2066, 746, 2940, 3292, 2727],
 194: [922, 2066, 746, 2940, 3292],
 195: [922, 2066, 746, 2940, 3292],
 196: [922, 2066, 746, 2940, 3292],
 197: [3121, 1153, 3380, 2066, 3292],
 198: [922, 2066, 746, 2940, 3292],
 199: [922, 2066, 746, 2940, 3292],
 200: [3121, 3380, 3292, 1153, 1154],
 201: [922, 2066, 746, 2940, 3292],
 202: [922, 2066, 746, 2940, 3292],
 203: [922, 2066, 746, 2940, 3292],
 204: [922, 2066, 746, 2940, 3292],
 205: [922, 2066, 746, 2940, 3292],
 206: [3121, 1153, 3380, 3292, 1154],
 207: [1154, 1153, 3121, 3380, 2940],
 208: [922, 2066, 746, 2940, 3292],
 209: [1154, 1153, 3121, 3380, 2940],
 210: [922, 2066, 746, 2940, 3292],
 211: [922, 2066, 746, 2940, 3292],
 212: [922, 2066, 746, 2940, 3292],
 213: [3121, 1153, 3380, 2066, 3292],
 214: [922, 2066, 746, 2940, 3292],
 215: [922, 2066, 746, 2940, 3292],
 216: [922, 2066, 746, 2940, 3292],
 217: [3121, 1153, 3380, 2066, 3292],
 218: [922, 2066, 746, 2940, 3292],
 219: [922, 2066, 746, 2940, 3292],
 220: [922, 2066, 746, 2940, 3292],
 221: [3121, 3380, 3292, 1153, 1154],
 222: [922, 2066, 746, 2940, 3292],
 223: [922, 2066, 746, 2940, 3292],
 224: [922, 2066, 746, 2940, 3292],
 225: [2066, 746, 2940, 3292, 2727],
 226: [3121, 1153, 3380, 2066, 3292],
 227: [3121, 1153, 3380, 3292, 1154],
 228: [3380, 3121, 2727, 1153, 1154],
 229: [922, 2066, 746, 2940, 3292],
 230: [922, 2066, 746, 2940, 3292],
 231: [922, 2066, 746, 2940, 3292],
 232: [922, 2066, 746, 2940, 3292],
 233: [922, 2066, 746, 2940, 3292],
 234: [3121, 1153, 3380, 3292, 1154],
 235: [2066, 746, 2940, 3292, 2727],
 236: [922, 2066, 746, 2940, 3292],
 237: [922, 2066, 746, 2940, 3292],
 238: [922, 2066, 746, 2940, 3292],
 239: [922, 2066, 746, 2940, 3292],
 240: [922, 2066, 746, 2940, 3292],
 241: [922, 2066, 746, 2940, 3292],
 242: [922, 2066, 746, 2940, 3292],
 243: [922, 2066, 746, 2940, 3292],
 244: [922, 2066, 746, 2940, 3292],
 245: [2066, 746, 2940, 3292, 2727],
 246: [3121, 1153, 3380, 3292, 1154],
 247: [3121, 1153, 3380, 3292, 1154],
 248: [922, 2066, 746, 2940, 3292],
 249: [922, 2066, 746, 2940, 3292],
 250: [3121, 1153, 3380, 2066, 3292],
 251: [922, 2066, 746, 2940, 3292],
 252: [922, 2066, 746, 2940, 3292],
 253: [922, 2066, 746, 2940, 3292],
 254: [1154, 1153, 3121, 3380, 2940],
 255: [922, 2066, 746, 2940, 3292],
 256: [922, 2066, 746, 2940, 3292],
 257: [922, 2066, 746, 2940, 3292],
 258: [922, 2066, 746, 2940, 3292],
 259: [922, 2066, 746, 2940, 3292],
 260: [922, 2066, 746, 2940, 3292],
 261: [922, 2066, 746, 2940, 3292],
 262: [922, 2066, 746, 2940, 3292],
 263: [922, 2066, 746, 2940, 3292],
 264: [922, 2066, 746, 2940, 3292],
 265: [922, 2066, 746, 2940, 3292],
 266: [922, 2066, 746, 2940, 3292],
 267: [922, 2066, 746, 2940, 3292],
 268: [922, 2066, 746, 2940, 3292],
 269: [3121, 1153, 3380, 3292, 1154],
 270: [922, 2066, 746, 2940, 3292],
 271: [922, 2066, 746, 2940, 3292],
 272: [922, 2066, 746, 2940, 3292],
 273: [922, 2066, 746, 2940, 3292],
 274: [922, 2066, 746, 2940, 3292],
 275: [922, 2066, 746, 2940, 3292],
 276: [2727, 1153, 3121, 1154, 3380],
 277: [3121, 1153, 3380, 2066, 3292],
 278: [922, 2066, 746, 2940, 3292],
 279: [922, 2066, 746, 2940, 3292],
 280: [922, 2066, 746, 2940, 3292],
 281: [922, 2066, 746, 2940, 3292],
 282: [3121, 1153, 3380, 3292, 1154],
 283: [3121, 1153, 3380, 3292, 1154],
 284: [922, 2066, 746, 2940, 3292],
 285: [922, 2066, 746, 2940, 3292],
 286: [922, 2066, 746, 2940, 3292],
 287: [922, 2066, 746, 2940, 3292],
 288: [922, 2066, 746, 2940, 3292],
 289: [922, 2066, 746, 2940, 3292],
 290: [922, 2066, 746, 2940, 3292],
 291: [922, 2066, 746, 2940, 3292],
 292: [922, 2066, 746, 2940, 3292],
 293: [922, 2066, 746, 2940, 3292],
 294: [922, 2066, 746, 2940, 3292],
 295: [922, 2066, 746, 2940, 3292],
 296: [922, 2066, 746, 2940, 3292],
 297: [922, 2066, 746, 2940, 3292],
 298: [3121, 1153, 3380, 3292, 1154],
 299: [922, 2066, 746, 2940, 3292],
 300: [2066, 746, 2940, 3292, 2727],
 301: [922, 2066, 746, 2940, 3292],
 302: [922, 2066, 746, 2940, 3292],
 303: [922, 2066, 746, 2940, 3292],
 304: [3380, 3292, 1153, 1154, 2727],
 305: [922, 2066, 746, 2940, 3292],
 306: [922, 2066, 746, 2940, 3292],
 307: [922, 2066, 746, 2940, 3292],
 308: [922, 2066, 746, 2940, 3292],
 309: [922, 2066, 746, 2940, 3292],
 310: [922, 2066, 746, 2940, 3292],
 311: [3121, 1153, 3380, 2066, 3292],
 312: [922, 2066, 746, 2940, 3292],
 313: [3380, 1154, 1153, 3121, 2727],
 314: [922, 2066, 746, 2940, 3292],
 315: [3121, 1153, 3380, 2066, 3292],
 316: [922, 2066, 746, 2940, 3292],
 317: [3121, 1153, 3380, 2066, 3292],
 318: [1153, 3380, 3121, 2066, 3292],
 319: [922, 2066, 746, 2940, 3292],
 320: [3121, 1153, 3380, 746, 2940],
 321: [922, 2066, 746, 2940, 3292],
 322: [922, 2066, 746, 2940, 3292],
 323: [922, 2066, 746, 2940, 3292],
 324: [922, 2066, 746, 2940, 3292],
 325: [922, 2066, 746, 2940, 3292],
 326: [922, 2066, 746, 2940, 3292],
 327: [2066, 746, 2940, 3292, 2727],
 328: [922, 2066, 746, 2940, 3292],
 329: [922, 2066, 746, 2940, 3292],
 330: [922, 2066, 746, 2940, 3292],
 331: [922, 2066, 746, 2940, 3292],
 332: [922, 2066, 746, 2940, 3292],
 333: [922, 2066, 746, 2940, 3292],
 334: [922, 2066, 746, 2940, 3292],
 335: [922, 2066, 746, 2940, 3292],
 336: [922, 2066, 746, 2940, 3292],
 337: [922, 2066, 746, 2940, 3292],
 338: [922, 2066, 746, 2940, 3292],
 339: [922, 2066, 746, 2940, 3292],
 340: [2066, 746, 2940, 3292, 2727],
 341: [1153, 1154, 3380, 3121, 2940],
 342: [922, 2066, 746, 2940, 3292],
 343: [922, 2066, 746, 2940, 3292],
 344: [922, 2066, 746, 2940, 3292],
 345: [1154, 1153, 3121, 3380, 2940],
 346: [922, 2066, 746, 2940, 3292],
 347: [922, 2066, 746, 2940, 3292],
 348: [922, 2066, 746, 2940, 3292],
 349: [922, 2066, 746, 2940, 3292],
 350: [922, 2066, 746, 2940, 3292],
 351: [922, 2066, 746, 2940, 3292],
 352: [922, 2066, 746, 2940, 3292],
 353: [1154, 1153, 3121, 3380, 2940],
 354: [922, 2066, 746, 2940, 3292],
 355: [922, 2066, 746, 2940, 3292],
 356: [1153, 3380, 3121, 2066, 3292],
 357: [922, 2066, 746, 2940, 3292],
 358: [922, 2066, 746, 2940, 3292],
 359: [922, 2066, 746, 2940, 3292],
 360: [922, 2066, 746, 2940, 3292],
 361: [3121, 3380, 3292, 1153, 1154],
 362: [922, 2066, 746, 2940, 3292],
 363: [922, 2066, 746, 2940, 3292],
 364: [3121, 1153, 3380, 3292, 1154],
 365: [922, 2066, 746, 2940, 3292],
 366: [922, 2066, 746, 2940, 3292],
 367: [3121, 1153, 3380, 3292, 1154],
 368: [922, 2066, 746, 2940, 3292],
 369: [922, 2066, 746, 2940, 3292],
 370: [922, 2066, 746, 2940, 3292],
 371: [922, 2066, 746, 2940, 3292],
 372: [922, 2066, 746, 2940, 3292],
 373: [3121, 1153, 3380, 3292, 1154],
 374: [922, 2066, 746, 2940, 3292],
 375: [922, 2066, 746, 2940, 3292],
 376: [922, 2066, 746, 2940, 3292],
 377: [922, 2066, 746, 2940, 3292],
 378: [922, 2066, 746, 2940, 3292],
 379: [922, 2066, 746, 2940, 3292],
 380: [922, 2066, 746, 2940, 3292],
 381: [922, 2066, 746, 2940, 3292],
 382: [922, 2066, 746, 2940, 3292],
 383: [1153, 3380, 3121, 2066, 3292],
 384: [3121, 1153, 1154, 3380, 2940],
 385: [922, 2066, 746, 2940, 3292],
 386: [922, 2066, 746, 2940, 3292],
 387: [922, 2066, 746, 2940, 3292],
 388: [922, 2066, 746, 2940, 3292],
 389: [922, 2066, 746, 2940, 3292],
 390: [2066, 746, 2940, 3292, 2727],
 391: [922, 2066, 2940, 3292, 2727],
 392: [922, 2066, 746, 2940, 3292],
 393: [922, 2066, 746, 2940, 3292],
 394: [922, 2066, 746, 2940, 3292],
 395: [2727, 1153, 3121, 1154, 3380],
 396: [922, 2066, 746, 2940, 3292],
 397: [922, 2066, 746, 2940, 3292],
 398: [922, 2066, 746, 2940, 3292],
 399: [922, 2066, 746, 2940, 3292],
 400: [922, 2066, 746, 2940, 3292],
 401: [922, 2066, 746, 2940, 3292],
 402: [922, 2066, 746, 2940, 3292],
 403: [922, 2066, 746, 2940, 3292],
 404: [922, 2066, 746, 2940, 3292],
 405: [922, 2066, 746, 2940, 3292],
 406: [922, 2066, 746, 2940, 3292],
 407: [922, 2066, 746, 2940, 3292],
 408: [922, 2066, 746, 2940, 3292],
 409: [922, 2066, 746, 2940, 3292],
 410: [922, 2066, 746, 2940, 3292],
 411: [922, 2066, 746, 2940, 3292],
 412: [922, 2066, 746, 3292, 2727],
 413: [922, 2066, 746, 2940, 3292],
 414: [922, 2066, 746, 2940, 3292],
 415: [922, 2066, 746, 2940, 3292],
 416: [922, 2066, 746, 2940, 3292],
 417: [3380, 1153, 3121, 2066, 3292],
 418: [922, 2066, 746, 2940, 3292],
 419: [922, 2066, 746, 2940, 3292],
 420: [922, 2066, 746, 2940, 3292],
 421: [3121, 1153, 3380, 2066, 3292],
 422: [922, 2066, 746, 2940, 3292],
 423: [922, 2066, 746, 2940, 3292],
 424: [2066, 746, 2940, 3292, 2727],
 425: [922, 2066, 746, 2940, 3292],
 426: [922, 2066, 746, 2940, 3292],
 427: [3121, 1153, 3380, 3292, 1154],
 428: [922, 2066, 746, 2940, 3292],
 429: [922, 2066, 746, 2940, 3292],
 430: [922, 2066, 746, 2940, 3292],
 431: [922, 2066, 746, 2940, 3292],
 432: [922, 2066, 746, 2940, 3292],
 433: [922, 2066, 746, 2940, 3292],
 434: [922, 2066, 746, 2940, 3292],
 435: [922, 2066, 746, 2940, 3292],
 436: [922, 2066, 746, 2940, 3292],
 437: [922, 2066, 746, 2940, 3292],
 438: [922, 2066, 746, 2940, 3292],
 439: [922, 2066, 746, 2940, 3292],
 440: [3121, 1153, 3380, 3292, 1154],
 441: [922, 2066, 746, 2940, 3292],
 442: [922, 2066, 746, 2940, 3292],
 443: [922, 2066, 746, 2940, 3292],
 444: [922, 2066, 746, 2940, 3292],
 445: [922, 2066, 746, 2940, 3292],
 446: [2066, 746, 2940, 3292, 2727],
 447: [922, 2066, 746, 2940, 3292],
 448: [2727, 1153, 3121, 1154, 3380],
 449: [922, 2066, 746, 2940, 3292],
 450: [922, 2066, 746, 2940, 3292],
 451: [922, 2066, 746, 2940, 3292],
 452: [922, 2066, 746, 2940, 3292],
 453: [922, 2066, 746, 2940, 3292],
 454: [922, 2066, 746, 2940, 3292],
 455: [1154, 1153, 3121, 3380, 2940],
 456: [922, 2066, 746, 2940, 3292],
 457: [922, 2066, 746, 2940, 3292],
 458: [922, 2066, 746, 2940, 3292],
 459: [922, 2066, 746, 2940, 3292],
 460: [922, 2066, 746, 2940, 3292],
 461: [922, 2066, 746, 2940, 3292],
 462: [922, 2066, 746, 2940, 3292],
 463: [922, 2066, 746, 2940, 3292],
 464: [922, 2066, 746, 2940, 3292],
 465: [922, 2066, 746, 2940, 3292],
 466: [922, 2066, 746, 2940, 3292],
 467: [922, 2066, 746, 2940, 3292],
 468: [3121, 3380, 3292, 1153, 1154],
 469: [922, 2066, 746, 2940, 3292],
 470: [922, 2066, 746, 2940, 3292],
 471: [922, 2066, 746, 2940, 3292],
 472: [922, 2066, 746, 2940, 3292],
 473: [922, 2066, 746, 2940, 3292],
 474: [922, 2066, 746, 2940, 3292],
 475: [922, 2066, 746, 2940, 3292],
 476: [922, 746, 2940, 3292, 2727],
 477: [922, 2066, 746, 2940, 3292],
 478: [922, 2066, 746, 2940, 3292],
 479: [922, 2066, 746, 2940, 3292],
 480: [922, 2066, 746, 2940, 3292],
 481: [922, 2066, 746, 2940, 3292],
 482: [922, 2066, 746, 2940, 3292],
 483: [3121, 1153, 3380, 3292, 1154],
 484: [922, 2066, 746, 2940, 3292],
 485: [922, 2066, 746, 2940, 3292],
 486: [922, 2066, 746, 2940, 3292],
 487: [922, 2066, 746, 2940, 3292],
 488: [1154, 1153, 3121, 3380, 2940],
 489: [1154, 1153, 3121, 3380, 2940],
 490: [922, 2066, 746, 2940, 3292],
 491: [1154, 1153, 3121, 3380, 2940],
 492: [922, 2066, 746, 2940, 3292],
 493: [922, 2066, 746, 2940, 3292],
 494: [922, 2066, 746, 2940, 3292],
 495: [922, 2066, 746, 2940, 3292],
 496: [922, 2066, 746, 2940, 3292],
 497: [1154, 1153, 3121, 3380, 2940],
 498: [922, 2066, 746, 2940, 3292],
 499: [922, 2066, 746, 2940, 3292],
 500: [922, 2066, 746, 2940, 3292],
 501: [922, 2066, 746, 2940, 3292],
 502: [3380, 1154, 1153, 3121, 2727],
 503: [3121, 1153, 3380, 3292, 1154],
 504: [746, 2940, 3292, 2727, 1154],
 505: [922, 2066, 746, 2940, 3292],
 506: [922, 2066, 746, 2940, 3292],
 507: [922, 2066, 746, 2940, 3292],
 508: [922, 2066, 746, 2940, 3292],
 509: [922, 2066, 746, 2940, 3292],
 510: [922, 2066, 746, 2940, 3292],
 511: [3121, 1153, 3380, 3292, 1154],
 512: [922, 2066, 746, 2940, 3292],
 513: [922, 2066, 746, 2940, 3292],
 514: [922, 2066, 746, 2940, 3292],
 515: [922, 2066, 746, 2940, 3292],
 516: [922, 2066, 746, 2940, 3292],
 517: [922, 2066, 746, 2940, 3292],
 518: [922, 2066, 746, 2940, 3292],
 519: [922, 2066, 746, 2940, 3292],
 520: [922, 2066, 746, 2940, 3292],
 521: [922, 2066, 746, 2940, 3292],
 522: [922, 2066, 746, 2940, 3292],
 523: [922, 2066, 746, 2940, 3292],
 524: [922, 2066, 746, 2940, 3292],
 525: [922, 2066, 746, 2940, 3292],
 526: [922, 2066, 746, 2940, 3292],
 527: [1154, 1153, 3121, 3380, 2940],
 528: [922, 2066, 746, 2940, 3292],
 529: [922, 2066, 746, 2940, 3292],
 530: [922, 2066, 746, 2940, 3292],
 531: [922, 2066, 746, 2940, 3292],
 532: [922, 2066, 746, 2940, 3292],
 533: [922, 2066, 746, 2940, 3292],
 534: [922, 2066, 746, 2940, 3292],
 535: [1153, 3380, 3121, 2066, 3292],
 536: [922, 2066, 746, 2940, 3292],
 537: [922, 2066, 746, 2940, 3292],
 538: [922, 2066, 746, 2940, 3292],
 539: [922, 2066, 746, 2940, 3292],
 540: [922, 2066, 746, 2940, 3292],
 541: [922, 2066, 746, 2940, 3292],
 542: [922, 2066, 746, 2940, 3292],
 543: [922, 2066, 746, 2940, 3292],
 544: [922, 2066, 746, 2940, 3292],
 545: [3380, 3121, 1153, 2940, 2727],
 546: [922, 2066, 746, 2940, 3292],
 547: [922, 2066, 746, 2940, 3292],
 548: [922, 2066, 746, 2940, 3292],
 549: [922, 2066, 746, 2940, 3292],
 550: [922, 2066, 746, 2940, 3292],
 551: [922, 2066, 746, 2940, 3292],
 552: [922, 2066, 746, 2940, 3292],
 553: [922, 2066, 746, 2940, 3292],

In [449]:
# Function to show user preferences dynamically
def show_user_preferences(user_id):
    try:
        user_id = int(user_id)  # Ensure user_id is an integer
        # Lookup user preferences from the DataFrame
        user_row = users[users["user_id"] == user_id]
        if not user_row.empty:
            preferences = (
                f"Occupation: {user_row['occupation'].values[0]}, "
                f"Age: {user_row['age'].values[0]}, "
                f"Gender: {user_row['gender'].values[0]}"
            )
            # Update the field to visible and return the preferences
            return gr.update(visible=True, value=preferences)
        else:
            # User not found
            return gr.update(visible=False, value="User not found!")
    except ValueError:
        # Handle invalid input
        return gr.update(visible=False, value="Invalid User ID!")

In [454]:
# Create the Gradio app
with gr.Blocks() as demo:
    gr.Markdown("## Recommendation Systems Comparison")  # Heading

    # Row to hold two identical blocks
    with gr.Row():
        with gr.Column():
            gr.Markdown("## Collaborative Filtering")  # Heading
            user_id_input = gr.Textbox(label="User ID", placeholder="Enter your ID here")
            user_preferences_output = gr.Textbox(label="User Preferences", visible=False)
            cf_recommendations_output = gr.Textbox(label="Recommendations")
            cf_generate_button = gr.Button("Generate CF Recommendations")

            cf_generate_button.click(CFGenerator, inputs=[user_id_input], outputs=[cf_recommendations_output])
            user_id_input.change(show_user_preferences, inputs=[user_id_input], outputs=[user_preferences_output])

        with gr.Column():
            gr.Markdown("## SBERT Two-Tower Model")  # Heading

            # Radio Button to Choose Input Method
            input_method_sbert = gr.Radio(
                choices=["User ID", "Manual Data Entry"],
                label="Choose Input Method",
                value="User ID"
            )

            # Fields for User ID Input
            user_id_input_sbert = gr.Textbox(label="User ID (SBERT)", visible=True, placeholder="Enter User ID")

            # Fields for Manual Data Entry
            occupation_input = gr.Textbox(label="Occupation", visible=False, placeholder="Enter Occupation")
            gender_input = gr.Textbox(label="Gender", visible=False, placeholder="Enter Gender")
            favorite_genres_input = gr.Textbox(label="Favorite Genres", visible=False, placeholder="Enter Favorite Genres (comma-separated)")

            # Output field
            tt_recommendations_output = gr.Textbox(label="Recommendations", interactive=False)
            tt_generate_button = gr.Button("Generate LLM Recommendations")

            # Dynamically show the relevant input fields based on the selected method
            input_method_sbert.change(
                lambda method: (
                    gr.update(visible=method == "User ID"),  # User ID field
                    gr.update(visible=method == "Manual Data Entry"),  # Occupation field
                    gr.update(visible=method == "Manual Data Entry"),  # Gender field
                    gr.update(visible=method == "Manual Data Entry")   # Favorite Genres field
                ),
                inputs=[input_method_sbert],
                outputs=[user_id_input_sbert, occupation_input, gender_input, favorite_genres_input]
            )

            # Handle button click for recommendations
            def generate_recommendations(user_id, occupation, gender, favorite_genres, input_method):
                try:
                    # Determine input_data based on the selected method
                    if input_method == "User ID":
                        input_data = user_id
                    else:
                        # Combine manual data into a single structure for processing
                        input_data = (
                            f"[USER_PROFILE] occupation: {occupation.strip()} [SEP] "
                            f"gender: {gender.strip()} [SEP] "
                            f"genres: {favorite_genres.strip()}"
                        )

                    # Call TTGenerator with the appropriate input
                    return TTGenerator(input_data=input_data, input_method=input_method)
                except Exception as e:
                    return f"An error occurred: {str(e)}"

            # Connect button to the generate_recommendations function
            tt_generate_button.click(
                generate_recommendations,
                inputs=[user_id_input_sbert, occupation_input, gender_input, favorite_genres_input, input_method_sbert],
                outputs=[tt_recommendations_output]
            )
        # Row for Hybrid Model
    with gr.Row():
        with gr.Column():
            gr.Markdown("## Hybrid Model")  # Heading

            # Radio Button to Choose Input Method
            input_method_hybrid = gr.Radio(
                choices=["User ID", "Manual Data Entry"],
                label="Choose Input Method",
                value="User ID"
            )

            # Fields for User ID Input
            user_id_input_hybrid = gr.Textbox(label="User ID (Hybrid)", visible=True, placeholder="Enter User ID")

           # Fields for Manual Data Entry
            occupation_input_hybrid = gr.Textbox(label="Occupation", visible=False, placeholder="Enter Occupation")
            gender_input_hybrid = gr.Textbox(label="Gender", visible=False, placeholder="Enter Gender")
            favorite_genres_input_hybrid = gr.Textbox(label="Favorite Genres", visible=False, placeholder="Enter Favorite Genres (comma-separated)")

            # Output field
            hybrid_recommendations_output = gr.Textbox(label="Recommendations", interactive=False)
            hybrid_generate_button = gr.Button("Generate Hybrid Recommendations")

            # Dynamically show the relevant input fields based on the selected method
            input_method_hybrid.change(
                lambda method: (
                    gr.update(visible=method == "User ID"),  # User ID field
                    gr.update(visible=method == "Manual Data Entry"),  # Occupation field
                    gr.update(visible=method == "Manual Data Entry"),  # Gender field
                    gr.update(visible=method == "Manual Data Entry")   # Favorite Genres field
                ),
                inputs=[input_method_hybrid],
                outputs=[user_id_input_hybrid, occupation_input_hybrid, gender_input_hybrid, favorite_genres_input_hybrid]
            )

            # Handle button click for hybrid recommendations
            def generate_hybrid_recommendations(user_id, occupation, gender, favorite_genres, input_method):
                try:
                    # Determine input_data based on the selected method
                    if input_method == "User ID":
                        input_data = user_id
                        return combine_recommendations_with_rrf_with_weight_for_gradio(
                            user_id=input_data, input_method="User ID"
                        )
                    else:
                        # Combine manual data into a single structure
                        input_data = (
                            f"[USER_PROFILE] occupation: {occupation.strip()} [SEP] "
                            f"gender: {gender.strip()} [SEP] "
                            f"genres: {favorite_genres.strip()}"
                        )
                        return combine_recommendations_with_rrf_with_weight_for_gradio(
                            user_id=input_data, input_method="Manual Data Entry"
                        )
                except Exception as e:
                    return f"An error occurred: {str(e)}"

            # Connect button to the generate_hybrid_recommendations function
            hybrid_generate_button.click(
                generate_hybrid_recommendations,
                inputs=[user_id_input_hybrid, occupation_input_hybrid, gender_input_hybrid, favorite_genres_input_hybrid, input_method_hybrid],
                outputs=[hybrid_recommendations_output]
            )
# Launch the app
demo.launch(share=True)

Running on local URL:  http://127.0.0.1:7941

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.