In [1]:
from sentence_transformers import SentenceTransformer, util

# Load the pre-trained SBERT model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

D:\Anaconda\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
D:\Anaconda\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [1]:
from sentence_transformers import SentenceTransformer, util

D:\Anaconda\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange

ImportError: cannot import name 'AutoConfig' from 'transformers' (unknown location)

In [49]:
# Define your sentences
sentence1 = "occupation: doctor/health care [SEP] age: 25-34 [SEP] gender: Male"
sentence2_list = [
    "title: Godfather, The [SEP] genres: Action, Crime, Drama [SEP] year: 1934",
    "title: Godfather, The [SEP] genres: Action|Crime|Drama [SEP] year: 1934",
    "title: Godfather, The [SEP] genres: Action, Crime, Drama",
    "genres: Action, Crime, Drama",
]

# Compute the embedding for the first sentence
embedding1 = model.encode(sentence1, convert_to_tensor=True)

# Compute the embeddings for the list of sentences
embeddings2 = model.encode(sentence2_list, convert_to_tensor=True)

# Compute the cosine similarity between the first sentence and each sentence in the list
similarities = util.pytorch_cos_sim(embedding1, embeddings2)

# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i+1}: {similarity.item()}")

Similarity with sentence 1: 0.05875241011381149
Similarity with sentence 2: 0.05363810807466507
Similarity with sentence 3: 0.049956221133470535
Similarity with sentence 4: 0.08661812543869019

In [55]:

# Define your sentences
sentence1 = "occupation: doctor/health care [SEP] gender: Male"
sentence2_list = [
    "title: Godfather, The [SEP] genres: Action, Crime, Drama [SEP] year: 1934",
    "title: Godfather, The [SEP] genres: Action|Crime|Drama [SEP] year: 1934",
    "title: Godfather, The [SEP] genres: Action, Crime, Drama",
    "genres: Action, Crime, Drama",
]

# Compute the embedding for the first sentence
embedding1 = model.encode(sentence1, convert_to_tensor=True)

# Compute the embeddings for the list of sentences
embeddings2 = model.encode(sentence2_list, convert_to_tensor=True)

# Compute the cosine similarity between the first sentence and each sentence in the list
similarities = util.pytorch_cos_sim(embedding1, embeddings2)

# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i + 1}: {similarity.item()}")

Similarity with sentence 1: 0.07378441840410233
Similarity with sentence 2: 0.07856899499893188
Similarity with sentence 3: 0.09538991004228592
Similarity with sentence 4: 0.14021624624729156

In [56]:
# Define your sentences
sentence1 = "[USER_PROFILE] occupation: doctor/health care [SEP] gender: Male"
sentence2_list = [
    "[MOVIE_DETAIL] title: Godfather, The [SEP] genres: Action, Crime, Drama [SEP] year: 1934",
    "[MOVIE_DETAIL] title: Godfather, The [SEP] genres: Action|Crime|Drama [SEP] year: 1934",
    "[MOVIE_DETAIL] title: Godfather, The [SEP] genres: Action, Crime, Drama",
    "[MOVIE_DETAIL] genres: Action, Crime, Drama",
]

# Compute the embedding for the first sentence
embedding1 = model.encode(sentence1, convert_to_tensor=True)

# Compute the embeddings for the list of sentences
embeddings2 = model.encode(sentence2_list, convert_to_tensor=True)

# Compute the cosine similarity between the first sentence and each sentence in the list
similarities = util.pytorch_cos_sim(embedding1, embeddings2)

# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i + 1}: {similarity.item()}")

Similarity with sentence 1: 0.03498101234436035
Similarity with sentence 2: 0.04984527826309204
Similarity with sentence 3: 0.08021058142185211
Similarity with sentence 4: 0.12176443636417389

In [68]:
# Define your sentences
# Action|Crime|Drama
sentence1 = "occupation: doctor/health care [SEP] gender: Male [SEP] history: Godfather, The"
sentence2_list = [
    "title: Silence of the Lambs, The [SEP] genres: Drama, Thriller [SEP] year: 1934",
    "title: Silence of the Lambs, The [SEP] genres: Drama|Thriller [SEP] year: 1934",
    "title: Silence of the Lambs, The [SEP] genres: Drama, Thriller",
]

# Compute the embedding for the first sentence
embedding1 = model.encode(sentence1, convert_to_tensor=True)

# Compute the embeddings for the list of sentences
embeddings2 = model.encode(sentence2_list, convert_to_tensor=True)

# Compute the cosine similarity between the first sentence and each sentence in the list
similarities = util.pytorch_cos_sim(embedding1, embeddings2)

# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i + 1}: {similarity.item()}")

Similarity with sentence 1: 0.2262524962425232
Similarity with sentence 2: 0.22121018171310425
Similarity with sentence 3: 0.21723076701164246

In [22]:
# Define your sentences
sentence1 = "occupation: doctor/health care [SEP] gender: Male [SEP] history: Godfather, Bound"
# sentence1 = "[USER_PROFILE] occupation: doctor/health care [SEP] gender: Male [SEP] history: Godfather, The, Bound (1996)"
# Bound (1996) Crime|Drama|Romance|Thriller
sentence2_list = [
    # "[MOVIE_DETAIL] title: Godfather, The [SEP] genres: Action, Crime, Drama [SEP] year: 1934",
    # "[MOVIE_DETAIL] title: Godfather, The [SEP] genres: Action, Crime, Drama",
    "title: Silence of the Lambs, The [SEP] genres: Drama, Thriller [SEP] year: 1934",
    "title: Silence of the Lambs, The [SEP] genres: Drama|Thriller [SEP] year: 1934",
    "title: Silence of the Lambs, The [SEP] genres: Drama, Thriller",
    "Pillow Book, The [SEP] genres: Drama, Romance [SEP] year: 1934",
    "Pillow Book, The [SEP] genres: Drama|Romance[SEP] year: 1934",
    "title: Pillow Book, The [SEP] genres: Drama, Romance",
]
# Pillow Book, The (1995) Drama|Romance
# Compute the embedding for the first sentence
embedding1 = model.encode(sentence1, convert_to_tensor=True)

# Compute the embeddings for the list of sentences
embeddings2 = model.encode(sentence2_list, convert_to_tensor=True)

# Compute the cosine similarity between the first sentence and each sentence in the list
similarities = util.pytorch_cos_sim(embedding1, embeddings2)

# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i + 1}: {similarity.item()}")

Similarity with sentence 1: 0.2127831131219864
Similarity with sentence 2: 0.21011391282081604
Similarity with sentence 3: 0.20810657739639282
Similarity with sentence 4: 0.31771332025527954
Similarity with sentence 5: 0.31849685311317444
Similarity with sentence 6: 0.2967834770679474

In [79]:
# Define your sentences
sentence1 = "occupation: doctor/health care [SEP] gender: Male [SEP] history: " \
            "title: Godfather, genres:Action|Crime|Drama " \
            "title: Bound, genres:Crime|Drama|Romance|Thriller"
# sentence1 = "[USER_PROFILE] occupation: doctor/health care [SEP] gender: Male [SEP] history: Godfather, The, Bound (1996)"
# Bound (1996) Crime|Drama|Romance|Thriller
sentence2_list = [
    # "title: Silence of the Lambs, The [SEP] genres: Drama, Thriller [SEP] year: 1934",
    # "title: Silence of the Lambs, The [SEP] genres: Drama|Thriller [SEP] year: 1934",
    # "title: Silence of the Lambs, The [SEP] genres: Drama, Thriller",
    # "title: Pillow Book, The [SEP] genres: Drama, Romance [SEP] year: 1934",
    # "Pillow Book, The [SEP] genres: Drama|Romance[SEP] year: 1934",
    # "title: Pillow Book, The [SEP] genres: Drama, Romance",
    "Silence of the Lambs [SEP] genres: Drama|Thriller",
    "Pillow Book [SEP] genres: Drama, Romance",
    "Carpool [SEP] genres: Comedy, Crime"
]
# Pillow Book, The (1995) Drama|Romance
# Compute the embedding for the first sentence
embedding1 = model.encode(sentence1, convert_to_tensor=True)

# Compute the embeddings for the list of sentences
embeddings2 = model.encode(sentence2_list, convert_to_tensor=True)

# Compute the cosine similarity between the first sentence and each sentence in the list
similarities = util.pytorch_cos_sim(embedding1, embeddings2)
# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i + 1}: {similarity.item()}")

Similarity with sentence 1: 0.5501798391342163
Similarity with sentence 2: 0.5624335408210754
Similarity with sentence 3: 0.5433527231216431

In [129]:
import torch
# Define your sentences

sentence1 = {
    "occupation_gender": "[USER_PROFILE] occupation: doctor/health care [SEP] gender: Male",
    "history": "title: Godfather, genres:Action|Crime|Drama [SEP] title: Seven Samurai, genres:Action|Drama [SEP] title: Silence of the Lambs, genres:Drama|Thriller"
}

sentence2_list = [
    {"title": "Silence of the Lambs", "genres": "Drama, Thriller"},
    {"title": "Rain Man", "genres": "Drama"},
    {"title": "Godfather 2", "genres": "Action|Drama"},
    {"title": "Pillow Book", "genres": "Drama|Romance"},
    {"title": "Carpool", "genres": "Comedy|Crime"},
    {"title": "Crying Game", "genres": "Drama|Romance|War"}
]

# Define weights for each part
weights1 = {"occupation_gender": 0.1, "history": 0.9}
weights2 = {"title": 0.2, "genres": 0.8}

# Compute embeddings for each part of sentence1
embedding1_parts = {key: model.encode(value, convert_to_tensor=True) for key, value in sentence1.items()}
weighted_embedding1 = torch.stack([weights1[key] * embedding for key, embedding in embedding1_parts.items()]).sum(dim=0)

# Compute weighted embeddings for each sentence in sentence2_list
weighted_embeddings2 = []
for sentence2_parts in sentence2_list:
    embedding2_parts = {key: model.encode(value, convert_to_tensor=True) for key, value in sentence2_parts.items()}
    weighted_embedding2 = torch.stack([weights2[key] * embedding for key, embedding in embedding2_parts.items()]).sum(dim=0)
    weighted_embeddings2.append(weighted_embedding2)

weighted_embeddings2 = torch.stack(weighted_embeddings2)

# Compute the cosine similarity between the weighted embedding of sentence1 and each weighted embedding in sentence2_list
similarities = util.pytorch_cos_sim(weighted_embedding1, weighted_embeddings2)

# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i + 1}: {similarity.item()}")

Similarity with sentence 1: 0.5862199664115906
Similarity with sentence 2: 0.46231943368911743
Similarity with sentence 3: 0.5660261511802673
Similarity with sentence 4: 0.4793689250946045
Similarity with sentence 5: 0.4359447956085205
Similarity with sentence 6: 0.5242535471916199

In [134]:
import torch

# Define your sentences
sentence1 = {
    "occupation_gender": "occupation: doctor/health care [SEP] gender: Male",
    "history": [
        {"title": "Godfather", "genres": "Action|Crime|Drama"},
        {"title": "Seven Samurai", "genres": "Action|Drama"},
        {"title": "Silence of the Lambs", "genres": "Drama|Thriller"}
    ]
}

sentence2_list = [
    {"title": "Silence of the Lambs", "genres": "Drama, Thriller"},
    {"title": "Rain Man", "genres": "Drama"},
    {"title": "Godfather 2", "genres": "Action|Drama"},
    {"title": "Pillow Book", "genres": "Drama|Romance"},
    {"title": "Carpool", "genres": "Comedy|Crime"},
    {"title": "Crying Game", "genres": "Drama|Romance|War"}
]

# Define weights for each part
weights1 = {"occupation_gender": 0.1, "history": 0.9}
history_weights = [0.2, 0.3, 0.5]  # Weights for each movie in history
weights2 = {"title": 0.2, "genres": 0.8}

# Compute embeddings for the occupation_gender part of sentence1
embedding1_occupation_gender = model.encode(sentence1["occupation_gender"], convert_to_tensor=True)

# Compute embeddings for each movie in the history part of sentence1
history_embeddings = []
for i, movie in enumerate(sentence1["history"]):
    title_embedding = model.encode(movie["title"], convert_to_tensor=True)
    genres_embedding = model.encode(movie["genres"], convert_to_tensor=True)
    movie_embedding = weights2["title"] * title_embedding + weights2["genres"] * genres_embedding
    weighted_movie_embedding = history_weights[i] * movie_embedding
    history_embeddings.append(weighted_movie_embedding)

# Combine the weighted history embeddings
weighted_history_embedding = torch.stack(history_embeddings).sum(dim=0)

# Combine occupation_gender and history embeddings with their respective weights
weighted_embedding1 = weights1["occupation_gender"] * embedding1_occupation_gender + weights1["history"] * weighted_history_embedding

# Compute weighted embeddings for each sentence in sentence2_list
weighted_embeddings2 = []
for sentence2_parts in sentence2_list:
    title_embedding = model.encode(sentence2_parts["title"], convert_to_tensor=True)
    genres_embedding = model.encode(sentence2_parts["genres"], convert_to_tensor=True)
    weighted_embedding2 = weights2["title"] * title_embedding + weights2["genres"] * genres_embedding
    weighted_embeddings2.append(weighted_embedding2)

weighted_embeddings2 = torch.stack(weighted_embeddings2)
# Compute the cosine similarity between the weighted embedding of sentence1 and each weighted embedding in sentence2_list
similarities = util.pytorch_cos_sim(weighted_embedding1, weighted_embeddings2)

# Print the similarity scores
for i, similarity in enumerate(similarities[0]):
    print(f"Similarity with sentence {i + 1}: {similarity.item()}")

Similarity with sentence 1: 0.8896061182022095
Similarity with sentence 2: 0.8496407270431519
Similarity with sentence 3: 0.9223478436470032
Similarity with sentence 4: 0.7832946181297302
Similarity with sentence 5: 0.6743572950363159
Similarity with sentence 6: 0.760257363319397

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [6]:
import torch
from sentence_transformers import SentenceTransformer, util

# Set device to GPU if available, otherwise CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class RecommenderSystem:
    def __init__(self):
        self.user_model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
        self.item_model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

    def compute_weighted_user_embedding(self, user_text):
        occupation_gender_weight = 0.1
        history_weight = 0.9

        # Ensure history_weights is on the correct device
        history_weights = torch.tensor([0.2, 0.3, 0.5], device=device)

        # Compute embeddings for the occupation_gender part of user_text
        occupation_gender_embedding = self.user_model.encode(user_text["occupation_gender"], convert_to_tensor=True).to(device)

        # Prepare input for batch processing
        history_texts = [f"title: {movie['title']} [SEP] genres: {movie['genres']}" for movie in user_text["history"]]

        if history_texts:
            # Batch process embeddings for history
            history_embeddings = self.user_model.encode(history_texts, convert_to_tensor=True).to(device)

            # Apply weights to embeddings
            history_weights_batch = history_weights[:len(history_embeddings)]
            weighted_history_embedding = torch.matmul(history_weights_batch, history_embeddings)
        else:
            weighted_history_embedding = torch.zeros_like(occupation_gender_embedding)

        # Combine occupation_gender and history embeddings with their respective weights
        weighted_embedding = (occupation_gender_weight * occupation_gender_embedding +
                              history_weight * weighted_history_embedding)
        print(history_texts)
        return weighted_embedding

    def compute_weighted_item_embedding(self, item_text):
        title_weight = 0.2
        genres_weight = 0.8

        # Compute embeddings for title and genres
        title_embedding = self.item_model.encode(f"title: {item_text['title']}", convert_to_tensor=True).to(device)
        genres_embedding = self.item_model.encode(f"genres: {item_text['genres']}", convert_to_tensor=True).to(device)

        # Combine embeddings with their respective weights
        weighted_embedding = (title_weight * title_embedding +
                              genres_weight * genres_embedding)

        return weighted_embedding


# Example Input Data
user_text = {
    "occupation_gender": "software engineer male",
    "history": [
        {"title": "Inception", "genres": "Action, Sci-Fi"},
        {"title": "The Matrix", "genres": "Action, Sci-Fi"},
        {"title": "Interstellar", "genres": "Adventure, Drama"}
    ]
}

item_text = {
    "title": "Inception",
    "genres": "Action, Sci-Fi"
}

# Initialize RecommenderSystem
recommender = RecommenderSystem()

# Compute embeddings
user_embedding = recommender.compute_weighted_user_embedding(user_text)
item_embedding = recommender.compute_weighted_item_embedding(item_text)

# Output embeddings
# print("User Embedding:", user_embedding)
# print("Item Embedding:", item_embedding)

['title: Inception [SEP] genres: Action, Sci-Fi', 'title: The Matrix [SEP] genres: Action, Sci-Fi', 'title: Interstellar [SEP] genres: Adventure, Drama']

In [19]:
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

In [1]:
import pandas as pd

In [57]:
ratings = pd.read_csv('processed_dataset/Amazon-Beauty/amazon_beauty_ratings.csv')
products = pd.read_csv('processed_dataset/Amazon-Beauty/amazon_beauty_reviews_meta.csv')

In [58]:
# Remove users with less than 5 interactions
user_interactions = ratings['user_id'].value_counts()
users_to_keep = user_interactions[user_interactions >= 2].index
filtered_ratings = ratings[ratings['user_id'].isin(users_to_keep)]

In [59]:
filtered_ratings

,rating,title,text,images,asin,parent_asin,user_id,timestamp,verified_purchase,helpful_vote
0,5,Such a lovely scent but not overpowering.,This spray is really nice. It smells really go...,[],B00YQ6X8EO,B00YQ6X8EO,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1.588690e+12,True,0
1,4,Works great but smells a little weird.,"This product does what I need it to do, I just...",[],B081TJ8YS3,B081TJ8YS3,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1.588620e+12,True,1
3,1,Synthetic feeling,Felt synthetic,[],B09JS339BZ,B09JS339BZ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1.643390e+12,True,0
4,5,A+,Love it,[],B08BZ63GMJ,B08BZ63GMJ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1.609320e+12,True,0
8,5,Great for at home use and so easy to use!,This is perfect for my between salon visits. I...,[],B08P2DZB4X,B08P2DZB4X,AFSKPY37N3C43SOI5IEXEK5JSIYA,1.627390e+12,False,0
...,...,...,...,...,...,...,...,...,...,...
701456,2,Cute but not water resistant,"I think the design of the caps is so cute, but...",[],B08CDWBNWC,B08CDWBNWC,AGAM6PJOXCDJLLOPYJVFNILD7DTQ,1.618860e+12,True,0
701474,5,Easy replacement after i dumped a water bottle...,"I used nylon interior trim removal tools, from...",[],B07HC84V8D,B07HC84V8D,AHOBG6Y2ONNVVJJR54QLT3OIVMLA,1.566870e+12,True,0
701477,5,Easy replacement after i dumped a water bottle...,"I used nylon interior trim removal tools, from...",[],B07HC84V8D,B07HC84V8D,AHOBG6Y2ONNVVJJR54QLT3OIVMLA,1.566870e+12,True,0
701518,1,One Star,"Cant do anything with it. No Heat, cant get it...",[],B01HO3M2II,B01HO3M2II,AF35ZHUHDHWFRMSP2BBRCTGBUMYA,1.524260e+12,True,0
701519,1,One Star,"Cant do anything with it. No Heat, cant get it...",[],B01HO3M2II,B01HO3M2II,AF35ZHUHDHWFRMSP2BBRCTGBUMYA,1.524260e+12,True,0

In [60]:
ratings = filtered_ratings.sort_values(by='timestamp')

In [61]:
ratings = ratings.drop(columns=['images', 'verified_purchase', 'helpful_vote', 'text'])
ratings = ratings.sort_values(by='timestamp')

In [62]:
ratings

,rating,title,asin,parent_asin,user_id,timestamp
597043,4,Timer toothbrush is good- but does not last fo...,B000050FDB,B000050FDB,AFZJZJXW4JCY4MWCV6FX5RRPRMYA,9.882960e+11
597044,4,Timer toothbrush is good- but does not last fo...,B000050FDB,B000050FDB,AFZJZJXW4JCY4MWCV6FX5RRPRMYA,9.882960e+11
385803,3,Spectra not Spectacular; Only its Price,B000068PBJ,B000068PBJ,AELUS5EVZT4256ZTANHE7TN5MH6Q,1.040960e+12
293364,3,I agree...,B000068PBP,B000068PBP,AHGFST33AIE4TMZEMQ7ZZWR26EZQ,1.042270e+12
334056,4,"It does a great job, but ...",B000068PBR,B000068PBR,AFQHRQCEKX3W533NRYKHZF2WRYQQ,1.053150e+12
...,...,...,...,...,...,...
692493,5,Natural,B0BCTVP9ND,B0BTLTVR1X,AE7JOTC5NKTZ5WONQ4SIP2YJFFAA,1.693440e+12
692492,5,Natural,B0BCTVP9ND,B0BTLTVR1X,AE7JOTC5NKTZ5WONQ4SIP2YJFFAA,1.693440e+12
698001,5,Recommended!,B0C1Z62W23,B0BTLTVR1X,AGI5NDMAHRCA2CXXZMFGA2AKSIZA,1.693610e+12
698000,5,Recommended!,B0C1Z62W23,B0BTLTVR1X,AGI5NDMAHRCA2CXXZMFGA2AKSIZA,1.693610e+12
701439,1,Hurt,B0CBBZ9MJ4,B0CBBZ9MJ4,AHURE3VT2MLCTARMYI7JA7KKDYAA,1.694220e+12

In [63]:
# Split the data into 8:1:1 for training, validation, and test sets
train_size = int(0.8 * len(ratings))
valid_size = int(0.1 * len(ratings))
test_size = len(ratings) - train_size - valid_size

In [64]:
train_set = ratings[:train_size]
valid_set = ratings[train_size:train_size + valid_size]
test_set = ratings[train_size + valid_size:]

In [65]:
test_set

,rating,title,asin,parent_asin,user_id,timestamp
79430,5,Nice variety of color,B08YZ3854D,B08YZ3854D,AEWUWC3QEJ5ZXJ2R6ERWG6OQWQBQ,1.642620e+12
210297,5,He loves it!,B097CMPW2L,B0C619KBLQ,AGPMUNWUHM6UED3E2BLSIBMIQJ2A,1.642620e+12
484168,5,Awesome!,B08HGHZLG4,B08HGHZLG4,AG5V5E75PRPAMFDKAXX5GNWWPSXA,1.642620e+12
196774,4,Worth every penny,B085NPFN6Q,B085NPFN6Q,AEG6XY5WSQSFUE6ZWNGNRN5ZW6WA,1.642620e+12
246344,5,Very Good Eyeshadow Just What I Wanted,B07Z9MQKS3,B07Z9MQKS3,AGXH5VMZ44KGOXZ7WVS4H63FHHQA,1.642620e+12
...,...,...,...,...,...,...
692493,5,Natural,B0BCTVP9ND,B0BTLTVR1X,AE7JOTC5NKTZ5WONQ4SIP2YJFFAA,1.693440e+12
692492,5,Natural,B0BCTVP9ND,B0BTLTVR1X,AE7JOTC5NKTZ5WONQ4SIP2YJFFAA,1.693440e+12
698001,5,Recommended!,B0C1Z62W23,B0BTLTVR1X,AGI5NDMAHRCA2CXXZMFGA2AKSIZA,1.693610e+12
698000,5,Recommended!,B0C1Z62W23,B0BTLTVR1X,AGI5NDMAHRCA2CXXZMFGA2AKSIZA,1.693610e+12
701439,1,Hurt,B0CBBZ9MJ4,B0CBBZ9MJ4,AHURE3VT2MLCTARMYI7JA7KKDYAA,1.694220e+12

In [66]:
# Sort each set again based on timestamp
train_set = train_set.sort_values(by='timestamp')
valid_set = valid_set.sort_values(by='timestamp')
test_set = test_set.sort_values(by='timestamp')

In [67]:
train_set.shape, valid_set.shape, test_set.shape

((94380, 6), (11797, 6), (11798, 6))

In [68]:
# Save the datasets to CSV files
train_set.to_csv('./amazon_beauty_ratings_train.csv', index=False)
valid_set.to_csv('./amazon_beauty_ratings_valid.csv', index=False)
test_set.to_csv('./amazon_beauty_ratings_test.csv', index=False)

In [9]:
products = products.drop(columns=['images', 'videos', 'categories', 'parent_asin', 'bought_together', 'rating_number', 'price', 'features', 'average_rating'])

In [10]:
products

,main_category,title,description,store,details
0,All Beauty,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",[],Howard Products,{'Package Dimensions': '7.1 x 5.5 x 3 inches; ...
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,[],Yes To,"{'Item Form': 'Powder', 'Skin Type': 'Acne Pro..."
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),[],Levine Health Products,{'Manufacturer': 'Levine Health Products'}
3,All Beauty,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",[],Cherioll,"{'Brand': 'Cherioll', 'Item Form': 'Powder', '..."
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,['The Precision Plunger Bars are designed to w...,Precision,{'UPC': '644287689178'}
...,...,...,...,...,...
112585,All Beauty,"TOPREETY 24""120gr 3/4 Full Head clip in hair e...",[],TOPREETY,"{'Is Discontinued By Manufacturer': 'No', 'Pac..."
112586,All Beauty,"Pets Playmate Pet Grooming Glove,Gentle Deshed...",[],Pets Playmate,"{'Is Discontinued By Manufacturer': 'No', 'Pac..."
112587,All Beauty,[10Pack] Makeup Brushes Set Cosmetics Tools Ki...,[],RainMakers,"{'Brand': 'RainMakers', 'Recommended Uses For ..."
112588,All Beauty,Xcoser Pretty Party Anna Wig Hair Tails Hair S...,[],Xcoser,"{'Is Discontinued By Manufacturer': 'No', 'Pac..."
112589,All Beauty,"DVIO Men's Voyage Perfume, Spicy woody fragran...",[],DVIO,"{'UPC': '736238729337', 'Manufacturer': 'DVIO'}"

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the datasets
ratings = pd.read_csv('processed_dataset/Amazon-Beauty/amazon_beauty_ratings.csv')
products = pd.read_csv('processed_dataset/Amazon-Beauty/amazon_beauty_reviews_meta.csv')

# Remove users with less than 5 interactions
user_interactions = ratings['user_id'].value_counts()
users_to_keep = user_interactions[user_interactions >= 10].index
filtered_ratings = ratings[ratings['user_id'].isin(users_to_keep)]

# Group data by user_id
grouped = filtered_ratings.groupby('user_id')

# Prepare containers for splits
train_list = []
val_list = []
test_list = []

# Define the sizes for validation and test sets
val_size = 0.1
test_size = 0.1

# Process each user's ratings
for userId, group in grouped:
    # If there are not enough samples, assign all to training set
    if len(group) < 3:
        train_list.append(group.sort_values(by='timestamp'))
        continue

    # Split the data for each userId
    train_data, temp_data = train_test_split(
        group,
        test_size=(val_size + test_size),
        random_state=42,
        shuffle=False  # Preserve timestamp order
    )

    if len(temp_data) < 2:  # If the temp_data is too small to split, add it all to the train set
        train_list.append(train_data.sort_values(by='timestamp'))
        continue

    val_data, test_data = train_test_split(
        temp_data,
        test_size=test_size / (val_size + test_size),
        random_state=42,
        shuffle=False  # Preserve timestamp order
    )

    # Append sorted data
    train_list.append(train_data.sort_values(by='timestamp'))
    val_list.append(val_data.sort_values(by='timestamp'))
    test_list.append(test_data.sort_values(by='timestamp'))

# Concatenate all user-wise splits into final datasets
train_set = pd.concat(train_list)
val_set = pd.concat(val_list)
test_set = pd.concat(test_list)

# Save the datasets to CSV files
train_set.to_csv('amazon_beauty_ratings_train.csv', index=False)
val_set.to_csv('amazon_beauty_ratings_val.csv', index=False)
test_set.to_csv('amazon_beauty_ratings_test.csv', index=False)

In [11]:
filtered_ratings

,rating,title,text,images,asin,parent_asin,user_id,timestamp,verified_purchase,helpful_vote
8,5,Great for at home use and so easy to use!,This is perfect for my between salon visits. I...,[],B08P2DZB4X,B08P2DZB4X,AFSKPY37N3C43SOI5IEXEK5JSIYA,1.627390e+12,False,0
9,5,Nice shampoo for the money,I get Keratin treatments at the salon at least...,[],B086QY6T7N,B086QY6T7N,AFSKPY37N3C43SOI5IEXEK5JSIYA,1.626610e+12,False,0
10,3,Not what I thought I would be getting,I was very disappointed when I got this facial...,[],B08DHTJ25J,B08DHTJ25J,AFSKPY37N3C43SOI5IEXEK5JSIYA,1.626210e+12,False,0
11,5,A little goes a long way!,This is a really nice moisturizing lotion. It ...,[],B07RBSLNFR,B07RBSLNFR,AFSKPY37N3C43SOI5IEXEK5JSIYA,1.621180e+12,False,0
12,3,Just ok,I try to get Keratin treatments every 3 months...,[],B07SLFWZKN,B07SLFWZKN,AFSKPY37N3C43SOI5IEXEK5JSIYA,1.619740e+12,False,0
...,...,...,...,...,...,...,...,...,...,...
695780,1,"Product works-ish, very lazy packing.",Kinda mad that i picked this poly gel set bc i...,[],B07PX9J8YJ,B07PX9J8YJ,AEUGNUJOAKJNWDHART2SX6VBTJ6A,1.608740e+12,False,1
695781,1,"Product works-ish, very lazy packing.",Kinda mad that i picked this poly gel set bc i...,[],B07PX9J8YJ,B07PX9J8YJ,AEUGNUJOAKJNWDHART2SX6VBTJ6A,1.608740e+12,False,1
695783,1,"Product works-ish, very lazy packing.",Kinda mad that i picked this poly gel set bc i...,[],B07PX9J8YJ,B07PX9J8YJ,AEUGNUJOAKJNWDHART2SX6VBTJ6A,1.608740e+12,False,1
695785,1,"Product works-ish, very lazy packing.",Kinda mad that i picked this poly gel set bc i...,[],B07PX9J8YJ,B07PX9J8YJ,AEUGNUJOAKJNWDHART2SX6VBTJ6A,1.608740e+12,False,1
695786,1,"Product works-ish, very lazy packing.",Kinda mad that i picked this poly gel set bc i...,[],B07PX9J8YJ,B07PX9J8YJ,AEUGNUJOAKJNWDHART2SX6VBTJ6A,1.608740e+12,False,1

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the datasets
ratings = pd.read_csv('./processed_dataset/Amazon-Beauty/original/amazon_beauty_ratings.csv')
products = pd.read_csv('./processed_dataset/Amazon-Beauty/amazon_beauty_reviews_meta_modified.csv')

# Remove users with less than 10 interactions
user_interactions = ratings['user_id'].value_counts()
users_to_keep = user_interactions[user_interactions >= 10].index
filtered_ratings = ratings[ratings['user_id'].isin(users_to_keep)]

# Binarize the rating column (example: threshold of 4.0)
threshold = 3.0
filtered_ratings['rating'] = (filtered_ratings['rating'] >= threshold).astype(int)


# Group data by user_id
grouped = filtered_ratings.groupby('user_id')

# Prepare containers for splits
train_list = []
val_list = []
test_list = []

# Define the sizes for validation and test sets
val_size = 0.1
test_size = 0.1

# Process each user's ratings
for userId, group in grouped:
    # If there are not enough samples, assign all to training set
    if len(group) < 3:
        train_list.append(group.sort_values(by='timestamp'))
        continue

    # Split the data for each userId
    train_data, temp_data = train_test_split(
        group,
        test_size=(val_size + test_size),
        random_state=42,
        shuffle=False  # Preserve timestamp order
    )

    if len(temp_data) < 2:  # If the temp_data is too small to split, add it all to the train set
        train_list.append(train_data.sort_values(by='timestamp'))
        continue

    val_data, test_data = train_test_split(
        temp_data,
        test_size=test_size / (val_size + test_size),
        random_state=42,
        shuffle=False  # Preserve timestamp order
    )

    # Append sorted data
    train_list.append(train_data.sort_values(by='timestamp'))
    val_list.append(val_data.sort_values(by='timestamp'))
    test_list.append(test_data.sort_values(by='timestamp'))

# Concatenate all user-wise splits into final datasets
train_set = pd.concat(train_list)
val_set = pd.concat(val_list)
test_set = pd.concat(test_list)

# Save the datasets to CSV files
train_set.to_csv('amazon_beauty_ratings_train.csv', index=False)
val_set.to_csv('amazon_beauty_ratings_val.csv', index=False)
test_set.to_csv('amazon_beauty_ratings_test.csv', index=False)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_11476\50682982.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_ratings['rating'] = (filtered_ratings['rating'] >= threshold).astype(int)

In [14]:
train_set

,rating,title,text,images,asin,parent_asin,user_id,timestamp,verified_purchase,helpful_vote
368296,1,Love the Turban,I'm such a lazy beauty enthusiast. I soak in t...,[{'small_image_url': 'https://images-na.ssl-im...,B0841WQNNZ,B0841WQNNZ,AE23ZBUF2YVBQPH2NN6F5XSA3QYQ,1.604550e+12,False,0
368295,1,No more chapped lips!,Moisturizing and flavorful at the same time! I...,[{'small_image_url': 'https://images-na.ssl-im...,B08G5YVHQP,B08G5YVHQP,AE23ZBUF2YVBQPH2NN6F5XSA3QYQ,1.605150e+12,False,0
368294,1,Mess Contained in a Nifty Storage Box,This is one of the best gifts you could get fo...,[],B08GS19PM7,B08GS19PM7,AE23ZBUF2YVBQPH2NN6F5XSA3QYQ,1.607730e+12,False,0
368293,1,Beauty Pageant Curls,I was a bit nervous to use this at first becau...,[{'small_image_url': 'https://images-na.ssl-im...,B08LPC1G23,B08LPC1G23,AE23ZBUF2YVBQPH2NN6F5XSA3QYQ,1.608390e+12,False,0
368292,1,Great Quality for a Cheaper Price,"At the price of $20 (at the time of review), t...",[],B08NTD1NM1,B08NTD1NM1,AE23ZBUF2YVBQPH2NN6F5XSA3QYQ,1.612040e+12,False,0
...,...,...,...,...,...,...,...,...,...,...
89191,1,"Bamboo pin brush, comb, fluff brush. SEE PIX",I have 2 standard poodles and their hair needs...,[{'small_image_url': 'https://images-na.ssl-im...,B071YDJ269,B071YDJ269,AHYUFOFTGNEV4TGMQLASS6EA7QAQ,1.504330e+12,False,14
89189,0,Metal is garbage. Not worth the price.,I don't often leave a one star review but here...,[],B079FHCDGZ,B079FHCDGZ,AHYUFOFTGNEV4TGMQLASS6EA7QAQ,1.524510e+12,False,0
89188,1,"Non-stick surface, accurate temp, LONG cord, i...",Love this multi-head curling iron. My daughte...,[{'small_image_url': 'https://images-na.ssl-im...,B08CXYYBHQ,B08CXYYBHQ,AHYUFOFTGNEV4TGMQLASS6EA7QAQ,1.600660e+12,True,9
89187,1,Beachy waves on straight hair? Yes please! *pix*,"My daughter's hair is poker straight, thick an...",[{'small_image_url': 'https://images-na.ssl-im...,B08W2534W3,B08W2534W3,AHYUFOFTGNEV4TGMQLASS6EA7QAQ,1.622630e+12,True,1
89186,0,"Sheer, MATTE and pale color unless you put on ...",Not sure what this formula is supposed to be. ...,[{'small_image_url': 'https://m.media-amazon.c...,B092YN4DG4,B092YN4DG4,AHYUFOFTGNEV4TGMQLASS6EA7QAQ,1.654790e+12,False,4

In [4]:
items = pd.read_csv('./processed_dataset/Amazon-Beauty/amazon_beauty_reviews_meta_modified.csv')

In [5]:
items = items.drop(columns=['images', 'average_rating', 'rating_number', 'price', 'videos', 'bought_together', 'categories'], errors='ignore')
items[:50]

,main_category,title,features,description,store,details,parent_asin
0,All Beauty,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",[],[],Howard Products,{'Package Dimensions': '7.1 x 5.5 x 3 inches; ...,B01CUPMQZE
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,[],[],Yes To,"{'Item Form': 'Powder', 'Skin Type': 'Acne Pro...",B076WQZGPM
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),[],[],Levine Health Products,{'Manufacturer': 'Levine Health Products'},B000B658RI
3,All Beauty,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",[],[],Cherioll,"{'Brand': 'Cherioll', 'Item Form': 'Powder', '...",B088FKY3VD
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,"['Material: 304 Stainless Steel; Brass tip', '...",['The Precision Plunger Bars are designed to w...,Precision,{'UPC': '644287689178'},B07NGFDN6G
5,All Beauty,Lurrose 100Pcs Full Cover Fake Toenails Artifi...,['The false toenails are durable with perfect ...,"['Description', 'The false toenails are durabl...",Lurrose,"{'Color': 'As Shown', 'Size': 'Large', 'Materi...",B07G9GWFSM
6,All Beauty,Stain Bonnet For Baby Bonnet Silk Sleep Cap Fo...,[],[],Edoneery,"{'Brand': 'Edoneery', 'Material': 'Silk', 'Num...",B08XZ97HFY
7,All Beauty,50 Pieces False Eyelash Packaging Box Empty Ey...,[],[],Maitys,{'Package Dimensions': '14.49 x 11.26 x 2.36 i...,B08DNQTTQK
8,All Beauty,Gold extatic Musk EDT 90ml,['Extatic Balmain Gold Musk By Balmain Edt Spr...,['Edt spray 3 oz design house: balmain'],Balmain,"{'Brand': 'Balmain', 'Item Form': 'Spray', 'It...",B01ERJEGS6
9,All Beauty,4 Pieces Satin Bonnet Adjustable Sleep Cap Dou...,[],[],Geyoga,{'Package Dimensions': '12.49 x 9.97 x 1.46 in...,B08P7LXKP7
10,All Beauty,Avon Big & False Lash Mascara - Brown/Black by...,[],[],AVON,"{'Color': 'black', 'Brand': 'AVON', 'Item Volu...",B01555WAOS
11,All Beauty,"Stainless Steel Beard Comb, Portable Fashionab...",[],[],Brrnoo,"{'Material': 'Metal', 'Brand': 'Brrnoo', 'Hair...",B07GGYR3LJ
12,All Beauty,Brand New Headrang Face line Contour V-line Ma...,[],[],NaN,"{'Is Discontinued By Manufacturer': 'No', 'Pac...",B06XJZ7955
13,All Beauty,"Loose Powder, 1.5oz Bottle Loose Face Powder, ...",[],[],GETMORE7,{},B07FVZVQKV
14,All Beauty,Small MONEY CLIP Leather Wallet ID Bag Cash Ho...,"['Package:OPP', 'Step 1 : Open Clip and Put Mo...",['Description Small MONEY CLIP Leather Wallet ...,Buytra,"{'Department': 'Mens', 'UPC': '520661393605 70...",B00FCQHYEW
15,All Beauty,Nomade By Chloe,[],['new'],Chloe,"{'Brand': 'Chloe', 'Item Volume': '100 Millili...",B07ZJW55Z5
16,All Beauty,"BioMiracle StarDust Pixie Bubble Mask, Clarify...",['GENTLE ON THE SKIN - This bubble face mask c...,"[""This foaming pixie sheet mask is infused wit...",BioMiracle,"{'Brand': 'BioMiracle', 'Item Form': 'Sheet', ...",B08X7JHQG5
17,All Beauty,PPY Eyelash Growth Serum – Natural Ingredients...,[],[],PPY,"{'Use for': 'Face', 'Scent': 'Aloe', 'Brand': ...",B07WFSQXL5
18,All Beauty,"Dingxiu (5Packs,24"") Two Tone Jumbo Braid Ombr...",[],[],dingxiu,"{'Is Discontinued By Manufacturer': 'No', 'Pac...",B074SHN8YC
19,All Beauty,Nadula Hair 10A Brazilian Body Wave U Part Hum...,[],[],Nadula,"{'Material': 'Human Hair', 'Hair Type': 'Curly...",B07MH4Z7J7
20,All Beauty,"2PC rainbow cloud bath bombs,Float on Water&Re...",[],[],NaN,{'Package Dimensions': '9.65 x 3.39 x 1.5 inch...,B07R13ZSV5
21,All Beauty,Wixar Natural Sea Moss Soap - (2 PACK) - Laven...,[],[],WIXAR NATURALS,"{'Item Form': 'Bar', 'Skin Type': 'Oily,Sensit...",B08BV6F6BC
22,All Beauty,VIROCHEMISTRY Pheromones For Women (Elixir) - ...,['🗽 SCIENTIFICALLY PROVEN! Scientifically Form...,['The Most Amazingly Effective and Fantastic S...,VIROCHEMISTRY,"{'Brand': 'VIROCHEMISTRY', 'Item Form': 'Liqui...",B07X1TK3VS
23,All Beauty,"VeSunny 20"" Clip in Hair Extensions Balayage C...",[],[],Ve Sunny,"{'Brand': 'Ve Sunny', 'Material': 'Human Hair'...",B07MDP86Q4
24,All Beauty,TOODOO 8 Sets Mermaid Face Gems Glitter Sticke...,['Wide usage: you can put these gems on your f...,"[""Feature: Wide usage: You can put these gems...",TOODOO,"{'Brand': 'TOODOO', 'Water Resistance Level': ...",B07CV988JX
25,All Beauty,muaowig Red Human Hair Bundles Body Wave Brazi...,[],"[""Hair Material: Brazilian Virgin Human Hair B...",muaowig,"{'Brand': 'muaowig', 'Material': 'Human Hair',...",B0B77LDV4B
26,All Beauty,10 PCS Professional Hair Cutting Scissors 6.7i...,[],[],Astraet,"{'Color': 'Pink', 'Material': 'Rubber', 'Brand...",B088ZB4DTH
27,All Beauty,"Nail File, 12 Pcs Nail Files and Buffers 7 Ste...",[],[],ELBT,"{'Material': 'Emery', 'Brand': 'ELBT', 'Unit C...",B086Y93JJC
28,All Beauty,7 Packs Deep Wave Crochet Hair 22 Inch Deep wa...,[],[],Yun Mei Hair,"{'Brand': 'Yun Mei Hair', 'Material': 'Synthet...",B07Z818MLY
29,All Beauty,"Garnier Fructis Color Sealer, Instant, Lightwe...",['Seals In Color And Conditions For Extra Soft...,['Proven to stop dry-out. Fight fade-out. The ...,Garnier,"{'Is Discontinued By Manufacturer': 'No', 'Pro...",B004ZWH3XG
30,All Beauty,BEWAVE Hair Brush Sponge Twist With Comb Hair ...,[],[],BEWAVE,"{'Brand': 'BEWAVE', 'Shape': 'Oblong', 'Unit C...",B071DY8Z4B
31,All Beauty,"Zydeco Chop Chop Cajun Seasoning Base, 8 Ounce...","['All Natural blend of Dehydrated Onion, Dehyd...",['Zydeco Chop Chop is a blend of Dehydrated On...,BORELTH,{'Package Dimensions': '9.61 x 7.17 x 3.07 inc...,B0BTLTVR1X
32,All Beauty,"Enjoy VOLUMIZING ELIXIR, Style (with Sleek Ste...",['includes a Sleek Steel Pin Tail Comb for eas...,['includes a Sleek Steel Pin Tail Comb for eas...,Enjoy Hair Care Products,"{'Is Discontinued By Manufacturer': 'No', 'Pac...",B07DRZLZQQ
33,Premium Beauty,Suavecito X Breast Cancer Solutions - Original...,[],[],NaN,{'Product Benefits': 'This water soluble pomad...,B01LZXWCXM
34,All Beauty,DOVE Pro Age Neck & Chest Beauty Serum 3.3oz (...,['Smoothes the appearance of fine lines and wr...,"[""Dove Pro-Age Neck & Chest Beauty Serum makes...",Co-t ARBrend,{'Package Dimensions': '6.9 x 5.2 x 1.8 inches...,B0017WUID4
35,All Beauty,John Frieda Frizz Ease Beyond Smooth Frizz-Imm...,[],['John Frieda Coconut Oil Infused Frizz Ease S...,John Frieda,"{'Item Form': 'Liquid', 'Brand': 'John Frieda'...",B086HRN773
36,All Beauty,Luxury Shimmer Pearl Loose Eyeshadow Powder Ey...,[],[],WindMax,{},B01D8DTE4I
37,All Beauty,Sharonelle Natural Cream Soft Wax for Sensitiv...,[],[],Sharonelle,"{'Item Form': 'Wax', 'Skin Type': 'Sensitive',...",B071G4NNH7
38,All Beauty,Kat Von D Shade Shifter Eyeshadow Love Letter ...,['Kat Von D Shade Shifter Eyeshadow Love Lette...,"['Very creative, innovative eye shadow with an...",Voronajj,"{'Brand': 'Voronajj', 'Finish Type': 'Shimmery...",B008U5QJYS
39,All Beauty,"Dufy Butterfly Nail Art Stickers Decals, 6 Lar...",[],[],Dufy,"{'Brand': 'Dufy', 'Color': 'Colorful,rose', 'S...",B087QGZXLP
40,All Beauty,Dionis Goat Milk Hand Cream 4 Piece Travel Gif...,[],[],Dionis,"{'Brand': 'Dionis', 'Unit Count': '4.00 tube',...",B01MCXNGP8
41,All Beauty,Zoella Beauty Tutti Fruity Foam Sweet Foam Sho...,[],[],NaN,"{'Item Form': 'Foam, Gel', 'Age Range (Descrip...",B017JPCGSM
42,All Beauty,100% PURE Glossy Locks: Grow More Shampoo (13....,['ENCOURAGES HAIR GROWTH - Instead of using to...,[],100% PURE,"{'Brand': '100% PURE', 'Item Form': 'Liquid', ...",B07B6F7NJ5
43,All Beauty,FeiDing Liquid Highlighter Illuminator Rose Go...,[],[],FeiDing,"{'Item Form': 'Spray', 'Finish Type': 'Velvet'...",B08CGWHCNN
44,All Beauty,Organic Sweet Almond Oil and Fractionated Coco...,[],[],Shiny Leaf,"{'Brand': 'Shiny Leaf', 'Scent': 'Almond Oil a...",B08LYT4Q2X
45,All Beauty,"Empty Brown Glass Spray Bottles2-Pack, Refilla...",[],[],Cherry,"{'Brand': 'Cherry', 'Material': 'Glass', 'Capa...",B089CSF11Y
46,All Beauty,"Nail Clippers Kit, Manicure Set 18 in 1 Stainl...",[],[],AGOAL,{'Package Dimensions': '6.46 x 4.41 x 1.06 inc...,B091SRVJLG
47,All Beauty,Cloud 9 Magic Capsule Cleanser 80ml - O2 Bubbl...,[],[],Cloud 9,"{'Item Form': 'Capsule', 'Skin Type': 'All', '...",B073RBSXY9
48,All Beauty,Rbenxia Sexy Satin Japan Kimono Dress Gown Bat...,[],[],NaN,{'Package Dimensions': '10.5 x 8 x 1.2 inches;...,B00GFDSKS0
49,All Beauty,"Bulk Herbs: Clay, White Kaolin","['1 oz bag', 'Excellent for Incense Blends', '...","['White kaolin, also known as China or white c...",Raven Moonlight,"{'Brand': 'Raven Moonlight', 'Item Form': 'Cla...",B005DT7YP2

In [7]:
items['title'] = items['title'].str.split(',', n=1).str[0]
items

,main_category,title,features,description,store,details,parent_asin
0,All Beauty,Howard LC0008 Leather Conditioner,[],[],Howard Products,{'Package Dimensions': '7.1 x 5.5 x 3 inches; ...,B01CUPMQZE
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,[],[],Yes To,"{'Item Form': 'Powder', 'Skin Type': 'Acne Pro...",B076WQZGPM
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),[],[],Levine Health Products,{'Manufacturer': 'Levine Health Products'},B000B658RI
3,All Beauty,Tattoo Eyebrow Stickers,[],[],Cherioll,"{'Brand': 'Cherioll', 'Item Form': 'Powder', '...",B088FKY3VD
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,"['Material: 304 Stainless Steel; Brass tip', '...",['The Precision Plunger Bars are designed to w...,Precision,{'UPC': '644287689178'},B07NGFDN6G
...,...,...,...,...,...,...,...
112585,All Beauty,"TOPREETY 24""120gr 3/4 Full Head clip in hair e...",[],[],TOPREETY,"{'Is Discontinued By Manufacturer': 'No', 'Pac...",B077D2Z5RF
112586,All Beauty,Pets Playmate Pet Grooming Glove,[],[],Pets Playmate,"{'Is Discontinued By Manufacturer': 'No', 'Pac...",B07DLRYKQZ
112587,All Beauty,[10Pack] Makeup Brushes Set Cosmetics Tools Ki...,[],[],RainMakers,"{'Brand': 'RainMakers', 'Recommended Uses For ...",B07HNP2NTF
112588,All Beauty,Xcoser Pretty Party Anna Wig Hair Tails Hair S...,[],[],Xcoser,"{'Is Discontinued By Manufacturer': 'No', 'Pac...",B00U3OB8PY
112589,All Beauty,DVIO Men's Voyage Perfume,"[""Features: Spicy woody notes, pure sandalwood...",[],DVIO,"{'UPC': '736238729337', 'Manufacturer': 'DVIO'}",B09B9TCYWG

In [11]:
ratings = ratings.drop(columns=['images', 'title', 'helpful_vote', 'text', 'asin', 'verified_purchase'], errors='ignore')
threshold = 3.0
ratings['rating'] = (ratings['rating'] >= threshold).astype(int)
ratings

        rating parent_asin                       user_id     timestamp
0            1  B00YQ6X8EO  AGKHLEW2SOWHNMFQIJGBECAF7INQ  1.588690e+12
1            1  B081TJ8YS3  AGKHLEW2SOWHNMFQIJGBECAF7INQ  1.588620e+12
2            1  B097R46CSY  AE74DYR3QUGVPZJ3P7RFWBGIX7XQ  1.589670e+12
3            0  B09JS339BZ  AFQLNQNQYFWQZPJQZS6V3NZU4QBQ  1.643390e+12
4            1  B08BZ63GMJ  AFQLNQNQYFWQZPJQZS6V3NZU4QBQ  1.609320e+12
...        ...         ...                           ...           ...
701523       1  B006YUIWKA  AFIXGFVEGLMOTMBTJL7H3VSIETDQ  1.478230e+12
701524       0  B006YUIWKA  AFV7YZFOJF564EZGET5LG45K4QEA  1.480910e+12
701525       1  B06ZZV9MZT  AHYDCWDMMVMLBX7FY7M7JKADKRDQ  1.590550e+12
701526       1  B000HB6VLE  AF6ZIAEN7TQ2WY5ZL77F6JDPV7XQ  1.184800e+12
701527       1  B0093MXHFG  AGIYQU6RK6TBKBCMWKVPBPBMMJNA  1.366940e+12

[701528 rows x 4 columns]

In [5]:
train_set = train_set.drop(columns=['images', 'title', 'helpful_vote', 'text', 'asin', 'verified_purchase'], errors='ignore')
val_set = val_set.drop(columns=['images', 'title', 'helpful_vote', 'text', 'asin', 'verified_purchase'], errors='ignore')
test_set = test_set.drop(columns=['images', 'title', 'helpful_vote', 'text', 'asin', 'verified_purchase'], errors='ignore')

In [12]:
# items.to_csv('amazon_beauty_reviews_meta_modified_comma_trimmed.csv', index=False)
ratings.to_csv('amazon_beauty_ratings_binarized_full.csv')
# val_set.to_csv('amazon_beauty_ratings_val.csv', index=False)
# test_set.to_csv('amazon_beauty_ratings_test.csv', index=False)

In [8]:
val_set

        rating parent_asin                       user_id     timestamp
368298       3  B087ZQK2G8  AE23ZBUF2YVBQPH2NN6F5XSA3QYQ  1.600100e+12
368297       4  B08BF4BKKM  AE23ZBUF2YVBQPH2NN6F5XSA3QYQ  1.601080e+12
124545       3  B08DXLRTSB  AE2IGWDKOWONDB3FQFX3STYGWCNQ  1.602260e+12
509365       2  B0829HHW2M  AE2O2C43KTYO4LXXGZWJZLE67GBQ  1.582760e+12
510267       5  B09Y1Z581L  AE2WYNQPBMS67OHFWV63NI4MSJEA  1.659480e+12
...        ...         ...                           ...           ...
437426       5  B08DG5CDXR  AHYOSWORVZFXM5QMRIAW3JTTFFIQ  1.599170e+12
437424       5  B08DNQJNFL  AHYOSWORVZFXM5QMRIAW3JTTFFIQ  1.599410e+12
437425       5  B08CMV3PV6  AHYOSWORVZFXM5QMRIAW3JTTFFIQ  1.599410e+12
437423       4  B08BY91SGT  AHYOSWORVZFXM5QMRIAW3JTTFFIQ  1.600320e+12
89194        4  B01GGEVW14  AHYUFOFTGNEV4TGMQLASS6EA7QAQ  1.467590e+12

[687 rows x 4 columns]

In [2]:
import pandas as pd

In [20]:
users = pd.read_csv('processed_dataset/MovieLens-1M/users/users_movielens_modified.csv')
age_mapping = {
    "Under 18": "Teenager",
    "18-24": "Young Adult",
    "25-34": "Adult",
    "35-44": "Middle-Aged Adult",
    "45-49": "Older Adult",
    "50-55": "Senior Adult",
    "56+": "Elder"
}

# Apply the mapping to the age column
users['age'] = users['age'].map(age_mapping)

users

      user_id  gender       age              occupation zip_code
0           1  Female  Under 18            K-12 student    48067
1           2    Male       56+           self-employed    70072
2           3    Male     25-34               scientist    55117
3           4    Male     45-49    executive/managerial    02460
4           5    Male     25-34                  writer    55455
...       ...     ...       ...                     ...      ...
6035     6036  Female     25-34               scientist    32603
6036     6037  Female     45-49       academic/educator    76006
6037     6038  Female       56+       academic/educator    14706
6038     6039  Female     45-49  other or not specified    01060
6039     6040    Male     25-34      doctor/health care    11106

[6040 rows x 5 columns]

In [11]:
import pandas as pd
import re

# Load the dataset
movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens.csv')

# Function to extract the year and create the decade string
def extract_decade(title):
    match = re.search(r'\((\d{4})\)', title)
    if match:
        year = int(match.group(1))
        decade = f"{(year // 10) * 10}s"
        # Remove the year from the title
        title = re.sub(r'\(\d{4}\)', '', title).strip()
        return title, decade
    return title, "Unknown"

# Function to clean up titles
def clean_title(title):
    # Remove ', The', ', A', or ', An' and adjust the title
    title = re.sub(r',\s(The|A|An)$', '', title).strip()
    # Remove all commas from the title
    title = title.replace(',', '')
    return title

# Function to process the title by cleaning and extracting the decade
def process_title(title):
    # Extract the decade and clean the title
    title, decade_text = extract_decade(title)
    # Further clean the title
    title = clean_title(title)
    return title, decade_text

# Apply the function to the dataset
movies[['title', 'decade']] = movies['title'].apply(lambda x: pd.Series(process_title(x)))

# Save the modified dataset (if needed)
# movies.to_csv('processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv', index=False)

# Display the first few rows to verify
movies

,item_id,title,genres,decade
0,1,Toy Story,Animation|Children's|Comedy,1990s
1,2,Jumanji,Adventure|Children's|Fantasy,1990s
2,3,Grumpier Old Men,Comedy|Romance,1990s
3,4,Waiting to Exhale,Comedy|Drama,1990s
4,5,Father of the Bride Part II,Comedy,1990s
...,...,...,...,...
3878,3948,Meet the Parents,Comedy,2000s
3879,3949,Requiem for a Dream,Drama,2000s
3880,3950,Tigerland,Drama,2000s
3881,3951,Two Family House,Drama,2000s
3882,3952,Contender,Drama|Thriller,2000s

In [6]:
import pandas as pd
import re

# Load the dataset
movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens.csv')

# Function to convert the year to descriptive text
def year_to_decade_text(year):
    if 2000 <= year < 2010:
        return "Two Thousands"
    elif 1990 <= year < 2000:
        return "Nineties"
    elif 1980 <= year < 1990:
        return "Eighties"
    elif 1970 <= year < 1980:
        return "Seventies"
    elif 1960 <= year < 1970:
        return "Sixties"
    elif 1950 <= year < 1960:
        return "Fifties"
    elif 1940 <= year < 1950:
        return "Forties"
    elif 1930 <= year < 1940:
        return "Thirties"
    elif 1920 <= year < 1930:
        return "Twenties"
    else:
        return "Older"

# Function to extract the year, convert it to text, and remove it from the title
def extract_decade_text(title):
    match = re.search(r'\((\d{4})\)', title)
    if match:
        year = int(match.group(1))
        decade_text = year_to_decade_text(year)
        # Remove the year from the title
        title = re.sub(r'\(\d{4}\)', '', title).strip()
        return title, decade_text
    return title, "Unknown"

# Apply the function to the dataset
movies[['title', 'decade']] = movies['title'].apply(lambda x: pd.Series(extract_decade_text(x)))

# Save the modified dataset (if needed)
# movies.to_csv('processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv', index=False)

# Display the first few rows to verify
print(movies.head())

   item_id                        title                        genres  \
0        1                    Toy Story   Animation|Children's|Comedy
1        2                      Jumanji  Adventure|Children's|Fantasy
2        3             Grumpier Old Men                Comedy|Romance
3        4            Waiting to Exhale                  Comedy|Drama
4        5  Father of the Bride Part II                        Comedy

     decade
0  Nineties
1  Nineties
2  Nineties
3  Nineties
4  Nineties

In [21]:
users.to_csv('users_movielens.csv', index=False)
movies.to_csv('movies_movielens_modified2.csv', index=False)

In [46]:
import pandas as pd
import re

# Load the dataset
# book_ratings = pd.read_csv('datasets/books/Books_rating.csv/Books_rating.csv')
book_ratings = pd.read_csv('processed_dataset/Amazon-Books/20 interactions fixed/amazon_books_ratings_full_filtered_fixed.csv')


books = pd.read_csv('processed_dataset/Amazon-Books/20 interactions fixed/books_data_with_new_id.csv')

In [18]:
book_ratings

,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
0,1,0826414346,Dr. Seuss: American Icon,A30TK6U7DNS82R,Kevin Killian,5.0,1095724800
1,3,0826414346,Dr. Seuss: American Icon,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",4.0,1090713600
2,5,0826414346,Dr. Seuss: American Icon,A2F6NONFUDB6UK,Malvin,4.0,1127174400
3,6,0826414346,Dr. Seuss: American Icon,A14OJS0VWMOSWO,Midwest Book Review,5.0,1100131200
4,11,0829814000,Wonderful Worship in Smaller Churches,A373VVEU6Z9M0N,Dr. Terry W. Dorsett,5.0,1291766400
...,...,...,...,...,...,...,...
522214,2999955,0786182431,Very Bad Deaths: Library Edition,A2PK3NTC9RMEF4,S. Potter,3.0,1179705600
522219,2999979,B00085PL4C,"Old Quebec,: The fortress of New France,",A32ZKBXJJ45BRY,James Gallen,3.0,1097452800
522220,2999988,0255364520,An End to Welfare Rights: The Rediscovery of I...,A25JH6CO4DVINS,Junglies,4.0,1045526400
522221,2999994,B000NSLVCU,The Idea of History,AOFGOUMXLMVZS,"S. Grotzke ""scquest""",4.0,1342483200
522222,2999996,B000NSLVCU,The Idea of History,A1SMUB9ASL5L9Y,jafrank,4.0,1331683200

In [34]:
# Remove rows where 'user_id' is NaN
book_ratings = book_ratings.dropna(subset=['user_id'])
book_ratings = book_ratings.dropna(subset=['Title'])

# Display the cleaned DataFrame
print("Dataset after removing rows with NaN 'user_id':")
print(book_ratings)

Dataset after removing rows with NaN 'user_id':
        Unnamed: 0     item_id  \
0                1  0826414346
1                3  0826414346
2                5  0826414346
3                6  0826414346
4               11  0829814000
...            ...         ...
522218     2999975  0449222543
522219     2999979  B00085PL4C
522220     2999988  0255364520
522221     2999994  B000NSLVCU
522222     2999996  B000NSLVCU

                                                    Title         user_id  \
0                                Dr. Seuss: American Icon  A30TK6U7DNS82R
1                                Dr. Seuss: American Icon  A2MVUWT453QH61
2                                Dr. Seuss: American Icon  A2F6NONFUDB6UK
3                                Dr. Seuss: American Icon  A14OJS0VWMOSWO
4                   Wonderful Worship in Smaller Churches  A373VVEU6Z9M0N
...                                                   ...             ...
522218                                            My Life  A3U5FGKX3UNBOJ
522219           Old Quebec,: The fortress of New France,  A32ZKBXJJ45BRY
522220  An End to Welfare Rights: The Rediscovery of I...  A25JH6CO4DVINS
522221                                The Idea of History   AOFGOUMXLMVZS
522222                                The Idea of History  A1SMUB9ASL5L9Y

                               profileName  rating   timestamp
0                            Kevin Killian     5.0  1095724800
1       Roy E. Perry "amateur philosopher"     4.0  1090713600
2                                   Malvin     4.0  1127174400
3                      Midwest Book Review     5.0  1100131200
4                     Dr. Terry W. Dorsett     5.0  1291766400
...                                    ...     ...         ...
522218                 louis smith "louis"     2.0  1153872000
522219                        James Gallen     3.0  1097452800
522220                            Junglies     4.0  1045526400
522221                S. Grotzke "scquest"     4.0  1342483200
522222                             jafrank     4.0  1331683200

[522223 rows x 7 columns]

In [35]:
# Identify duplicates based on 'item_id' and 'user_id'
duplicates = book_ratings[book_ratings.duplicated(subset=['item_id', 'user_id'], keep=False)]

# Remove duplicates to create a cleaned DataFrame
book_ratings = book_ratings.drop_duplicates(subset=['item_id', 'user_id'])

# Display the removed duplicate rows
print("Removed duplicate rows based on 'item_id' and 'user_id':")
print(duplicates[['user_id', 'item_id']])

Removed duplicate rows based on 'item_id' and 'user_id':
               user_id     item_id
48      A3DKP67DK28RUB  1597400602
49      A24DTVSHSWZVR5  1597400602
158     A2TXR85WQLE32N  B0006AUI9W
159     A19Q6JEEEBNOAU  B0006AUI9W
160      AAL7QMRIOAGVD  B0006AUI9W
...                ...         ...
522204  A18DH7N6ZI48L4  B000PGDJW0
522215   A9Q28YTLYREO7  0449222543
522216  A3LPQAPU2ILDD0  0449222543
522217  A22LX6529JJ166  0449222543
522218  A3U5FGKX3UNBOJ  0449222543

[126349 rows x 2 columns]

In [144]:
empty_cells_count = book_ratings.isna().sum()

empty_cells_count

Id                          0
Title                       0
Price                 1987063
User_id                     0
profileName               118
review/helpfulness          0
review/score                0
review/time                 0
review/summary            397
review/text                 1
dtype: int64

In [36]:
# Find rows where 'Title' is NaN
empty_title_rows = book_ratings[book_ratings['Title'].isna()]

# Display the rows with empty 'Title'
print("Rows with empty 'Title':")
print(empty_title_rows)

Rows with empty 'Title':
Empty DataFrame
Columns: [Unnamed: 0, item_id, Title, user_id, profileName, rating, timestamp]
Index: []

In [37]:
# Remove rows where 'user_id' is NaN
book_ratings = book_ratings.dropna(subset=['user_id'])

# Display the cleaned DataFrame
print("Dataset after removing rows with NaN 'user_id':")
print(book_ratings)

Dataset after removing rows with NaN 'user_id':
        Unnamed: 0     item_id  \
0                1  0826414346
1                3  0826414346
2                5  0826414346
3                6  0826414346
4               11  0829814000
...            ...         ...
522214     2999955  0786182431
522219     2999979  B00085PL4C
522220     2999988  0255364520
522221     2999994  B000NSLVCU
522222     2999996  B000NSLVCU

                                                    Title         user_id  \
0                                Dr. Seuss: American Icon  A30TK6U7DNS82R
1                                Dr. Seuss: American Icon  A2MVUWT453QH61
2                                Dr. Seuss: American Icon  A2F6NONFUDB6UK
3                                Dr. Seuss: American Icon  A14OJS0VWMOSWO
4                   Wonderful Worship in Smaller Churches  A373VVEU6Z9M0N
...                                                   ...             ...
522214                   Very Bad Deaths: Library Edition  A2PK3NTC9RMEF4
522219           Old Quebec,: The fortress of New France,  A32ZKBXJJ45BRY
522220  An End to Welfare Rights: The Rediscovery of I...  A25JH6CO4DVINS
522221                                The Idea of History   AOFGOUMXLMVZS
522222                                The Idea of History  A1SMUB9ASL5L9Y

                               profileName  rating   timestamp
0                            Kevin Killian     5.0  1095724800
1       Roy E. Perry "amateur philosopher"     4.0  1090713600
2                                   Malvin     4.0  1127174400
3                      Midwest Book Review     5.0  1100131200
4                     Dr. Terry W. Dorsett     5.0  1291766400
...                                    ...     ...         ...
522214                           S. Potter     3.0  1179705600
522219                        James Gallen     3.0  1097452800
522220                            Junglies     4.0  1045526400
522221                S. Grotzke "scquest"     4.0  1342483200
522222                             jafrank     4.0  1331683200

[439768 rows x 7 columns]

In [38]:
# Group by 'Title' and find titles associated with more than one unique ID
duplicate_titles = book_ratings.groupby('Title').filter(lambda x: x['item_id'].nunique() > 1)

# Display the results: Titles with more than one unique ID
duplicate_titles_sorted = duplicate_titles.sort_values(by='Title')

print("Books with the same title but different IDs:")
print(duplicate_titles_sorted[['item_id', 'Title']])

Books with the same title but different IDs:
Empty DataFrame
Columns: [item_id, Title]
Index: []

In [150]:
# Iterate over each title and set the same ID
for title in duplicate_titles['Title'].unique():
    # Get the unique IDs for the title
    ids = book_ratings.loc[book_ratings['Title'] == title, 'Id'].unique()

    # Choose one ID (for example, the first one)
    chosen_id = ids[0]

    # Update all rows with this title to have the same ID
    book_ratings.loc[book_ratings['Title'] == title, 'Id'] = chosen_id

# Display the modified DataFrame
print("Updated book_ratings with same IDs for duplicate titles:")
print(book_ratings[['Id', 'Title']].sort_values(by='Title'))

Updated book_ratings with same IDs for duplicate titles:
                 Id                                              Title
1664107  B0000CK3SI           " Film technique, " and, " Film acting "
1664106  B0000CK3SI           " Film technique, " and, " Film acting "
402729   B000K1C2HS  " We'll Always Have Paris": The Definitive Gui...
402728   B000K1C2HS  " We'll Always Have Paris": The Definitive Gui...
1604731  B000HEEPWS  "... And Poetry is Born ..." Russian Classical...
...             ...                                                ...
1279132  B000NRY0YC                           with an everlasting love
911688   B000PSN464                                work and Motivation
1180027  078930287X                             www.whitbread.org/book
1180028  078930287X                             www.whitbread.org/book
1982127  0256204322  xBase Programming for the True Beginner: An In...

[2397419 rows x 2 columns]

In [32]:
book_ratings.to_csv('amazon_books_ratings_full_filtered_fixed.csv')

In [39]:
book_ratings = book_ratings.drop(columns=['Price', 'review/helpfulness', 'review/summary', 'review/text'], errors='ignore')
book_ratings = book_ratings.rename(columns={"User_id": "user_id", "Id": "item_id", "review/time": "timestamp", "review/score": "rating"})

In [42]:
book_ratings

,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
0,1,0826414346,Dr. Seuss: American Icon,A30TK6U7DNS82R,Kevin Killian,5.0,1095724800
1,3,0826414346,Dr. Seuss: American Icon,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",4.0,1090713600
2,5,0826414346,Dr. Seuss: American Icon,A2F6NONFUDB6UK,Malvin,4.0,1127174400
3,6,0826414346,Dr. Seuss: American Icon,A14OJS0VWMOSWO,Midwest Book Review,5.0,1100131200
4,11,0829814000,Wonderful Worship in Smaller Churches,A373VVEU6Z9M0N,Dr. Terry W. Dorsett,5.0,1291766400
...,...,...,...,...,...,...,...
522214,2999955,0786182431,Very Bad Deaths: Library Edition,A2PK3NTC9RMEF4,S. Potter,3.0,1179705600
522219,2999979,B00085PL4C,"Old Quebec,: The fortress of New France,",A32ZKBXJJ45BRY,James Gallen,3.0,1097452800
522220,2999988,0255364520,An End to Welfare Rights: The Rediscovery of I...,A25JH6CO4DVINS,Junglies,4.0,1045526400
522221,2999994,B000NSLVCU,The Idea of History,AOFGOUMXLMVZS,"S. Grotzke ""scquest""",4.0,1342483200
522222,2999996,B000NSLVCU,The Idea of History,A1SMUB9ASL5L9Y,jafrank,4.0,1331683200

In [47]:
valid_item_ids = set(books['item_id'])
valid_item_ids

{'1558746137',
 '708928994',
 '039471508X',
 '534362958',
 '889652368',
 '764226266',
 '807128880',
 '084395261X',
 '140288236',
 'B000EOONX2',
 'B000FO7OKA',
 '970365403',
 'B00086DVCK',
 'B0007EIX5S',
 '810978687',
 '883855356',
 'B000COH3PY',
 'B000OX9YLE',
 '895778971',
 '929387279',
 '387196587',
 '4770015437',
 '3861870622',
 'B000KX9L9I',
 '1580083323',
 '385491247',
 '785269002',
 'B000GPP47I',
 '873959825',
 '679006826',
 '1557502862',
 '8879111981',
 '848716345',
 '804836590',
 'B000OX9XWE',
 '785267891',
 'B000KQ0TCI',
 '745937047',
 'B000PAVFBI',
 'B000PAWUAI',
 'B0007ISLUQ',
 '1400001854',
 'B000HQRVCC',
 '1861008317',
 '1929297211',
 '806970758',
 '091358987X',
 '850317053',
 '097589921X',
 'B000HB28Z2',
 '300087446',
 '764311123',
 'B000J46IGM',
 '1890449296',
 '553573950',
 'B000NREG5K',
 '767913825',
 '517800837',
 'B0006YL7K2',
 '60193654',
 '553580418',
 '1559584998',
 '760301719',
 '890796254',
 'B0007KF61G',
 '8466616888',
 '1591143012',
 'B0007FV9KS',
 '9758176099',
 '840784104',
 '3925443908',
 '312268742',
 'B000QCQGQE',
 '1899531041',
 '805210148',
 '964921030',
 '091383663X',
 '140371915',
 '1564552926',
 'B0007J5S3S',
 '791405966',
 'B000N5982I',
 'B0007IWLK2',
 '912075023',
 '689824459',
 '449132978',
 '226288501',
 '195178548',
 '1890733016',
 '924486473',
 '141344735X',
 'B000NAWCJE',
 'B000MVQGRS',
 'B0006BM32G',
 '439678625',
 'B000GLKB9S',
 '977117707',
 'B00005J6VJ',
 'B00072P13M',
 'B0006CDYN2',
 '312972105',
 '184467066X',
 '941711161',
 '1903223482',
 '883686414',
 '1567181864',
 '830736727',
 '823414469',
 '752866524',
 'B000PWLCZU',
 '964012561',
 '1852330554',
 '449132994',
 'B000857OO2',
 '754815048',
 '321011260',
 '395720990',
 'B000OWPHR0',
 '802769241',
 '896583155',
 '887847331',
 '262541416',
 'B0007E202A',
 '185010073X',
 '965932532',
 '851517374',
 '451210751',
 '1413762166',
 'B00086XQDO',
 '679600205',
 'B000IEJOJ6',
 'B0007F3BNQ',
 'B000PCDEYW',
 '1424117917',
 '953057593',
 '773757333',
 '553061194',
 '821712942',
 'B000NRFYYW',
 '373225725',
 'B000PVELWM',
 '62051598',
 '441871607',
 '840212763',
 'B000L2DDZ6',
 '849902150',
 '1412906687',
 'B000KJ5HBS',
 'B000MUC1YQ',
 'B000865DFI',
 '970145403',
 'B000J00XOE',
 '310914787',
 'B000P10SCO',
 'B000PGPRQ6',
 '820323454',
 'B0008B7NFQ',
 'B000MMYO8U',
 '1591473268',
 '9686941487',
 'B000JZSIHS',
 '389204919',
 '521366887',
 '962050784',
 'B000F3FWZK',
 'B0007DR49U',
 '28642627',
 '684859661',
 '1402703309',
 '971394229',
 '1592233430',
 'B0008A44AO',
 '712619194',
 '743423879',
 '1566563593',
 'B000EHTAHS',
 '1929659008',
 '938294806',
 '1903471087',
 'B000NNCKFM',
 '930031970',
 '805042156',
 '395206715',
 '833024930',
 '1401900577',
 '1577490649',
 '749920246',
 '786406984',
 '1556433328',
 '1883305004',
 '1402728360',
 '446718505',
 '1929998724',
 '1566409926',
 '486402649',
 '439179785',
 'B000PUUCDU',
 '1413419747',
 'B000MLGJPM',
 '1572492171',
 'B0006EXE2Q',
 '1402203926',
 '848706196',
 '806646497',
 '133494578',
 'B000HTDCMW',
 '059536084X',
 'B000H2N5HG',
 'B000KZ9QFA',
 '088113256X',
 '935989870',
 '1570671184',
 '714119482',
 '1859607209',
 '738702862',
 'B0007SEGRI',
 '1413443141',
 '201059584',
 '874161304',
 'B0006EN688',
 '1583880844',
 'B0007DN2B4',
 'B000PRX3PC',
 '130802581',
 '766100367',
 'B000P29XGU',
 '878754881',
 '9685368074',
 '373122012',
 '972899219',
 'B000855CXM',
 '759945136',
 '312323158',
 '878440879',
 '394718763',
 '810978873',
 'B000O1BY7S',
 '078471262X',
 'B00071UC8W',
 'B0006C06H4',
 '1886969434',
 '1563896915',
 '1887120076',
 'B000GZGVIO',
 'B000NPE3N2',
 '373272693',
 '1557508313',
 '873583493',
 'B000FGGL9I',
 '972332901',
 'B0007176K4',
 '1568810075',
 '801411319',
 'B0007DXCXM',
 '938566903',
 'B00085YLJ8',
 '1558175067',
 '70329672',
 '805057498',
 '1880549123',
 'B000NQLO2O',
 '974881732',
 '806527013',
 '304357839',
 '892720832',
 '757301517',
 'B000NUMSMU',
 '517114496',
 'B000GLFG5W',
 'B000IOGWA0',
 '805035737',
 'B0006E58Q6',
 'B0006AV32I',
 '425048209',
 '1894898087',
 '929387317',
 '761551379',
 '941523039',
 'B000FZE89Y',
 '719538572',
 '711218285',
 'B000NTDMWQ',
 '809311984',
 '1590581172',
 '964578603',
 '679441786',
 '1563332434',
 '553574558',
 'B0007EUPR2',
 '1859607098',
 '743250990',
 'B000Q2X7I4',
 'B000NP1HO0',
 'B000N6QJ38',
 '1563975963',
 '9995498251',
 'B000N76ZRC',
 'B000FCMWQI',
 '446530727',
 'B000FIJFJY',
 '828832730',
 '136493858',
 '1566950767',
 'B0006W9D64',
 '1591297966',
 '059069216X',
 'B000PX5W5K',
 'B00005WK0Y',
 'B000N707US',
 '1565481844',
 'B0006APKEK',
 'B000728FKI',
 '807009431',
 'B0006DE2F0',
 'B000JPKY0W',
 '471978582',
 '944715664',
 'B000PXHV1I',
 'B0007DNC3M',
 'B0007IOZYM',
 'B000K1AMVG',
 '1877617008',
 'B000GPP4FA',
 'B0002OKA1I',
 'B0007FOCDE',
 'B0006AXTXO',
 'B00087VFWC',
 'B000J5O0DY',
 'B00086UJ98',
 'B000HWYUL6',
 'B0007ELL84',
 '066919543X',
 '094239688X',
 '1877717053',
 '967638062',
 '1890627518',
 '678005516',
 '1565042778',
 'B0006IU3M6',
 '385721579',
 'B000MWTO3A',
 '4871990419',
 'B000JRGZBW',
 '027100424X',
 '1568361963',
 '60550708',
 '754002233',
 '891415378',
 'B00005VQKB',
 'B000MU5A8U',
 '1552975401',
 'B0006BVZD4',
 'B0006D6E4M',
 'B000K0C0IK',
 '156565966X',
 'B000GC440E',
 'B000MQYV98',
 'B0006WWQ7C',
 '595176941',
 '844225517',
 '70304165',
 '582051541',
 '517888491',
 '1569752834',
 '373037104',
 '1566866855',
 'B000OZ05N8',
 '836438930',
 '399231625',
 'B000N7ML16',
 '1558673148',
 'B000KQK2PW',
 '1416002553',
 '822013541',
 'B0000CL1YH',
 '262232057',
 '791067025',
 'B00085SQHG',
 'B000HCYH7I',
 '970314051',
 'B000CSZQXQ',
 '736913556',
 '1421800039',
 'B00071DM66',
 'B000OX9Y7I',
 'B000O040Q6',
 '883686546',
 '9622320023',
 '1841198056',
 '1562439618',
 'B000NRBBNK',
 '1410748987',
 '976666200',
 'B00009MB53',
 'B0006AV616',
 'B000IOF1JI',
 'B000I3E4WE',
 'B0007E4MBW',
 '533120500',
 '812931661',
 'B000892BE6',
 '1580083579',
 '198661886',
 '785741208',
 '1577943260',
 '595329411',
 '1584882727',
 'B000N6OV2O',
 '205351883',
 'B000PSDJN2',
 '1582450137',
 'B000EMBE1S',
 '3540661581',
 '683300091',
 'B000HT5HUC',
 'B000AXWEEM',
 '809237822',
 'B000I8MA2A',
 '966462491',
 '1594672539',
 '696016060',
 'B000GT5ICA',
 '426203135',
 '1898323755',
 '789496488',
 '758203799',
 '29126630',
 'B00086BKMS',
 'B000JQ0R7G',
 '471114650',
 '878793054',
 '595314317',
 'B0006EQ9PU',
 'B0006D70KY',
 '916397386',
 'B00088RD5O',
 'B0006YR2MY',
 '767321839',
 '1887269401',
 'B000J5JDJ0',
 '802403417',
 '745601731',
 'B000GA5RRK',
 '1560445661',
 '515114871',
 '786929987',
 '1886363102',
 '080613741X',
 '1585030872',
 '870991426',
 '1569711402',
 'B0002RQ1IG',
 '1596581786',
 'B000NG9BWO',
 'B000TBDRD2',
 'B000OWX948',
 '743252136',
 'B000N74PSI',
 'B0007BK8XQ',
 '1930771207',
 '1572491639',
 '198521448',
 'B000NVZEOI',
 '1578064384',
 '802438806',
 'B000NQ6GUO',
 'B000OTWPIM',
 '1401019323',
 '1563831007',
 '1930928122',
 'B000MU6R5K',
 'B000GQU5NK',
 'B00087DDBS',
 '786605979',
 '1929156006',
 'B000GPZ4QO',
 '814631525',
 'B000GCG3XK',
 '080281221X',
 '1555582591',
 'B000N6DHTC',
 'B0006QFSO6',
 '375822682',
 '1597641774',
 'B0007J6PZI',
 '813828139',
 '609803441',
 '801063884',
 '786118520',
 'B0007E5IEW',
 '1572233885',
 '816520763',
 '471382485',
 '816148341',
 'B000MT9AFK',
 '886771862',
 '1556344163',
 'B000GRL772',
 '907871631',
 '521807816',
 '786280662',
 'B000HX7F26',
 '736655948',
 '1401203469',
 '080183614X',
 '761450513',
 '931580528',
 '945575831',
 '394520599',
 '039607779X',
 '1558535993',
 '1872292100',
 '441783058',
 '815151403',
 '807842605',
 '440225531',
 '262220725',
 '877936994',
 '875964664',
 '1932360646',
 'B0007DS2ZK',
 '201741636',
 '333138678',
 '922820058',
 '1560760699',
 'B0006BU9EK',
 '1565481895',
 'B000QC6T8O',
 'B000APV9Y6',
 '375810951',
 '446531375',
 '684860732',
 'B000P3A6OC',
 '1558761861',
 'B00089ZO22',
 '851318282',
 '786864036',
 'B000GTC75Q',
 'B000E7C1GU',
 'B000MOIY8E',
 'B000H9FKUY',
 '806955430',
 'B000ES6I40',
 'B000733KHK',
 '812097386',
 'B000GT3QR4',
 'B000N7BNVA',
 '448147017',
 '764598309',
 '891091270',
 'B00085940O',
 '1594710147',
 '789721953',
 '140247084',
 '595176712',
 'B000NLPJ0W',
 '805371559',
 '452270480',
 '394555767',
 'B000N79MZY',
 '3908247438',
 'B000Q5OO88',
 '158479335X',
 '837608767',
 '801845890',
 'B00086DBAM',
 '140548823',
 '714880191',
 '671520458',
 '966243005',
 '815318766',
 'B000L1RWAY',
 '1844014983',
 'B000GKTGPO',
 '890878994',
 'B0007ENY8O',
 'B000MV89A0',
 '2203001046',
 'B0006CTR9W',
 '425146898',
 'B000QEAA64',
 'B000MU84GU',
 'B000K6JZRI',
 'B000OI0SBE',
 'B000PSUAV6',
 'B00086QYQ0',
 '618432892',
 'B000KY7TR8',
 '970479506',
 '1574090933',
 '1563526212',
 '059534982X',
 '811211797',
 '1932581626',
 'B0007US9JM',
 '1879427036',
 'B0007DZMRG',
 '684808455',
 '1556433573',
 '803283539',
 '883188708',
 '1585030996',
 'B0007DMHYM',
 '1887250115',
 '946688494',
 '2880862833',
 'B000OY6A74',
 'B0006C6GL4',
 '1885217943',
 '1566705401',
 '130304565',
 '446404616',
 'B000892UCY',
 'B000FGGLB6',
 '1562057480',
 '316000752',
 '1583220488',
 'B000MC5M4A',
 '4770020740',
 '1550226827',
 '821802879',
 '915442787',
 '1846370795',
 'B000ETLPL0',
 'B000Q1K0ZS',
 '70533946',
 '9004088598',
 '786004363',
 '307128687',
 'B0007ECJTE',
 'B0006FE2A8',
 'B000OIZUIA',
 '882544454',
 '935127429',
 'B0006BMXJY',
 '1592170641',
 '967867703',
 '609603965',
 '671006673',
 '1590072332',
 '9041122486',
 '856358967',
 '312876866',
 '1851825592',
 'B000855ANE',
 '567084086',
 'B000N7IEQW',
 'B0006AU69O',
 '674411528',
 '595193218',
 'B0006D70HW',
 '1879431998',
 '201485354',
 'B0007EPOC8',
 '373247206',
 '72503084',
 '738201057',
 'B00086RVMQ',
 'B0008E123M',
 '1893361527',
 'B000K5PSDO',
 '393307867',
 '763613053',
 '1862320209',
 '1561701076',
 '882210033',
 '1891776169',
 '4721349',
 'B0007BNVP8',
 '013938622X',
 '1885061420',
 '201103427',
 '804711259',
 '312909292',
 'B000J0PNF8',
 'B0006S0Q82',
 '767903528',
 '1591452155',
 '865979774',
 '740716875',
 '521394368',
 'B000Q0QR92',
 '963022245',
 '787220795',
 '801022975',
 '1560525401',
 'B000TYTFAI',
 '972381104',
 '096375470X',
 'B00088POBE',
 '1555610277',
 'B000OTU17Y',
 '966918304',
 '821777165',
 'B00088YOTW',
 '882904825',
 '486280918',
 '1575440695',
 '967856620',
 '1401900585',
 'B000NPH8XE',
 '517165686',
 '345231597',
 '1892123398',
 '373802315',
 '1560241551',
 '1559125055',
 '1850750637',
 'B000MU6O80',
 '1555703704',
 'B0006R1J0M',
 '1893554600',
 '712110542',
 'B000FGGNFA',
 'B000H5ELOO',
 '019852580X',
 'B000I3E4J2',
 'B000IOF2WE',
 '299118401',
 '1929382030',
 '975324330',
 '787981370',
 '1557884935',
 '1413746268',
 '763611921',
 '613358910',
 '1411651936',
 '807826537',
 '395416523',
 'B000K85OJE',
 '679886524',
 'B000HZ3GRM',
 'B000864JJE',
 '516201557',
 '201531798',
 '1420817752',
 '813190002',
 '373035918',
 '72119306',
 '262560968',
 '1578630312',
 '801882753',
 '20285612',
 '971352127',
 '1576107159',
 'B000N78PWU',
 '672326965',
 '736645586',
 'B0006ER54E',
 '1843532212',
 '785110925',
 '425046982',
 'B000IOEM2U',
 '618343970',
 '921100094',
 '880921706',
 'B00085G25E',
 'B000J03LWK',
 '1571451927',
 '1861082096',
 'B000EDQK70',
 '563526327',
 '689859546',
 'B000GQV2H8',
 '595320155',
 'B000QAB670',
 '292702175',
 'B000AY89VS',
 '590120514',
 '679437096',
 'B000K0FLGS',
 '963278002',
 'B0007F9OV4',
 'B000PC3QD6',
 '966603702',
 'B000H99YSI',
 '890969183',
 '394529707',
 '943452309',
 '3829003773',
 '393051595',
 'B000MV8HIO',
 'B000NTBEIK',
 '096483622X',
 '1576904067',
 '961641274',
 'B000N67S2Y',
 'B0006AITDO',
 '9707180994',
 '595218792',
 '034086656X',
 '844231533',
 'B0007E6YVI',
 '761901876',
 'B000EBLEZA',
 'B000HU709M',
 '71479015',
 'B000K0B6J4',
 '097530271X',
 'B000867RQ6',
 '898624126',
 '975453904',
 'B000J3JCP2',
 '078725231X',
 'B000K5NYX0',
 'B000N758GG',
 '870335731',
 '205277896',
 '521625343',
 'B0006AUI9W',
 '1570021341',
 'B0006CS0YA',
 'B000N3Z5XQ',
 '399116540',
 'B000BGS8R0',
 'B000I532PW',
 '971230927',
 '142003638',
 'B0007PC506',
 '1418427004',
 '1565120892',
 '590926721',
 'B000NZ7Q0Y',
 '393308146',
 '753114534',
 '007048595X',
 '700608966',
 'B00009V2NN',
 'B000JJTPTO',
 'B00005U01R',
 '425177734',
 'B0007XSNCC',
 '971388105',
 '859361217',
 '684855607',
 '521435765',
 'B0007DWGMK',
 'B000H2IZZS',
 'B000711O9S',
 'B000H7RT50',
 'B0006BM5UG',
 '9700717615',
 '307165205',
 '1843107570',
 '967605504',
 'B0007ZNUY6',
 '373834292',
 '829419799',
 '1563925168',
 '787969583',
 '006254862X',
 'B00075V1SS',
 'B0006J5UNW',
 '295983914',
 '961740612',
 'B000KPBWRK',
 '824797604',
 'B0006AV2Y2',
 'B0007JCUQ6',
 '052124739X',
 'B0006P8PYM',
 '340405376',
 'B000JK7BR6',
 '1563896842',
 '1889668001',
 '878770895',
 '967457939',
 'B000FMRSUS',
 'B0006WHCC6',
 '764534726',
 'B00006CRVP',
 '802067239',
 'B000N6KRLI',
 '877937206',
 '312422415',
 '861711572',
 'B0006SHMIO',
 '941402118',
 'B00005VO83',
 'B0007ELPGM',
 '971958610',
 '819194719',
 '967702011',
 '553570064',
 '966142888',
 'B00085GEVQ',
 '1933037466',
 '451209958',
 'B000KW1F3E',
 '1418482943',
 '686178076',
 'B000GM9WLU',
 '960376607',
 'B000P0HORM',
 '1894872053',
 'B0006CYSV4',
 '1881022234',
 'B00087CHE2',
 'B000MQAEBC',
 '806949724',
 '198290675',
 '3931141896',
 '052159409X',
 '752824732',
 'B0006F6HEW',
 '764105701',
 '966550846',
 'B0006BLJSA',
 '1591295033',
 '767411277',
 '1903889022',
 'B0007HD7W4',
 'B000NSMPBG',
 '085640697X',
 'B000NAWZW8',
 '195128087',
 '943158508',
 '61117579',
 '1932907114',
 '3791326007',
 '1556523068',
 'B000K3C7VM',
 '053458814X',
 'B0000CIPAS',
 '888996306',
 '71377859',
 'B00087KMJY',
 'B0006AH1FQ',
 'B00085MDMA',
 '960853405',
 '882680587',
 'B00005XZKS',
 '1856263975',
 'B000GRR3WA',
 '786004096',
 '375701737',
 '1891502816',
 '080411336X',
 'B00086SSBY',
 '158820104X',
 '793127467',
 '425162664',
 '1591452163',
 '1580624189',
 'B0007J8Y2U',
 'B00087HH6U',
 '1590402413',
 '813120829',
 'B000C0QS7W',
 'B0006C9K76',
 '8423979776',
 'B0006C2CFI',
 'B000L1RC4U',
 'B000HIASYS',
 'B000QAUFJK',
 '096381740X',
 '131924931',
 'B000H2N2L0',
 '936758252',
 'B000NPM5SM',
 '393958086',
 '1582973199',
 '971565856',
 'B000L64O8C',
 '1579212573',
 'B0006VZVRK',
 'B000KEK27M',
 '5554950426',
 '375811761',
 '1420834037',
 '571196365',
 'B000PCMZW4',
 'B000E28VAK',
 '399152687',
 '1885003609',
 '966793005',
 'B00069X4V2',
 '055356787X',
 '964378639',
 '373691696',
 '691025568',
 '088001606X',
 '521397812',
 '975422707',
 '4810866386',
 'B000NWLXWO',
 'B000H7GZ6E',
 '130289221',
 '471492396',
 '451216180',
 'B000MU2PJW',
 '193155904X',
 '074516661X',
 '9264186085',
 '842377972',
 '373691874',
 '076141505X',
 'B000MZQK0C',
 '1840593571',
 '943990971',
 ...}

In [50]:
book_ratings = book_ratings[book_ratings['item_id'].isin(valid_item_ids)]

In [51]:
user_rating_counts = book_ratings['user_id'].value_counts()
users_to_keep = user_rating_counts[user_rating_counts >= 20].index
book_ratings = book_ratings[book_ratings['user_id'].isin(users_to_keep)]

In [52]:
book_ratings

,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
11,174,B000857LFE,"Thomas Jefferson, (American statesmen)",A1WGUNNY90U041,"Jon L. Albee ""Faulkner Wannabe""",2.0,1193443200
12,176,1884734766,Dealing With Disappointment: Helping Kids Cope...,A14OJS0VWMOSWO,Midwest Book Review,5.0,1081814400
13,182,157067051X,Voices from the Farm: Adventures in Community ...,A1ER5AYS3FQ9O3,"K. Corn ""reviewer""",5.0,1160870400
14,198,B0007DVHU2,Treat yourself to life,A1RJD10TTI568L,"Pieter Uys ""Toypom""",5.0,973987200
15,199,B0007DVHU2,Treat yourself to life,A1LJX75GT1KKLT,"""pageh""",5.0,946684800
...,...,...,...,...,...,...,...
522202,2999914,B000PGDJW0,The Red Right Hand,A1WD8SD9L65UN3,Chris Ward,5.0,1132099200
522203,2999915,B000PGDJW0,The Red Right Hand,A2Y1SCM930PZI7,Jabberwocky,5.0,1140566400
522219,2999979,B00085PL4C,"Old Quebec,: The fortress of New France,",A32ZKBXJJ45BRY,James Gallen,3.0,1097452800
522221,2999994,B000NSLVCU,The Idea of History,AOFGOUMXLMVZS,"S. Grotzke ""scquest""",4.0,1342483200
522222,2999996,B000NSLVCU,The Idea of History,A1SMUB9ASL5L9Y,jafrank,4.0,1331683200

In [53]:
book_ratings = book_ratings.sort_values(by='timestamp')

# Calculate sparsity
total_entries = book_ratings.shape[0]
unique_users = book_ratings['user_id'].nunique()
unique_items = book_ratings['item_id'].nunique()
unique_users, unique_items

(6318, 51881)

In [54]:
from sklearn.model_selection import train_test_split

# Assuming `book_ratings` is already loaded and processed

# Create empty lists to store the split data
train_set = pd.DataFrame()
validation_set = pd.DataFrame()
test_set = pd.DataFrame()

# Group by 'user_id' and split each group
for user, group in book_ratings.groupby('user_id'):
    train, temp = train_test_split(group, test_size=0.2, random_state=42)
    validation, test = train_test_split(temp, test_size=0.5, random_state=42)

    # Append to the respective datasets
    train_set = pd.concat([train_set, train])
    validation_set = pd.concat([validation_set, validation])
    test_set = pd.concat([test_set, test])

# Reset index to ensure consistency
train_set = train_set.reset_index(drop=True)
validation_set = validation_set.reset_index(drop=True)
test_set = test_set.reset_index(drop=True)

In [55]:
# Display the sizes of the resulting datasets
print(f"Train set size: {train_set.shape[0]}")
print(f"Validation set size: {validation_set.shape[0]}")
print(f"Test set size: {test_set.shape[0]}")

Train set size: 262296
Validation set size: 32669
Test set size: 36027

In [56]:
train_set = train_set.sort_values(by='timestamp')
validation_set = validation_set.sort_values(by='timestamp')
test_set = test_set.sort_values(by='timestamp')

train_set.to_csv('amazon_books_ratings_train_filtered_fixed.csv')
validation_set.to_csv('amazon_books_ratings_val_filtered_fixed.csv')
test_set.to_csv('amazon_books_ratings_test_filtered_fixed.csv')

In [57]:
book_ratings.to_csv('amazon_books_ratings_full_filtered_fixed.csv')

In [173]:
books['item_id'] = None

In [174]:
books[10000:50050]

,Unnamed: 0,item_id,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
10000,10000,None,MCSE Windows 2000 Directory Services Exam Prep...,Here's the book you need to prepare for Exam 7...,"['Anil Desai', 'James Chellis']",http://books.google.com/books/content?id=HHG4N...,http://books.google.nl/books?id=HHG4NAEACAAJ&d...,Sybex,6/20/2001,http://books.google.nl/books?id=HHG4NAEACAAJ&d...,['Computers'],NaN
10001,10001,None,Autonomy and Community: Readings in Contempora...,Shows how Kant's basic position applies to and...,"['Jane Kneller', 'Sidney Axinn']",http://books.google.com/books/content?id=XKicZ...,http://books.google.nl/books?id=XKicZOagZksC&p...,SUNY Press,1/1/1998,http://books.google.nl/books?id=XKicZOagZksC&d...,['Philosophy'],NaN
10002,10002,None,Manual of Political Economy,NaN,['Erasmus Peshine Smith'],http://books.google.com/books/content?id=OtcMA...,http://books.google.nl/books?id=OtcMAAAAYAAJ&p...,NaN,1853,https://play.google.com/store/books/details?id...,['Economics'],NaN
10003,10003,None,To Place Our Deeds: The African American Commu...,To Place Our Deeds traces the development of t...,['Shirley Ann Wilson Moore'],http://books.google.com/books/content?id=TPLkD...,http://books.google.nl/books?id=TPLkDwAAQBAJ&p...,Univ of California Press,1/5/2000,https://play.google.com/store/books/details?id...,['History'],NaN
10004,10004,None,New York Run (Endworld),The Alpha Triad warriors undertake a mission i...,['David Robbins'],NaN,http://books.google.nl/books?id=kAZYAAAACAAJ&d...,NaN,1988,http://books.google.nl/books?id=kAZYAAAACAAJ&d...,['Fiction'],1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
50045,50045,None,Hungry Men.,Recipes and strategies for bringing back the f...,['Lucinda Scala Quinn'],http://books.google.com/books/content?id=BQ_Y5...,http://books.google.com/books?id=BQ_Y5u404_YC&...,Artisan Books,8/28/2012,http://books.google.com/books?id=BQ_Y5u404_YC&...,['Cooking'],5.0
50046,50046,None,Little Infamies: Stories,"Cunning, fantastical tales about a Greek villa...",['Panos Karnezis'],http://books.google.com/books/content?id=vxbgr...,http://books.google.com/books?id=vxbgrGdrqAEC&...,"Farrar, Straus and Giroux",3/1/2004,https://play.google.com/store/books/details?id...,['Fiction'],1.0
50047,50047,None,Gradual failure: The air war over North Vietna...,NaN,NaN,http://books.google.com/books/content?id=Lk6Cd...,http://books.google.com/books?id=Lk6CdTcReLgC&...,DIANE Publishing,NaN,https://play.google.com/store/books/details?id...,NaN,1.0
50048,50048,None,"History of the World, The Pelican",Rev. ed. of: The Hutchinson history of the wor...,['John Morris Roberts'],http://books.google.com/books/content?id=I_2Bz...,http://books.google.com/books?id=I_2BzlaAqyUC&...,Viking Press,1987,http://books.google.com/books?id=I_2BzlaAqyUC&...,['History'],NaN
50049,50049,None,Dear Peter Rabbit,Presents letters between such fairy tale chara...,['Alma Flor Ada'],http://books.google.com/books/content?id=7k37d...,http://books.google.com/books?id=7k37dFJCP60C&...,Aladdin,1/10/2006,http://books.google.com/books?id=7k37dFJCP60C&...,['Juvenile Fiction'],NaN

In [2]:
book_ratings = pd.read_csv('processed_dataset/Amazon-Books/amazon_books_ratings_original_fixed.csv')

In [6]:
books

,Unnamed: 0,item_id,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,0,1882931173,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN
1,1,826414346,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,1/1/2005,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
2,2,829814000,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,NaN,2000,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,['Religion'],NaN
3,3,595344550,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,iUniverse,2005-02,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,['Fiction'],NaN
4,4,253338352,"Nation Dance: Religion, Identity and Cultural ...",NaN,['Edward Long'],NaN,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,3/1/2003,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
212399,212399,590482467,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",['Elvira Woodruff'],http://books.google.com/books/content?id=J7M-N...,http://books.google.com/books?id=J7M-NwAACAAJ&...,Scholastic Paperbacks,6/1/2000,http://books.google.com/books?id=J7M-NwAACAAJ&...,['Juvenile Fiction'],2.0
212400,212400,570047870,Red Boots for Christmas,Everyone in the village of Friedensdorf is hap...,NaN,http://books.google.com/books/content?id=3n8k6...,http://books.google.com/books?id=3n8k6wl4BbYC&...,NaN,1995,http://books.google.com/books?id=3n8k6wl4BbYC&...,['Juvenile Fiction'],NaN
212401,212401,B000OVF7JY,Mamaw,"Give your Mamaw a useful, beautiful and though...",['Wild Wild Cabbage'],NaN,http://books.google.com/books?id=zytVswEACAAJ&...,NaN,1/17/2018,http://books.google.com/books?id=zytVswEACAAJ&...,NaN,NaN
212402,212402,1402508735,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,['Zadie Smith'],http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,Vintage,8/12/2003,https://play.google.com/store/books/details?id...,['Fiction'],19.0
212403,212403,534400604,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",http://books.google.com/books/content?id=dehfP...,http://books.google.com/books?id=dehfPgAACAAJ&...,Brooks/Cole Publishing Company,1/1/1998,http://books.google.com/books?id=dehfPgAACAAJ&...,NaN,NaN

In [7]:
books['item_id'] = None

# Iterate through each row in the books dataframe
for i, row in books.iterrows():
    # Get the title from the current row
    title = row['Title']

    # Find the matching row in the book_ratings dataframe
    matching_row = book_ratings[book_ratings['Title'] == title]

    # If a matching row is found, update the 'Id' in the books dataframe
    if not matching_row.empty:
        books.at[i, 'Id'] = matching_row['Id'].values[0]
    else:
        # If no match is found, print the row and title
        print(f"No match found for row {i}: {title}")

    if (i + 1) % 1000 == 0:
        print(f"Processed {i + 1} rows...")

No match found for row 77: Information Theory in Analytical Chemistry (Chemical Analysis: A Series of Monographs on Analytical Chemistry and Its Applications)
No match found for row 148: The Complete Works of Nathanael West
No match found for row 175: Voices of a Summer Day
No match found for row 194: Deadville
No match found for row 317: Women Creating Lives: Identities, Resilience, And Resistance
No match found for row 562: The Book of Love Laughter & Romance
No match found for row 567: The Face of the Third Reich
No match found for row 582: Spirit of the Moon
No match found for row 617: Five Sermons
No match found for row 620: Pokemon - 2.B.A. Master: Piano Fun! Pack
No match found for row 641: THE SHADOW IN THE GLASS
No match found for row 678: Membership Development: An Action Plan for Results (Aspen's Nonprofit Management Series)
No match found for row 718: Change and Continuity in Spatial Planning
No match found for row 795: In Search of Therese (Way of the Christian Mystics)
No match found for row 831: Plasticville
No match found for row 839: Swinger of Birches with Book
No match found for row 852: THE THEORY OF ECONOMIC GROWTH
No match found for row 889: Teach Yourself 101 Key Ideas: LINGUISTICS
No match found for row 941: The charismatic renewal among Lutherans: A pastoral and theological perspective
Processed 1000 rows...
No match found for row 1025: Teach Yourself Instant Russian Audio Pack
No match found for row 1034: Certification & Accreditationprogram Directory 2 (Certification and Accreditation Programs Directory)
No match found for row 1049: Lonely Planet Zimbabwe, Botswana and Namibia Travel Atlas
No match found for row 1066: nan
No match found for row 1116: Legal Planning for your Parents
No match found for row 1124: Journey Toward Intimacy: A handbook for lesbian couples
No match found for row 1129: A Jesse Stuart Harvest
No match found for row 1215: The Other Side : L'altra Faccia
No match found for row 1302: On Beyond Euclid
No match found for row 1324: King David and His Songs: A Story of the Psalms
No match found for row 1351: Visions of You
No match found for row 1371: For All Time
No match found for row 1382: ABC Biz Jets: Business & Corporate Aircraft (Ian Allan ABC)
No match found for row 1433: Long-Term Caring For Your Parents
No match found for row 1539: China Since 1911
No match found for row 1542: Highlife for Caliban (African Writers Library)
No match found for row 1578: Connections & Reflections: Mothers & Daughters in Their Own Light, in Their Own Words
No match found for row 1608: Telecommunications Act Handbook: A Complete Reference for Business
No match found for row 1633: Roll of Thunder Hear My Cry (Book Wise Literature Guides)
No match found for row 1639: Strange Power of Speech: Wordsworth, Coleridge, and Literary Possession
No match found for row 1650: Love Song (You're the One! (PB))
No match found for row 1673: Tiger Lil
No match found for row 1674: Tried and Trousseau: The Bride Guide
No match found for row 1708: Student Guide With Map Exercises to Accompany the Enduring Vision: A History of the American People, Volume Two: From 1865
No match found for row 1726: Heaven Help The Home
No match found for row 1745: Ghost Dancing
No match found for row 1785: 2001 CodeTracker Area Code Map : area codes of US, Canada and parts of the Caribbean
No match found for row 1929: Buffalo hunt
No match found for row 1957: The Universe: Theoretical Physics and Astronomy for the Young Adult
Processed 2000 rows...
No match found for row 2001: The crooked crown (A Golden super adventure book)
No match found for row 2097: Opportunities in Chiropractic Health-Care Careers
No match found for row 2159: Saab Aircraft (Archive Photographs)
No match found for row 2204: Practical Course in Esperanto
No match found for row 2223: Dwelling in Possibility: Women Poets and Critics on Poetry (Reading Women Writing)
No match found for row 2262: Filipino Americans: Transformation and Identity
No match found for row 2333: Singular Enlightenment
No match found for row 2363: WARNING: College Unathorized
No match found for row 2441: S-M: The Last Taboo
No match found for row 2472: The Secret World of the Irish Male (Reed Audio)
No match found for row 2623: A Filly For Joan
No match found for row 2632: Sexual Subversions: Three French Feminists
No match found for row 2685: The official mixer's manual,
No match found for row 2732: Shooting Star
No match found for row 2790: CHRISTOPHER + ALEXANDRA CL
No match found for row 2807: Commentaries on equity jurisprudence,: As administered in England and America
No match found for row 2826: NAS Exhaustive Concordance:
No match found for row 2827: Partners in Marriage (Silhouette Special Edition Ser, No. 1205)
No match found for row 2842: Antarctica: The last unspoiled continent
No match found for row 2851: Have You Started Yet?
No match found for row 2965: Parliamentary law at a glance: Based on Robert's Rules of order revised
Processed 3000 rows...
No match found for row 3000: Rhinos and Raspberries: Tolerance Tales for the Early Grades
No match found for row 3018: Essays By Robert Louis Stevenson
No match found for row 3044: A Visit From the Footbinder
No match found for row 3069: Cloud of Death
No match found for row 3123: A literature guide to The book of three: By Lloyd Alexander
No match found for row 3197: An Introduction to Composition Studies
No match found for row 3241: The Destroyer: 95
No match found for row 3301: The Future Of Home Schooling -
No match found for row 3311: Introducing the New Testament (SCM cheap edition)
No match found for row 3323: Isaiah and Jeremiah (Expositions of Holy Scripture)
No match found for row 3353: The autobiography and correspondence of Mary Granville, Mrs. Delany;: With interesting reminiscences of King George the Third and Queen Charlotte
No match found for row 3398: What'll We Talk About? : A Vocabulary and Conversation Book
No match found for row 3401: Pagemaker 6 for Windows for Dummies, Second Edition
No match found for row 3405: Baird's Manual of American College Fraternities
No match found for row 3421: Tales from the Barricades: Being the True and Faithful Account of the Life and Times of Ulster's Modern Cuchullian, B.A. Grimshaw, and His Heroic Part in Ireland's Fight for
No match found for row 3472: The City of Women: A Sequence of Poems and Prose
No match found for row 3526: A History of the Warfare of Science with Theology in Christendom
No match found for row 3538: James Thurber: a bibliography,
No match found for row 3570: Newnes Building Services Pocket Book, Second Edition (Newnes Pocket Books)
No match found for row 3575: Supersymmetry and supergravity (Princeton series in physics)
No match found for row 3590: The world of flying saucers; a scientific examination of a major myth of the space age
No match found for row 3656: The Jews in Toledo and their synagogues
No match found for row 3692: New Essays on Sister Carrie (The American Novel)
No match found for row 3704: The two Carolines
No match found for row 3745: Statistical problem solving (SPS) (SAE)
No match found for row 3769: Baird's manual of American college fraternities
No match found for row 3823: Last Love in Constantinople: A Tarot Novel for Divination
No match found for row 3854: World order (Civitas Dei)
No match found for row 3861: The pioneer twins
No match found for row 3904: Fables of Modernity: Literature and Culture in the English Eighteenth Century
No match found for row 3918: clarence goes to town
No match found for row 3962: Clarence Goes to Town
No match found for row 3975: The Cultural Transformation of A Native American Family and Its Tribe 1763-1995: A Basket of Apples (Sociocultural, Political, and Historical Studies in Education)
Processed 4000 rows...
No match found for row 4001: SAT II: Math Level IC (REA) -- The Best Test Prep for the SAT II (SAT PSAT ACT (College Admission) Prep)
No match found for row 4024: Italian for Educated Guessers: Shortcuts to the Language
No match found for row 4140: EL jardn increible
No match found for row 4185: A Man With a Maid: And Other Entertainments
No match found for row 4206: Light Nights and Wet Feet: A Walk Through Modern Scotland
No match found for row 4320: Communication and the Sexes
No match found for row 4329: Of skies and seas
No match found for row 4343: Watch Learning Problems Disappear: The Power of Imagery
No match found for row 4345: The Collected Works of J.G. Frazer: Folk-Lore in the Old Testament: Studies in Comparative Religion, Legend and Law (The Collected Works of James G. Frazer)
No match found for row 4359: Heaven Help the Home!
No match found for row 4363: The Woman Manager's Troubleshooter: Pinpointing the Causes & Cures of Today's Tough Supervisory Problems
No match found for row 4380: Pre-Columbian Man Finds Central America : The Archaeological Bridge
No match found for row 4391: To Harass Our People: The Story of the IRS
No match found for row 4398: Micah Clarke
No match found for row 4455: The White Peacock (The Cambridge Edition of the Works of D. H. Lawrence)
No match found for row 4460: The Best of Larry King Live: The Greatest Interviews
No match found for row 4496: The Book of Uncommon Prayer
No match found for row 4503: For the Love of Children
No match found for row 4548: Shike: Time of the Dragons
No match found for row 4553: Margaret Ogilvy (The works of J.M. Barrie)
No match found for row 4606: Pimpon (Coleccion Puertas al Sol)
No match found for row 4622: Fiction: Reading, Reacting, Writing
No match found for row 4650: The Statler Brothers Discography (Discographies: Association for Recorded Sound Collections Discographic Reference)
No match found for row 4717: THE EVASIVE NEUTRAL: GERMANY, BRITAIN AND THE QUEST FOR A TURKISH ALLIANCE IN THE SECOND WORLD WAR.
No match found for row 4722: Polish Solidarity Movement (Routledge Studies of Societies in Transition)
No match found for row 4745: The tales of Ivan Belkin (Classics of Russian literature)
No match found for row 4749: Over the Edge: The Growth of Homelessness in the 1980s
No match found for row 4790: Kaplan/Newsweek College Catalog 2002 (Unofficial, Unbiased Insider's Guide to the 360 Most Interesting Colleges)
No match found for row 4798: Racial Theories in Fascist Italy
No match found for row 4953: All Fall Down Pb (Big Books)
Processed 5000 rows...
No match found for row 5066: The boy apprenticed to an enchanter
No match found for row 5085: Hogans: Navajo Houses and House Songs (Wesleyan Poetry in Translation)
No match found for row 5118: How to Write a Research Report, Grades 3-6
No match found for row 5180: Reconstructing Yeats
No match found for row 5185: The Secret of Borges
No match found for row 5211: Knowledge Management and Organizational Design (Resources for the Knowledge-Based Economy)
No match found for row 5229: Elizabeth I: The Competition for Representation
No match found for row 5231: Princeton Review: Cracking the GMAT CAT, 2000 Edition
No match found for row 5242: Corvettes (High Performance)
No match found for row 5301: The Secret of Borges: A Psychoanalytic Inquiry into His Work
No match found for row 5314: Parent, Child, and Adolescent: Understanding and Care
No match found for row 5339: The Turret
No match found for row 5343: Buffalo Nickel
No match found for row 5353: Hijos De Dune/Children of Dune (Spanish Edition)
No match found for row 5360: Knowledge Management Tools (Resources for the Knowledge-Based Economy)
No match found for row 5423: Chicken Soup for Little Souls: A Dog of My Own (Chicken Soup for the Soul)
No match found for row 5460: Luann: Homework Is Ruining My Life
No match found for row 5476: Swansdowne
No match found for row 5517: Raising Real People: A Guide to Parents
No match found for row 5541: OF CABBAGES AND KINGS COUNTY: AGRICULTURE AND THE FORMATION OF MODERN BROOKLYN.
No match found for row 5560: Oil Sands Scientist: The Letters of Karl A. Clark, 1920-1949
No match found for row 5566: THE LECHEROUS UNIVERSITY: What Every Student and Parent Should Know About the Sexual Harassment Epidemic on Campus
No match found for row 5664: Step By Step Book About Iguanas
No match found for row 5667: The frogmen
No match found for row 5669: Cable Car Days in San Francisco
No match found for row 5689: Porsche Cayenne
No match found for row 5693: Comic Values Annual 1999 : Comic Books Price Guide
No match found for row 5718: Power Tools: An Electrifying Celebration and Grounded Guide
No match found for row 5800: Anthropology (Humanistic scholarship in America)
No match found for row 5843: Arco Suspension and Steeringfor Ase Test A4 (Chek-Chart's Ase Study Guides)
No match found for row 5856: YOU NEVER CAN TELL
No match found for row 5960: Literature: An Introduction to Reading and Writing
No match found for row 5992: The Cid, Cinna, the Theatrical Illusion
Processed 6000 rows...
No match found for row 6036: Higher Forces
No match found for row 6037: Arco Brakesfor Ase Test A5 (Chek-Chart's Ase Study Guides)
No match found for row 6071: Rama
No match found for row 6094: The law of obligations in the Louisiana jurisprudence: A coursebook
No match found for row 6163: Cars 1998 (Serial)
No match found for row 6258: Modern Parties (Modern)
No match found for row 6260: The House of the Arrow
No match found for row 6368: Arco Electrical and Electronic Systemsfor Ase Test A6 (Chek-Chart's Ase Study Guides)
No match found for row 6402: Loyalty and Betrayal: The Story of the American Mob
No match found for row 6475: Dante, Chaucer, and the Currency of the Word: Money, Images, and Reference in Late Medieval Poetry
No match found for row 6528: Wine of Morning
No match found for row 6559: Arco Heating and Air Conditioningfor Ase Test A7 (Chek-Chart's Ase Study Guides)
No match found for row 6659: Arco Engine Performancefor Ase Test A8 (Chek-Chart's Ase Study Guides)
No match found for row 6665: Strange & Unexplained Mysteries of the 20th Century
No match found for row 6691: Liquid Fire (Early American Literature and Culture Through the American Renaissance, 2)
No match found for row 6747: Through the Eyes of an Afghan Girl
No match found for row 6875: Introduction to Microsoft Windows NT Cluster Server: Programming and Administration
No match found for row 6893: Interchange Intro Student's Cassette B: English for International Communication
No match found for row 6900: Fundamentals of Codes, Graphs, and Iterative Decoding (The International Series in Engineering and Computer Science)
No match found for row 6952: Communication, Organization, and Performance (Contemporary Studies in Comm Culture Info)
No match found for row 6970: A Companion to The Grapes of Wrath
No match found for row 6982: Pointz Hall: The earlier and later typescripts of Between the acts
Processed 7000 rows...
No match found for row 7063: A German-English dictionary for chemists
No match found for row 7083: Pbs Straight Talk Stock Invest
No match found for row 7093: Shiphandling Simulation: Application to Waterway Design
No match found for row 7317: Common Information Model: Implementing the Object Model for Enterprise Management
No match found for row 7326: Curso Intensivo De Espanol Ejercicios Practicos (Spanish Edition)
No match found for row 7338: Turn Not Pale, Beloved Snail; A Book about Writing among Other Things.
No match found for row 7371: Kaplan AP World History 2004
No match found for row 7377: The Poetry of the Faerie Queene
No match found for row 7394: Little is the Light
No match found for row 7445: Life Row: A Case Study of How a Family Can Survive a Medical Crisis
No match found for row 7455: 103 Questions Children Ask about Right from Wrong (Questions Children Ask)
No match found for row 7513: Looking Good On The Web: Build Your Knowledge Base for Creating Professional, Compelling, and Well-Designed Web Sites
No match found for row 7538: Red Hat Linux System Administration Handbook
No match found for row 7548: SQL: Implmenting the SQL Foundation Standard
No match found for row 7557: Whitaker's Almanack 2004
No match found for row 7586: Getting Started With Sap R/3 (Prima Techs Sap Book Series)
No match found for row 7647: The Slovene Dialect of Resia: San Giorgio (Studies in Slavic and General Linguistics)
No match found for row 7673: Get Your IT Degree and Get Ahead
No match found for row 7687: Mastering Lotus Notes 4.6
No match found for row 7688: Petersburg: Out of the Trenches
No match found for row 7701: McSe Exam Notes: Windows 98 (McSe Exam Notes)
No match found for row 7707: Vascular plants of Ohio;: A manual for use in field and laboratory
No match found for row 7719: DIGITAL TRANSMISSION ENGINEERING
No match found for row 7763: Families of ancient New Haven
No match found for row 7778: Teaching Grammar of Thai
No match found for row 7793: Far Side of the Earth: Poems
No match found for row 7906: The life of Charles M. Doughty,
No match found for row 7933: Coming Out of the Classroom Closet: Gay and Lesbian Students, Teachers, and Curricula
No match found for row 7949: Flash for the Real World: E-Commerce Case Studies
No match found for row 7969: The Nursing Father: Moses as a Political Leader
No match found for row 7989: B East
No match found for row 7991: 30 for a Harry
Processed 8000 rows...
No match found for row 8052: Uncertainty
No match found for row 8076: Master Strokes: Pastel: A Step-By-Step Guide to Using the Techniques of the Masters
No match found for row 8098: Jewish Writers/Irish Writers: Selected Essays on the Love of Words
No match found for row 8248: Outspoken: Free Speech Stories
No match found for row 8270: The troublesome triangle: Mother-in-law, son, wife
No match found for row 8304: When Feeling Bad is Good
No match found for row 8316: Systems Programming for Windows 95 with Disk (Microsoft Progamming Series)
No match found for row 8361: Star Wars - Wraith Squadron (X-Wing , No 5)
No match found for row 8408: Italian Women Writing (Italian Texts)
No match found for row 8426: Capture a Shadow
No match found for row 8433: The Hole Is More Than the Sum of the Putts
No match found for row 8485: The Listening Silence
No match found for row 8503: Psychology for musicians,
No match found for row 8508: Face lifting by exercise
No match found for row 8525: Macho Marines: True Homosexual Military Stories, Volume 6
No match found for row 8567: Zip! pop! hop! and other fun words to say
No match found for row 8592: Animals' Christmas Carol (Merry Christmas!)
No match found for row 8695: Word Watch: The Stories Behind the Words of Our Lives (Henry Holt Reference Book)
No match found for row 8728: 200 Cigarettes -
No match found for row 8738: Everyday Creative Play: Simple Fun Things You Can Do to Help Your Preschooler Learn
No match found for row 8757: Travel and Travellers of the Middle Ages
No match found for row 8784: A background for beauty
No match found for row 8791: The Times Atlas of the World
No match found for row 8793: Interavia Space Directory, 1992-93 (Jane's Space Directory)
No match found for row 8805: Working Together: How Workplace Bonds Strengthen a Diverse Democracy
No match found for row 8848: INCOMMENSURABILITY, INCOMPARABILITY, AND PRACTICAL REASON
No match found for row 8876: Medieval Iberia: An Encyclopedia (Routledge Encyclopedias of the Middle Ages)
No match found for row 8918: Poor Toms Ghost
No match found for row 8922: Website Automation Toolkit
No match found for row 8974: Ace the Technical Job: Programming
Processed 9000 rows...
No match found for row 9031: Oracle8 Developer's Guide
No match found for row 9045: North Dakota
No match found for row 9181: Using Windows 98
No match found for row 9188: Nettravel: How Travelers Use the Internet (Songline Guides)
No match found for row 9195: Microsoft Sql Server Training: Hands-On, Self-Paced Training for Microsoft Sql Server Version 6.5
No match found for row 9328: Outcast Cape Town
No match found for row 9341: NetWare 5 CNE: Core Technologies Study Guide

In [8]:
books.to_csv('books_data_with_new_id.csv')

In [38]:
empty_rows_count = books['Id'].isnull().sum()
empty_rows_count

1

In [14]:
# Perform a left join on the Title column to only add matching Ids from the book_ratings to books
books_with_id = pd.merge(books, book_ratings[['Id', 'Title']], on='Title', how='left')

# Check if the merge worked correctly by examining the number of rows and inspecting the results
books_with_id_count = books_with_id.shape[0]
books_original_count = books.shape[0]

# Display the counts to understand if the operation was successful
books_with_unique_ids = books_with_id.drop_duplicates(subset=['Id'])
books_with_unique_ids
# Now, if everything is correct, display the first few rows to verify the matching
# books_with_id

,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount,Id
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN,1882931173
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN,0826414346
10,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,NaN,2000,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,['Religion'],NaN,0829814000
14,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,iUniverse,2005-02,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,['Fiction'],NaN,0595344550
46,"Nation Dance: Religion, Identity and Cultural ...",NaN,['Edward Long'],NaN,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,2003-03-01,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,NaN,0253338352
...,...,...,...,...,...,...,...,...,...,...,...
2999959,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",['Elvira Woodruff'],http://books.google.com/books/content?id=J7M-N...,http://books.google.com/books?id=J7M-NwAACAAJ&...,Scholastic Paperbacks,2000-06-01,http://books.google.com/books?id=J7M-NwAACAAJ&...,['Juvenile Fiction'],2.0,0590482467
2999987,Red Boots for Christmas,Everyone in the village of Friedensdorf is hap...,NaN,http://books.google.com/books/content?id=3n8k6...,http://books.google.com/books?id=3n8k6wl4BbYC&...,NaN,1995,http://books.google.com/books?id=3n8k6wl4BbYC&...,['Juvenile Fiction'],NaN,0570047870
2999989,Mamaw,"Give your Mamaw a useful, beautiful and though...",['Wild Wild Cabbage'],NaN,http://books.google.com/books?id=zytVswEACAAJ&...,NaN,2018-01-17,http://books.google.com/books?id=zytVswEACAAJ&...,NaN,NaN,B000OVF7JY
2999992,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,['Zadie Smith'],http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,Vintage,2003-08-12,https://play.google.com/store/books/details?id...,['Fiction'],19.0,1402508735
2999996,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",http://books.google.com/books/content?id=dehfP...,http://books.google.com/books?id=dehfPgAACAAJ&...,Brooks/Cole Publishing Company,1998-01-01,http://books.google.com/books?id=dehfPgAACAAJ&...,NaN,NaN,0534400604

In [66]:
wuthering_heights_ids = book_ratings[book_ratings['Title'] == 'Wuthering Heights']['Id'].unique()
wuthering_heights_ids

array(['1593355548'], dtype=object)

In [63]:
wuthering_heights_ids = book_ratings[book_ratings['Title'].str.contains('Wuthering Heights', case=False, na=False)]['Id'].unique()

wuthering_heights_ids

array(['0681410000', '0435126083', '0192822853', 'B0007HWKAO',
       '031206523X', 'B000FKPBMW', '1593355548', '0395051029',
       '0671777017', '0140860282', '1569602093', '1578152607',
       '0451519582', '0393957608', 'B0006BV6RY', 'B000FFQ85G',
       '0393964140', 'B000P4Q3JS', '0743261992', '0312212666',
       '0194230759', '0521597986'], dtype=object)

In [153]:
book_ratings

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...
...,...,...,...,...,...,...,...,...,...,...
2999990,B000NSLVCU,The Idea of History,NaN,AI1QNMVF2E3TN,"Robin George ""Master of Arts""",28/29,5.0,1057017600,R. G. Collingwood's Most Famous Book,Highly Recommended.This book is one of the bes...
2999994,B000NSLVCU,The Idea of History,NaN,AOFGOUMXLMVZS,"S. Grotzke ""scquest""",3/3,4.0,1342483200,Thoughtful Critic of History,History is not a scientific process of cutting...
2999996,B000NSLVCU,The Idea of History,NaN,A1SMUB9ASL5L9Y,jafrank,1/1,4.0,1331683200,Quite good and ahead of its time occasionally,This is pretty interesting. Collingwood seems ...
2999997,B000NSLVCU,The Idea of History,NaN,A2AQMEKZKK5EE4,"L. L. Poulos ""Muslim Mom""",0/0,4.0,1180224000,Easier reads of those not well versed in histo...,"This is a good book but very esoteric. ""What i..."
2999998,B000NSLVCU,The Idea of History,NaN,A18SQGYBKS852K,"Julia A. Klein ""knitting rat""",1/11,5.0,1163030400,"Yes, it is cheaper than the University Bookstore","My daughter, a freshman at Indiana University,..."

In [105]:
book_ratings = book_ratings.rename(columns={"User_id": "user_id", "Id": "item_id", "review/time": "timestamp"})

In [106]:
# random_ids = books['Id'].dropna().sample(1, random_state=54).tolist() random_ids = ['0134354575', '068199570X']

random_ids = ['0395051029']
book_titles = books[books['item_id'].isin(random_ids)][['item_id', 'Title']]
matched_titles = book_ratings[book_ratings['item_id'].isin(random_ids)][['item_id', 'Title']]
# Display the results
print("Randomly Selected Books from books_data.csv:")
print(book_titles)
print("\nMatched Titles from Books_rating.csv:")
print(matched_titles)

Randomly Selected Books from books_data.csv:
Empty DataFrame
Columns: [item_id, Title]
Index: []

Matched Titles from Books_rating.csv:
           item_id                                   Title
940955  0395051029  Wuthering Heights (Riverside editions)
940956  0395051029  Wuthering Heights (Riverside editions)
940957  0395051029  Wuthering Heights (Riverside editions)
940958  0395051029  Wuthering Heights (Riverside editions)
940959  0395051029  Wuthering Heights (Riverside editions)
...            ...                                     ...
942030  0395051029  Wuthering Heights (Riverside editions)
942031  0395051029  Wuthering Heights (Riverside editions)
942032  0395051029  Wuthering Heights (Riverside editions)
942033  0395051029  Wuthering Heights (Riverside editions)
942034  0395051029  Wuthering Heights (Riverside editions)

[1080 rows x 2 columns]

In [107]:
# Group by 'Title' and find titles associated with more than one unique ID
duplicate_titles = book_ratings.groupby('Title').filter(lambda x: x['item_id'].nunique() > 1)

# Display the results: Titles with more than one unique ID
duplicate_titles_sorted = duplicate_titles.sort_values(by='Title')

print("Books with the same title but different IDs:")
print(duplicate_titles_sorted[['item_id', 'Title']])

Books with the same title but different IDs:
Empty DataFrame
Columns: [item_id, Title]
Index: []

In [58]:
# Iterate over each title and set the same ID
for title in duplicate_titles['Title'].unique():
    # Get the unique IDs for the title
    ids = book_ratings.loc[book_ratings['Title'] == title, 'Id'].unique()

    # Choose one ID (for example, the first one)
    chosen_id = ids[0]

    # Update all rows with this title to have the same ID
    book_ratings.loc[book_ratings['Title'] == title, 'Id'] = chosen_id

# Display the modified DataFrame
print("Updated book_ratings with same IDs for duplicate titles:")
print(book_ratings[['Id', 'Title']].sort_values(by='Title'))

Updated book_ratings with same IDs for duplicate titles:
                 Id                                              Title
1664106  B0000CK3SI           " Film technique, " and, " Film acting "
1664107  B0000CK3SI           " Film technique, " and, " Film acting "
402728   B000K1C2HS  " We'll Always Have Paris": The Definitive Gui...
402729   B000K1C2HS  " We'll Always Have Paris": The Definitive Gui...
1604731  B000HEEPWS  "... And Poetry is Born ..." Russian Classical...
...             ...                                                ...
2826589  059528812X                                                NaN
2826590  059528812X                                                NaN
2826591  059528812X                                                NaN
2826592  059528812X                                                NaN
2826593  059528812X                                                NaN

[3000000 rows x 2 columns]

In [57]:
len(duplicate_titles_sorted)

627388

In [70]:
book_ratings

,Unnamed: 0,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...
...,...,...,...,...,...,...,...,...,...,...,...
2999995,2999995,B000NSLVCU,The Idea of History,NaN,NaN,NaN,14/19,4.0,937612800,Difficult,"This is an extremely difficult book to digest,..."
2999996,2999996,B000NSLVCU,The Idea of History,NaN,A1SMUB9ASL5L9Y,jafrank,1/1,4.0,1331683200,Quite good and ahead of its time occasionally,This is pretty interesting. Collingwood seems ...
2999997,2999997,B000NSLVCU,The Idea of History,NaN,A2AQMEKZKK5EE4,"L. L. Poulos ""Muslim Mom""",0/0,4.0,1180224000,Easier reads of those not well versed in histo...,"This is a good book but very esoteric. ""What i..."
2999998,2999998,B000NSLVCU,The Idea of History,NaN,A18SQGYBKS852K,"Julia A. Klein ""knitting rat""",1/11,5.0,1163030400,"Yes, it is cheaper than the University Bookstore","My daughter, a freshman at Indiana University,..."
2999999,2999999,B000NSLVCU,The Idea of History,NaN,NaN,NaN,7/49,1.0,905385600,Collingwood's ideas sink in a quagmire or verb...,"The guy has a few good ideas but, reader, bewa..."

In [3]:
merged_books = pd.merge(books, book_ratings[['Id', 'Title']], on='Title', how='left')

In [4]:
merged_books

,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount,Id
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN,1882931173
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN,0826414346
2,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN,0826414346
3,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN,0826414346
4,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN,0826414346
...,...,...,...,...,...,...,...,...,...,...,...
2999995,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,['Zadie Smith'],http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,Vintage,2003-08-12,https://play.google.com/store/books/details?id...,['Fiction'],19.0,1402508735
2999996,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",http://books.google.com/books/content?id=dehfP...,http://books.google.com/books?id=dehfPgAACAAJ&...,Brooks/Cole Publishing Company,1998-01-01,http://books.google.com/books?id=dehfPgAACAAJ&...,NaN,NaN,0534400604
2999997,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",http://books.google.com/books/content?id=dehfP...,http://books.google.com/books?id=dehfPgAACAAJ&...,Brooks/Cole Publishing Company,1998-01-01,http://books.google.com/books?id=dehfPgAACAAJ&...,NaN,NaN,0534400604
2999998,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",http://books.google.com/books/content?id=dehfP...,http://books.google.com/books?id=dehfPgAACAAJ&...,Brooks/Cole Publishing Company,1998-01-01,http://books.google.com/books?id=dehfPgAACAAJ&...,NaN,NaN,0534400604
2999999,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",http://books.google.com/books/content?id=dehfP...,http://books.google.com/books?id=dehfPgAACAAJ&...,Brooks/Cole Publishing Company,1998-01-01,http://books.google.com/books?id=dehfPgAACAAJ&...,NaN,NaN,0534400604

In [9]:
mismatches = []

for index, row in merged_books[100:1000].iterrows():
    book_id = row['Id']
    book_title = row['Title']

    # Find the corresponding row in the book_ratings dataset
    matching_row = book_ratings[book_ratings['Id'] == book_id]

    if not matching_row.empty:
        rating_title = matching_row['Title'].values[0]
        if rating_title != book_title:
            mismatches.append((book_id, book_title, rating_title))
    else:
        mismatches.append((book_id, book_title, "No matching Id in ratings"))
mismatches

[]

In [73]:
books = books.drop(columns=['image', 'previewLink', 'infoLink', 'ratingsCount'], errors='ignore')

In [2]:
book_ratings

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...
...,...,...,...,...,...,...,...,...,...,...
2999995,B000NSLVCU,The Idea of History,NaN,NaN,NaN,14/19,4.0,937612800,Difficult,"This is an extremely difficult book to digest,..."
2999996,B000NSLVCU,The Idea of History,NaN,A1SMUB9ASL5L9Y,jafrank,1/1,4.0,1331683200,Quite good and ahead of its time occasionally,This is pretty interesting. Collingwood seems ...
2999997,B000NSLVCU,The Idea of History,NaN,A2AQMEKZKK5EE4,"L. L. Poulos ""Muslim Mom""",0/0,4.0,1180224000,Easier reads of those not well versed in histo...,"This is a good book but very esoteric. ""What i..."
2999998,B000NSLVCU,The Idea of History,NaN,A18SQGYBKS852K,"Julia A. Klein ""knitting rat""",1/11,5.0,1163030400,"Yes, it is cheaper than the University Bookstore","My daughter, a freshman at Indiana University,..."
2999999,B000NSLVCU,The Idea of History,NaN,NaN,NaN,7/49,1.0,905385600,Collingwood's ideas sink in a quagmire or verb...,"The guy has a few good ideas but, reader, bewa..."

In [84]:
book_ratings = book_ratings.drop(columns=['Price', 'review/helpfulness', 'review/summary', 'review/text'], errors='ignore')
book_ratings = book_ratings.rename(columns={"User_id": "user_id", "Id": "item_id", "review/time": "timestamp"})

book_ratings = book_ratings.rename(columns={"User_id": "user_id", "Id": "item_id", "review/time": "timestamp"})
user_rating_counts = book_ratings['user_id'].value_counts()
users_to_keep = user_rating_counts[user_rating_counts >= 20].index
book_ratings = book_ratings[book_ratings['user_id'].isin(users_to_keep)]

book_ratings = book_ratings.sort_values(by='timestamp')

# Calculate sparsity
total_entries = book_ratings.shape[0]
unique_users = book_ratings['user_id'].nunique()
unique_items = book_ratings['item_id'].nunique()

from sklearn.model_selection import train_test_split

# Assuming `book_ratings` is already loaded and processed

# Create empty lists to store the split data
train_set = pd.DataFrame()
validation_set = pd.DataFrame()
test_set = pd.DataFrame()

# Group by 'user_id' and split each group
for user, group in book_ratings.groupby('user_id'):
    train, temp = train_test_split(group, test_size=0.2, random_state=42)
    validation, test = train_test_split(temp, test_size=0.5, random_state=42)

    # Append to the respective datasets
    train_set = pd.concat([train_set, train])
    validation_set = pd.concat([validation_set, validation])
    test_set = pd.concat([test_set, test])

# Reset index to ensure consistency
train_set = train_set.reset_index(drop=True)
validation_set = validation_set.reset_index(drop=True)
test_set = test_set.reset_index(drop=True)

# Display the sizes of the resulting datasets
print(f"Train set size: {train_set.shape[0]}")
print(f"Validation set size: {validation_set.shape[0]}")
print(f"Test set size: {test_set.shape[0]}")

train_set = train_set.sort_values(by='timestamp')
validation_set = validation_set.sort_values(by='timestamp')
test_set = test_set.sort_values(by='timestamp')

train_set.to_csv('amazon_books_ratings_train_fixed.csv')
validation_set.to_csv('amazon_books_ratings_val_fixed.csv')
test_set.to_csv('amazon_books_ratings_test_fixed.csv')

In [85]:
book_ratings

,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
2971446,2971446,B000G167FA,Silver Pennies,AZUNT3QP2CWTL,"Ellen C. Falkenberry ""ellenf""",5.0,-1
2006209,2006209,B00005O4HA,Playing for the Ashes,A3RTKL9KB8KLID,Stan Vernooy,5.0,840240000
2111966,2111966,B000PRURRE,Have Space Suit - Will Travel,A3PPXVR5J6U2JD,"Michael J. Tresca ""Talien""",5.0,850694400
1359864,1359864,0671536109,Star Trek Chronology: The History of the Future,A3PPXVR5J6U2JD,"Michael J. Tresca ""Talien""",5.0,850694400
100284,100284,B0001BJEG4,"Have Space Suit, Will Travel",A3PPXVR5J6U2JD,"Michael J. Tresca ""Talien""",5.0,850694400
...,...,...,...,...,...,...,...
367885,367885,0435126075,Pride & Prejudice (New Windmill),A2FC4THFBC4UNQ,tara,5.0,1362268800
367887,367887,0435126075,Pride & Prejudice (New Windmill),A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800
2283029,2283029,1844560333,Pride and Prejudice,A2FC4THFBC4UNQ,tara,5.0,1362268800
960832,960832,1850891648,Frankenstein (Isis Large Print Fiction),A1584OSWVF80GN,John Romero,5.0,1362268800
354477,354477,0451519329,Great Expectations (Signet classics),A1584OSWVF80GN,John Romero,5.0,1362268800

In [27]:
sparsity = (total_entries / (unique_users * unique_items)) * 100

# Prepare the results
results = {
    "Sparsity (%)": sparsity,
    "Number of unique users": unique_users,
    "Number of unique items": unique_items
}

In [28]:
results

{'Sparsity (%)': 0.05589557465749259,
 'Number of unique users': 9745,
 'Number of unique items': 100630}

Train set size: 434634
Validation set size: 54153
Test set size: 59347

In [51]:
user_id_to_check = 'A2ULDDL3MLJPUR'
train_count_all_users = train_set['user_id'].value_counts()
validation_count_all_users = validation_set['user_id'].value_counts()
test_count_all_users = test_set['user_id'].value_counts()

train_count = train_count_all_users.get(user_id_to_check, 0)
validation_count = validation_count_all_users.get(user_id_to_check, 0)
test_count = test_count_all_users.get(user_id_to_check, 0)

(train_count, validation_count, test_count)

(20, 2, 3)

In [57]:
books

,Title,description,authors,publisher,publishedDate,categories
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],NaN,1996,['Comics & Graphic Novels']
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],A&C Black,2005-01-01,['Biography & Autobiography']
2,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],NaN,2000,['Religion']
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],iUniverse,2005-02,['Fiction']
4,"Nation Dance: Religion, Identity and Cultural ...",NaN,['Edward Long'],NaN,2003-03-01,NaN
...,...,...,...,...,...,...
212399,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",['Elvira Woodruff'],Scholastic Paperbacks,2000-06-01,['Juvenile Fiction']
212400,Red Boots for Christmas,Everyone in the village of Friedensdorf is hap...,NaN,NaN,1995,['Juvenile Fiction']
212401,Mamaw,"Give your Mamaw a useful, beautiful and though...",['Wild Wild Cabbage'],NaN,2018-01-17,NaN
212402,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,['Zadie Smith'],Vintage,2003-08-12,['Fiction']
212403,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",Brooks/Cole Publishing Company,1998-01-01,NaN

In [82]:
book_ratings = book_ratings.drop(columns=['Price', 'review/helpfulness', 'review/text', 'review/summary'], errors='ignore')
book_ratings = book_ratings.rename(columns={"review/score": "rating", "title": "Title", "review/time": "timestamp"})

In [48]:
train_set = train_set.drop(columns=['Price', 'review/helpfulness', 'review/text', 'review/summary'], errors='ignore')
train_set = train_set.rename(columns={"review/score": "rating", "Title": "title", "review/time": "timestamp"})

validation_set = validation_set.drop(columns=['Price', 'review/helpfulness', 'review/text', 'review/summary'], errors='ignore')
validation_set = validation_set.rename(columns={"review/score": "rating", "Title": "title", "review/time": "timestamp"})

test_set = test_set.drop(columns=['Price', 'review/helpfulness', 'review/text', 'review/summary'], errors='ignore')
test_set = test_set.rename(columns={"review/score": "rating", "Title": "title", "review/time": "timestamp"})

In [93]:
train_set

,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
434301,2971446,B000G167FA,Silver Pennies,AZUNT3QP2CWTL,"Ellen C. Falkenberry ""ellenf""",5.0,-1
312424,1359864,0671536109,Star Trek Chronology: The History of the Future,A3PPXVR5J6U2JD,"Michael J. Tresca ""Talien""",5.0,850694400
312430,1655665,B000P9X16G,The I Inside,A3PPXVR5J6U2JD,"Michael J. Tresca ""Talien""",5.0,850694400
312427,100284,B0001BJEG4,"Have Space Suit, Will Travel",A3PPXVR5J6U2JD,"Michael J. Tresca ""Talien""",5.0,850694400
312431,2152629,B0007G24HY,"A dictionary of angels,: Including the fallen ...",A3PPXVR5J6U2JD,"Michael J. Tresca ""Talien""",5.0,850780800
...,...,...,...,...,...,...,...
172844,1343380,1569602093,Wuthering Heights.,A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800
172843,2092962,1593355548,Wuthering Heights,A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800
172842,861843,1593355548,Wuthering Heights,A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800
110131,77979,0972311602,Assault on the Liberty,A1VYAN8RO7ZUEX,"john thames ""scholar1""",5.0,1362268800
55936,2461010,081613751X,The Neverending Story,A1G0DH7UQ4ILS6,Daniel Estes,4.0,1362268800

In [94]:
train_set.to_csv('amazon_books_ratings_train_fixed.csv')
validation_set.to_csv('amazon_books_ratings_val_fixed.csv')
test_set.to_csv('amazon_books_ratings_test_fixed.csv')

In [68]:
book_ratings.to_csv('amazon_books_ratings_full_fixed.csv')

In [76]:
book_ratings['Title'] = book_ratings['Title'].str.lower().str.strip()
books['Title'] = books['Title'].str.lower().str.strip()

In [78]:
merged_df = pd.merge(books, book_ratings[['Id', 'Title']], on='Title', how='left')

In [79]:
merged_df.rename(columns={'id': 'bookId'}, inplace=True)

In [80]:
merged_df

,Title,description,authors,publisher,publishedDate,categories,Id
0,its only art if its well hung!,NaN,['Julie Strain'],NaN,1996,['Comics & Graphic Novels'],1882931173
1,dr. seuss: american icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],A&C Black,2005-01-01,['Biography & Autobiography'],0826414346
2,dr. seuss: american icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],A&C Black,2005-01-01,['Biography & Autobiography'],0826414346
3,dr. seuss: american icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],A&C Black,2005-01-01,['Biography & Autobiography'],0826414346
4,dr. seuss: american icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],A&C Black,2005-01-01,['Biography & Autobiography'],0826414346
...,...,...,...,...,...,...,...
3320448,the autograph man,Alex-Li Tandem sells autographs. His business ...,['Zadie Smith'],Vintage,2003-08-12,['Fiction'],1402508735
3320449,student's solutions manual for johnson/mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",Brooks/Cole Publishing Company,1998-01-01,NaN,0534400604
3320450,student's solutions manual for johnson/mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",Brooks/Cole Publishing Company,1998-01-01,NaN,0534400604
3320451,student's solutions manual for johnson/mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",Brooks/Cole Publishing Company,1998-01-01,NaN,0534400604
3320452,student's solutions manual for johnson/mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",Brooks/Cole Publishing Company,1998-01-01,NaN,0534400604

In [83]:
empty_ids = merged_df[merged_df['Id'].isna()]

# Display the rows with empty bookId
print("Rows with empty bookId:")
print(empty_ids)
# Alternatively, display the count of rows with empty bookId
empty_count = empty_ids.shape[0]
print(f"\nNumber of rows with empty bookId: {empty_count}")

Rows with empty bookId:
Empty DataFrame
Columns: [Title, description, authors, publisher, publishedDate, categories, Id]
Index: []

Number of rows with empty bookId: 0

In [ ]:
# Merge the datasets on 'bookId' to compare the titles
merged_check_df = pd.merge(book_ratings[['Id', 'Title']],
                           merged_df[['Id', 'Title']],
                           left_on='Id', right_on='Id',
                           how='inner')

# Find mismatches where titles don't match for the same bookId
mismatches = merged_check_df[merged_check_df['Title_x'] != merged_check_df['Title_y']]

# Count the number of mismatches
mismatch_count = mismatches.shape[0]
print(f"Number of mismatches: {mismatch_count}")

# Optionally, display the mismatches
print("\nMismatched Titles:")
print(mismatches[['bookId', 'Title_x', 'Title_y']])

In [1]:
import pandas as pd
items = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/books_data_with_new_id.csv')
# movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens.csv')

full_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_full_filtered_fixed.csv')
train_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_train_filtered_fixed.csv')
val_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_val_filtered_fixed.csv')
test_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_test_filtered_fixed.csv')

In [3]:
# Binarize the 'rating' column
def binarize_ratings(df):
    df['rating'] = df['rating'].apply(lambda x: 0 if x < 3 else 1)
    return df

# Apply binarization
full_ratings = binarize_ratings(full_ratings)
train_ratings = binarize_ratings(train_ratings)
val_ratings = binarize_ratings(val_ratings)
test_ratings = binarize_ratings(test_ratings)

In [8]:
full_ratings.to_csv('amazon_books_ratings_full_filtered_fixed_binarized.csv')
train_ratings.to_csv('amazon_books_ratings_train_fixed_binarized.csv')
val_ratings.to_csv('amazon_books_ratings_val_fixed_binarized.csv')
test_ratings.to_csv('amazon_books_ratings_test_fixed_binarized.csv')

In [7]:
train_ratings

,Unnamed: 0.1,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp
0,192634,2808945,B000NWR0W6,and ladies of the club,A3RTKL9KB8KLID,Stan Vernooy,1,854150400
1,192637,2144019,B000MVVYNO,Bethlehem Road,A3RTKL9KB8KLID,Stan Vernooy,1,862358400
2,195879,2520883,B000HEV3WS,"HERCULES, MY SHIPMATE",A3TEH90X39WC8F,"Stuart W. Mirsky ""swm""",1,863308800
3,195797,2196179,B0007E212E,"Hercules, My Shipmate",A3TEH90X39WC8F,"Stuart W. Mirsky ""swm""",1,863308800
4,238620,346828,B000KISQC6,"Guns, Germs, and Steel: The Fates of Human Soc...",AMGVCPHMT1DWE,Gregory N. Hullender,1,865468800
...,...,...,...,...,...,...,...,...
262291,96431,1558301,1593355548,Wuthering Heights,A2DKTZMMG3JHN4,K. Burns,1,1362268800
262292,96428,1343379,1569602093,Wuthering Heights.,A2DKTZMMG3JHN4,K. Burns,1,1362268800
262293,96420,861842,1593355548,Wuthering Heights,A2DKTZMMG3JHN4,K. Burns,1,1362268800
262294,103760,2616778,1844560333,Pride and Prejudice,A2GDT5QQSFZD14,Joy Hilda Handley,1,1362268800
262295,103763,637896,8188280046,Pride & Prejudice (Classic Library),A2GDT5QQSFZD14,Joy Hilda Handley,1,1362268800

In [10]:
import pandas as pd
book_ratings = pd.read_csv('processed_dataset/Amazon-Books/original (not edited at all)/books_data.csv')

In [7]:
# Calculate the number of unique users and unique books
unique_users = book_ratings['User_id'].nunique()
unique_books = book_ratings['Id'].nunique()

# Calculate the total number of possible user-book interactions
total_possible_interactions = unique_users * unique_books

# Calculate the number of non-zero interactions (actual ratings)
non_zero_interactions = len(book_ratings)

# Calculate sparsity as the ratio of missing interactions to total interactions
sparsity = 1 - (non_zero_interactions / total_possible_interactions)

unique_users,unique_books, sparsity

(1008972, 221998, 0.9999866065309464)

In [11]:
book_ratings

,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
2,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,NaN,2000,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,['Religion'],NaN
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,iUniverse,2005-02,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,['Fiction'],NaN
4,"Nation Dance: Religion, Identity and Cultural ...",NaN,['Edward Long'],NaN,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,2003-03-01,http://books.google.nl/books?id=399SPgAACAAJ&d...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
212399,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",['Elvira Woodruff'],http://books.google.com/books/content?id=J7M-N...,http://books.google.com/books?id=J7M-NwAACAAJ&...,Scholastic Paperbacks,2000-06-01,http://books.google.com/books?id=J7M-NwAACAAJ&...,['Juvenile Fiction'],2.0
212400,Red Boots for Christmas,Everyone in the village of Friedensdorf is hap...,NaN,http://books.google.com/books/content?id=3n8k6...,http://books.google.com/books?id=3n8k6wl4BbYC&...,NaN,1995,http://books.google.com/books?id=3n8k6wl4BbYC&...,['Juvenile Fiction'],NaN
212401,Mamaw,"Give your Mamaw a useful, beautiful and though...",['Wild Wild Cabbage'],NaN,http://books.google.com/books?id=zytVswEACAAJ&...,NaN,2018-01-17,http://books.google.com/books?id=zytVswEACAAJ&...,NaN,NaN
212402,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,['Zadie Smith'],http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,Vintage,2003-08-12,https://play.google.com/store/books/details?id...,['Fiction'],19.0
212403,Student's Solutions Manual for Johnson/Mowry's...,Discover the many ways mathematics is relevant...,"['David B. Johnson', 'Thomas A. Mowry']",http://books.google.com/books/content?id=dehfP...,http://books.google.com/books?id=dehfPgAACAAJ&...,Brooks/Cole Publishing Company,1998-01-01,http://books.google.com/books?id=dehfPgAACAAJ&...,NaN,NaN

In [25]:

import pandas as pd
from libreco.data import DatasetPure
from libreco.algorithms import UserCF

train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_traindata_movielens.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_valdata_movielens.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_testdata_movielens.csv')

movies = pd.read_csv('./processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')
users = pd.read_csv('./processed_dataset/MovieLens-1M/users/users_movielens.csv')

train_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'},
                     inplace=True)
val_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
test_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'},
                    inplace=True)

train_data, data_info = DatasetPure.build_trainset(train_ratings)
eval_data = DatasetPure.build_evalset(val_ratings)
test_data = DatasetPure.build_testset(test_ratings)

train_ratings = train_ratings.sort_values(by='time')
val_ratings = val_ratings.sort_values(by='time')
test_ratings = test_ratings.sort_values(by='time')

user_cf = UserCF(task="ranking", data_info=data_info, k_sim=20, sim_type="cosine", mode='invert')

user_cf.fit(train_data, verbose=2, eval_data=eval_data, k=5,
            metrics=["loss", "roc_auc", "precision", "recall", "ndcg"], neg_sampling=True)

Training start time: 2025-02-01 12:44:50
Final block size and num: (6040, 1)
sim_matrix elapsed: 3.741s
sim_matrix, shape: (6040, 6040), num_elements: 33103268, density: 90.7396 %

top_k: 100%|██████████| 6040/6040 [00:07<00:00, 795.18it/s]
eval_pointwise:   0%|          | 0/25 [00:00<?, ?it/s]

Detect 1 unknown interaction(s), position: [5602]
No common interaction or similar neighbor for user 0 and item 91, proceed with default prediction
No common interaction or similar neighbor for user 0 and item 818, proceed with default prediction
No common interaction or similar neighbor for user 0 and item 2700, proceed with default prediction
No common interaction or similar neighbor for user 1 and item 2481, proceed with default prediction
No common interaction or similar neighbor for user 1 and item 3271, proceed with default prediction
No common interaction or similar neighbor for user 1 and item 1547, proceed with default prediction

eval_pointwise:   4%|▍         | 1/25 [00:00<00:05,  4.27it/s]

Detect 1 unknown interaction(s), position: [5320]

eval_pointwise:   8%|▊         | 2/25 [00:00<00:05,  4.22it/s]

Detect 2 unknown interaction(s), position: [6104, 4798]

eval_pointwise:  20%|██        | 5/25 [00:01<00:04,  4.35it/s]

Detect 4 unknown interaction(s), position: [7664, 3522, 7728, 7722]

eval_pointwise:  24%|██▍       | 6/25 [00:01<00:04,  4.40it/s]

Detect 1 unknown interaction(s), position: [4480]

eval_pointwise:  32%|███▏      | 8/25 [00:01<00:03,  4.37it/s]

Detect 1 unknown interaction(s), position: [6206]

eval_pointwise:  36%|███▌      | 9/25 [00:02<00:03,  4.40it/s]

Detect 1 unknown interaction(s), position: [4080]

eval_pointwise:  48%|████▊     | 12/25 [00:02<00:03,  4.29it/s]

Detect 1 unknown interaction(s), position: [1426]

eval_pointwise:  60%|██████    | 15/25 [00:03<00:02,  4.33it/s]

Detect 1 unknown interaction(s), position: [4530]

eval_pointwise:  64%|██████▍   | 16/25 [00:03<00:02,  4.36it/s]

Detect 2 unknown interaction(s), position: [8026, 7654]

eval_pointwise:  68%|██████▊   | 17/25 [00:03<00:01,  4.39it/s]

Detect 2 unknown interaction(s), position: [1280, 3058]

eval_pointwise:  84%|████████▍ | 21/25 [00:04<00:00,  4.41it/s]

Detect 1 unknown interaction(s), position: [3300]

eval_pointwise: 100%|██████████| 25/25 [00:05<00:00,  4.47it/s]
eval_listwise: 100%|██████████| 2997/2997 [00:36<00:00, 81.34it/s]

	 eval log_loss: 7.6579
	 eval roc_auc: 0.6702
	 eval precision@5: 0.0699
	 eval recall@5: 0.0463
	 eval ndcg@5: 0.1665
==============================

In [26]:
def CFGenerator(user_id):
    k=10
    user_id = int(user_id)
    # Check if user_id exists in the users dataframe
    # if user_id not in users["user_id"].values:
    #     return [f"User ID {user_id} does not exist in the database."]

    recommended_items = user_cf.recommend_user(user_id, n_rec=k, filter_consumed=True)
    movie_ids = recommended_items[user_id]
    movie_titles = []
    for movie_id in movie_ids:
        title_row = movies[movies["item_id"] == movie_id]
        if not title_row.empty:
            movie_titles.append(title_row["title"].values[0])
        else:
            movie_titles.append(f"Unknown Movie ID: {movie_id}")

    # Add ranks to the movie titles with proper newline formatting
    movie_titles_string = "\n".join([f"{i + 1}. {title}" for i, title in enumerate(movie_titles)])
    return movie_titles_string

In [27]:
CFGenerator(234234)

Detect unknown user: 234234

'1. Back to the Future\n2. As Good As It Gets\n3. Star Trek: The Wrath of Khan\n4. Godfather: Part II, The\n5. Godfather: Part II, The\n6. Arachnophobia\n7. Back to the Future\n8. Clerks\n9. Being John Malkovich\n10. Raiders of the Lost Ark'

In [28]:
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_traindata_movielens.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_valdata_movielens.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_testdata_movielens.csv')

In [32]:
import pandas as pd
import numpy as np
from sklearn.metrics import ndcg_score

# Load training and test datasets
# train_ratings = pd.read_csv('./datasets/ml_1m_train_movielens.csv')
# test_ratings = pd.read_csv('./datasets/ml_1m_test_movielens.csv')

# Identify Cold Start Users (Users in test but not in train)
cold_start_users = set(test_ratings['user_id']) - set(train_ratings['user_id'])
cold_start_items = set(test_ratings['item_id']) - set(train_ratings['item_id'])

cold_start_user_ratio = len(cold_start_users) / len(set(test_ratings['user_id']))
cold_start_item_ratio = len(cold_start_items) / len(set(test_ratings['item_id']))

print(f"Cold Start User Ratio: {cold_start_user_ratio:.2%}")
print(f"Cold Start Item Ratio: {cold_start_item_ratio:.2%}")

# Evaluate NDCG for Cold Start Users
def compute_ndcg_for_cold_start(model, test_data, k=5):
    print(cold_start_users)
    cold_users = test_data[test_data['user_id'].isin(cold_start_users)]
    y_true = cold_users.groupby('user_id')['rating'].apply(lambda x: list(x)).tolist()

    y_pred = []
    for user in cold_start_users:
        print(user)
        recs = model.recommend_user(user, n_rec=k)
        y_pred.append([1 if item in recs else 0 for item in cold_users[cold_users['user_id'] == user]['item_id']])

    return np.mean([ndcg_score([true], [pred]) for true, pred in zip(y_true, y_pred)])

# Assuming `user_cf` is your trained model
ndcg_cold = compute_ndcg_for_cold_start(user_cf, test_ratings, k=5)
print(f"NDCG@5 for Cold Users: {ndcg_cold:.4f}")

Cold Start User Ratio: 0.00%
Cold Start Item Ratio: 0.78%
set()
NDCG@5 for Cold Users: nan

D:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\Anaconda\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [1]:
import pandas as pd
import numpy as np
from libreco.data import DatasetPure
from libreco.algorithms import UserCF

# Load datasets
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_traindata_movielens.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_valdata_movielens.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_testdata_movielens.csv')

movies = pd.read_csv('./processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')
users = pd.read_csv('./processed_dataset/MovieLens-1M/users/users_movielens.csv')

# Rename columns for consistency
rename_map = {'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}
train_ratings.rename(columns=rename_map, inplace=True)
val_ratings.rename(columns=rename_map, inplace=True)
test_ratings.rename(columns=rename_map, inplace=True)

# Sort by timestamp BEFORE training
train_ratings = train_ratings.sort_values(by='time')
val_ratings = val_ratings.sort_values(by='time')
test_ratings = test_ratings.sort_values(by='time')

# Build datasets
train_data, data_info = DatasetPure.build_trainset(train_ratings)
eval_data = DatasetPure.build_evalset(val_ratings)
test_data = DatasetPure.build_testset(test_ratings)

# Train UserCF model
user_cf = UserCF(task="ranking", data_info=data_info, k_sim=20, sim_type="cosine", mode='invert')

user_cf.fit(train_data, verbose=2, eval_data=eval_data, k=5,
            metrics=["loss", "roc_auc", "precision", "recall", "ndcg"], neg_sampling=True)

WARNING:tensorflow:From D:\Anaconda\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Training start time: 2025-02-06 04:38:00
Final block size and num: (6040, 1)
sim_matrix elapsed: 2.771s
sim_matrix, shape: (6040, 6040), num_elements: 33103268, density: 90.7396 %

top_k: 100%|██████████| 6040/6040 [00:07<00:00, 788.61it/s]
eval_pointwise:   0%|          | 0/25 [00:00<?, ?it/s]

No common interaction or similar neighbor for user 6038 and item 1108, proceed with default prediction
No common interaction or similar neighbor for user 6038 and item 91, proceed with default prediction
No common interaction or similar neighbor for user 6038 and item 830, proceed with default prediction
No common interaction or similar neighbor for user 6038 and item 818, proceed with default prediction
No common interaction or similar neighbor for user 6038 and item 831, proceed with default prediction
No common interaction or similar neighbor for user 6038 and item 2700, proceed with default prediction

eval_pointwise:   8%|▊         | 2/25 [00:00<00:05,  4.05it/s]

Detect 1 unknown interaction(s), position: [1320]

eval_pointwise:  20%|██        | 5/25 [00:01<00:04,  4.31it/s]

Detect 1 unknown interaction(s), position: [3088]

eval_pointwise:  36%|███▌      | 9/25 [00:02<00:03,  4.43it/s]

Detect 1 unknown interaction(s), position: [6306]

eval_pointwise:  48%|████▊     | 12/25 [00:02<00:03,  4.33it/s]

Detect 2 unknown interaction(s), position: [1266, 5038]

eval_pointwise:  52%|█████▏    | 13/25 [00:03<00:02,  4.33it/s]

Detect 1 unknown interaction(s), position: [3492]

eval_pointwise:  56%|█████▌    | 14/25 [00:03<00:02,  4.31it/s]

Detect 3 unknown interaction(s), position: [7498, 7420, 7502]

eval_pointwise:  64%|██████▍   | 16/25 [00:03<00:02,  4.36it/s]

Detect 1 unknown interaction(s), position: [3712]

eval_pointwise:  72%|███████▏  | 18/25 [00:04<00:01,  4.37it/s]

Detect 1 unknown interaction(s), position: [2030]

eval_pointwise:  76%|███████▌  | 19/25 [00:04<00:01,  4.37it/s]

Detect 1 unknown interaction(s), position: [5664]

eval_pointwise:  80%|████████  | 20/25 [00:04<00:01,  4.35it/s]

Detect 2 unknown interaction(s), position: [890, 7706]

eval_pointwise:  84%|████████▍ | 21/25 [00:04<00:00,  4.36it/s]

Detect 1 unknown interaction(s), position: [710]

eval_pointwise:  92%|█████████▏| 23/25 [00:05<00:00,  4.40it/s]

Detect 3 unknown interaction(s), position: [6312, 2514, 8140]

eval_pointwise: 100%|██████████| 25/25 [00:05<00:00,  4.47it/s]
eval_listwise:  67%|██████▋   | 2020/2997 [00:23<00:11, 84.60it/s]

KeyboardInterrupt:

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the full dataset
ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_fulldata_movielens.csv')

# Get unique users
unique_users = ratings['user_id'].unique()

# Define percentage of cold-start users (e.g., 10% of users)
cold_start_ratio = 0.1
num_cold_start_users = int(len(unique_users) * cold_start_ratio)

# Randomly select cold-start users
cold_start_users = np.random.choice(unique_users, num_cold_start_users, replace=False)

# Split data
train_data = ratings[~ratings['user_id'].isin(cold_start_users)]
test_data = ratings[ratings['user_id'].isin(cold_start_users)]

# Save datasets
train_data.to_csv("train_data.csv", index=False)
test_data.to_csv("test_data.csv", index=False)

print(f"Cold start users: {len(cold_start_users)}")
print(f"Train set size: {len(train_data)}, Test set size: {len(test_data)}")

Cold start users: 604
Train set size: 904286, Test set size: 95923

In [3]:
import pandas as pd
import numpy as np

# Load dataset
ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_fulldata_movielens.csv')

# Get unique users
unique_users = ratings['user_id'].unique()

# Set split ratios
cold_start_ratio = 0.1  # 10% of users for cold start (test only)
val_ratio = 0.1         # 10% of users for validation
train_ratio = 0.8       # 80% of users for training

# Shuffle user IDs for randomness
np.random.seed(42)  # Ensure reproducibility
np.random.shuffle(unique_users)

# Split users
num_users = len(unique_users)
num_cold_start_users = int(num_users * cold_start_ratio)
num_val_users = int(num_users * val_ratio)

cold_start_users = unique_users[:num_cold_start_users]
val_users = unique_users[num_cold_start_users:num_cold_start_users + num_val_users]
train_users = unique_users[num_cold_start_users + num_val_users:]

# Create datasets
train_data = ratings[ratings['user_id'].isin(train_users)]
val_data = ratings[ratings['user_id'].isin(val_users)]
test_data = ratings[ratings['user_id'].isin(cold_start_users)]

# Save datasets
train_data.to_csv("train_data.csv", index=False)
val_data.to_csv("val_data.csv", index=False)
test_data.to_csv("test_data.csv", index=False)

print(f"Cold start users (Test only): {len(cold_start_users)}")
print(f"Train users: {len(train_users)}, Validation users: {len(val_users)}")
print(f"Train set size: {len(train_data)}, Validation set size: {len(val_data)}, Test set size: {len(test_data)}")

Cold start users (Test only): 604
Train users: 4832, Validation users: 604
Train set size: 799785, Validation set size: 97810, Test set size: 102614

In [8]:
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/train_data.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/val_data.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/test_data.csv')

# print(f"Cold start users (Test only): {len(cold_start_users)}")
print(f"Train users: {len(train_users)}, Validation users: {len(val_users)}")
print(f"Train set size: {len(train_data)}, Validation set size: {len(val_data)}, Test set size: {len(test_data)}")

Train users: 4832, Validation users: 604
Train set size: 799785, Validation set size: 97810, Test set size: 102614

In [85]:
import pandas as pd
import numpy as np
from libreco.data import DatasetPure
from libreco.algorithms import UserCF

# ======= Load Data =======
full_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_fulldata_movielens.csv')
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/train_data.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/val_data.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/test_data.csv')

movies = pd.read_csv('./processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')
users = pd.read_csv('processed_dataset/MovieLens-1M/users/users_movielens.csv')

# ======= Preprocess Data =======
# Rename columns to match Libreco format
train_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
val_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)
test_ratings.rename(columns={'user_id': 'user', 'item_id': 'item', 'rating': 'label', 'timestamp': 'time'}, inplace=True)

# Sort data by timestamp (helps in time-aware splitting)
train_ratings = train_ratings.sort_values(by='time')
val_ratings = val_ratings.sort_values(by='time')
test_ratings = test_ratings.sort_values(by='time')

# ======= Convert Data to Libreco Format =======
train_data, data_info = DatasetPure.build_trainset(train_ratings)
eval_data = DatasetPure.build_evalset(val_ratings)
test_data = DatasetPure.build_testset(test_ratings)

# ======= Train User-based Collaborative Filtering Model =======
user_cf = UserCF(task="ranking", data_info=data_info, k_sim=20, sim_type="cosine", mode='invert')

user_cf.fit(
    train_data, verbose=2, eval_data=eval_data, k=5,
    metrics=["loss", "roc_auc", "precision", "recall", "ndcg"],
    neg_sampling=True
)

Training start time: 2025-02-06 11:17:40
Final block size and num: (4832, 1)
sim_matrix elapsed: 2.462s
sim_matrix, shape: (4832, 4832), num_elements: 21913848, density: 93.8566 %

top_k: 100%|██████████| 4832/4832 [00:06<00:00, 724.70it/s]
eval_pointwise: 100%|██████████| 24/24 [00:00<00:00, 143.01it/s]

Detect 8192 unknown interaction(s), position: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2815, 2816, 2817, 2818, 2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2908, 2909, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2979, 2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2994, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278, 3279, 3280, 3281, 3282, 3283, 3284, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 3318, 3319, 3320, 3321, 3322, 3323, 3324, 3325, 3326, 3327, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3342, 3343, 3344, 3345, 3346, 3347, 3348, 3349, 3350, 3351, 3352, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3393, 3394, 3395, 3396, 3397, 3398, 3399, 3400, 3401, 3402, 3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3482, 3483, 3484, 3485, 3486, 3487, 3488, 3489, 3490, 3491, 3492, 3493, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, 3503, 3504, 3505, 3506, 3507, 3508, 3509, 351

eval_listwise: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]

	 eval log_loss: 18.0218
	 eval roc_auc: 0.5000
	 eval precision@5: 0.8000
	 eval recall@5: 0.0013
	 eval ndcg@5: 1.0000
==============================

In [86]:
# ======= Identify Cold-Start Users =======
cold_start_users = set(test_ratings['user']) - set(train_ratings['user'])
print(f"Number of Cold-Start Users: {len(cold_start_users)}")

Number of Cold-Start Users: 604

In [87]:

# ======= Generate Recommendations for Cold-Start Users =======
final_recommendations = {}

for user_id in cold_start_users:
    final_recommendations[user_id] = user_cf.recommend_user(user_id, n_rec=10, filter_consumed=True)[user_id]

Detect unknown user: 2
Detect unknown user: 5
Detect unknown user: 2054
Detect unknown user: 4114
Detect unknown user: 27
Detect unknown user: 4124
Detect unknown user: 29
Detect unknown user: 4128
Detect unknown user: 35
Detect unknown user: 38
Detect unknown user: 2087
Detect unknown user: 50
Detect unknown user: 4147
Detect unknown user: 4148
Detect unknown user: 4149
Detect unknown user: 57
Detect unknown user: 4155
Detect unknown user: 2107
Detect unknown user: 2110
Detect unknown user: 63
Detect unknown user: 4162
Detect unknown user: 4164
Detect unknown user: 4165
Detect unknown user: 69
Detect unknown user: 72
Detect unknown user: 4185
Detect unknown user: 90
Detect unknown user: 2139
Detect unknown user: 2140
Detect unknown user: 2149
Detect unknown user: 4199
Detect unknown user: 4203
Detect unknown user: 2156
Detect unknown user: 2155
Detect unknown user: 2164
Detect unknown user: 2165
Detect unknown user: 4214
Detect unknown user: 123
Detect unknown user: 4223
Detect unknown user: 2176
Detect unknown user: 2177
Detect unknown user: 130
Detect unknown user: 2186
Detect unknown user: 2190
Detect unknown user: 142
Detect unknown user: 2204
Detect unknown user: 156
Detect unknown user: 4259
Detect unknown user: 163
Detect unknown user: 4266
Detect unknown user: 4274
Detect unknown user: 182
Detect unknown user: 192
Detect unknown user: 2242
Detect unknown user: 201
Detect unknown user: 4298
Detect unknown user: 2251
Detect unknown user: 4301
Detect unknown user: 4302
Detect unknown user: 2257
Detect unknown user: 4306
Detect unknown user: 4310
Detect unknown user: 214
Detect unknown user: 2264
Detect unknown user: 219
Detect unknown user: 4319
Detect unknown user: 2273
Detect unknown user: 230
Detect unknown user: 2284
Detect unknown user: 4333
Detect unknown user: 2286
Detect unknown user: 4340
Detect unknown user: 2295
Detect unknown user: 248
Detect unknown user: 249
Detect unknown user: 4344
Detect unknown user: 4345
Detect unknown user: 2310
Detect unknown user: 262
Detect unknown user: 4367
Detect unknown user: 4368
Detect unknown user: 2320
Detect unknown user: 4370
Detect unknown user: 2319
Detect unknown user: 275
Detect unknown user: 2326
Detect unknown user: 2327
Detect unknown user: 4377
Detect unknown user: 2331
Detect unknown user: 4382
Detect unknown user: 4385
Detect unknown user: 4389
Detect unknown user: 2342
Detect unknown user: 2344
Detect unknown user: 297
Detect unknown user: 304
Detect unknown user: 309
Detect unknown user: 4409
Detect unknown user: 314
Detect unknown user: 4419
Detect unknown user: 4422
Detect unknown user: 4423
Detect unknown user: 2377
Detect unknown user: 330
Detect unknown user: 337
Detect unknown user: 340
Detect unknown user: 2391
Detect unknown user: 4440
Detect unknown user: 4444
Detect unknown user: 2396
Detect unknown user: 2403
Detect unknown user: 360
Detect unknown user: 362
Detect unknown user: 364
Detect unknown user: 367
Detect unknown user: 2419
Detect unknown user: 2420
Detect unknown user: 4470
Detect unknown user: 4473
Detect unknown user: 4477
Detect unknown user: 4478
Detect unknown user: 2430
Detect unknown user: 4480
Detect unknown user: 381
Detect unknown user: 4482
Detect unknown user: 386
Detect unknown user: 4493
Detect unknown user: 4495
Detect unknown user: 400
Detect unknown user: 2452
Detect unknown user: 4505
Detect unknown user: 410
Detect unknown user: 2466
Detect unknown user: 2470
Detect unknown user: 425
Detect unknown user: 4526
Detect unknown user: 4531
Detect unknown user: 435
Detect unknown user: 4533
Detect unknown user: 4535
Detect unknown user: 441
Detect unknown user: 444
Detect unknown user: 4542
Detect unknown user: 2494
Detect unknown user: 4544
Detect unknown user: 2497
Detect unknown user: 452
Detect unknown user: 4552
Detect unknown user: 4555
Detect unknown user: 4557
Detect unknown user: 4560
Detect unknown user: 4569
Detect unknown user: 2522
Detect unknown user: 2533
Detect unknown user: 4586
Detect unknown user: 4592
Detect unknown user: 2546
Detect unknown user: 505
Detect unknown user: 2560
Detect unknown user: 512
Detect unknown user: 517
Detect unknown user: 4614
Detect unknown user: 518
Detect unknown user: 4618
Detect unknown user: 2578
Detect unknown user: 534
Detect unknown user: 4634
Detect unknown user: 2587
Detect unknown user: 543
Detect unknown user: 4640
Detect unknown user: 4643
Detect unknown user: 2595
Detect unknown user: 549
Detect unknown user: 4647
Detect unknown user: 4657
Detect unknown user: 564
Detect unknown user: 4668
Detect unknown user: 4669
Detect unknown user: 572
Detect unknown user: 575
Detect unknown user: 2626
Detect unknown user: 581
Detect unknown user: 2632
Detect unknown user: 4682
Detect unknown user: 588
Detect unknown user: 591
Detect unknown user: 4688
Detect unknown user: 596
Detect unknown user: 4694
Detect unknown user: 2653
Detect unknown user: 605
Detect unknown user: 4704
Detect unknown user: 2665
Detect unknown user: 4724
Detect unknown user: 631
Detect unknown user: 4729
Detect unknown user: 2685
Detect unknown user: 2696
Detect unknown user: 2697
Detect unknown user: 649
Detect unknown user: 651
Detect unknown user: 2703
Detect unknown user: 4767
Detect unknown user: 2719
Detect unknown user: 679
Detect unknown user: 4778
Detect unknown user: 2731
Detect unknown user: 2730
Detect unknown user: 689
Detect unknown user: 4795
Detect unknown user: 713
Detect unknown user: 4816
Detect unknown user: 4818
Detect unknown user: 4819
Detect unknown user: 724
Detect unknown user: 728
Detect unknown user: 732
Detect unknown user: 2787
Detect unknown user: 4840
Detect unknown user: 2792
Detect unknown user: 748
Detect unknown user: 4845
Detect unknown user: 4846
Detect unknown user: 4853
Detect unknown user: 4856
Detect unknown user: 761
Detect unknown user: 763
Detect unknown user: 766
Detect unknown user: 4863
Detect unknown user: 4867
Detect unknown user: 772
Detect unknown user: 2826
Detect unknown user: 778
Detect unknown user: 4876
Detect unknown user: 4878
Detect unknown user: 782
Detect unknown user: 4881
Detect unknown user: 2833
Detect unknown user: 2839
Detect unknown user: 793
Detect unknown user: 2842
Detect unknown user: 2844
Detect unknown user: 4897
Detect unknown user: 805
Detect unknown user: 2861
Detect unknown user: 2870
Detect unknown user: 4920
Detect unknown user: 827
Detect unknown user: 828
Detect unknown user: 2882
Detect unknown user: 4942
Detect unknown user: 847
Detect unknown user: 2904
Detect unknown user: 4953
Detect unknown user: 2911
Detect unknown user: 865
Detect unknown user: 4964
Detect unknown user: 4965
Detect unknown user: 4966
Detect unknown user: 868
Detect unknown user: 874
Detect unknown user: 4982
Detect unknown user: 2935
Detect unknown user: 891
Detect unknown user: 892
Detect unknown user: 4992
Detect unknown user: 5000
Detect unknown user: 5001
Detect unknown user: 2954
Detect unknown user: 914
Detect unknown user: 5017
Detect unknown user: 2969
Detect unknown user: 926
Detect unknown user: 2976
Detect unknown user: 2980
Detect unknown user: 2987
Detect unknown user: 5036
Detect unknown user: 5042
Detect unknown user: 5044
Detect unknown user: 3001
Detect unknown user: 956
Detect unknown user: 3006
Detect unknown user: 3007
Detect unknown user: 3016
Detect unknown user: 972
Detect unknown user: 3022
Detect unknown user: 975
Detect unknown user: 5075
Detect unknown user: 3028
Detect unknown user: 3029
Detect unknown user: 985
Detect unknown user: 1002
Detect unknown user: 3054
Detect unknown user: 1006
Detect unknown user: 3063
Detect unknown user: 5113
Detect unknown user: 1020
Detect unknown user: 3074
Detect unknown user: 3080
Detect unknown user: 1036
Detect unknown user: 3097
Detect unknown user: 5146
Detect unknown user: 3102
Detect unknown user: 1056
Detect unknown user: 1057
Detect unknown user: 5158
Detect unknown user: 5160
Detect unknown user: 3114
Detect unknown user: 3115
Detect unknown user: 1071
Detect unknown user: 1073
Detect unknown user: 3123
Detect unknown user: 3124
Detect unknown user: 5175
Detect unknown user: 3140
Detect unknown user: 3146
Detect unknown user: 3150
Detect unknown user: 3153
Detect unknown user: 1105
Detect unknown user: 1107
Detect unknown user: 1126
Detect unknown user: 5228
Detect unknown user: 5229
Detect unknown user: 5230
Detect unknown user: 3181
Detect unknown user: 5232
Detect unknown user: 3185
Detect unknown user: 3183
Detect unknown user: 5235
Detect unknown user: 1136
Detect unknown user: 3189
Detect unknown user: 5240
Detect unknown user: 5246
Detect unknown user: 1151
Detect unknown user: 5253
Detect unknown user: 3206
Detect unknown user: 5257
Detect unknown user: 1162
Detect unknown user: 3212
Detect unknown user: 3214
Detect unknown user: 1168
Detect unknown user: 3220
Detect unknown user: 1173
Detect unknown user: 1175
Detect unknown user: 1179
Detect unknown user: 5277
Detect unknown user: 3231
Detect unknown user: 1187
Detect unknown user: 5285
Detect unknown user: 3237
Detect unknown user: 1189
Detect unknown user: 3241
Detect unknown user: 5293
Detect unknown user: 1198
Detect unknown user: 5298
Detect unknown user: 3252
Detect unknown user: 1212
Detect unknown user: 1214
Detect unknown user: 3265
Detect unknown user: 5328
Detect unknown user: 5330
Detect unknown user: 1235
Detect unknown user: 5334
Detect unknown user: 3287
Detect unknown user: 1240
Detect unknown user: 3289
Detect unknown user: 1239
Detect unknown user: 1243
Detect unknown user: 1238
Detect unknown user: 3294
Detect unknown user: 5344
Detect unknown user: 5349
Detect unknown user: 1257
Detect unknown user: 5355
Detect unknown user: 5358
Detect unknown user: 1263
Detect unknown user: 1264
Detect unknown user: 5363
Detect unknown user: 1269
Detect unknown user: 1270
Detect unknown user: 3333
Detect unknown user: 5384
Detect unknown user: 1289
Detect unknown user: 1302
Detect unknown user: 1303
Detect unknown user: 3357
Detect unknown user: 3359
Detect unknown user: 5413
Detect unknown user: 5414
Detect unknown user: 5417
Detect unknown user: 3378
Detect unknown user: 5435
Detect unknown user: 1341
Detect unknown user: 3390
Detect unknown user: 5440
Detect unknown user: 1345
Detect unknown user: 3394
Detect unknown user: 5453
Detect unknown user: 3407
Detect unknown user: 3411
Detect unknown user: 5463
Detect unknown user: 3417
Detect unknown user: 1370
Detect unknown user: 3420
Detect unknown user: 5475
Detect unknown user: 5478
Detect unknown user: 1383
Detect unknown user: 1382
Detect unknown user: 1386
Detect unknown user: 3437
Detect unknown user: 5486
Detect unknown user: 1396
Detect unknown user: 3446
Detect unknown user: 5495
Detect unknown user: 1400
Detect unknown user: 5501
Detect unknown user: 5504
Detect unknown user: 5505
Detect unknown user: 3456
Detect unknown user: 5509
Detect unknown user: 3464
Detect unknown user: 3468
Detect unknown user: 1421
Detect unknown user: 1432
Detect unknown user: 5533
Detect unknown user: 5538
Detect unknown user: 3490
Detect unknown user: 1456
Detect unknown user: 1462
Detect unknown user: 5563
Detect unknown user: 1468
Detect unknown user: 5566
Detect unknown user: 5567
Detect unknown user: 3521
Detect unknown user: 5570
Detect unknown user: 1473
Detect unknown user: 5574
Detect unknown user: 3531
Detect unknown user: 3539
Detect unknown user: 3540
Detect unknown user: 1494
Detect unknown user: 5600
Detect unknown user: 3562
Detect unknown user: 5613
Detect unknown user: 5619
Detect unknown user: 1526
Detect unknown user: 5629
Detect unknown user: 3582
Detect unknown user: 5631
Detect unknown user: 3588
Detect unknown user: 5638
Detect unknown user: 3591
Detect unknown user: 1543
Detect unknown user: 3597
Detect unknown user: 5646
Detect unknown user: 3598
Detect unknown user: 1552
Detect unknown user: 3603
Detect unknown user: 3606
Detect unknown user: 5666
Detect unknown user: 5668
Detect unknown user: 3622
Detect unknown user: 3627
Detect unknown user: 3634
Detect unknown user: 3637
Detect unknown user: 1590
Detect unknown user: 5688
Detect unknown user: 1595
Detect unknown user: 5693
Detect unknown user: 3652
Detect unknown user: 1606
Detect unknown user: 3659
Detect unknown user: 3662
Detect unknown user: 1617
Detect unknown user: 5714
Detect unknown user: 5715
Detect unknown user: 5716
Detect unknown user: 5720
Detect unknown user: 3675
Detect unknown user: 1628
Detect unknown user: 3681
Detect unknown user: 5731
Detect unknown user: 1636
Detect unknown user: 5736
Detect unknown user: 3691
Detect unknown user: 5742
Detect unknown user: 5743
Detect unknown user: 1650
Detect unknown user: 3702
Detect unknown user: 5760
Detect unknown user: 1667
Detect unknown user: 3716
Detect unknown user: 3721
Detect unknown user: 1674
Detect unknown user: 3724
Detect unknown user: 3725
Detect unknown user: 5776
Detect unknown user: 1681
Detect unknown user: 1680
Detect unknown user: 5780
Detect unknown user: 3734
Detect unknown user: 3736
Detect unknown user: 5785
Detect unknown user: 1688
Detect unknown user: 3741
Detect unknown user: 1696
Detect unknown user: 1697
Detect unknown user: 1698
Detect unknown user: 3751
Detect unknown user: 5800
Detect unknown user: 1706
Detect unknown user: 5806
Detect unknown user: 5809
Detect unknown user: 5811
Detect unknown user: 1718
Detect unknown user: 1719
Detect unknown user: 1721
Detect unknown user: 5818
Detect unknown user: 1728
Detect unknown user: 1729
Detect unknown user: 3787
Detect unknown user: 1739
Detect unknown user: 5840
Detect unknown user: 5841
Detect unknown user: 3794
Detect unknown user: 1758
Detect unknown user: 3807
Detect unknown user: 5858
Detect unknown user: 3813
Detect unknown user: 5862
Detect unknown user: 5871
Detect unknown user: 5872
Detect unknown user: 1776
Detect unknown user: 1783
Detect unknown user: 5881
Detect unknown user: 5883
Detect unknown user: 3842
Detect unknown user: 3844
Detect unknown user: 1797
Detect unknown user: 3848
Detect unknown user: 1809
Detect unknown user: 5907
Detect unknown user: 1820
Detect unknown user: 1832
Detect unknown user: 1837
Detect unknown user: 3886
Detect unknown user: 5937
Detect unknown user: 3891
Detect unknown user: 3896
Detect unknown user: 5945
Detect unknown user: 3898
Detect unknown user: 5951
Detect unknown user: 5955
Detect unknown user: 5959
Detect unknown user: 5960
Detect unknown user: 3921
Detect unknown user: 3922
Detect unknown user: 1873
Detect unknown user: 1874
Detect unknown user: 5974
Detect unknown user: 3926
Detect unknown user: 5976
Detect unknown user: 1890
Detect unknown user: 1893
Detect unknown user: 5990
Detect unknown user: 3942
Detect unknown user: 3945
Detect unknown user: 3946
Detect unknown user: 5996
Detect unknown user: 3949
Detect unknown user: 1902
Detect unknown user: 1903
Detect unknown user: 3954
Detect unknown user: 6003
Detect unknown user: 3957
Detect unknown user: 1909
Detect unknown user: 1911
Detect unknown user: 6008
Detect unknown user: 6009
Detect unknown user: 3963
Detect unknown user: 6017
Detect unknown user: 6023
Detect unknown user: 6025
Detect unknown user: 6026
Detect unknown user: 6032
Detect unknown user: 3987
Detect unknown user: 1945
Detect unknown user: 3998
Detect unknown user: 1955
Detect unknown user: 1960
Detect unknown user: 4016
Detect unknown user: 4022
Detect unknown user: 1984
Detect unknown user: 1987
Detect unknown user: 1993
Detect unknown user: 2008
Detect unknown user: 2014
Detect unknown user: 2016
Detect unknown user: 4069
Detect unknown user: 4076
Detect unknown user: 4078
Detect unknown user: 4079
Detect unknown user: 2030
Detect unknown user: 4089

In [88]:

# ======= Evaluation Metrics =======
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k) if dcg(ideal_labels, k) > 0 else 0

def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count if relevant_count > 0 else 0

def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0

In [21]:
test_ratings[test_ratings['user'] == 1]

Empty DataFrame
Columns: [user, item, label, time]
Index: []

In [89]:

def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    unique_users = test_ratings['user'].unique()

    for user in unique_users:
        if user not in final_recommendations:
            continue  # Skip if no recommendations

        recommended_items = final_recommendations[user]
        user_test_data = test_ratings[test_ratings['user'] == user]
        test_items = user_test_data['item'].values

        y_score = [1 if item in test_items else 0 for item in recommended_items]
        # y_score = [
        #     user_test_data[user_test_data['item'] == item]['label'].values[0] if item in test_items else 0
        #     for item in recommended_items
        # ]
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    return {
        'NDCG@{}'.format(k): np.nanmean(ndcg_scores),
        'Recall@{}'.format(k): np.nanmean(recall_scores),
        'MRR@{}'.format(k): np.nanmean(mrr_scores),
    }

In [23]:
# ======= Evaluate Cold-Start Performance =======
cold_start_eval_results = evaluate_final_recommendations(final_recommendations, test_ratings, k=10)

In [24]:
# ======= Print Results =======
print("\nCold-Start User Performance:")
for metric, value in cold_start_eval_results.items():
    print(f"{metric}: {value:.4f}")

Cold-Start User Performance:
NDCG@10: 0.5650
Recall@10: 0.0250
MRR@10: 0.4741

In [25]:
# ======= Print Results =======
print("\nCold-Start User Performance:")
for metric, value in cold_start_eval_results.items():
    print(f"{metric}: {value:.4f}")

Cold-Start User Performance:
NDCG@10: 0.5650
Recall@10: 0.0250
MRR@10: 0.4741

In [90]:
cf_recommendations = {}

# Assume unique_users is a list or array of all user IDs
for user in test_ratings['user'].unique():
    # Generate top N recommendations for the user using the Collaborative Filtering model
    recommended_items = user_cf.recommend_user(user, n_rec=10, filter_consumed=True)
    cf_recommendations[user] = recommended_items[user]  # Store the recommendations in the dictionary
cf_recommendations

Detect unknown user: 6032
Detect unknown user: 6026
Detect unknown user: 6025
Detect unknown user: 6023
Detect unknown user: 6017
Detect unknown user: 6009
Detect unknown user: 6008
Detect unknown user: 6003
Detect unknown user: 5996
Detect unknown user: 5990
Detect unknown user: 5976
Detect unknown user: 5974
Detect unknown user: 5960
Detect unknown user: 5959
Detect unknown user: 5955
Detect unknown user: 5951
Detect unknown user: 5945
Detect unknown user: 5937
Detect unknown user: 5907
Detect unknown user: 5883
Detect unknown user: 5881
Detect unknown user: 5872
Detect unknown user: 5871
Detect unknown user: 5862
Detect unknown user: 5858
Detect unknown user: 5841
Detect unknown user: 5840
Detect unknown user: 5818
Detect unknown user: 5811
Detect unknown user: 5809
Detect unknown user: 5806
Detect unknown user: 5800
Detect unknown user: 5785
Detect unknown user: 5780
Detect unknown user: 5776
Detect unknown user: 5760
Detect unknown user: 5743
Detect unknown user: 5742
Detect unknown user: 5736
Detect unknown user: 5731
Detect unknown user: 5720
Detect unknown user: 5716
Detect unknown user: 5715
Detect unknown user: 5714
Detect unknown user: 5693
Detect unknown user: 5688
Detect unknown user: 5668
Detect unknown user: 5666
Detect unknown user: 5646
Detect unknown user: 5638
Detect unknown user: 5631
Detect unknown user: 5629
Detect unknown user: 5619
Detect unknown user: 5613
Detect unknown user: 5600
Detect unknown user: 5574
Detect unknown user: 5570
Detect unknown user: 5567
Detect unknown user: 5566
Detect unknown user: 5563
Detect unknown user: 5538
Detect unknown user: 5533
Detect unknown user: 5509
Detect unknown user: 5505
Detect unknown user: 5504
Detect unknown user: 5501
Detect unknown user: 5495
Detect unknown user: 5486
Detect unknown user: 5478
Detect unknown user: 5475
Detect unknown user: 5463
Detect unknown user: 5453
Detect unknown user: 5440
Detect unknown user: 5435
Detect unknown user: 5417
Detect unknown user: 5414
Detect unknown user: 5413
Detect unknown user: 5384
Detect unknown user: 5363
Detect unknown user: 5358
Detect unknown user: 5355
Detect unknown user: 5349
Detect unknown user: 5344
Detect unknown user: 5334
Detect unknown user: 5330
Detect unknown user: 5328
Detect unknown user: 5298
Detect unknown user: 5293
Detect unknown user: 5285
Detect unknown user: 5277
Detect unknown user: 5257
Detect unknown user: 5253
Detect unknown user: 5246
Detect unknown user: 5240
Detect unknown user: 5235
Detect unknown user: 5232
Detect unknown user: 5230
Detect unknown user: 5229
Detect unknown user: 5228
Detect unknown user: 5175
Detect unknown user: 5160
Detect unknown user: 5158
Detect unknown user: 5146
Detect unknown user: 5113
Detect unknown user: 5075
Detect unknown user: 5044
Detect unknown user: 5042
Detect unknown user: 5036
Detect unknown user: 5017
Detect unknown user: 5001
Detect unknown user: 5000
Detect unknown user: 4992
Detect unknown user: 4982
Detect unknown user: 4966
Detect unknown user: 4965
Detect unknown user: 4964
Detect unknown user: 4953
Detect unknown user: 4942
Detect unknown user: 4920
Detect unknown user: 4897
Detect unknown user: 4881
Detect unknown user: 4878
Detect unknown user: 4876
Detect unknown user: 4867
Detect unknown user: 4863
Detect unknown user: 4856
Detect unknown user: 4853
Detect unknown user: 4846
Detect unknown user: 4845
Detect unknown user: 4840
Detect unknown user: 4819
Detect unknown user: 4818
Detect unknown user: 4816
Detect unknown user: 4795
Detect unknown user: 4778
Detect unknown user: 4767
Detect unknown user: 4729
Detect unknown user: 4724
Detect unknown user: 4704
Detect unknown user: 4694
Detect unknown user: 4688
Detect unknown user: 4682
Detect unknown user: 4669
Detect unknown user: 4668
Detect unknown user: 4657
Detect unknown user: 4647
Detect unknown user: 4643
Detect unknown user: 4640
Detect unknown user: 4634
Detect unknown user: 4618
Detect unknown user: 4614
Detect unknown user: 4592
Detect unknown user: 4586
Detect unknown user: 4569
Detect unknown user: 4560
Detect unknown user: 4557
Detect unknown user: 4555
Detect unknown user: 4552
Detect unknown user: 4544
Detect unknown user: 4542
Detect unknown user: 4535
Detect unknown user: 4533
Detect unknown user: 4531
Detect unknown user: 4526
Detect unknown user: 4505
Detect unknown user: 4495
Detect unknown user: 4493
Detect unknown user: 4482
Detect unknown user: 4480
Detect unknown user: 4478
Detect unknown user: 4477
Detect unknown user: 4473
Detect unknown user: 4470
Detect unknown user: 4444
Detect unknown user: 4440
Detect unknown user: 4423
Detect unknown user: 4422
Detect unknown user: 4419
Detect unknown user: 4409
Detect unknown user: 4389
Detect unknown user: 4385
Detect unknown user: 4382
Detect unknown user: 4377
Detect unknown user: 4370
Detect unknown user: 4368
Detect unknown user: 4367
Detect unknown user: 4345
Detect unknown user: 4344
Detect unknown user: 4340
Detect unknown user: 4333
Detect unknown user: 4319
Detect unknown user: 4310
Detect unknown user: 4306
Detect unknown user: 4302
Detect unknown user: 4301
Detect unknown user: 4298
Detect unknown user: 4274
Detect unknown user: 4266
Detect unknown user: 4259
Detect unknown user: 4223
Detect unknown user: 4214
Detect unknown user: 4203
Detect unknown user: 4199
Detect unknown user: 4165
Detect unknown user: 4164
Detect unknown user: 4162
Detect unknown user: 4185
Detect unknown user: 4155
Detect unknown user: 4149
Detect unknown user: 4148
Detect unknown user: 4147
Detect unknown user: 4128
Detect unknown user: 4124
Detect unknown user: 4114
Detect unknown user: 4089
Detect unknown user: 4079
Detect unknown user: 4078
Detect unknown user: 4076
Detect unknown user: 4069
Detect unknown user: 4022
Detect unknown user: 4016
Detect unknown user: 3998
Detect unknown user: 3987
Detect unknown user: 3963
Detect unknown user: 3957
Detect unknown user: 3954
Detect unknown user: 3949
Detect unknown user: 3946
Detect unknown user: 3945
Detect unknown user: 3942
Detect unknown user: 3926
Detect unknown user: 3922
Detect unknown user: 3921
Detect unknown user: 3898
Detect unknown user: 3896
Detect unknown user: 3891
Detect unknown user: 3886
Detect unknown user: 3848
Detect unknown user: 3844
Detect unknown user: 3842
Detect unknown user: 3813
Detect unknown user: 3807
Detect unknown user: 3794
Detect unknown user: 3787
Detect unknown user: 3751
Detect unknown user: 3741
Detect unknown user: 3736
Detect unknown user: 3734
Detect unknown user: 3725
Detect unknown user: 3724
Detect unknown user: 3721
Detect unknown user: 3716
Detect unknown user: 3702
Detect unknown user: 3691
Detect unknown user: 3681
Detect unknown user: 3675
Detect unknown user: 3662
Detect unknown user: 3659
Detect unknown user: 3652
Detect unknown user: 3637
Detect unknown user: 3634
Detect unknown user: 3627
Detect unknown user: 3622
Detect unknown user: 3606
Detect unknown user: 3603
Detect unknown user: 3598
Detect unknown user: 3597
Detect unknown user: 3591
Detect unknown user: 3588
Detect unknown user: 3582
Detect unknown user: 3562
Detect unknown user: 3540
Detect unknown user: 3539
Detect unknown user: 3531
Detect unknown user: 3521
Detect unknown user: 3490
Detect unknown user: 3468
Detect unknown user: 3464
Detect unknown user: 3456
Detect unknown user: 3446
Detect unknown user: 3437
Detect unknown user: 3420
Detect unknown user: 3417
Detect unknown user: 3411
Detect unknown user: 3407
Detect unknown user: 3394
Detect unknown user: 3390
Detect unknown user: 3378
Detect unknown user: 3359
Detect unknown user: 3357
Detect unknown user: 3333
Detect unknown user: 3294
Detect unknown user: 3289
Detect unknown user: 3287
Detect unknown user: 3265
Detect unknown user: 3252
Detect unknown user: 3241
Detect unknown user: 3237
Detect unknown user: 3231
Detect unknown user: 3220
Detect unknown user: 3214
Detect unknown user: 3212
Detect unknown user: 3206
Detect unknown user: 3189
Detect unknown user: 3185
Detect unknown user: 3183
Detect unknown user: 3181
Detect unknown user: 3153
Detect unknown user: 3150
Detect unknown user: 3146
Detect unknown user: 3140
Detect unknown user: 3124
Detect unknown user: 3123
Detect unknown user: 3114
Detect unknown user: 3102
Detect unknown user: 3115
Detect unknown user: 3097
Detect unknown user: 3080
Detect unknown user: 3074
Detect unknown user: 3063
Detect unknown user: 3054
Detect unknown user: 3029
Detect unknown user: 3028
Detect unknown user: 3022
Detect unknown user: 3016
Detect unknown user: 3007
Detect unknown user: 3006
Detect unknown user: 3001
Detect unknown user: 2987
Detect unknown user: 2976
Detect unknown user: 2969
Detect unknown user: 2954
Detect unknown user: 2935
Detect unknown user: 2911
Detect unknown user: 2904
Detect unknown user: 2882
Detect unknown user: 2870
Detect unknown user: 2861
Detect unknown user: 2844
Detect unknown user: 2842
Detect unknown user: 2839
Detect unknown user: 2833
Detect unknown user: 2826
Detect unknown user: 2792
Detect unknown user: 2787
Detect unknown user: 2731
Detect unknown user: 2730
Detect unknown user: 2719
Detect unknown user: 2703
Detect unknown user: 2697
Detect unknown user: 2696
Detect unknown user: 2685
Detect unknown user: 2665
Detect unknown user: 2653
Detect unknown user: 2632
Detect unknown user: 2626
Detect unknown user: 2595
Detect unknown user: 2587
Detect unknown user: 2578
Detect unknown user: 2560
Detect unknown user: 2546
Detect unknown user: 2533
Detect unknown user: 2522
Detect unknown user: 2497
Detect unknown user: 2494
Detect unknown user: 2470
Detect unknown user: 2466
Detect unknown user: 2452
Detect unknown user: 2430
Detect unknown user: 2420
Detect unknown user: 2419
Detect unknown user: 2403
Detect unknown user: 2396
Detect unknown user: 2391
Detect unknown user: 2377
Detect unknown user: 2344
Detect unknown user: 2342
Detect unknown user: 2331
Detect unknown user: 2327
Detect unknown user: 2326
Detect unknown user: 2320
Detect unknown user: 2319
Detect unknown user: 2310
Detect unknown user: 2295
Detect unknown user: 2286
Detect unknown user: 2284
Detect unknown user: 2273
Detect unknown user: 2264
Detect unknown user: 2257
Detect unknown user: 2251
Detect unknown user: 2242
Detect unknown user: 2204
Detect unknown user: 2190
Detect unknown user: 2186
Detect unknown user: 2177
Detect unknown user: 2176
Detect unknown user: 2165
Detect unknown user: 2164
Detect unknown user: 2156
Detect unknown user: 2155
Detect unknown user: 2149
Detect unknown user: 2140
Detect unknown user: 2139
Detect unknown user: 2110
Detect unknown user: 2107
Detect unknown user: 2087
Detect unknown user: 2054
Detect unknown user: 2030
Detect unknown user: 2016
Detect unknown user: 2014
Detect unknown user: 2008
Detect unknown user: 1993
Detect unknown user: 1987
Detect unknown user: 1984
Detect unknown user: 1960
Detect unknown user: 1955
Detect unknown user: 1945
Detect unknown user: 1909
Detect unknown user: 1911
Detect unknown user: 1903
Detect unknown user: 1902
Detect unknown user: 1893
Detect unknown user: 1890
Detect unknown user: 1873
Detect unknown user: 1874
Detect unknown user: 1837
Detect unknown user: 1832
Detect unknown user: 1820
Detect unknown user: 1809
Detect unknown user: 1797
Detect unknown user: 1783
Detect unknown user: 1776
Detect unknown user: 1758
Detect unknown user: 1739
Detect unknown user: 1729
Detect unknown user: 1728
Detect unknown user: 1719
Detect unknown user: 1721
Detect unknown user: 1718
Detect unknown user: 1706
Detect unknown user: 1698
Detect unknown user: 1697
Detect unknown user: 1696
Detect unknown user: 1688
Detect unknown user: 1681
Detect unknown user: 1680
Detect unknown user: 1674
Detect unknown user: 1667
Detect unknown user: 1650
Detect unknown user: 1636
Detect unknown user: 1628
Detect unknown user: 1617
Detect unknown user: 1606
Detect unknown user: 1595
Detect unknown user: 1590
Detect unknown user: 1552
Detect unknown user: 1543
Detect unknown user: 1526
Detect unknown user: 1494
Detect unknown user: 1473
Detect unknown user: 1468
Detect unknown user: 1462
Detect unknown user: 1456
Detect unknown user: 1432
Detect unknown user: 1421
Detect unknown user: 1400
Detect unknown user: 1396
Detect unknown user: 1386
Detect unknown user: 1383
Detect unknown user: 1382
Detect unknown user: 1370
Detect unknown user: 1345
Detect unknown user: 1341
Detect unknown user: 1303
Detect unknown user: 1302
Detect unknown user: 1289
Detect unknown user: 1270
Detect unknown user: 1269
Detect unknown user: 1264
Detect unknown user: 1263
Detect unknown user: 1257
Detect unknown user: 1243
Detect unknown user: 1240
Detect unknown user: 1239
Detect unknown user: 1238
Detect unknown user: 1235
Detect unknown user: 1214
Detect unknown user: 1212
Detect unknown user: 1198
Detect unknown user: 1189
Detect unknown user: 1187
Detect unknown user: 1179
Detect unknown user: 1175
Detect unknown user: 1173
Detect unknown user: 1168
Detect unknown user: 1162
Detect unknown user: 1151
Detect unknown user: 1136
Detect unknown user: 1126
Detect unknown user: 1107
Detect unknown user: 1105
Detect unknown user: 1073
Detect unknown user: 1071
Detect unknown user: 1057
Detect unknown user: 1056
Detect unknown user: 1036
Detect unknown user: 1020
Detect unknown user: 1006
Detect unknown user: 1002
Detect unknown user: 985
Detect unknown user: 975
Detect unknown user: 972
Detect unknown user: 956
Detect unknown user: 926
Detect unknown user: 914
Detect unknown user: 892
Detect unknown user: 891
Detect unknown user: 874
Detect unknown user: 868
Detect unknown user: 865
Detect unknown user: 847
Detect unknown user: 828
Detect unknown user: 827
Detect unknown user: 805
Detect unknown user: 793
Detect unknown user: 782
Detect unknown user: 778
Detect unknown user: 772
Detect unknown user: 766
Detect unknown user: 763
Detect unknown user: 761
Detect unknown user: 748
Detect unknown user: 732
Detect unknown user: 728
Detect unknown user: 724
Detect unknown user: 713
Detect unknown user: 689
Detect unknown user: 679
Detect unknown user: 651
Detect unknown user: 649
Detect unknown user: 631
Detect unknown user: 605
Detect unknown user: 596
Detect unknown user: 591
Detect unknown user: 588
Detect unknown user: 581
Detect unknown user: 575
Detect unknown user: 572
Detect unknown user: 564
Detect unknown user: 549
Detect unknown user: 543
Detect unknown user: 534
Detect unknown user: 518
Detect unknown user: 517
Detect unknown user: 512
Detect unknown user: 505
Detect unknown user: 452
Detect unknown user: 444
Detect unknown user: 441
Detect unknown user: 435
Detect unknown user: 425
Detect unknown user: 410
Detect unknown user: 400
Detect unknown user: 386
Detect unknown user: 381
Detect unknown user: 367
Detect unknown user: 364
Detect unknown user: 362
Detect unknown user: 360
Detect unknown user: 340
Detect unknown user: 337
Detect unknown user: 330
Detect unknown user: 314
Detect unknown user: 309
Detect unknown user: 304
Detect unknown user: 297
Detect unknown user: 275
Detect unknown user: 262
Detect unknown user: 249
Detect unknown user: 248
Detect unknown user: 230
Detect unknown user: 219
Detect unknown user: 214
Detect unknown user: 201
Detect unknown user: 192
Detect unknown user: 182
Detect unknown user: 163
Detect unknown user: 156
Detect unknown user: 142
Detect unknown user: 130
Detect unknown user: 123
Detect unknown user: 90
Detect unknown user: 72
Detect unknown user: 69
Detect unknown user: 63
Detect unknown user: 57
Detect unknown user: 50
Detect unknown user: 38
Detect unknown user: 35
Detect unknown user: 29
Detect unknown user: 27
Detect unknown user: 5
Detect unknown user: 2
Detect unknown user: 2980

{6032: array([1221, 1198, 3114,  527,  457, 2791, 2762, 2987, 2716,  223]),
 6026: array([3481, 2858, 1968, 2174,   50, 1127, 1784,   50,  589,   50]),
 6025: array([ 356, 2987, 2628, 2762, 1527,  608, 2291, 1374, 1721,  588]),
 6023: array([2858, 1214, 1265, 3114,  648, 1584,   50, 2628,   39, 2918]),
 6017: array([ 590,  780,  780, 2987,  592, 2997, 1220,  527, 1127,  457]),
 6009: array([2174, 2797,  588, 1784,  858, 1097, 1225, 2355, 2571, 3418]),
 6008: array([2174,  260, 1784, 1968, 1721, 1923, 1387, 1127, 1721, 1617]),
 6003: array([2396,  223, 2997, 1036, 2716, 2628, 1307, 2683,  780,  110]),
 5996: array([ 858, 1197, 1225,  457,   50, 1270,  780,  588,   34, 3793]),
 5990: array([1265, 2762, 1304,  589,  780,  457, 1196,  377, 3176,  589]),
 5976: array([ 380,  377, 2959, 2571, 1923, 1196, 1393, 3793, 3578, 2858]),
 5974: array([1721,  593, 1968, 1573, 2716, 2628,  318,  318, 1198,  858]),
 5960: array([3793, 1214, 1784,  380,  590,  377,  457,   39, 1097, 1127]),
 5959: array([3175,  592, 2000, 1394,  588,  919, 2706, 1197,  588,  527]),
 5955: array([3481,  919, 3176,  608, 1127, 1393,  480, 2716,  593, 2916]),
 5951: array([ 919, 1721,  356, 2396, 1197, 2804, 2406,  318, 1617, 2028]),
 5945: array([2406, 2291,  590,    1, 2174, 2028, 2918, 3114, 3578, 1374]),
 5937: array([2174,  924, 1265,  260, 2804, 1240, 1214, 2797,  356,   50]),
 5907: array([1374, 1307, 3793, 2858, 3175, 1221,  648, 2396, 2396,  590]),
 5883: array([2918,  380,  296, 2699,  296, 3793, 1197,  588, 3578, 2683]),
 5881: array([3578, 1394, 3175,  589, 1617, 2797, 1617,  296, 2000,  356]),
 5872: array([ 608, 1704, 2797, 1304, 1230,  608, 1193, 2628, 1393,  377]),
 5871: array([2571, 2599,  480,  296, 2959, 1036,  590, 3114,  223, 1291]),
 5862: array([2028, 1270, 1573, 1210,   50, 1196, 1214, 1307,  527, 1127]),
 5858: array([2699, 1270,  589,  296, 3418,   34,  648, 1210, 1304,  589]),
 5841: array([1374, 2762, 3481,    1, 1265, 3578, 2858, 1197, 1307, 1214]),
 5840: array([1259, 2683,  608,  919, 1265, 2355, 3578,  480, 1270, 3481]),
 5818: array([2028, 1784,  588, 1127,  457, 1573, 1527,  608, 3176, 1230]),
 5811: array([2762, 2028, 1374, 1270, 1968,  589, 2599, 2628, 2571,  589]),
 5809: array([1265, 2000, 1270, 2683, 1968,    1, 1527, 3793, 2918,  527]),
 5806: array([1374, 1610, 1527, 1221, 2918, 1200,  480,  608, 1923, 1304]),
 5800: array([ 541, 2599, 2858, 1210, 1036, 1704, 2804, 3471,  356,  380]),
 5785: array([1387, 3418,  527,  260, 2028, 2699,  593, 2804, 2959, 2762]),
 5780: array([1923, 2762, 2762, 3114, 1240,    1, 1617, 1968,  260,  858]),
 5776: array([1610, 2355, 2599, 2997, 2174, 3471, 2987,  356, 1610, 3114]),
 5760: array([2571, 1291, 2396, 1291, 2804,  377,  590, 1214,   39,  380]),
 5743: array([ 588,  592, 2174, 1213,   39,  223, 2791,  593, 2858, 2628]),
 5742: array([ 589, 2997, 1580, 1527, 2571, 1704, 1259,  527, 2291, 1220]),
 5736: array([1394, 1220, 1307, 2918, 2762, 3481,  592,  356, 1259, 1721]),
 5731: array([1196,  380, 1240, 1270, 3578,  750,  296,  377,  380, 1210]),
 5720: array([3471, 1240, 2599, 1265,  110, 1784, 2683, 1527, 2918, 1127]),
 5716: array([1617,    1, 2174, 1200, 2355, 1197,  924, 2628, 1198,  110]),
 5715: array([ 912,  541, 2571,  912, 1197, 1196,  110,  780, 2406,  858]),
 5714: array([1240,  858, 1259, 1374, 2916, 3793, 1584, 1230, 1291, 1374]),
 5693: array([ 588, 1784,    1,  110, 1198, 1225, 1610,    1, 1200, 1240]),
 5688: array([2683, 1721, 2706, 1214, 1221,  608, 1220,  912, 1610, 2791]),
 5668: array([ 296, 1230, 2355, 2918, 1210,  296, 2683,  593, 1580, 2683]),
 5666: array([1214,  296, 1291, 1617,  480, 2858, 1270, 2396, 2599,    1]),
 5646: array([1270, 1196, 1221,  223, 3578,  589,  318, 1387, 1265, 1220]),
 5638: array([ 590, 1200, 2406, 2916, 2762, 2804, 2406,  457, 1307,  527]),
 5631: array([2174, 2599, 2291, 1291, 2291, 1610,  380,  527, 2355, 2791]),
 5629: array([ 377, 2762, 2916, 2406, 1580,  648,   32, 1221, 1210, 1210]),
 5619: array([ 296, 1580, 2571, 1197, 1617,  750,  648, 1210, 1704,  110]),
 5613: array([1193, 1210, 2571,  110,  924, 1127, 1259, 1704, 2959, 2959]),
 5600: array([3114, 2000, 1387, 2628, 2355, 1196, 3176,   50, 3471, 2406]),
 5574: array([1387, 1923, 1221,  110,  260,  110, 1230, 1221,  457,  780]),
 5570: array([ 356, 2706, 2699,  593, 1374, 3578,  480,   39,  589, 1097]),
 5567: array([ 260, 1221, 1307, 2916, 1270, 1198, 2804, 2683, 2804,  377]),
 5566: array([2000, 1784, 1721,  924,    1, 2355,  589, 1617, 1304, 1923]),
 5563: array([1580, 2571,  593, 1394,  457, 2916, 1196, 1220,  924, 1394]),
 5538: array([2291, 2762, 2683, 1610, 1968, 1097,  223, 2804,   34, 2571]),
 5533: array([ 223, 1225, 1036, 3114,  318,  589, 1230, 2355,  296, 2599]),
 5509: array([ 260, 1270,  858, 3175,  541, 1265, 1259, 3578, 1213, 1291]),
 5505: array([1225, 2683,    1, 1393, 1213, 1265, 1200,  592, 3418,   50]),
 5504: array([2396, 1617, 1580, 2599, 1036, 3175, 2918, 3418, 1394,  110]),
 5501: array([1136, 1225, 1573, 2916,  919, 1584, 1210, 1213, 1198, 1584]),
 5495: array([1210,  260, 2916, 1097, 1387,    1, 1259, 1291, 1291, 2804]),
 5486: array([2355, 1291, 2918,  527,   32, 1923,  457,  527, 1200,  296]),
 5478: array([1136, 1923, 1307,  608,  457, 2797, 3578, 1136, 2599, 2916]),
 5475: array([2174,  919,  110,   50,  780, 2858, 1584, 1213, 1210, 1923]),
 5463: array([3481, 1196, 1197,  541, 1036, 2959, 1193, 1721, 1196, 3793]),
 5453: array([ 588, 1213, 3175,    1, 2406, 1210, 1240,  110, 1923, 2355]),
 5440: array([  39,   32, 1610,  912, 1097, 1291, 2797, 3176, 2000, 2804]),
 5435: array([1230, 1213,  924, 2762, 2716, 2706,  110,  919, 2599,  858]),
 5417: array([1220, 2174,  260,  858,  592, 1923,   39, 3481, 1270, 2959]),
 5414: array([1198, 1270, 2599, 1221, 2174, 3481,  589, 1213,  750,  780]),
 5413: array([1213, 1387, 1393,  480, 2706,  380,  380, 2791,  912,  541]),
 5384: array([ 356, 2706, 1036, 2959, 1580, 1784, 3793, 2699,  110, 2000]),
 5363: array([ 912,  377, 2028, 1221,    1, 1721, 2628,  924, 1704,  589]),
 5358: array([1784, 1374, 2028,  589, 3481, 1240, 1923, 1387, 1200,  296]),
 5355: array([3793, 1580,   34, 1200, 2396, 1259, 1213, 2918,  593, 2706]),
 5349: array([2706, 2599,   39, 1193, 3418, 2959, 1291,  527, 1610, 1393]),
 5344: array([1527,  780,  858,  592, 1270, 2396, 1291, 2699, 2916,  780]),
 5334: array([2916,  780, 2858, 1307, 1307,  457, 2716,  590, 1265,  480]),
 5330: array([ 480, 1225,  541, 1580, 2706, 2762, 3578,  260, 2918, 2599]),
 5328: array([3471, 2716, 2916, 2804, 3418, 1210, 2599,  380, 1610,  648]),
 5298: array([2858, 1210, 1210, 2396, 2699,  648, 1784,    1, 2804, 1617]),
 5293: array([1393, 1210,  260, 1270, 1394,  356, 3175, 1221, 1784, 1200]),
 5285: array([2858, 2987, 1240, 1304, 3471, 2571, 1394, 1270, 1721, 2987]),
 5277: array([1214, 2355,  457, 1394, 3176,  380,  924, 1036,  780, 1394]),
 5257: array([1610, 1127,   34,   50, 1610, 2797,  924, 2683, 3418, 1193]),
 5253: array([1393,  527, 2804,    1, 1291, 1240,  780, 1200, 2291,  593]),
 5246: array([ 750, 1393, 1291, 2000, 2599, 1617,  592, 2997, 2918, 1214]),
 5240: array([ 592, 1394, 1097, 1721, 1387,    1, 1136, 2699, 2858, 2406]),
 5235: array([3481, 1213, 1721,  541,  608, 3114,  380, 2628, 1374,  592]),
 5232: array([3471, 1200,  919, 2791, 3481, 1393, 2791, 3176, 3114, 2987]),
 5230: array([2858, 1721, 2174, 3176, 1374,  260, 1291,  592, 1387, 1193]),
 5229: array([2683, 1721, 2797, 1127,  296,  912, 2406, 1968, 2291,  608]),
 5228: array([1527,  858, 1220,  780,  588, 1584, 3471,  588, 1968,  223]),
 5175: array([ 527, 1270, 2000, 2683,  590, 1213, 1213, 1968, 1923,  223]),
 5160: array([1580, 1307, 2987, 1394, 1036, 2699,  924, 2918, 1580, 2804]),
 5158: array([2396,   50,  750, 3176, 2355, 2355,  480, 1220, 1196,  260]),
 5146: array([1221, 2858, 1197, 1704, 2291,    1, 1394, 1968,  318, 1374]),
 5113: array([1307,  380, 2396, 2628, 1214, 1200, 1225, 1304, 2000, 2000]),
 5075: array([1225,  780,  318,  110, 3578, 3793, 1221, 1193, 2355, 1220]),
 5044: array([2699, 1197, 1198,  858, 3481, 3175, 1923, 2174, 1610, 1240]),
 5042: array([1200, 2762,  912, 1240,    1, 1210, 1394, 2804, 1387,  377]),
 5036: array([  39,  912, 1704, 1193,  912, 1213, 1374, 1968, 1036, 1270]),
 5017: array([1393, 1225, 1265,    1, 1220, 2916,  380, 1784, 1923, 1196]),
 5001: array([2355, 1291,  750,  318, 1214,  527,  590, 2699, 2762, 2628]),
 5000: array([1214, 1225,  780, 1240, 2916, 1307, 2987, 2762, 3418, 1193]),
 4992: array([ 356, 2959,  592, 2396, 1270,  480,  590, 1704, 1394, 1704]),
 4982: array([  34, 1136, 2959,  919,  588, 1584, 2683, 2699,  919, 1198]),
 4966: array([2355,  592, 1573, 2987,    1,  780, 2683,  589, 2916,  318]),
 4965: array([2683, 1127,  593, 2716,  480, 1221, 2699, 1291, 1923,  592]),
 4964: array([1225,  457, 2406, 2628,  924, 2797, 1240, 2716,  110, 2858]),
 4953: array([1036, 1527,  318,  780, 2804, 1573, 2858, 1036, 2762,  858]),
 4942: array([ 858, 1721, 1617,  356,  318, 1259, 3793,  919, 2916,  912]),
 4920: array([1721, 1196, 1584,  588, 1968, 3114, 2599,  780,  541, 1259]),
 4897: array([2396,  223, 2916, 1240, 3176, 1036, 1704,  858,  296, 2959]),
 4881: array([3175, 2762,  750,   34,   32, 1200, 1291, 1573, 1225, 1097]),
 4878: array([2918,  588, 2174, 2762, 1265, 1097, 1580, 3471, 3176,  912]),
 4876: array([1307, 1573, 2791, 1221, 1136, 1214,  589, 1291, 3418, 1270]),
 4867: array([2997, 2716, 2683, 1036,  377, 2174,  296, 1374, 1210, 1198]),
 4863: array([ 380, 3793,  527,  924, 2028, 2918, 3471,  296, 1259, 2628]),
 4856: array([2987,  296,  858,  924, 3481,  590,    1, 1230, 2997,  588]),
 4853: array([1214, 2000, 1097,  590,  457, 2706,  593, 1036, 2396, 1225]),
 4846: array([2791, 2918, 2706,  377, 2028,  318, 2997,  588, 1393, 1221]),
 4845: array([1584,  858, 2918,  919,  858,  356, 2791, 3578, 2997, 3578]),
 4840: array([ 608, 3176,   50, 1580, 3114, 1225, 1259,  223, 1721, 1304]),
 4819: array([   1, 1210, 1200,   39, 1394, 1784, 2706,   50, 2916,   39]),
 4818: array([3114,    1,  296, 2706, 2028,  589, 1304, 2858,  527, 2699]),
 4816: array([1193, 2959, 2355, 2571, 1265,  590, 2571, 1307, 1200,   50]),
 4795: array([2406, 1968, 1721, 1259, 2987, 2797, 1210, 2628, 1968, 1704]),
 4778: array([2571, 1784, 2000, 2628, 3471, 2699, 1193, 1240,    1, 1307]),
 4767: array([ 480, 2355,  260, 1210,  924,  592, 1225,  593,  858, 1193]),
 4729: array([3114, 1527, 2797,  377,  589,  593, 2396,   32, 3578,  858]),
 4724: array([2918,  380,  924, 1225, 1304, 1374, 1923, 1265, 3471, 2406]),
 4704: array([2699, 3114, 3471, 1225, 3481, 1584,  750, 2987, 1304, 2791]),
 4694: array([2683,  380, 2804, 1136, 1221, 1197,  648, 1291,  912, 2918]),
 4688: array([3481, 2762,  924, 2959,  380, 1573, 1394, 3481, 3176, 1968]),
 4682: array([ 858, 1291, 2291, 1580, 3471, 2000, 2804, 2997, 1393,  780]),
 4669: array([3114,   32, 3114, 1393, 1197, 2959, 1220,  318,  356, 1221]),
 4668: array([2959, 2406, 1394, 1394,  780, 2174, 2997, 1127, 1265,  260]),
 4657: array([3481, 2683,  912, 1196, 2571, 1198, 1374, 1097,  356, 1923]),
 4647: array([2706,  590, 1214, 3114, 1097, 3481,  593,  592,  912, 3471]),
 4643: array([3175, 2396, 3471,  648, 1127,   50, 1200, 2355, 2716, 1240]),
 4640: array([ 296, 1196,   39, 2628, 1197, 2396, 1527, 1221, 2916,   34]),
 4634: array([ 593,  457,  858, 2683, 2028, 1193, 1394,  750,  912,  318]),
 4618: array([3578,  318,   32,    1,  648, 3793, 2804,   50, 3176,   34]),
 4614: array([2797,   32,  380, 1127, 1394, 1259, 1387, 1387, 2291, 1721]),
 4592: array([1270, 2683, 3471, 1580, 3176,   32,  593, 1387,  750,  296]),
 4586: array([2804, 2791,  318, 1259, 1213, 2797,   39, 1617, 3176, 1213]),
 4569: array([ 608,   39, 1200, 1704, 2599, 1196,  318, 2797, 2916, 2858]),
 4560: array([ 260, 3418, 2396, 1580, 1291, 1198, 3793, 2000, 2174, 1387]),
 4557: array([1573, 2174, 2791, 1196,  296,  110, 1196,  296, 1097, 1270]),
 4555: array([ 457, 1036,  527,  296,  260, 2028, 2396, 3175,   32, 1784]),
 4552: array([1704, 1721, 2804,  356, 1394, 2804, 1291,  223,  110, 2706]),
 4544: array([1291,  318,  589, 1374,  924,  457,  919, 2699, 1193, 1270]),
 4542: array([ 296, 2762, 2797, 2683,  223,  648,  590, 2791, 1704, 1580]),
 4535: array([ 377, 1610, 1210, 2000, 2959,  541, 2000, 1240,  296,  608]),
 4533: array([2916, 2683, 2804,  648, 1704, 1721, 1221, 1193, 1704, 1784]),
 4531: array([2791, 1291, 1221, 1240,    1, 1270,  924, 1374, 2797, 1527]),
 4526: array([1210,  590, 1394,  924, 1240, 1259, 2797, 1923, 2174,  912]),
 4505: array([3793, 1270, 1968,  480, 2406, 1225, 1036,   50, 1304,  648]),
 4495: array([2291,  912, 2628, 1270, 1240, 1213, 1193, 1036,  296, 2804]),
 4493: array([ 541,  223,  919,  780, 1968, 2716, 2997,   50, 2683, 2762]),
 4482: array([ 924, 2918, 2291,  924,  593, 1196, 1127,  380,  260, 1225]),
 4480: array([2918, 2858, 1200,  318, 1230, 1610, 2916,  296, 1291, 2858]),
 4478: array([ 356, 1197, 1704,   32, 1127, 2762,   50,  223, 1097, 1197]),
 4477: array([1198,  380, 1198, 1136, 2699, 2174, 2791, 1097, 2858, 2396]),
 4473: array([2406, 2762, 1196,  380, 2791, 1259, 1374, 1213,  588, 1127]),
 4470: array([1374, 2706, 1127, 1240, 1220,  318, 1210, 3114, 1527,  593]),
 4444: array([ 223,  750,   39, 1193,  356,  912, 2762,  223,   32, 2355]),
 4440: array([ 912, 1374, 1213,  750,   39, 1230, 1704,  592,  457, 1210]),
 4423: array([  34, 2706,  110, 2000, 1617, 1193, 2762, 1304,  380, 3471]),
 4422: array([2291, 2628,  377, 1580,   50, 1036,   32, 2571,  380, 3175]),
 4419: array([1225, 1213, 2000, 2599,  380, 2396,  912,  260, 1221,  380]),
 4409: array([1923, 1240, 2987, 1610,  919,  527, 1214,   34,  912,   39]),
 4389: array([2000, 2987,   32, 1573,  924, 2355, 2997, 1923, 1923,  527]),
 4385: array([1200,  296,   39,  589, 1097,  457, 1291,  858,  377,  592]),
 4382: array([3418, 2571,  110, 2571, 1393, 3793,  377, 1394, 1136, 2628]),
 4377: array([ 912, 2291, 1210, 1968, 1387,  589, 2716,  780, 1200,    1]),
 4370: array([2174,   34, 1387, 1394, 2571, 1259, 1270,   39, 1265,  380]),
 4368: array([1617, 2916, 1968,  750,  527, 2997, 1225, 2916, 1097,  592]),
 4367: array([2571, 1923, 2706, 3481,    1, 1198, 1193, 3578, 2406,  648]),
 4345: array([1230, 3471, 1374, 1198,  589,  480, 1307, 1097, 1527,  110]),
 4344: array([1230,   32, 1580, 2028,  919, 3578,  457, 1213,  608,  608]),
 4340: array([2599, 2699,  296, 2804, 1200, 3578, 2571, 1193, 1387,   32]),
 4333: array([2396, 1265,  924,  589, 2762, 1704, 2406, 3114, 2762, 2699]),
 4319: array([1213, 1374, 1617, 3114, 1270, 1704, 1097, 1393, 2028, 3793]),
 4310: array([ 110, 2797, 1387, 3176, 3793,   50,  593, 1307,  780, 2028]),
 4306: array([1136, 1097, 2628, 2858,   50, 2997, 1270,  924,  318,  110]),
 4302: array([1127,  589, 2699, 1221, 2699, 1225, 1220, 2000, 1193, 1374]),
 4301: array([ 593,  223, 2916, 2858, 2628,  858, 1196,   32, 2571,  223]),
 4298: array([3175, 1374, 3578,  110, 1265, 2174, 1374, 2716, 1259, 1230]),
 4274: array([3481, 2791,  858, 1214,  377, 1291, 1265,  589, 1387, 1394]),
 4266: array([2396,   34, 1197,  858, 1721, 1240, 2716, 2699,  527, 1265]),
 4259: array([  39, 1610,  480, 1193, 1291,  356, 2000, 2174,  356,  380]),
 4223: array([3175, 3176,  593, 2916, 2959, 1584,  318, 1527, 1617, 2791]),
 4214: array([ 457, 1193, 1393, 1304, 1394,  356, 1230,  924, 3793, 2599]),
 4203: array([  32, 1968, 2355, 2174, 1393, 2987,  912, 1265, 1259, 1573]),
 4199: array([2174, 2997, 2000,  380,  608,  589,  919, 3793,  457, 3418]),
 4165: array([ 223,  377,   50,  480, 3418, 1584,  780,  912, 3471, 2599]),
 4164: array([ 110, 2918,   39, 3471, 2355, 1213,  356,   32,  858, 1200]),
 4162: array([2716, 3578,  541,  593, 1374,  780, 1230, 1265,   32,  527]),
 4185: array([2000, 1387,  780, 3793, 3418,  457,  223, 1265,    1,  457]),
 4155: array([2406, 1198,  919, 1193, 2683, 2355, 3176,  592, 2291, 3471]),
 4149: array([1197,  780, 1136, 1097, 1198,  110, 1784, 3793, 1240, 1304]),
 4148: array([2599,  380,  588, 1225, 1265,  590,  919,   34, 2174, 1968]),
 4147: array([2791, 2699,  527, 2571,  260,  380,   34,  924, 2174,  924]),
 4128: array([3114, 2028, 2396, 2804, 3175, 1197,  541, 3578,  296,    1]),
 4124: array([2959, 1580, 1214, 1127, 2000, 1225,   39,    1,  377,  260]),
 4114: array([1721, 2396, 1270, 2918,  527, 1221, 1580,  592,  590, 3114]),
 4089: array([ 750,  924, 1265, 2396, 2997, 1097, 2916, 2997, 1307, 2762]),
 4079: array([1704, 3578, 2797,  912, 1393,  924,    1, 1136, 3793,  924]),
 4078: array([1610, 1221, 1214,  457, 1393, 2918, 2571, 3176, 1374, 2028]),
 4076: array([2959, 1136,  588, 2355,  912,  457, 2916, 1721, 3418, 1584]),
 4069: array([1573, 1968, 1036, 3578,  590,  457, 2716, 1923, 1136, 1259]),
 4022: array([1923, 3176,  457, 1213, 2355, 2291, 2406, 2000, 1394, 1307]),
 4016: array([1225,   34, 2987, 1193, 2699, 1721, 2396,  480,  912, 2683]),
 3998: array([1221, 1291, 1394,  912, 1393,  648, 1304, 1784, 1704, 2028]),
 3987: array([1193, 2762,  912, 2762, 1036, 1200,  260,  608, 1036, 1270]),
 3963: array([3481, 3471, 2291,  527, 1394,  648,  919, 2858, 1213, 1394]),
 3957: array([1210, 2028, 2987,  912, 1221, 1193,  356, 2028, 1210, 2571]),
 3954: array([2599, 1784,  924, 1270, 2791, 1527,  858, 1387,  377, 2916]),
 3949: array([ 924, 1221, 1221, 1374, 1136, 2028, 2858, 2791, 1393, 1210]),
 3946: array([1270, 2918, 3175, 2628, 1097,   32, 1213,  648, 1240, 1213]),
 3945: array([1923,  457,  919, 1197,  648, 1210,  858, 1374, 1196, 1527]),
 3942: array([  34,  919,  377,  648, 3175, 1225, 3176, 1097, 2291, 1214]),
 3926: array([2699,  356,    1, 1374, 1784,  608, 1610, 1200, 1721, 1610]),
 3922: array([1527, 2804, 3793, 2918, 1584, 1265, 2959, 1573,  608, 1225]),
 3921: array([2599, 1200, 2355, 2355,  588, 3176, 2683, 3793, 1580,  588]),
 3898: array([ 110, 1197,  589, 1230, 1387, 2628,  593, 2791, 2959, 2699]),
 3896: array([1610, 1968,  750, 1393,  296, 2699,  912, 2804, 1198, 2571]),
 3891: array([1225, 2918,  527, 1584, 1580, 2797, 1097, 1270, 2683,  223]),
 3886: array([1580, 2571, 1721,  260,  592,  588, 3471, 2628, 1617, 2797]),
 3848: array([ 589,  377,  780,  592, 1097,  590, 2599, 2628, 1259,  589]),
 3844: array([ 780, 2716, 1198, 1610, 1291,  593, 1265,  593, 2918, 3578]),
 3842: array([1270, 1617, 1220,  356, 2797, 1127, 1265, 1214, 1196,  592]),
 3813: array([3578, 1387, 2396, 3418, 2997, 1291, 2706, 1374, 1968, 1225]),
 3807: array([ 527, 3176, 1610,   34,  356,  592, 1220, 2599, 1210, 1127]),
 3794: array([1304,  919, 1573, 2291,  589, 1610,  527, 2355, 2987, 2683]),
 3787: array([1923, 1127,  377, 1704, 3793,  648, 1784, 1527, 3418,  110]),
 3751: array([1221, 1127, 1036, 1213, 1374, 1193, 2716, 3175, 3481,  457]),
 3741: array([ 260, 1220, 1617, 1968, 2683,  296, 1200, 1240, 2762, 2396]),
 3736: array([1265, 3175,  377, 1196,  223, 2918, 1270,  223, 1210, 1291]),
 3734: array([1127, 1036, 2406,   39,  296, 3114, 2406, 2959, 1225,  924]),
 3725: array([1240,  912,  380,   39, 2797, 2291,  912,  457, 1193, 1387]),
 3724: array([ 380, 1610, 1394,  260, 3471, 1036, 2699, 1221, 1221,  608]),
 3721: array([2683, 2291, 1923, 2571, 2997, 2706,  480, 1036,   34, 2804]),
 3716: array([3481, 1584, 1240, 1136, 2291, 3176, 2858, 1220, 1259,  608]),
 3702: array([1721, 1784,  608,  480, 1584, 2804, 2396, 1393, 1393, 2699]),
 3691: array([2997, 3114, 2699, 1393, 1968, 1617,  593,  356,  589, 1617]),
 3681: array([1270,  590, 1136,  912, 2683, 2791,   34, 1097,  780,  527]),
 3675: array([1136, 2699,  377,    1, 2797, 3418, 1221,  356, 1374, 1265]),
 3662: array([2699,  457, 1259, 2959, 1196, 1097,  608,  919, 1610,  527]),
 3659: array([1200, 1573, 2804, 1196, 1704,  260, 1213, 2706, 1394, 2628]),
 3652: array([ 356, 1784,  380, 1240, 2858,  780, 1721,  780, 2804,  380]),
 3637: array([1784,  260, 3481, 3471,  919, 1136, 3418, 1393, 1610,  480]),
 3634: array([1721, 2797, 2028,  380, 1097, 1584, 1610, 2916, 2028, 1196]),
 3627: array([ 592,   50,  223, 2628,   39, 1230, 1580, 2174, 2804, 2916]),
 3622: array([ 589, 2706, 1221,  260,  223, 2918, 1270,  356, 1196, 2406]),

In [91]:
import torch
import torch.nn as nn
import torch.optim as optim
import pytorch_lightning as pl
from sentence_transformers import SentenceTransformer
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
from pytorch_lightning.callbacks import Callback
import pandas as pd

In [92]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [93]:
# full_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_fulldata_movielens.csv')
# train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_traindata_movielens.csv')
# val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_valdata_movielens.csv')
# test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_testdata_movielens.csv')

full_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ratings_fulldata_movielens.csv')
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/train_data.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/val_data.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/cold-start/test_data.csv')

movies = pd.read_csv('./processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')
users = pd.read_csv('processed_dataset/MovieLens-1M/users/users_movielens.csv')

In [94]:
movies['movie_features'] = '[MOVIE_DETAIL] title: ' + movies['title'] + ' [SEP] genres: ' + movies['genres']

In [95]:
# Create a dictionary for fast lookup
movie_features_dict = movies.set_index('item_id')['movie_features'].to_dict()

# Create lists of user and item texts
item_texts = [movie_features_dict[movieId] for movieId in full_ratings['item_id'].unique()]

# Create a mapping from userId and movieId to indices
movie_id_to_idx = {movieId: idx for idx, movieId in enumerate(full_ratings['item_id'].unique())}

# Map userId and movieId in ratings_df to indices
train_ratings['movie_idx'] = train_ratings['item_id'].map(movie_id_to_idx)

# Map userId and movieId in ratings_val to indices
val_ratings['movie_idx'] = val_ratings['item_id'].map(movie_id_to_idx)

# Map userId and movieId in ratings_test to indices
test_ratings['movie_idx'] = test_ratings['item_id'].map(movie_id_to_idx)

# Extract user indices, item indices, and ratings
train_item_indices = torch.LongTensor(train_ratings['movie_idx'].values).to(device)
train_labels = torch.FloatTensor(train_ratings['rating'].values).to(device)

# Extract user indices, item indices, and ratings for validation
val_item_indices = torch.LongTensor(val_ratings['movie_idx'].values).to(device)
val_labels = torch.FloatTensor(val_ratings['rating'].values).to(device)

# Extract user indices, item indices, and ratings for test
test_item_indices = torch.LongTensor(test_ratings['movie_idx'].values).to(device)
test_labels = torch.FloatTensor(test_ratings['rating'].values).to(device)

In [96]:
class TwoTowerModel(pl.LightningModule):
    def __init__(self, user_model_name, item_model_name, embedding_size=384):
        super(TwoTowerModel, self).__init__()
        self.user_model = SentenceTransformer(user_model_name)
        self.item_model = SentenceTransformer(item_model_name)

        self.user_fc = nn.Linear(embedding_size, embedding_size)
        self.item_fc = nn.Linear(embedding_size, embedding_size)

        self.criterion = nn.MSELoss()
        self.epoch_losses = {'train_loss': [], 'val_loss': []}

    def forward(self, user_text, item_text):
        user_embedding = self.user_model.encode(user_text, convert_to_tensor=True).to(device)
        item_embedding = self.item_model.encode(item_text, convert_to_tensor=True).to(device)

        user_output = self.user_fc(user_embedding)
        item_output = self.item_fc(item_embedding)

        dot_product = torch.matmul(user_output.squeeze(), item_output.T)
        dot_product = 4 * torch.sigmoid(dot_product) + 1

        return dot_product

    def training_step(self, batch, batch_idx):
        users, items, ratings = batch

        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        users, items, ratings = batch

        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('val_loss', loss)
        return loss

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=1e-5)


class PrintLossesCallback(Callback):
    def on_train_epoch_end(self, trainer, pl_module):
        train_loss = trainer.callback_metrics.get('train_loss')
        if train_loss is not None:
            pl_module.epoch_losses['train_loss'].append(train_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Train Loss: {train_loss.item()}")

    def on_validation_epoch_end(self, trainer, pl_module):
        val_loss = trainer.callback_metrics.get('val_loss')
        if val_loss is not None:
            pl_module.epoch_losses['val_loss'].append(val_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Val Loss: {val_loss.item()}")

In [97]:
best_model_path = './lightning_logs/version_0/checkpoints/epoch=4-step=62320.ckpt'
# best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L6-v2', item_model_name='paraphrase-MiniLM-L6-v2').to(device)
best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L12-v2',
                                                item_model_name='paraphrase-MiniLM-L12-v2').to(device)

D:\Anaconda\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [98]:
def generate_last_user_texts_with_history(users, movies, ratings):
    user_histories = {user_id: [] for user_id in users['user_id'].unique()}
    last_user_texts = {}

    # Convert relevant columns to dictionaries for faster access
    user_features_dict = users.set_index('user_id').to_dict('index')
    movie_titles_dict = movies.set_index('item_id')['genres'].to_dict()

    for _, row in ratings.iterrows():
        user_id = row['user_id']
        movie_id = row['item_id']

        # Get user features
        user = user_features_dict[user_id]
        user_features = f"[USER_PROFILE] occupation: {user['occupation']} [SEP] gender: {user['gender']}"

        # Append the user's history (only the last 3 movies)
        history_movies = [movie_titles_dict[mid] for mid in user_histories[user_id][-3:]]

        history_str = ", ".join(history_movies)

        if history_str:
            combined_features = f"{user_features} [SEP] genres: {history_str}"
        else:
            combined_features = f"{user_features}"

        # Update the dictionary to keep the last text for each user
        last_user_texts[user_id] = combined_features

        # Update the user history after generating combined features
        user_histories[user_id].append(movie_id)

    return last_user_texts


# Generate the last user texts for the validation data
val_last_user_texts = generate_last_user_texts_with_history(users, movies, test_ratings)

In [99]:
val_last_user_texts.get(5)

'[USER_PROFILE] occupation: writer [SEP] gender: Male [SEP] genres: Drama, Comedy, Drama, Comedy'

In [100]:
full_items_embeddings = torch.stack(
    [best_model.item_model.encode(item_text, convert_to_tensor=True) for item_text in item_texts]).to(device)

In [101]:
def get_top_n_items_with_history_unseen_items(model, userId, n):
    # Ensure the model is in evaluation mode
    model.eval()

    # Get the user text for the given userId
    user_text = val_last_user_texts[userId]
    # Encode the user text
    user_embedding = model.user_model.encode(user_text, convert_to_tensor=True).to(device)

    # Compute the scores (dot product between user embedding and each item embedding)
    user_output = model.user_fc(user_embedding).to(device)
    item_output = model.item_fc(full_items_embeddings).to(device)
    dot_product = torch.matmul(user_output, item_output.t()).squeeze()

    # Get items the user has seen in the training and validation data
    seen_items_train = train_ratings[train_ratings['user_id'] == userId]['item_id'].values
    seen_items_val = val_ratings[val_ratings['user_id'] == userId]['item_id'].values
    seen_items = set(np.concatenate((seen_items_train, seen_items_val)))

    # Get the top n + len(seen_items) item indices and their scores
    top_n_scores, top_n_indices = torch.topk(dot_product, n + len(seen_items))

    # Map indices back to item IDs
    top_n_item_ids = [list(movie_id_to_idx.keys())[list(movie_id_to_idx.values()).index(idx.item())] for idx in
                      top_n_indices]

    # Filter out seen items
    unseen_top_n_item_ids = [item for item in top_n_item_ids if item not in seen_items]
    # print(unseen_top_n_item_ids[:n])
    return unseen_top_n_item_ids[:n]

In [102]:
tt_recommendations = {}

for user in test_ratings['user_id'].unique():
    # Generate top N recommendations for the user using the Two-Tower model
    recommended_items = get_top_n_items_with_history_unseen_items(best_model, user, n=10)
    tt_recommendations[user] = recommended_items  # Store the recommendations in the dictionary

In [103]:
val_last_user_texts

{6032: "[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Animation, Children's, Musical, Animation, Children's, Musical, Animation, Children's",
 6026: '[USER_PROFILE] occupation: doctor/health care [SEP] gender: Male [SEP] genres: Adventure, War, Action, Drama, War, Drama',
 6025: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Female [SEP] genres: Comedy, Sci-Fi, Comedy, Comedy, Drama',
 6023: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Crime, Drama, Thriller, Crime, Thriller, Comedy, Crime',
 6017: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Female [SEP] genres: Comedy, Drama, Drama, Drama, Romance',
 6009: '[USER_PROFILE] occupation: programmer [SEP] gender: Female [SEP] genres: Action, Thriller, Action, Drama, Thriller, War, Action, Drama, Romance, Thriller',
 6008: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Action, Adventure, Sci-Fi, Action, Adventure, Fantasy, Sci-Fi, Action, Adventure, Sci-Fi',
 6003: '[USER_PROFILE] occupation: technician/engineer [SEP] gender: Female [SEP] genres: Comedy, Comedy, Crime, Mystery, Thriller, Drama',
 5996: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Action, Adventure, Drama, Action, Adventure, Drama, Romance, Comedy, Romance',
 5990: '[USER_PROFILE] occupation: writer [SEP] gender: Female [SEP] genres: Thriller, Comedy, Comedy, Romance',
 5976: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Female [SEP] genres: Drama, Drama, Romance, Comedy, Drama',
 5974: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Female [SEP] genres: Drama, Thriller, Drama, Action, Drama, War',
 5960: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Comedy, Drama, Adventure, Animation, Film-Noir, Comedy',
 5959: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Action, Comedy, War, Comedy, Drama, Drama, Musical',
 5955: "[USER_PROFILE] occupation: executive/managerial [SEP] gender: Female [SEP] genres: Comedy, Musical, Animation, Children's, Thriller",
 5951: "[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Drama, Animation, Children's, Comedy, Comedy, Drama",
 5945: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Drama, Drama, Drama',
 5937: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Mystery, Thriller, Comedy, Fantasy, Romance, Drama',
 5907: "[USER_PROFILE] occupation: artist [SEP] gender: Male [SEP] genres: Adventure, Children's, Drama, Musical, Crime, Thriller, Comedy, Drama",
 5883: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Animation, Comedy, Action, Thriller, Adventure, Animation, Film-Noir',
 5881: '[USER_PROFILE] occupation: technician/engineer [SEP] gender: Male [SEP] genres: Drama, Action, Adventure, Crime, Action, Adventure, Thriller',
 5872: '[USER_PROFILE] occupation: technician/engineer [SEP] gender: Male [SEP] genres: Comedy, Drama, Romance, Comedy, Horror, Comedy, Thriller',
 5871: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Drama, Action, Crime, Drama, War',
 5862: '[USER_PROFILE] occupation: homemaker [SEP] gender: Female [SEP] genres: Adventure, Comedy, Comedy, Comedy, Romance',
 5858: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Comedy, Sci-Fi, Drama, Action, Sci-Fi',
 5841: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Female [SEP] genres: Thriller, Comedy, Sci-Fi, Comedy',
 5840: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Drama, Thriller, Drama, Mystery, Thriller, Horror',
 5818: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Adventure, Animation, Film-Noir, Film-Noir, Sci-Fi, Crime, Film-Noir, Mystery, Thriller',
 5811: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Action, Adventure, Comedy, Drama, Romance, Action, Crime',
 5809: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Comedy, Comedy, Comedy, Drama, Romance',
 5806: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Female [SEP] genres: Drama, Drama, Drama',
 5800: "[USER_PROFILE] occupation: tradesman/craftsman [SEP] gender: Male [SEP] genres: Thriller, Action, Animation, Children's, Comedy",
 5785: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Female [SEP] genres: Comedy, Sci-Fi, Drama, Action, Crime, Drama',
 5780: '[USER_PROFILE] occupation: technician/engineer [SEP] gender: Male [SEP] genres: Sci-Fi, Thriller, Thriller, Sci-Fi, Thriller',
 5776: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Crime, Thriller, Drama, Romance, Drama, War',
 5760: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Comedy, Comedy, Drama, Comedy',
 5743: "[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Children's, Comedy, Drama, Drama, Drama, War",
 5742: "[USER_PROFILE] occupation: programmer [SEP] gender: Female [SEP] genres: Animation, Children's, Musical, Comedy, Drama, Musical, Animation, Children's, Comedy, Musical",
 5736: "[USER_PROFILE] occupation: academic/educator [SEP] gender: Male [SEP] genres: Comedy, Horror, Children's, Comedy, Comedy",
 5731: '[USER_PROFILE] occupation: lawyer [SEP] gender: Female [SEP] genres: Action, Adventure, Romance, Sci-Fi, War, Action, Adventure, Fantasy, Sci-Fi, Action, Adventure, Sci-Fi',
 5720: "[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Adventure, Fantasy, Animation, Children's, Fantasy, War, Comedy, Fantasy, Romance, Sci-Fi",
 5716: "[USER_PROFILE] occupation: K-12 student [SEP] gender: Male [SEP] genres: Children's, Comedy, Drama, Animation, Comedy, Documentary",
 5715: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Action, Crime, Action, Adventure, Action',
 5714: '[USER_PROFILE] occupation: artist [SEP] gender: Male [SEP] genres: Comedy, Drama, Adventure, Comedy, Sci-Fi, Action, Adventure, Fantasy, Sci-Fi',
 5693: "[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Children's, Drama, Fantasy, Sci-Fi, Drama, Drama",
 5688: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Drama, Thriller, Drama, Comedy, Drama',
 5668: '[USER_PROFILE] occupation: clerical/admin [SEP] gender: Female [SEP] genres: Comedy, Musical, Drama, Comedy, Horror',
 5666: '[USER_PROFILE] occupation: self-employed [SEP] gender: Male [SEP] genres: Drama, Action, Drama, Horror',
 5646: "[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Action, Children's, Comedy, Musical, Animation, Children's",
 5638: "[USER_PROFILE] occupation: academic/educator [SEP] gender: Male [SEP] genres: Action, Adventure, Drama, Action, Drama, Adventure, Children's, Drama",
 5631: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Drama, Action, Drama, War, Crime, Drama, Romance, Thriller',
 5629: '[USER_PROFILE] occupation: sales/marketing [SEP] gender: Male [SEP] genres: Drama, Drama, Drama',
 5619: "[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Action, Adventure, Fantasy, Adventure, Children's, Comedy, Fantasy, Sci-Fi, Children's, Fantasy, Musical",
 5613: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Comedy, Comedy, Romance, Comedy, Horror',
 5600: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Comedy, Drama, Action, Comedy, Crime, Drama, Comedy, Drama, Musical',
 5574: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Drama, Romance, Drama, Horror, Romance',
 5570: "[USER_PROFILE] occupation: academic/educator [SEP] gender: Male [SEP] genres: Action, Drama, Mystery, Thriller, Animation, Children's, Musical",
 5567: '[USER_PROFILE] occupation: clerical/admin [SEP] gender: Male [SEP] genres: Western, Action, Sci-Fi, Thriller, Western, Western',
 5566: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Drama, Drama, Drama',
 5563: "[USER_PROFILE] occupation: executive/managerial [SEP] gender: Female [SEP] genres: Crime, Drama, Drama, Children's, Drama, Fantasy, Sci-Fi",
 5538: "[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Romance, Animation, Children's, Fantasy, Musical, Horror, Sci-Fi",
 5533: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Action, Drama, War, Action, Adventure, Action, Adventure, Romance, War',
 5509: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Drama, Drama, Drama, Sci-Fi',
 5505: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Action, Thriller, Action, Drama, Thriller, Action, Thriller',
 5504: "[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Comedy, Comedy, Children's, Comedy",
 5501: '[USER_PROFILE] occupation: artist [SEP] gender: Male [SEP] genres: Comedy, Comedy, Action, Comedy',
 5495: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Action, Crime, Romance, Drama, Drama',
 5486: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Action, Adventure, Crime, Drama, Crime, Horror, Crime, Drama',
 5478: "[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Animation, Children's, Musical, Action, Adventure, Sci-Fi, Comedy, Romance",
 5475: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Comedy, Drama, Action, Romance',
 5463: "[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Adventure, Comedy, Drama, Comedy, Romance, Animation, Children's, Musical",
 5453: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Action, Horror, Sci-Fi, Thriller, Action, Adventure, Sci-Fi, Thriller, Film-Noir, Mystery',
 5440: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Comedy, Romance, Comedy, Drama, Comedy',
 5435: '[USER_PROFILE] occupation: tradesman/craftsman [SEP] gender: Male [SEP] genres: Action, Adventure, Fantasy, Sci-Fi, Action, Adventure, Sci-Fi, Drama, Sci-Fi',
 5417: '[USER_PROFILE] occupation: technician/engineer [SEP] gender: Male [SEP] genres: Sci-Fi, Horror, Sci-Fi, Adventure, Comedy, Sci-Fi',
 5414: '[USER_PROFILE] occupation: K-12 student [SEP] gender: Male [SEP] genres: Horror, Horror, Horror',
 5413: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Male [SEP] genres: Drama, Drama, Thriller, Thriller',
 5384: "[USER_PROFILE] occupation: clerical/admin [SEP] gender: Female [SEP] genres: Animation, Children's, Musical, Animation, Children's, Musical, Musical",
 5363: '[USER_PROFILE] occupation: retired [SEP] gender: Male [SEP] genres: Action, Crime, Action, Thriller, Action, Horror, Sci-Fi',
 5358: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Action, Adventure, Comedy, Crime, Action, Action, Adventure',
 5355: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Action, Thriller, Thriller, Horror, Thriller',
 5349: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Comedy, Horror, Drama',
 5344: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Female [SEP] genres: Comedy, Drama, Drama, Drama',
 5334: "[USER_PROFILE] occupation: retired [SEP] gender: Female [SEP] genres: Action, Drama, Animation, Children's",
 5330: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Drama, Action, Comedy, Crime, Drama, Drama, Romance, War',
 5328: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Horror, Horror, Thriller, Horror, Thriller',
 5298: '[USER_PROFILE] occupation: technician/engineer [SEP] gender: Male [SEP] genres: Action, Sci-Fi, Action, Adventure, Sci-Fi, Action, Sci-Fi',
 5293: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Action, Thriller, Adventure, Fantasy, Sci-Fi, Comedy',
 5285: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Comedy, Comedy, Drama, Action, Comedy, Musical',
 5277: '[USER_PROFILE] occupation: writer [SEP] gender: Male [SEP] genres: Action, Drama, Romance, Thriller, Comedy, Drama, War',
 5257: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Comedy, Horror, Musical, Sci-Fi, Comedy, Sci-Fi, Action, Adventure, Sci-Fi',
 5253: '[USER_PROFILE] occupation: retired [SEP] gender: Female [SEP] genres: Action, Adventure, Horror, Adventure, Drama, Thriller, Action, Adventure, Comedy, Crime',
 5246: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Comedy, Comedy, Comedy, Drama',
 5240: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Female [SEP] genres: Comedy, Romance, Comedy, Romance, Comedy, Drama, Romance',
 5235: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Action, Adventure, Drama, Sci-Fi, War, Film-Noir, Sci-Fi, Thriller, Action, Sci-Fi',
 5232: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Action, Comedy, Fantasy, Crime, Film-Noir, Mystery, Thriller, Film-Noir, Mystery, Thriller',
 5230: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Action, Adventure, Sci-Fi, Film-Noir, Sci-Fi, Action, Drama, War',
 5229: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Action, Adventure, Sci-Fi, War, Action, Adventure, Fantasy, Sci-Fi, Action, Drama, Sci-Fi, Thriller',
 5228: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Drama, Comedy, Thriller',
 5175: '[USER_PROFILE] occupation: homemaker [SEP] gender: Female [SEP] genres: Action, Drama, War, Action, Thriller, Action, Drama',
 5160: "[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Drama, Drama, War, Children's, Musical",
 5158: "[USER_PROFILE] occupation: college/grad student [SEP] gender: Female [SEP] genres: Drama, Musical, Comedy, Musical, Romance, Adventure, Children's, Comedy, Musical",
 5146: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Male [SEP] genres: Drama, Drama, Horror',
 5113: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Drama, Comedy, Drama, Action, Drama',
 5075: '[USER_PROFILE] occupation: doctor/health care [SEP] gender: Male [SEP] genres: Action, Adventure, Sci-Fi, Sci-Fi, Thriller, Horror, Sci-Fi',
 5044: '[USER_PROFILE] occupation: doctor/health care [SEP] gender: Female [SEP] genres: Drama, Drama, Drama',
 5042: "[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Drama, Romance, Film-Noir, Sci-Fi, Children's, Drama",
 5036: "[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Children's, Comedy, Action, Action, Sci-Fi, Western",
 5017: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Drama, Sci-Fi, Sci-Fi, Drama, Mystery, Sci-Fi, Thriller',
 5001: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Drama, Drama, Drama',
 5000: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Romance, Adventure, Comedy, Musical, Sci-Fi',
 4992: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Horror, Sci-Fi, Comedy, Drama, Romance',
 4982: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Action, Adventure, Sci-Fi, Thriller, Action, Adventure, Sci-Fi, Action, Comedy, Musical',
 4966: '[USER_PROFILE] occupation: sales/marketing [SEP] gender: Male [SEP] genres: Action, Sci-Fi, Thriller, Action, Horror, Sci-Fi, Thriller, Action, Sci-Fi',
 4965: '[USER_PROFILE] occupation: K-12 student [SEP] gender: Male [SEP] genres: Sci-Fi, Horror, Mystery, Thriller, Comedy',
 4964: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Western, Western, Western',
 4953: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Drama, War, Action, Drama, War, Drama, War',
 4942: '[USER_PROFILE] occupation: programmer [SEP] gender: Male [SEP] genres: Action, Comedy, Drama, Comedy, Western',
 4920: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Male [SEP] genres: Comedy, War, Action, Adventure, Fantasy, Sci-Fi, Documentary',
 4897: "[USER_PROFILE] occupation: self-employed [SEP] gender: Male [SEP] genres: Horror, Comedy, Thriller, Animation, Children's",
 4881: '[USER_PROFILE] occupation: self-employed [SEP] gender: Male [SEP] genres: Comedy, Romance, Comedy, Romance, Thriller',
 4878: '[USER_PROFILE] occupation: college/grad student [SEP] gender: Male [SEP] genres: Comedy, Comedy, Drama, Comedy, Drama',
 4876: '[USER_PROFILE] occupation: technician/engineer [SEP] gender: Female [SEP] genres: Comedy, Adventure, Comedy, Sci-Fi, Comedy, Romance',
 4867: '[USER_PROFILE] occupation: self-employed [SEP] gender: Male [SEP] genres: Comedy, Drama, Action, Sci-Fi',
 4863: '[USER_PROFILE] occupation: homemaker [SEP] gender: Female [SEP] genres: Comedy, Romance, Comedy, Romance, Comedy',
 4856: "[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Animation, Children's, Comedy, Animation, Comedy, Animation, Children's, Musical",
 4853: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Sci-Fi, Film-Noir, Sci-Fi, Comedy, Drama, Musical',
 4846: '[USER_PROFILE] occupation: artist [SEP] gender: Female [SEP] genres: Comedy, Comedy, Comedy',
 4845: '[USER_PROFILE] occupation: academic/educator [SEP] gender: Female [SEP] genres: Drama, Comedy, Drama, Drama',
 4840: '[USER_PROFILE] occupation: doctor/health care [SEP] gender: Female [SEP] genres: Comedy, Drama, Musical, Comedy, Crime, Fantasy',
 4819: '[USER_PROFILE] occupation: tradesman/craftsman [SEP] gender: Male [SEP] genres: Adventure, Drama, Romance, Drama, Drama',
 4818: "[USER_PROFILE] occupation: technician/engineer [SEP] gender: Female [SEP] genres: Action, Adventure, Animation, Animation, Children's, Musical, Animation, Children's, Comedy",
 4816: '[USER_PROFILE] occupation: doctor/health care [SEP] gender: Female [SEP] genres: Action, Thriller, Crime, Drama, Drama',
 4795: '[USER_PROFILE] occupation: self-employed [SEP] gender: Male [SEP] genres: Sci-Fi, Action, Drama, War, Crime, Film-Noir, Mystery, Thriller',
 4778: '[USER_PROFILE] occupation: other or not specified [SEP] gender: Male [SEP] genres: Comedy, Romance, Drama, Thriller, Thriller',
 4767: "[USER_PROFILE] occupation: homemaker [SEP] gender: Female [SEP] genres: Animation, Children's, Fantasy, Musical, Animation, Children's, Musical, Animation, Children's, Musical",
 4729: '[USER_PROFILE] occupation: self-employed [SEP] gender: Male [SEP] genres: Drama, Drama, Drama',
 4724: '[USER_PROFILE] occupation: doctor/health care [SEP] gender: Female [SEP] genres: Drama, Drama, Comedy',
 4704: '[USER_PROFILE] occupation: writer [SEP] gender: Male [SEP] genres: Film-Noir, Sci-Fi, Comedy, Drama, Sci-Fi, Drama, Thriller',
 4694: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Drama, Thriller, Sci-Fi, Action, Sci-Fi, Thriller',
 4688: '[USER_PROFILE] occupation: homemaker [SEP] gender: Male [SEP] genres: Drama, Thriller, Drama, Drama, Romance',
 4682: '[USER_PROFILE] occupation: executive/managerial [SEP] gender: Male [SEP] genres: Comedy, Documentary, Thriller',

In [104]:
cf_recommendations

{6032: array([1221, 1198, 3114,  527,  457, 2791, 2762, 2987, 2716,  223]),
 6026: array([3481, 2858, 1968, 2174,   50, 1127, 1784,   50,  589,   50]),
 6025: array([ 356, 2987, 2628, 2762, 1527,  608, 2291, 1374, 1721,  588]),
 6023: array([2858, 1214, 1265, 3114,  648, 1584,   50, 2628,   39, 2918]),
 6017: array([ 590,  780,  780, 2987,  592, 2997, 1220,  527, 1127,  457]),
 6009: array([2174, 2797,  588, 1784,  858, 1097, 1225, 2355, 2571, 3418]),
 6008: array([2174,  260, 1784, 1968, 1721, 1923, 1387, 1127, 1721, 1617]),
 6003: array([2396,  223, 2997, 1036, 2716, 2628, 1307, 2683,  780,  110]),
 5996: array([ 858, 1197, 1225,  457,   50, 1270,  780,  588,   34, 3793]),
 5990: array([1265, 2762, 1304,  589,  780,  457, 1196,  377, 3176,  589]),
 5976: array([ 380,  377, 2959, 2571, 1923, 1196, 1393, 3793, 3578, 2858]),
 5974: array([1721,  593, 1968, 1573, 2716, 2628,  318,  318, 1198,  858]),
 5960: array([3793, 1214, 1784,  380,  590,  377,  457,   39, 1097, 1127]),
 5959: array([3175,  592, 2000, 1394,  588,  919, 2706, 1197,  588,  527]),
 5955: array([3481,  919, 3176,  608, 1127, 1393,  480, 2716,  593, 2916]),
 5951: array([ 919, 1721,  356, 2396, 1197, 2804, 2406,  318, 1617, 2028]),
 5945: array([2406, 2291,  590,    1, 2174, 2028, 2918, 3114, 3578, 1374]),
 5937: array([2174,  924, 1265,  260, 2804, 1240, 1214, 2797,  356,   50]),
 5907: array([1374, 1307, 3793, 2858, 3175, 1221,  648, 2396, 2396,  590]),
 5883: array([2918,  380,  296, 2699,  296, 3793, 1197,  588, 3578, 2683]),
 5881: array([3578, 1394, 3175,  589, 1617, 2797, 1617,  296, 2000,  356]),
 5872: array([ 608, 1704, 2797, 1304, 1230,  608, 1193, 2628, 1393,  377]),
 5871: array([2571, 2599,  480,  296, 2959, 1036,  590, 3114,  223, 1291]),
 5862: array([2028, 1270, 1573, 1210,   50, 1196, 1214, 1307,  527, 1127]),
 5858: array([2699, 1270,  589,  296, 3418,   34,  648, 1210, 1304,  589]),
 5841: array([1374, 2762, 3481,    1, 1265, 3578, 2858, 1197, 1307, 1214]),
 5840: array([1259, 2683,  608,  919, 1265, 2355, 3578,  480, 1270, 3481]),
 5818: array([2028, 1784,  588, 1127,  457, 1573, 1527,  608, 3176, 1230]),
 5811: array([2762, 2028, 1374, 1270, 1968,  589, 2599, 2628, 2571,  589]),
 5809: array([1265, 2000, 1270, 2683, 1968,    1, 1527, 3793, 2918,  527]),
 5806: array([1374, 1610, 1527, 1221, 2918, 1200,  480,  608, 1923, 1304]),
 5800: array([ 541, 2599, 2858, 1210, 1036, 1704, 2804, 3471,  356,  380]),
 5785: array([1387, 3418,  527,  260, 2028, 2699,  593, 2804, 2959, 2762]),
 5780: array([1923, 2762, 2762, 3114, 1240,    1, 1617, 1968,  260,  858]),
 5776: array([1610, 2355, 2599, 2997, 2174, 3471, 2987,  356, 1610, 3114]),
 5760: array([2571, 1291, 2396, 1291, 2804,  377,  590, 1214,   39,  380]),
 5743: array([ 588,  592, 2174, 1213,   39,  223, 2791,  593, 2858, 2628]),
 5742: array([ 589, 2997, 1580, 1527, 2571, 1704, 1259,  527, 2291, 1220]),
 5736: array([1394, 1220, 1307, 2918, 2762, 3481,  592,  356, 1259, 1721]),
 5731: array([1196,  380, 1240, 1270, 3578,  750,  296,  377,  380, 1210]),
 5720: array([3471, 1240, 2599, 1265,  110, 1784, 2683, 1527, 2918, 1127]),
 5716: array([1617,    1, 2174, 1200, 2355, 1197,  924, 2628, 1198,  110]),
 5715: array([ 912,  541, 2571,  912, 1197, 1196,  110,  780, 2406,  858]),
 5714: array([1240,  858, 1259, 1374, 2916, 3793, 1584, 1230, 1291, 1374]),
 5693: array([ 588, 1784,    1,  110, 1198, 1225, 1610,    1, 1200, 1240]),
 5688: array([2683, 1721, 2706, 1214, 1221,  608, 1220,  912, 1610, 2791]),
 5668: array([ 296, 1230, 2355, 2918, 1210,  296, 2683,  593, 1580, 2683]),
 5666: array([1214,  296, 1291, 1617,  480, 2858, 1270, 2396, 2599,    1]),
 5646: array([1270, 1196, 1221,  223, 3578,  589,  318, 1387, 1265, 1220]),
 5638: array([ 590, 1200, 2406, 2916, 2762, 2804, 2406,  457, 1307,  527]),
 5631: array([2174, 2599, 2291, 1291, 2291, 1610,  380,  527, 2355, 2791]),
 5629: array([ 377, 2762, 2916, 2406, 1580,  648,   32, 1221, 1210, 1210]),
 5619: array([ 296, 1580, 2571, 1197, 1617,  750,  648, 1210, 1704,  110]),
 5613: array([1193, 1210, 2571,  110,  924, 1127, 1259, 1704, 2959, 2959]),
 5600: array([3114, 2000, 1387, 2628, 2355, 1196, 3176,   50, 3471, 2406]),
 5574: array([1387, 1923, 1221,  110,  260,  110, 1230, 1221,  457,  780]),
 5570: array([ 356, 2706, 2699,  593, 1374, 3578,  480,   39,  589, 1097]),
 5567: array([ 260, 1221, 1307, 2916, 1270, 1198, 2804, 2683, 2804,  377]),
 5566: array([2000, 1784, 1721,  924,    1, 2355,  589, 1617, 1304, 1923]),
 5563: array([1580, 2571,  593, 1394,  457, 2916, 1196, 1220,  924, 1394]),
 5538: array([2291, 2762, 2683, 1610, 1968, 1097,  223, 2804,   34, 2571]),
 5533: array([ 223, 1225, 1036, 3114,  318,  589, 1230, 2355,  296, 2599]),
 5509: array([ 260, 1270,  858, 3175,  541, 1265, 1259, 3578, 1213, 1291]),
 5505: array([1225, 2683,    1, 1393, 1213, 1265, 1200,  592, 3418,   50]),
 5504: array([2396, 1617, 1580, 2599, 1036, 3175, 2918, 3418, 1394,  110]),
 5501: array([1136, 1225, 1573, 2916,  919, 1584, 1210, 1213, 1198, 1584]),
 5495: array([1210,  260, 2916, 1097, 1387,    1, 1259, 1291, 1291, 2804]),
 5486: array([2355, 1291, 2918,  527,   32, 1923,  457,  527, 1200,  296]),
 5478: array([1136, 1923, 1307,  608,  457, 2797, 3578, 1136, 2599, 2916]),
 5475: array([2174,  919,  110,   50,  780, 2858, 1584, 1213, 1210, 1923]),
 5463: array([3481, 1196, 1197,  541, 1036, 2959, 1193, 1721, 1196, 3793]),
 5453: array([ 588, 1213, 3175,    1, 2406, 1210, 1240,  110, 1923, 2355]),
 5440: array([  39,   32, 1610,  912, 1097, 1291, 2797, 3176, 2000, 2804]),
 5435: array([1230, 1213,  924, 2762, 2716, 2706,  110,  919, 2599,  858]),
 5417: array([1220, 2174,  260,  858,  592, 1923,   39, 3481, 1270, 2959]),
 5414: array([1198, 1270, 2599, 1221, 2174, 3481,  589, 1213,  750,  780]),
 5413: array([1213, 1387, 1393,  480, 2706,  380,  380, 2791,  912,  541]),
 5384: array([ 356, 2706, 1036, 2959, 1580, 1784, 3793, 2699,  110, 2000]),
 5363: array([ 912,  377, 2028, 1221,    1, 1721, 2628,  924, 1704,  589]),
 5358: array([1784, 1374, 2028,  589, 3481, 1240, 1923, 1387, 1200,  296]),
 5355: array([3793, 1580,   34, 1200, 2396, 1259, 1213, 2918,  593, 2706]),
 5349: array([2706, 2599,   39, 1193, 3418, 2959, 1291,  527, 1610, 1393]),
 5344: array([1527,  780,  858,  592, 1270, 2396, 1291, 2699, 2916,  780]),
 5334: array([2916,  780, 2858, 1307, 1307,  457, 2716,  590, 1265,  480]),
 5330: array([ 480, 1225,  541, 1580, 2706, 2762, 3578,  260, 2918, 2599]),
 5328: array([3471, 2716, 2916, 2804, 3418, 1210, 2599,  380, 1610,  648]),
 5298: array([2858, 1210, 1210, 2396, 2699,  648, 1784,    1, 2804, 1617]),
 5293: array([1393, 1210,  260, 1270, 1394,  356, 3175, 1221, 1784, 1200]),
 5285: array([2858, 2987, 1240, 1304, 3471, 2571, 1394, 1270, 1721, 2987]),
 5277: array([1214, 2355,  457, 1394, 3176,  380,  924, 1036,  780, 1394]),
 5257: array([1610, 1127,   34,   50, 1610, 2797,  924, 2683, 3418, 1193]),
 5253: array([1393,  527, 2804,    1, 1291, 1240,  780, 1200, 2291,  593]),
 5246: array([ 750, 1393, 1291, 2000, 2599, 1617,  592, 2997, 2918, 1214]),
 5240: array([ 592, 1394, 1097, 1721, 1387,    1, 1136, 2699, 2858, 2406]),
 5235: array([3481, 1213, 1721,  541,  608, 3114,  380, 2628, 1374,  592]),
 5232: array([3471, 1200,  919, 2791, 3481, 1393, 2791, 3176, 3114, 2987]),
 5230: array([2858, 1721, 2174, 3176, 1374,  260, 1291,  592, 1387, 1193]),
 5229: array([2683, 1721, 2797, 1127,  296,  912, 2406, 1968, 2291,  608]),
 5228: array([1527,  858, 1220,  780,  588, 1584, 3471,  588, 1968,  223]),
 5175: array([ 527, 1270, 2000, 2683,  590, 1213, 1213, 1968, 1923,  223]),
 5160: array([1580, 1307, 2987, 1394, 1036, 2699,  924, 2918, 1580, 2804]),
 5158: array([2396,   50,  750, 3176, 2355, 2355,  480, 1220, 1196,  260]),
 5146: array([1221, 2858, 1197, 1704, 2291,    1, 1394, 1968,  318, 1374]),
 5113: array([1307,  380, 2396, 2628, 1214, 1200, 1225, 1304, 2000, 2000]),
 5075: array([1225,  780,  318,  110, 3578, 3793, 1221, 1193, 2355, 1220]),
 5044: array([2699, 1197, 1198,  858, 3481, 3175, 1923, 2174, 1610, 1240]),
 5042: array([1200, 2762,  912, 1240,    1, 1210, 1394, 2804, 1387,  377]),
 5036: array([  39,  912, 1704, 1193,  912, 1213, 1374, 1968, 1036, 1270]),
 5017: array([1393, 1225, 1265,    1, 1220, 2916,  380, 1784, 1923, 1196]),
 5001: array([2355, 1291,  750,  318, 1214,  527,  590, 2699, 2762, 2628]),
 5000: array([1214, 1225,  780, 1240, 2916, 1307, 2987, 2762, 3418, 1193]),
 4992: array([ 356, 2959,  592, 2396, 1270,  480,  590, 1704, 1394, 1704]),
 4982: array([  34, 1136, 2959,  919,  588, 1584, 2683, 2699,  919, 1198]),
 4966: array([2355,  592, 1573, 2987,    1,  780, 2683,  589, 2916,  318]),
 4965: array([2683, 1127,  593, 2716,  480, 1221, 2699, 1291, 1923,  592]),
 4964: array([1225,  457, 2406, 2628,  924, 2797, 1240, 2716,  110, 2858]),
 4953: array([1036, 1527,  318,  780, 2804, 1573, 2858, 1036, 2762,  858]),
 4942: array([ 858, 1721, 1617,  356,  318, 1259, 3793,  919, 2916,  912]),
 4920: array([1721, 1196, 1584,  588, 1968, 3114, 2599,  780,  541, 1259]),
 4897: array([2396,  223, 2916, 1240, 3176, 1036, 1704,  858,  296, 2959]),
 4881: array([3175, 2762,  750,   34,   32, 1200, 1291, 1573, 1225, 1097]),
 4878: array([2918,  588, 2174, 2762, 1265, 1097, 1580, 3471, 3176,  912]),
 4876: array([1307, 1573, 2791, 1221, 1136, 1214,  589, 1291, 3418, 1270]),
 4867: array([2997, 2716, 2683, 1036,  377, 2174,  296, 1374, 1210, 1198]),
 4863: array([ 380, 3793,  527,  924, 2028, 2918, 3471,  296, 1259, 2628]),
 4856: array([2987,  296,  858,  924, 3481,  590,    1, 1230, 2997,  588]),
 4853: array([1214, 2000, 1097,  590,  457, 2706,  593, 1036, 2396, 1225]),
 4846: array([2791, 2918, 2706,  377, 2028,  318, 2997,  588, 1393, 1221]),
 4845: array([1584,  858, 2918,  919,  858,  356, 2791, 3578, 2997, 3578]),
 4840: array([ 608, 3176,   50, 1580, 3114, 1225, 1259,  223, 1721, 1304]),
 4819: array([   1, 1210, 1200,   39, 1394, 1784, 2706,   50, 2916,   39]),
 4818: array([3114,    1,  296, 2706, 2028,  589, 1304, 2858,  527, 2699]),
 4816: array([1193, 2959, 2355, 2571, 1265,  590, 2571, 1307, 1200,   50]),
 4795: array([2406, 1968, 1721, 1259, 2987, 2797, 1210, 2628, 1968, 1704]),
 4778: array([2571, 1784, 2000, 2628, 3471, 2699, 1193, 1240,    1, 1307]),
 4767: array([ 480, 2355,  260, 1210,  924,  592, 1225,  593,  858, 1193]),
 4729: array([3114, 1527, 2797,  377,  589,  593, 2396,   32, 3578,  858]),
 4724: array([2918,  380,  924, 1225, 1304, 1374, 1923, 1265, 3471, 2406]),
 4704: array([2699, 3114, 3471, 1225, 3481, 1584,  750, 2987, 1304, 2791]),
 4694: array([2683,  380, 2804, 1136, 1221, 1197,  648, 1291,  912, 2918]),
 4688: array([3481, 2762,  924, 2959,  380, 1573, 1394, 3481, 3176, 1968]),
 4682: array([ 858, 1291, 2291, 1580, 3471, 2000, 2804, 2997, 1393,  780]),
 4669: array([3114,   32, 3114, 1393, 1197, 2959, 1220,  318,  356, 1221]),
 4668: array([2959, 2406, 1394, 1394,  780, 2174, 2997, 1127, 1265,  260]),
 4657: array([3481, 2683,  912, 1196, 2571, 1198, 1374, 1097,  356, 1923]),
 4647: array([2706,  590, 1214, 3114, 1097, 3481,  593,  592,  912, 3471]),
 4643: array([3175, 2396, 3471,  648, 1127,   50, 1200, 2355, 2716, 1240]),
 4640: array([ 296, 1196,   39, 2628, 1197, 2396, 1527, 1221, 2916,   34]),
 4634: array([ 593,  457,  858, 2683, 2028, 1193, 1394,  750,  912,  318]),
 4618: array([3578,  318,   32,    1,  648, 3793, 2804,   50, 3176,   34]),
 4614: array([2797,   32,  380, 1127, 1394, 1259, 1387, 1387, 2291, 1721]),
 4592: array([1270, 2683, 3471, 1580, 3176,   32,  593, 1387,  750,  296]),
 4586: array([2804, 2791,  318, 1259, 1213, 2797,   39, 1617, 3176, 1213]),
 4569: array([ 608,   39, 1200, 1704, 2599, 1196,  318, 2797, 2916, 2858]),
 4560: array([ 260, 3418, 2396, 1580, 1291, 1198, 3793, 2000, 2174, 1387]),
 4557: array([1573, 2174, 2791, 1196,  296,  110, 1196,  296, 1097, 1270]),
 4555: array([ 457, 1036,  527,  296,  260, 2028, 2396, 3175,   32, 1784]),
 4552: array([1704, 1721, 2804,  356, 1394, 2804, 1291,  223,  110, 2706]),
 4544: array([1291,  318,  589, 1374,  924,  457,  919, 2699, 1193, 1270]),
 4542: array([ 296, 2762, 2797, 2683,  223,  648,  590, 2791, 1704, 1580]),
 4535: array([ 377, 1610, 1210, 2000, 2959,  541, 2000, 1240,  296,  608]),
 4533: array([2916, 2683, 2804,  648, 1704, 1721, 1221, 1193, 1704, 1784]),
 4531: array([2791, 1291, 1221, 1240,    1, 1270,  924, 1374, 2797, 1527]),
 4526: array([1210,  590, 1394,  924, 1240, 1259, 2797, 1923, 2174,  912]),
 4505: array([3793, 1270, 1968,  480, 2406, 1225, 1036,   50, 1304,  648]),
 4495: array([2291,  912, 2628, 1270, 1240, 1213, 1193, 1036,  296, 2804]),
 4493: array([ 541,  223,  919,  780, 1968, 2716, 2997,   50, 2683, 2762]),
 4482: array([ 924, 2918, 2291,  924,  593, 1196, 1127,  380,  260, 1225]),
 4480: array([2918, 2858, 1200,  318, 1230, 1610, 2916,  296, 1291, 2858]),
 4478: array([ 356, 1197, 1704,   32, 1127, 2762,   50,  223, 1097, 1197]),
 4477: array([1198,  380, 1198, 1136, 2699, 2174, 2791, 1097, 2858, 2396]),
 4473: array([2406, 2762, 1196,  380, 2791, 1259, 1374, 1213,  588, 1127]),
 4470: array([1374, 2706, 1127, 1240, 1220,  318, 1210, 3114, 1527,  593]),
 4444: array([ 223,  750,   39, 1193,  356,  912, 2762,  223,   32, 2355]),
 4440: array([ 912, 1374, 1213,  750,   39, 1230, 1704,  592,  457, 1210]),
 4423: array([  34, 2706,  110, 2000, 1617, 1193, 2762, 1304,  380, 3471]),
 4422: array([2291, 2628,  377, 1580,   50, 1036,   32, 2571,  380, 3175]),
 4419: array([1225, 1213, 2000, 2599,  380, 2396,  912,  260, 1221,  380]),
 4409: array([1923, 1240, 2987, 1610,  919,  527, 1214,   34,  912,   39]),
 4389: array([2000, 2987,   32, 1573,  924, 2355, 2997, 1923, 1923,  527]),
 4385: array([1200,  296,   39,  589, 1097,  457, 1291,  858,  377,  592]),
 4382: array([3418, 2571,  110, 2571, 1393, 3793,  377, 1394, 1136, 2628]),
 4377: array([ 912, 2291, 1210, 1968, 1387,  589, 2716,  780, 1200,    1]),
 4370: array([2174,   34, 1387, 1394, 2571, 1259, 1270,   39, 1265,  380]),
 4368: array([1617, 2916, 1968,  750,  527, 2997, 1225, 2916, 1097,  592]),
 4367: array([2571, 1923, 2706, 3481,    1, 1198, 1193, 3578, 2406,  648]),
 4345: array([1230, 3471, 1374, 1198,  589,  480, 1307, 1097, 1527,  110]),
 4344: array([1230,   32, 1580, 2028,  919, 3578,  457, 1213,  608,  608]),
 4340: array([2599, 2699,  296, 2804, 1200, 3578, 2571, 1193, 1387,   32]),
 4333: array([2396, 1265,  924,  589, 2762, 1704, 2406, 3114, 2762, 2699]),
 4319: array([1213, 1374, 1617, 3114, 1270, 1704, 1097, 1393, 2028, 3793]),
 4310: array([ 110, 2797, 1387, 3176, 3793,   50,  593, 1307,  780, 2028]),
 4306: array([1136, 1097, 2628, 2858,   50, 2997, 1270,  924,  318,  110]),
 4302: array([1127,  589, 2699, 1221, 2699, 1225, 1220, 2000, 1193, 1374]),
 4301: array([ 593,  223, 2916, 2858, 2628,  858, 1196,   32, 2571,  223]),
 4298: array([3175, 1374, 3578,  110, 1265, 2174, 1374, 2716, 1259, 1230]),
 4274: array([3481, 2791,  858, 1214,  377, 1291, 1265,  589, 1387, 1394]),
 4266: array([2396,   34, 1197,  858, 1721, 1240, 2716, 2699,  527, 1265]),
 4259: array([  39, 1610,  480, 1193, 1291,  356, 2000, 2174,  356,  380]),
 4223: array([3175, 3176,  593, 2916, 2959, 1584,  318, 1527, 1617, 2791]),
 4214: array([ 457, 1193, 1393, 1304, 1394,  356, 1230,  924, 3793, 2599]),
 4203: array([  32, 1968, 2355, 2174, 1393, 2987,  912, 1265, 1259, 1573]),
 4199: array([2174, 2997, 2000,  380,  608,  589,  919, 3793,  457, 3418]),
 4165: array([ 223,  377,   50,  480, 3418, 1584,  780,  912, 3471, 2599]),
 4164: array([ 110, 2918,   39, 3471, 2355, 1213,  356,   32,  858, 1200]),
 4162: array([2716, 3578,  541,  593, 1374,  780, 1230, 1265,   32,  527]),
 4185: array([2000, 1387,  780, 3793, 3418,  457,  223, 1265,    1,  457]),
 4155: array([2406, 1198,  919, 1193, 2683, 2355, 3176,  592, 2291, 3471]),
 4149: array([1197,  780, 1136, 1097, 1198,  110, 1784, 3793, 1240, 1304]),
 4148: array([2599,  380,  588, 1225, 1265,  590,  919,   34, 2174, 1968]),
 4147: array([2791, 2699,  527, 2571,  260,  380,   34,  924, 2174,  924]),
 4128: array([3114, 2028, 2396, 2804, 3175, 1197,  541, 3578,  296,    1]),
 4124: array([2959, 1580, 1214, 1127, 2000, 1225,   39,    1,  377,  260]),
 4114: array([1721, 2396, 1270, 2918,  527, 1221, 1580,  592,  590, 3114]),
 4089: array([ 750,  924, 1265, 2396, 2997, 1097, 2916, 2997, 1307, 2762]),
 4079: array([1704, 3578, 2797,  912, 1393,  924,    1, 1136, 3793,  924]),
 4078: array([1610, 1221, 1214,  457, 1393, 2918, 2571, 3176, 1374, 2028]),
 4076: array([2959, 1136,  588, 2355,  912,  457, 2916, 1721, 3418, 1584]),
 4069: array([1573, 1968, 1036, 3578,  590,  457, 2716, 1923, 1136, 1259]),
 4022: array([1923, 3176,  457, 1213, 2355, 2291, 2406, 2000, 1394, 1307]),
 4016: array([1225,   34, 2987, 1193, 2699, 1721, 2396,  480,  912, 2683]),
 3998: array([1221, 1291, 1394,  912, 1393,  648, 1304, 1784, 1704, 2028]),
 3987: array([1193, 2762,  912, 2762, 1036, 1200,  260,  608, 1036, 1270]),
 3963: array([3481, 3471, 2291,  527, 1394,  648,  919, 2858, 1213, 1394]),
 3957: array([1210, 2028, 2987,  912, 1221, 1193,  356, 2028, 1210, 2571]),
 3954: array([2599, 1784,  924, 1270, 2791, 1527,  858, 1387,  377, 2916]),
 3949: array([ 924, 1221, 1221, 1374, 1136, 2028, 2858, 2791, 1393, 1210]),
 3946: array([1270, 2918, 3175, 2628, 1097,   32, 1213,  648, 1240, 1213]),
 3945: array([1923,  457,  919, 1197,  648, 1210,  858, 1374, 1196, 1527]),
 3942: array([  34,  919,  377,  648, 3175, 1225, 3176, 1097, 2291, 1214]),
 3926: array([2699,  356,    1, 1374, 1784,  608, 1610, 1200, 1721, 1610]),
 3922: array([1527, 2804, 3793, 2918, 1584, 1265, 2959, 1573,  608, 1225]),
 3921: array([2599, 1200, 2355, 2355,  588, 3176, 2683, 3793, 1580,  588]),
 3898: array([ 110, 1197,  589, 1230, 1387, 2628,  593, 2791, 2959, 2699]),
 3896: array([1610, 1968,  750, 1393,  296, 2699,  912, 2804, 1198, 2571]),
 3891: array([1225, 2918,  527, 1584, 1580, 2797, 1097, 1270, 2683,  223]),
 3886: array([1580, 2571, 1721,  260,  592,  588, 3471, 2628, 1617, 2797]),
 3848: array([ 589,  377,  780,  592, 1097,  590, 2599, 2628, 1259,  589]),
 3844: array([ 780, 2716, 1198, 1610, 1291,  593, 1265,  593, 2918, 3578]),
 3842: array([1270, 1617, 1220,  356, 2797, 1127, 1265, 1214, 1196,  592]),
 3813: array([3578, 1387, 2396, 3418, 2997, 1291, 2706, 1374, 1968, 1225]),
 3807: array([ 527, 3176, 1610,   34,  356,  592, 1220, 2599, 1210, 1127]),
 3794: array([1304,  919, 1573, 2291,  589, 1610,  527, 2355, 2987, 2683]),
 3787: array([1923, 1127,  377, 1704, 3793,  648, 1784, 1527, 3418,  110]),
 3751: array([1221, 1127, 1036, 1213, 1374, 1193, 2716, 3175, 3481,  457]),
 3741: array([ 260, 1220, 1617, 1968, 2683,  296, 1200, 1240, 2762, 2396]),
 3736: array([1265, 3175,  377, 1196,  223, 2918, 1270,  223, 1210, 1291]),
 3734: array([1127, 1036, 2406,   39,  296, 3114, 2406, 2959, 1225,  924]),
 3725: array([1240,  912,  380,   39, 2797, 2291,  912,  457, 1193, 1387]),
 3724: array([ 380, 1610, 1394,  260, 3471, 1036, 2699, 1221, 1221,  608]),
 3721: array([2683, 2291, 1923, 2571, 2997, 2706,  480, 1036,   34, 2804]),
 3716: array([3481, 1584, 1240, 1136, 2291, 3176, 2858, 1220, 1259,  608]),
 3702: array([1721, 1784,  608,  480, 1584, 2804, 2396, 1393, 1393, 2699]),
 3691: array([2997, 3114, 2699, 1393, 1968, 1617,  593,  356,  589, 1617]),
 3681: array([1270,  590, 1136,  912, 2683, 2791,   34, 1097,  780,  527]),
 3675: array([1136, 2699,  377,    1, 2797, 3418, 1221,  356, 1374, 1265]),
 3662: array([2699,  457, 1259, 2959, 1196, 1097,  608,  919, 1610,  527]),
 3659: array([1200, 1573, 2804, 1196, 1704,  260, 1213, 2706, 1394, 2628]),
 3652: array([ 356, 1784,  380, 1240, 2858,  780, 1721,  780, 2804,  380]),
 3637: array([1784,  260, 3481, 3471,  919, 1136, 3418, 1393, 1610,  480]),
 3634: array([1721, 2797, 2028,  380, 1097, 1584, 1610, 2916, 2028, 1196]),
 3627: array([ 592,   50,  223, 2628,   39, 1230, 1580, 2174, 2804, 2916]),
 3622: array([ 589, 2706, 1221,  260,  223, 2918, 1270,  356, 1196, 2406]),

In [105]:
tt_recommendations

{6032: [791, 1787, 3182, 363, 3207, 199, 793, 720, 3473, 1111],
 6026: [791, 1787, 3182, 363, 3207, 199, 793, 1111, 720, 2591],
 6025: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 6023: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 6017: [791, 1787, 3182, 363, 3207, 793, 720, 199, 3473, 1111],
 6009: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 2591],
 6008: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 6003: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 5996: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5990: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 5976: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5974: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5960: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5959: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5955: [791, 1787, 3182, 363, 3207, 199, 720, 793, 3473, 1111],
 5951: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5945: [791, 1787, 3182, 363, 3207, 793, 199, 720, 2591, 1111],
 5937: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5907: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5883: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5881: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5872: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5871: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5862: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 5858: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5841: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 3473],
 5840: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5818: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5811: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5809: [791, 1787, 3182, 363, 3207, 199, 720, 793, 3473, 1111],
 5806: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 2591],
 5800: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5785: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 3473],
 5780: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5776: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5760: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 3473],
 5743: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5742: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 3473],
 5736: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5731: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5720: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5716: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5715: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5714: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5693: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5688: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5668: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 5666: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5646: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5638: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5631: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5629: [791, 1787, 3182, 363, 3207, 199, 793, 1111, 720, 2591],
 5619: [791, 1787, 3182, 363, 3207, 793, 199, 720, 2591, 1111],
 5613: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5600: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5574: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5570: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5567: [791, 1787, 3182, 363, 3207, 199, 793, 3473, 720, 1111],
 5566: [791, 1787, 3182, 363, 3207, 199, 793, 720, 3473, 1111],
 5563: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 5538: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5533: [791, 1787, 3182, 363, 3207, 793, 199, 720, 2591, 1111],
 5509: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5505: [791, 1787, 3182, 363, 3207, 720, 793, 199, 2591, 1111],
 5504: [791, 1787, 3182, 363, 3207, 199, 720, 793, 3473, 1111],
 5501: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5495: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5486: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5478: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 5475: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5463: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5453: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5440: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 5435: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5417: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5414: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5413: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5384: [791, 1787, 3182, 363, 3207, 793, 199, 720, 3473, 1111],
 5363: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5358: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 5355: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5349: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5344: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5334: [791, 3182, 1787, 363, 3207, 199, 793, 720, 2591, 1111],
 5330: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5328: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5298: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5293: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5285: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5277: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5257: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5253: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5246: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 5240: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 5235: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5232: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5230: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5229: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5228: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 5175: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 5160: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5158: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5146: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5113: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5075: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 5044: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 3473],
 5042: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5036: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 5017: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 5001: [791, 1787, 3182, 363, 3207, 793, 199, 720, 2591, 1111],
 5000: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4992: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4982: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4966: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4965: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4964: [791, 1787, 3182, 363, 3207, 199, 793, 3473, 3277, 720],
 4953: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4942: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 3473],
 4920: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4897: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4881: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4878: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4876: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4867: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4863: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 4856: [791, 1787, 3182, 363, 3207, 199, 720, 793, 3473, 1111],
 4853: [791, 1787, 3182, 363, 3207, 199, 793, 720, 3473, 2591],
 4846: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 4845: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4840: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4819: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4818: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4816: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 2591],
 4795: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4778: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4767: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4729: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4724: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 4704: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4694: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 4688: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4682: [791, 1787, 3182, 363, 3207, 199, 720, 793, 3473, 1111],
 4669: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 4668: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4657: [791, 1787, 3182, 363, 3207, 199, 793, 1111, 720, 2591],
 4647: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4643: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4640: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4634: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4618: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4614: [791, 1787, 3182, 363, 3207, 720, 793, 199, 1111, 2591],
 4592: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4586: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4569: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4560: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4557: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4555: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4552: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4544: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4542: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4535: [791, 1787, 3182, 363, 3207, 793, 199, 720, 2591, 1111],
 4533: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4531: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4526: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4505: [791, 1787, 3182, 363, 3207, 199, 793, 720, 3473, 1111],
 4495: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4493: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 4482: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4480: [791, 1787, 3182, 363, 3207, 199, 793, 2591, 720, 3473],
 4478: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4477: [791, 1787, 3182, 363, 3207, 199, 793, 720, 3473, 1111],
 4473: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4470: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4444: [791, 1787, 3182, 363, 3207, 793, 199, 720, 2591, 1111],
 4440: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4423: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4422: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 4419: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4409: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4389: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4385: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4382: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4377: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4370: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4368: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4367: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4345: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 4344: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4340: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4333: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4319: [791, 1787, 3182, 363, 3207, 199, 720, 793, 3473, 1111],
 4310: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4306: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 4302: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4301: [791, 1787, 3182, 363, 3207, 199, 1111, 793, 720, 2591],
 4298: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4274: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4266: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4259: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4223: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4214: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4203: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4199: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 4165: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 4164: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4162: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4185: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4155: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4149: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4148: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 3473],
 4147: [791, 1787, 3182, 363, 3207, 720, 793, 199, 1111, 3473],
 4128: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4124: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4114: [791, 1787, 3182, 363, 3207, 199, 793, 1111, 720, 2591],
 4089: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 3473],
 4079: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4078: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 4076: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 4069: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 4022: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 4016: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3998: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3987: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 3963: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3957: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 3954: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3949: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3946: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 2591],
 3945: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3942: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3926: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3922: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3921: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 3898: [791, 1787, 3182, 363, 3207, 199, 720, 1111, 793, 2591],
 3896: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3891: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 3886: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3848: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3844: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3842: [791, 1787, 3182, 363, 3207, 720, 199, 793, 3473, 2591],
 3813: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3807: [791, 1787, 3182, 363, 3207, 720, 793, 199, 2591, 1111],
 3794: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3787: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 3751: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 2591],
 3741: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3736: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 3734: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3725: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3724: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3721: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3716: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3702: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3691: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3681: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3675: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 3473],
 3662: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3659: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3652: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3637: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3634: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 3627: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 3622: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3606: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 3603: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3598: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3597: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3591: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3588: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3582: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3562: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 3473],
 3540: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3539: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 722],
 3531: [791, 1787, 3182, 363, 3207, 720, 199, 1111, 793, 2591],
 3521: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3490: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3468: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3464: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3456: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3446: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3437: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 3420: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 3473],
 3417: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3411: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3407: [791, 1787, 3182, 363, 3207, 793, 720, 199, 1111, 3473],
 3394: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3390: [791, 1787, 3182, 363, 3207, 720, 199, 793, 1111, 2591],
 3378: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3359: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3357: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3333: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3294: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3289: [791, 1787, 3182, 363, 3207, 199, 793, 1111, 720, 2591],
 3287: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3265: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 2591],
 3252: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3241: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 2591],
 3237: [791, 1787, 3182, 363, 3207, 199, 720, 793, 1111, 3473],
 3231: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3220: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3214: [791, 1787, 3182, 363, 3207, 720, 199, 793, 3473, 1111],
 3212: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 3206: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3189: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3185: [791, 1787, 3182, 363, 3207, 199, 720, 793, 3473, 1111],
 3183: [791, 1787, 3182, 363, 3207, 199, 793, 720, 1111, 3473],
 3181: [791, 1787, 3182, 363, 3207, 199, 720, 793, 2591, 1111],
 3153: [791, 1787, 3182, 363, 3207, 720, 199, 793, 2591, 1111],
 3150: [791, 1787, 3182, 363, 3207, 793, 199, 720, 1111, 3473],
 3146: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3140: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],
 3124: [791, 1787, 3182, 363, 3207, 199, 793, 720, 2591, 1111],

In [106]:
def rrf_score(ranks, k=5):
    return sum([1 / (k + rank) for rank in ranks])

def combine_recommendations_with_rrf_with_weight(user_id, cf_recommendations, tt_recommendations, k=5, cf_weight=1,
                                                 tt_weight=4):
    # Create a dictionary to hold the RRF scores
    combined_scores = {}

    # Assign ranks and calculate weighted RRF scores from Collaborative Filtering recommendations
    for rank, item in enumerate(cf_recommendations[user_id], start=1):
        weighted_rank = rank * cf_weight  # Apply the weight to CF ranks
        if item not in combined_scores:
            combined_scores[item] = rrf_score([weighted_rank], k)
        else:
            combined_scores[item] += rrf_score([weighted_rank], k)

    # Assign ranks and calculate weighted RRF scores from Two-Tower recommendations
    for rank, item in enumerate(tt_recommendations[user_id], start=1):
        weighted_rank = rank * tt_weight  # Apply the weight to TT ranks
        if item not in combined_scores:
            combined_scores[item] = rrf_score([weighted_rank], k)
        else:
            combined_scores[item] += rrf_score([weighted_rank], k)

    # Sort the items based on their RRF scores in descending order
    sorted_items = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)

    # Return the top N items
    return [item for item, score in sorted_items[:k]]

In [107]:
final_recommendations_with_weight = {}
for user_id in test_ratings['user_id'].unique():
    final_recommendations_with_weight[user_id] = combine_recommendations_with_rrf_with_weight(user_id,
                                                                                              cf_recommendations,
                                                                                              tt_recommendations, k=10)

# Now final_recommendations contains the combined top N recommendations for each user
final_recommendations_with_weight

{6032: [1221, 1198, 3114, 527, 791, 457, 2791, 2762, 2987, 1787],
 6026: [50, 3481, 2858, 1968, 2174, 791, 1127, 1784, 1787, 589],
 6025: [356, 2987, 2628, 2762, 791, 1527, 608, 2291, 1374, 1787],
 6023: [2858, 1214, 1265, 3114, 791, 648, 1584, 50, 2628, 1787],
 6017: [780, 590, 2987, 791, 592, 2997, 1220, 527, 1787, 1127],
 6009: [2174, 2797, 588, 1784, 791, 858, 1097, 1225, 2355, 1787],
 6008: [1721, 2174, 260, 1784, 1968, 791, 1923, 1387, 1127, 1787],
 6003: [2396, 223, 2997, 1036, 791, 2716, 2628, 1307, 2683, 1787],
 5996: [858, 1197, 1225, 457, 791, 50, 1270, 780, 588, 1787],
 5990: [589, 1265, 2762, 1304, 791, 780, 457, 1196, 377, 1787],
 5976: [380, 377, 2959, 2571, 791, 1923, 1196, 1393, 3793, 1787],
 5974: [318, 1721, 593, 1968, 1573, 791, 2716, 2628, 1787, 1198],
 5960: [3793, 1214, 1784, 380, 791, 590, 377, 457, 39, 1787],
 5959: [588, 3175, 592, 2000, 1394, 791, 919, 2706, 1197, 1787],
 5955: [3481, 919, 3176, 608, 791, 1127, 1393, 480, 2716, 1787],
 5951: [919, 1721, 356, 2396, 791, 1197, 2804, 2406, 318, 1787],
 5945: [2406, 2291, 590, 1, 791, 2174, 2028, 2918, 3114, 1787],
 5937: [2174, 924, 1265, 260, 791, 2804, 1240, 1214, 2797, 1787],
 5907: [2396, 1374, 1307, 3793, 2858, 791, 3175, 1221, 648, 1787],
 5883: [296, 2918, 380, 2699, 791, 3793, 1197, 588, 1787, 3578],
 5881: [1617, 3578, 1394, 3175, 589, 791, 2797, 296, 1787, 2000],
 5872: [608, 1704, 2797, 1304, 791, 1230, 1193, 2628, 1787, 1393],
 5871: [2571, 2599, 480, 296, 791, 2959, 1036, 590, 3114, 1787],
 5862: [2028, 1270, 1573, 1210, 791, 50, 1196, 1214, 1307, 1787],
 5858: [589, 2699, 1270, 296, 791, 3418, 34, 648, 1210, 1787],
 5841: [1374, 2762, 3481, 1, 791, 1265, 3578, 2858, 1197, 1787],
 5840: [1259, 2683, 608, 919, 791, 1265, 2355, 3578, 480, 1787],
 5818: [2028, 1784, 588, 1127, 791, 457, 1573, 1527, 608, 1787],
 5811: [589, 2762, 2028, 1374, 1270, 791, 1968, 2599, 2628, 1787],
 5809: [1265, 2000, 1270, 2683, 791, 1968, 1, 1527, 3793, 1787],
 5806: [1374, 1610, 1527, 1221, 791, 2918, 1200, 480, 608, 1787],
 5800: [541, 2599, 2858, 1210, 791, 1036, 1704, 2804, 3471, 1787],
 5785: [1387, 3418, 527, 260, 791, 2028, 2699, 593, 2804, 1787],
 5780: [2762, 1923, 3114, 791, 1240, 1, 1617, 1968, 1787, 260],
 5776: [1610, 2355, 2599, 2997, 791, 2174, 3471, 2987, 356, 1787],
 5760: [1291, 2571, 2396, 791, 2804, 377, 590, 1214, 1787, 39],
 5743: [588, 592, 2174, 1213, 791, 39, 223, 2791, 593, 1787],
 5742: [589, 2997, 1580, 1527, 791, 2571, 1704, 1259, 527, 1787],
 5736: [1394, 1220, 1307, 2918, 791, 2762, 3481, 592, 356, 1787],
 5731: [380, 1196, 1240, 1270, 791, 3578, 750, 296, 377, 1787],
 5720: [3471, 1240, 2599, 1265, 791, 110, 1784, 2683, 1527, 1787],
 5716: [1617, 1, 2174, 1200, 791, 2355, 1197, 924, 2628, 1787],
 5715: [912, 541, 2571, 791, 1197, 1196, 110, 780, 1787, 2406],
 5714: [1374, 1240, 858, 1259, 791, 2916, 3793, 1584, 1230, 1787],
 5693: [1, 588, 1784, 110, 791, 1198, 1225, 1610, 1787, 1200],
 5688: [2683, 1721, 2706, 1214, 791, 1221, 608, 1220, 912, 1787],
 5668: [296, 2683, 1230, 2355, 2918, 791, 1210, 593, 1787, 1580],
 5666: [1214, 296, 1291, 1617, 791, 480, 2858, 1270, 2396, 1787],
 5646: [1270, 1196, 1221, 223, 791, 3578, 589, 318, 1387, 1787],
 5638: [2406, 590, 1200, 2916, 791, 2762, 2804, 457, 1787, 1307],
 5631: [2291, 2174, 2599, 1291, 791, 1610, 380, 527, 1787, 2355],
 5629: [1210, 377, 2762, 2916, 2406, 791, 1580, 648, 32, 1221],
 5619: [296, 1580, 2571, 1197, 791, 1617, 750, 648, 1210, 1787],
 5613: [2959, 1193, 1210, 2571, 110, 791, 924, 1127, 1259, 1704],
 5600: [3114, 2000, 1387, 2628, 791, 2355, 1196, 3176, 50, 1787],
 5574: [110, 1221, 1387, 1923, 791, 260, 1230, 1787, 457, 780],
 5570: [356, 2706, 2699, 593, 791, 1374, 3578, 480, 39, 1787],
 5567: [2804, 260, 1221, 1307, 2916, 791, 1270, 1198, 2683, 1787],
 5566: [2000, 1784, 1721, 924, 791, 1, 2355, 589, 1617, 1787],
 5563: [1394, 1580, 2571, 593, 791, 457, 2916, 1196, 1220, 1787],
 5538: [2291, 2762, 2683, 1610, 791, 1968, 1097, 223, 2804, 1787],
 5533: [223, 1225, 1036, 3114, 791, 318, 589, 1230, 2355, 1787],
 5509: [260, 1270, 858, 3175, 791, 541, 1265, 1259, 3578, 1787],
 5505: [1225, 2683, 1, 1393, 791, 1213, 1265, 1200, 592, 1787],
 5504: [2396, 1617, 1580, 2599, 791, 1036, 3175, 2918, 3418, 1787],
 5501: [1584, 1136, 1225, 1573, 2916, 791, 919, 1210, 1213, 1787],
 5495: [1291, 1210, 260, 2916, 1097, 791, 1387, 1, 1259, 1787],
 5486: [527, 2355, 1291, 2918, 791, 32, 1923, 457, 1787, 1200],
 5478: [1136, 1923, 1307, 608, 791, 457, 2797, 3578, 1787, 2599],
 5475: [2174, 919, 110, 50, 791, 780, 2858, 1584, 1213, 1787],
 5463: [1196, 3481, 1197, 541, 791, 1036, 2959, 1193, 1721, 1787],
 5453: [588, 1213, 3175, 1, 791, 2406, 1210, 1240, 110, 1787],
 5440: [39, 32, 1610, 912, 791, 1097, 1291, 2797, 3176, 1787],
 5435: [1230, 1213, 924, 2762, 791, 2716, 2706, 110, 919, 1787],
 5417: [1220, 2174, 260, 858, 791, 592, 1923, 39, 3481, 1787],
 5414: [1198, 1270, 2599, 1221, 791, 2174, 3481, 589, 1213, 1787],
 5413: [380, 1213, 1387, 1393, 480, 791, 2706, 2791, 1787, 912],
 5384: [356, 2706, 1036, 2959, 791, 1580, 1784, 3793, 2699, 1787],
 5363: [912, 377, 2028, 1221, 791, 1, 1721, 2628, 924, 1787],
 5358: [1784, 1374, 2028, 589, 791, 3481, 1240, 1923, 1387, 1787],
 5355: [3793, 1580, 34, 1200, 791, 2396, 1259, 1213, 2918, 1787],
 5349: [2706, 2599, 39, 1193, 791, 3418, 2959, 1291, 527, 1787],
 5344: [780, 1527, 858, 592, 791, 1270, 2396, 1291, 2699, 1787],
 5334: [1307, 2916, 780, 2858, 791, 457, 2716, 590, 3182, 1265],
 5330: [480, 1225, 541, 1580, 791, 2706, 2762, 3578, 260, 1787],
 5328: [3471, 2716, 2916, 2804, 791, 3418, 1210, 2599, 380, 1787],
 5298: [1210, 2858, 2396, 791, 2699, 648, 1784, 1, 1787, 2804],
 5293: [1393, 1210, 260, 1270, 791, 1394, 356, 3175, 1221, 1787],
 5285: [2987, 2858, 1240, 1304, 791, 3471, 2571, 1394, 1270, 1787],
 5277: [1394, 1214, 2355, 457, 791, 3176, 380, 924, 1036, 1787],
 5257: [1610, 1127, 34, 50, 791, 2797, 924, 2683, 1787, 3418],
 5253: [1393, 527, 2804, 1, 791, 1291, 1240, 780, 1200, 1787],
 5246: [750, 1393, 1291, 2000, 791, 2599, 1617, 592, 2997, 1787],
 5240: [592, 1394, 1097, 1721, 791, 1387, 1, 1136, 2699, 1787],
 5235: [3481, 1213, 1721, 541, 791, 608, 3114, 380, 2628, 1787],
 5232: [2791, 3471, 1200, 919, 791, 3481, 1393, 3176, 1787, 3114],
 5230: [2858, 1721, 2174, 3176, 791, 1374, 260, 1291, 592, 1787],
 5229: [2683, 1721, 2797, 1127, 791, 296, 912, 2406, 1968, 1787],
 5228: [588, 1527, 858, 1220, 780, 791, 1584, 3471, 1787, 1968],
 5175: [1213, 527, 1270, 2000, 2683, 791, 590, 1968, 1787, 1923],
 5160: [1580, 1307, 2987, 1394, 791, 1036, 2699, 924, 2918, 1787],
 5158: [2355, 2396, 50, 750, 3176, 791, 480, 1220, 1787, 1196],
 5146: [1221, 2858, 1197, 1704, 791, 2291, 1, 1394, 1968, 1787],
 5113: [2000, 1307, 380, 2396, 2628, 791, 1214, 1200, 1225, 1304],
 5075: [1225, 780, 318, 110, 791, 3578, 3793, 1221, 1193, 1787],
 5044: [2699, 1197, 1198, 858, 791, 3481, 3175, 1923, 2174, 1787],
 5042: [1200, 2762, 912, 1240, 791, 1, 1210, 1394, 2804, 1787],
 5036: [912, 39, 1704, 1193, 791, 1213, 1374, 1968, 1787, 1036],
 5017: [1393, 1225, 1265, 1, 791, 1220, 2916, 380, 1784, 1787],
 5001: [2355, 1291, 750, 318, 791, 1214, 527, 590, 2699, 1787],
 5000: [1214, 1225, 780, 1240, 791, 2916, 1307, 2987, 2762, 1787],
 4992: [1704, 356, 2959, 592, 2396, 791, 1270, 480, 590, 1787],
 4982: [919, 34, 1136, 2959, 791, 588, 1584, 2683, 2699, 1787],
 4966: [2355, 592, 1573, 2987, 791, 1, 780, 2683, 589, 1787],
 4965: [2683, 1127, 593, 2716, 791, 480, 1221, 2699, 1291, 1787],
 4964: [1225, 457, 2406, 2628, 791, 924, 2797, 1240, 2716, 1787],
 4953: [1036, 1527, 318, 780, 791, 2804, 1573, 2858, 1787, 2762],
 4942: [858, 1721, 1617, 356, 791, 318, 1259, 3793, 919, 1787],
 4920: [1721, 1196, 1584, 588, 791, 1968, 3114, 2599, 780, 1787],
 4897: [2396, 223, 2916, 1240, 791, 3176, 1036, 1704, 858, 1787],
 4881: [3175, 2762, 750, 34, 791, 32, 1200, 1291, 1573, 1787],
 4878: [2918, 588, 2174, 2762, 791, 1265, 1097, 1580, 3471, 1787],
 4876: [1307, 1573, 2791, 1221, 791, 1136, 1214, 589, 1291, 1787],
 4867: [2997, 2716, 2683, 1036, 791, 377, 2174, 296, 1374, 1787],
 4863: [380, 3793, 527, 924, 791, 2028, 2918, 3471, 296, 1787],
 4856: [2987, 296, 858, 924, 791, 3481, 590, 1, 1230, 1787],
 4853: [1214, 2000, 1097, 590, 791, 457, 2706, 593, 1036, 1787],
 4846: [2791, 2918, 2706, 377, 791, 2028, 318, 2997, 588, 1787],
 4845: [858, 3578, 1584, 2918, 919, 791, 356, 2791, 1787, 2997],
 4840: [608, 3176, 50, 1580, 791, 3114, 1225, 1259, 223, 1787],
 4819: [39, 1, 1210, 1200, 791, 1394, 1784, 2706, 50, 1787],
 4818: [3114, 1, 296, 2706, 791, 2028, 589, 1304, 2858, 1787],
 4816: [2571, 1193, 2959, 2355, 791, 1265, 590, 1307, 1787, 1200],
 4795: [1968, 2406, 1721, 1259, 791, 2987, 2797, 1210, 2628, 1787],
 4778: [2571, 1784, 2000, 2628, 791, 3471, 2699, 1193, 1240, 1787],
 4767: [480, 2355, 260, 1210, 791, 924, 592, 1225, 593, 1787],
 4729: [3114, 1527, 2797, 377, 791, 589, 593, 2396, 32, 1787],
 4724: [2918, 380, 924, 1225, 791, 1304, 1374, 1923, 1265, 1787],
 4704: [2699, 3114, 3471, 1225, 791, 3481, 1584, 750, 2987, 1787],
 4694: [2683, 380, 2804, 1136, 791, 1221, 1197, 648, 1291, 1787],
 4688: [3481, 2762, 924, 2959, 791, 380, 1573, 1394, 1787, 3176],
 4682: [858, 1291, 2291, 1580, 791, 3471, 2000, 2804, 2997, 1787],
 4669: [3114, 32, 1393, 791, 1197, 2959, 1220, 318, 1787, 356],
 4668: [1394, 2959, 2406, 791, 780, 2174, 2997, 1127, 1787, 1265],
 4657: [3481, 2683, 912, 1196, 791, 2571, 1198, 1374, 1097, 1787],
 4647: [2706, 590, 1214, 3114, 791, 1097, 3481, 593, 592, 1787],
 4643: [3175, 2396, 3471, 648, 791, 1127, 50, 1200, 2355, 1787],
 4640: [296, 1196, 39, 2628, 791, 1197, 2396, 1527, 1221, 1787],
 4634: [593, 457, 858, 2683, 791, 2028, 1193, 1394, 750, 1787],
 4618: [3578, 318, 32, 1, 791, 648, 3793, 2804, 50, 1787],
 4614: [1387, 2797, 32, 380, 1127, 791, 1394, 1259, 1787, 2291],
 4592: [1270, 2683, 3471, 1580, 791, 3176, 32, 593, 1387, 1787],
 4586: [1213, 2804, 2791, 318, 1259, 791, 2797, 39, 1617, 1787],
 4569: [608, 39, 1200, 1704, 791, 2599, 1196, 318, 2797, 1787],
 4560: [260, 3418, 2396, 1580, 791, 1291, 1198, 3793, 2000, 1787],
 4557: [1196, 296, 1573, 2174, 2791, 791, 110, 1787, 1097, 1270],
 4555: [457, 1036, 527, 296, 791, 260, 2028, 2396, 3175, 1787],
 4552: [2804, 1704, 1721, 356, 791, 1394, 1291, 223, 1787, 110],
 4544: [1291, 318, 589, 1374, 791, 924, 457, 919, 2699, 1787],
 4542: [296, 2762, 2797, 2683, 791, 223, 648, 590, 2791, 1787],
 4535: [2000, 377, 1610, 1210, 791, 2959, 541, 1240, 1787, 296],
 4533: [1704, 2916, 2683, 2804, 648, 791, 1721, 1221, 1193, 1787],
 4531: [2791, 1291, 1221, 1240, 791, 1, 1270, 924, 1374, 1787],
 4526: [1210, 590, 1394, 924, 791, 1240, 1259, 2797, 1923, 1787],
 4505: [3793, 1270, 1968, 480, 791, 2406, 1225, 1036, 50, 1787],
 4495: [2291, 912, 2628, 1270, 791, 1240, 1213, 1193, 1036, 1787],
 4493: [541, 223, 919, 780, 791, 1968, 2716, 2997, 50, 1787],
 4482: [924, 2918, 2291, 791, 593, 1196, 1127, 380, 1787, 260],
 4480: [2858, 2918, 1200, 318, 791, 1230, 1610, 2916, 296, 1787],
 4478: [1197, 356, 1704, 32, 791, 1127, 2762, 50, 223, 1787],
 4477: [1198, 380, 1136, 791, 2699, 2174, 2791, 1097, 1787, 2858],
 4473: [2406, 2762, 1196, 380, 791, 2791, 1259, 1374, 1213, 1787],
 4470: [1374, 2706, 1127, 1240, 791, 1220, 318, 1210, 3114, 1787],
 4444: [223, 750, 39, 1193, 791, 356, 912, 2762, 1787, 32],
 4440: [912, 1374, 1213, 750, 791, 39, 1230, 1704, 592, 1787],
 4423: [34, 2706, 110, 2000, 791, 1617, 1193, 2762, 1304, 1787],
 4422: [2291, 2628, 377, 1580, 791, 50, 1036, 32, 2571, 1787],
 4419: [380, 1225, 1213, 2000, 2599, 791, 2396, 912, 260, 1787],
 4409: [1923, 1240, 2987, 1610, 791, 919, 527, 1214, 34, 1787],
 4389: [1923, 2000, 2987, 32, 1573, 791, 924, 2355, 2997, 1787],
 4385: [1200, 296, 39, 589, 791, 1097, 457, 1291, 858, 1787],
 4382: [2571, 3418, 110, 791, 1393, 3793, 377, 1394, 1787, 1136],
 4377: [912, 2291, 1210, 1968, 791, 1387, 589, 2716, 780, 1787],
 4370: [2174, 34, 1387, 1394, 791, 2571, 1259, 1270, 39, 1787],
 4368: [2916, 1617, 1968, 750, 791, 527, 2997, 1225, 1787, 1097],
 4367: [2571, 1923, 2706, 3481, 791, 1, 1198, 1193, 3578, 1787],
 4345: [1230, 3471, 1374, 1198, 791, 589, 480, 1307, 1097, 1787],
 4344: [608, 1230, 32, 1580, 2028, 791, 919, 3578, 457, 1213],
 4340: [2599, 2699, 296, 2804, 791, 1200, 3578, 2571, 1193, 1787],
 4333: [2762, 2396, 1265, 924, 589, 791, 1704, 2406, 3114, 1787],
 4319: [1213, 1374, 1617, 3114, 791, 1270, 1704, 1097, 1393, 1787],
 4310: [110, 2797, 1387, 3176, 791, 3793, 50, 593, 1307, 1787],
 4306: [1136, 1097, 2628, 2858, 791, 50, 2997, 1270, 924, 1787],
 4302: [2699, 1127, 589, 1221, 791, 1225, 1220, 2000, 1787, 1193],
 4301: [223, 593, 2916, 2858, 791, 2628, 858, 1196, 32, 1787],
 4298: [1374, 3175, 3578, 110, 791, 1265, 2174, 2716, 1787, 1259],
 4274: [3481, 2791, 858, 1214, 791, 377, 1291, 1265, 589, 1787],
 4266: [2396, 34, 1197, 858, 791, 1721, 1240, 2716, 2699, 1787],
 4259: [356, 39, 1610, 480, 1193, 791, 1291, 2000, 2174, 1787],
 4223: [3175, 3176, 593, 2916, 791, 2959, 1584, 318, 1527, 1787],
 4214: [457, 1193, 1393, 1304, 791, 1394, 356, 1230, 924, 1787],
 4203: [32, 1968, 2355, 2174, 791, 1393, 2987, 912, 1265, 1787],
 4199: [2174, 2997, 2000, 380, 791, 608, 589, 919, 3793, 1787],
 4165: [223, 377, 50, 480, 791, 3418, 1584, 780, 912, 1787],
 4164: [110, 2918, 39, 3471, 791, 2355, 1213, 356, 32, 1787],
 4162: [2716, 3578, 541, 593, 791, 1374, 780, 1230, 1265, 1787],
 4185: [457, 2000, 1387, 780, 3793, 791, 3418, 223, 1265, 1787],
 4155: [2406, 1198, 919, 1193, 791, 2683, 2355, 3176, 592, 1787],
 4149: [1197, 780, 1136, 1097, 791, 1198, 110, 1784, 3793, 1787],
 4148: [2599, 380, 588, 1225, 791, 1265, 590, 919, 34, 1787],
 4147: [924, 2791, 2699, 527, 2571, 791, 260, 380, 34, 1787],
 4128: [3114, 2028, 2396, 2804, 791, 3175, 1197, 541, 3578, 1787],
 4124: [2959, 1580, 1214, 1127, 791, 2000, 1225, 39, 1, 1787],
 4114: [1721, 2396, 1270, 2918, 791, 527, 1221, 1580, 592, 1787],
 4089: [2997, 750, 924, 1265, 2396, 791, 1097, 2916, 1787, 1307],
 4079: [924, 1704, 3578, 2797, 912, 791, 1393, 1, 1136, 1787],
 4078: [1610, 1221, 1214, 457, 791, 1393, 2918, 2571, 3176, 1787],
 4076: [2959, 1136, 588, 2355, 791, 912, 457, 2916, 1721, 1787],
 4069: [1573, 1968, 1036, 3578, 791, 590, 457, 2716, 1923, 1787],
 4022: [1923, 3176, 457, 1213, 791, 2355, 2291, 2406, 2000, 1787],
 4016: [1225, 34, 2987, 1193, 791, 2699, 1721, 2396, 480, 1787],
 3998: [1221, 1291, 1394, 912, 791, 1393, 648, 1304, 1784, 1787],
 3987: [2762, 1036, 1193, 912, 791, 1200, 260, 608, 1787, 1270],
 3963: [1394, 3481, 3471, 2291, 527, 791, 648, 919, 2858, 1787],
 3957: [1210, 2028, 2987, 912, 791, 1221, 1193, 356, 1787, 2571],
 3954: [2599, 1784, 924, 1270, 791, 2791, 1527, 858, 1387, 1787],
 3949: [1221, 924, 1374, 791, 1136, 2028, 2858, 2791, 1787, 1393],
 3946: [1213, 1270, 2918, 3175, 2628, 791, 1097, 32, 648, 1787],
 3945: [1923, 457, 919, 1197, 791, 648, 1210, 858, 1374, 1787],
 3942: [34, 919, 377, 648, 791, 3175, 1225, 3176, 1097, 1787],
 3926: [1610, 2699, 356, 1, 1374, 791, 1784, 608, 1200, 1787],
 3922: [1527, 2804, 3793, 2918, 791, 1584, 1265, 2959, 1573, 1787],
 3921: [2355, 588, 2599, 1200, 791, 3176, 2683, 3793, 1787, 1580],
 3898: [110, 1197, 589, 1230, 791, 1387, 2628, 593, 2791, 1787],
 3896: [1610, 1968, 750, 1393, 791, 296, 2699, 912, 2804, 1787],
 3891: [1225, 2918, 527, 1584, 791, 1580, 2797, 1097, 1270, 1787],
 3886: [1580, 2571, 1721, 260, 791, 592, 588, 3471, 2628, 1787],
 3848: [589, 377, 780, 592, 791, 1097, 590, 2599, 2628, 1787],
 3844: [593, 780, 2716, 1198, 1610, 791, 1291, 1265, 1787, 2918],
 3842: [1270, 1617, 1220, 356, 791, 2797, 1127, 1265, 1214, 1787],
 3813: [3578, 1387, 2396, 3418, 791, 2997, 1291, 2706, 1374, 1787],
 3807: [527, 3176, 1610, 34, 791, 356, 592, 1220, 2599, 1787],
 3794: [1304, 919, 1573, 2291, 791, 589, 1610, 527, 2355, 1787],
 3787: [1923, 1127, 377, 1704, 791, 3793, 648, 1784, 1527, 1787],
 3751: [1221, 1127, 1036, 1213, 791, 1374, 1193, 2716, 3175, 1787],
 3741: [260, 1220, 1617, 1968, 791, 2683, 296, 1200, 1240, 1787],
 3736: [223, 1265, 3175, 377, 1196, 791, 2918, 1270, 1787, 1210],
 3734: [2406, 1127, 1036, 39, 791, 296, 3114, 2959, 1787, 1225],
 3725: [912, 1240, 380, 39, 791, 2797, 2291, 457, 1787, 1193],
 3724: [1221, 380, 1610, 1394, 260, 791, 3471, 1036, 2699, 1787],
 3721: [2683, 2291, 1923, 2571, 791, 2997, 2706, 480, 1036, 1787],
 3716: [3481, 1584, 1240, 1136, 791, 2291, 3176, 2858, 1220, 1787],
 3702: [1393, 1721, 1784, 608, 480, 791, 1584, 2804, 2396, 1787],
 3691: [1617, 2997, 3114, 2699, 1393, 791, 1968, 593, 356, 1787],
 3681: [1270, 590, 1136, 912, 791, 2683, 2791, 34, 1097, 1787],
 3675: [1136, 2699, 377, 1, 791, 2797, 3418, 1221, 356, 1787],
 3662: [2699, 457, 1259, 2959, 791, 1196, 1097, 608, 919, 1787],
 3659: [1200, 1573, 2804, 1196, 791, 1704, 260, 1213, 2706, 1787],
 3652: [380, 780, 356, 1784, 1240, 791, 2858, 1721, 1787, 2804],
 3637: [1784, 260, 3481, 3471, 791, 919, 1136, 3418, 1393, 1787],
 3634: [2028, 1721, 2797, 380, 791, 1097, 1584, 1610, 2916, 1787],
 3627: [592, 50, 223, 2628, 791, 39, 1230, 1580, 2174, 1787],
 3622: [589, 2706, 1221, 260, 791, 223, 2918, 1270, 356, 1787],
 3606: [608, 260, 1394, 912, 1136, 791, 380, 1584, 1196, 1787],
 3603: [1291, 593, 2628, 377, 791, 1304, 1200, 1230, 2699, 1787],
 3598: [2706, 2959, 912, 780, 791, 750, 1610, 1265, 2699, 1787],
 3597: [3793, 1136, 2028, 1387, 791, 1584, 2628, 2599, 3481, 1787],
 3591: [457, 2599, 2355, 1704, 791, 592, 1374, 858, 3471, 1787],
 3588: [3793, 1584, 1220, 2699, 791, 592, 1307, 1198, 2987, 1787],
 3582: [924, 1136, 2762, 1374, 791, 1210, 1240, 2706, 1787, 1198],
 3562: [1197, 912, 593, 1230, 791, 1307, 2997, 1193, 1787, 2959],
 3540: [1617, 2959, 1584, 318, 791, 260, 2406, 1213, 1573, 1787],
 3539: [912, 318, 2997, 1221, 1580, 791, 223, 588, 1036, 1787],
 3531: [2396, 3418, 2959, 2762, 791, 1136, 377, 1097, 608, 1787],
 3521: [912, 858, 3793, 480, 791, 1259, 2000, 924, 1721, 1787],
 3490: [1573, 3471, 3578, 2396, 223, 791, 2797, 1394, 1787, 592],
 3468: [1307, 1196, 296, 1573, 791, 1127, 1393, 1610, 1787, 588],
 3464: [50, 2706, 3471, 791, 1197, 1387, 2174, 1787, 2028, 1374],
 3456: [592, 318, 2396, 1704, 791, 356, 1230, 1573, 2406, 1787],
 3446: [1240, 912, 1196, 2858, 2918, 791, 1214, 2174, 1787, 1265],
 3437: [1721, 2628, 318, 1259, 791, 1307, 356, 50, 2000, 1787],
 3420: [2683, 110, 2762, 2628, 1240, 791, 260, 3176, 1214, 1787],
 3417: [750, 1580, 50, 592, 791, 3114, 2858, 1291, 2683, 1787],
 3411: [1214, 2628, 1, 1200, 791, 3175, 480, 296, 1787, 457],
 3407: [2706, 2918, 588, 1291, 791, 1580, 1393, 3175, 2797, 1787],
 3394: [2355, 1240, 1610, 1304, 791, 260, 110, 223, 1291, 1787],
 3390: [3793, 1584, 32, 2916, 791, 1213, 2628, 3578, 2797, 1787],
 3378: [1136, 1214, 480, 2291, 791, 3418, 1304, 1193, 3793, 1787],
 3359: [2916, 2997, 3176, 32, 791, 527, 1923, 2396, 1307, 1787],
 3357: [2699, 3793, 1584, 791, 2628, 2571, 1393, 39, 1787, 296],
 3333: [2174, 1270, 480, 2804, 791, 1387, 1198, 3793, 541, 1787],
 3294: [2628, 2174, 3418, 1193, 791, 1220, 780, 3175, 1225, 1787],
 3289: [1394, 1374, 858, 919, 791, 1923, 1721, 1240, 2916, 1787],
 3287: [590, 1198, 1240, 791, 377, 2699, 1213, 1923, 1787, 3481],
 3265: [2699, 592, 1580, 2858, 791, 296, 1196, 1259, 1787, 1221],
 3252: [1573, 1387, 2997, 3481, 2571, 791, 780, 1196, 2918, 1787],
 3241: [1721, 1784, 1127, 2858, 791, 110, 3175, 919, 1394, 1787],
 3237: [3471, 1265, 2987, 608, 791, 2916, 1136, 1573, 1787, 912],
 3231: [2706, 1220, 608, 1307, 791, 1198, 318, 1214, 2174, 1787],
 3220: [1, 1721, 590, 1527, 791, 858, 1304, 593, 2000, 1787],
 3214: [1573, 39, 3481, 2791, 791, 1304, 1210, 1610, 480, 1787],
 3212: [2797, 750, 2628, 2699, 791, 1610, 2918, 1573, 648, 1787],
 3206: [1036, 3793, 3481, 2355, 791, 1198, 2571, 260, 1787, 32],
 3189: [1923, 2291, 2762, 1580, 791, 541, 39, 480, 1265, 1787],
 3185: [1527, 2797, 1387, 2762, 791, 1259, 1213, 296, 2291, 1787],
 3183: [356, 608, 2959, 1127, 791, 1240, 2997, 1270, 1221, 1787],

In [108]:
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count

def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0

def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_ratings['user_id'].unique()

    for user in unique_users:
        # Get the recommended items for the user
        recommended_items = final_recommendations[user]

        # Get the actual items the user interacted with in the test set
        user_test_data = test_ratings[test_ratings['user_id'] == user]
        test_items = user_test_data['item_id'].values

        # Create a binary relevance score list (1 if item is in the test set, 0 otherwise)
        y_score = [1 if item in test_items else 0 for item in recommended_items]

        # Calculate the evaluation metrics
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        # Store the scores
        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # Compute average scores
    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
        'Recall@{}'.format(k): avg_recall,
        'MRR@{}'.format(k): avg_mrr,
    }

# Evaluate the final recommendations
eval_result = evaluate_final_recommendations(final_recommendations_with_weight, test_ratings, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_19440\2627640135.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@10': 0.6606512471627343, 'Recall@10': 0.01885157423096693, 'MRR@10': 0.4631793335435719}

In [109]:
def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_ratings['user_id'].unique()

    for user in unique_users:
        # Get the recommended items for the user
        recommended_items = final_recommendations[user]

        # Get the actual items the user interacted with in the test set
        user_test_data = test_ratings[test_ratings['user_id'] == user]
        test_items = user_test_data['item_id'].values

        # Create a binary relevance score list (1 if item is in the test set, 0 otherwise)
        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 2.5
            for item in recommended_items
        ]
        # Calculate the evaluation metrics
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        # Store the scores
        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # Compute average scores
    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }


# Evaluate the final recommendations
eval_result = evaluate_final_recommendations(final_recommendations_with_weight, test_ratings, k=10)
print(eval_result)

{'NDCG@10': 0.9292338814597455}

In [110]:
def evaluate_final_recommendations(final_recommendations, test_ratings, k=5):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_ratings['user_id'].unique()

    for user in unique_users:
        # Get the recommended items for the user
        recommended_items = final_recommendations[user]

        # Get the actual items the user interacted with in the test set
        user_test_data = test_ratings[test_ratings['user_id'] == user]
        test_items = user_test_data['item_id'].values

        # Create a binary relevance score list (1 if item is in the test set, 0 otherwise)
        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 0
            for item in recommended_items
        ]
        # Calculate the evaluation metrics
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        # Store the scores
        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # Compute average scores
    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
    }


# Evaluate the final recommendations
eval_result = evaluate_final_recommendations(final_recommendations_with_weight, test_ratings, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_19440\2627640135.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@10': 0.6515561044175682}