In [3]:
!pip install -U sentence-transformers

Collecting sentence-transformers
  Using cached sentence_transformers-3.0.1-py3-none-any.whl (227 kB)
Requirement already satisfied: numpy in d:\anaconda\lib\site-packages (from sentence-transformers) (1.24.3)
Requirement already satisfied: torch>=1.11.0 in d:\anaconda\lib\site-packages (from sentence-transformers) (2.3.1)
Requirement already satisfied: huggingface-hub>=0.15.1 in d:\anaconda\lib\site-packages (from sentence-transformers) (0.23.4)
Requirement already satisfied: Pillow in d:\anaconda\lib\site-packages (from sentence-transformers) (10.4.0)
Requirement already satisfied: scipy in d:\anaconda\lib\site-packages (from sentence-transformers) (1.10.1)
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in d:\anaconda\lib\site-packages (from sentence-transformers) (4.41.2)
Requirement already satisfied: scikit-learn in d:\anaconda\lib\site-packages (from sentence-transformers) (1.4.2)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: packaging>=20.9 in d:\anaconda\lib\site-packages (from huggingface-hub>=0.15.1->sentence-transformers) (24.1)
Requirement already satisfied: fsspec>=2023.5.0 in d:\anaconda\lib\site-packages (from huggingface-hub>=0.15.1->sentence-transformers) (2024.5.0)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda\lib\site-packages (from huggingface-hub>=0.15.1->sentence-transformers) (6.0.1)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from huggingface-hub>=0.15.1->sentence-transformers) (2.32.3)
Requirement already satisfied: filelock in d:\anaconda\lib\site-packages (from huggingface-hub>=0.15.1->sentence-transformers) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\anaconda\lib\site-packages (from huggingface-hub>=0.15.1->sentence-transformers) (4.11.0)
Requirement already satisfied: sympy in d:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.13.2)
Requirement already satisfied: networkx in d:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in d:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in d:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (2021.4.0)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: safetensors>=0.4.1 in d:\anaconda\lib\site-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers) (0.4.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in d:\anaconda\lib\site-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers) (0.19.1)
Requirement already satisfied: regex!=2019.12.17 in d:\anaconda\lib\site-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers) (2024.7.24)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: tbb==2021.* in d:\anaconda\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.11.0->sentence-transformers) (2021.13.1)
Requirement already satisfied: intel-openmp==2021.* in d:\anaconda\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.11.0->sentence-transformers) (2021.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (2024.7.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\anaconda\lib\site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-3.0.1

In [2]:
!pip install transformers==4.34.0

Collecting transformers==4.34.0
  Downloading transformers-4.34.0-py3-none-any.whl (7.7 MB)
     ---------------------------------------- 7.7/7.7 MB 954.2 kB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in d:\anaconda\lib\site-packages (from transformers==4.34.0) (4.66.5)
Requirement already satisfied: regex!=2019.12.17 in d:\anaconda\lib\site-packages (from transformers==4.34.0) (2024.7.24)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda\lib\site-packages (from transformers==4.34.0) (6.0.1)
Collecting tokenizers<0.15,>=0.14
  Downloading tokenizers-0.14.1-cp310-none-win_amd64.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 965.0 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in d:\anaconda\lib\site-packages (from transformers==4.34.0) (1.24.3)
Requirement already satisfied: filelock in d:\anaconda\lib\site-packages (from transformers==4.34.0) (3.13.1)
Requirement already satisfied: packaging>=20.0 in d:\anaconda\lib\site-packages (from transformers==4.34.0) (24.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in d:\anaconda\lib\site-packages (from transformers==4.34.0) (0.23.4)
Requirement already satisfied: safetensors>=0.3.1 in d:\anaconda\lib\site-packages (from transformers==4.34.0) (0.4.3)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from transformers==4.34.0) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\anaconda\lib\site-packages (from huggingface-hub<1.0,>=0.16.4->transformers==4.34.0) (4.11.0)
Requirement already satisfied: fsspec>=2023.5.0 in d:\anaconda\lib\site-packages (from huggingface-hub<1.0,>=0.16.4->transformers==4.34.0) (2024.5.0)
Collecting huggingface-hub<1.0,>=0.16.4
  Using cached huggingface_hub-0.17.3-py3-none-any.whl (295 kB)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm>=4.27->transformers==4.34.0) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests->transformers==4.34.0) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->transformers==4.34.0) (2.2.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests->transformers==4.34.0) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests->transformers==4.34.0) (2024.7.4)
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.23.4
    Uninstalling huggingface-hub-0.23.4:
      Successfully uninstalled huggingface-hub-0.23.4
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.13.3
    Uninstalling tokenizers-0.13.3:
      Successfully uninstalled tokenizers-0.13.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.24.0
    Uninstalling transformers-4.24.0:
      Successfully uninstalled transformers-4.24.0
Successfully installed huggingface-hub-0.17.3 tokenizers-0.14.1 transformers-4.34.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 2.20.0 requires huggingface-hub>=0.21.2, but you have huggingface-hub 0.17.3 which is incompatible.

In [5]:
!pip install huggingface-hub==0.21.2

Collecting huggingface-hub==0.21.2
  Downloading huggingface_hub-0.21.2-py3-none-any.whl (346 kB)
     ------------------------------------ 346.2/346.2 kB 796.0 kB/s eta 0:00:00
Requirement already satisfied: packaging>=20.9 in d:\anaconda\lib\site-packages (from huggingface-hub==0.21.2) (24.1)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda\lib\site-packages (from huggingface-hub==0.21.2) (6.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in d:\anaconda\lib\site-packages (from huggingface-hub==0.21.2) (2024.5.0)
Requirement already satisfied: tqdm>=4.42.1 in d:\anaconda\lib\site-packages (from huggingface-hub==0.21.2) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\anaconda\lib\site-packages (from huggingface-hub==0.21.2) (4.11.0)
Requirement already satisfied: filelock in d:\anaconda\lib\site-packages (from huggingface-hub==0.21.2) (3.13.1)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from huggingface-hub==0.21.2) (2.32.3)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm>=4.42.1->huggingface-hub==0.21.2) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests->huggingface-hub==0.21.2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests->huggingface-hub==0.21.2) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests->huggingface-hub==0.21.2) (2024.7.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->huggingface-hub==0.21.2) (2.2.2)
Installing collected packages: huggingface-hub
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.17.3
    Uninstalling huggingface-hub-0.17.3:
      Successfully uninstalled huggingface-hub-0.17.3
Successfully installed huggingface-hub-0.21.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tokenizers 0.14.1 requires huggingface_hub<0.18,>=0.16.4, but you have huggingface-hub 0.21.2 which is incompatible.

In [5]:
!pip install pyarrow --upgrade

Requirement already satisfied: pyarrow in d:\anaconda\lib\site-packages (16.1.0)
Collecting pyarrow
  Downloading pyarrow-17.0.0-cp310-cp310-win_amd64.whl (25.1 MB)
     -------------------------------------- 25.1/25.1 MB 950.0 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.6 in d:\anaconda\lib\site-packages (from pyarrow) (1.24.3)
Installing collected packages: pyarrow
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 16.1.0
    Uninstalling pyarrow-16.1.0:
      Successfully uninstalled pyarrow-16.1.0
Successfully installed pyarrow-17.0.0

In [1]:
import transformers
print(transformers.__version__)

D:\Anaconda\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

4.34.0

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import pytorch_lightning as pl
from sentence_transformers import SentenceTransformer
from torch.utils.data import DataLoader, TensorDataset
from pytorch_lightning.callbacks import Callback
import pandas as pd
import numpy as np
from pytorch_lightning.callbacks import ModelCheckpoint

D:\Anaconda\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
D:\Anaconda\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [3]:
# users = pd.read_csv('processed_dataset/MovieLens-1M/users/users_movielens_modified.csv')
users = pd.read_csv('processed_dataset/MovieLens-1M/users/users_movielens.csv')

# movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens_modified2.csv')
# movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens_modified.csv')
movies = pd.read_csv('processed_dataset/MovieLens-1M/movies/movies_movielens.csv')

full_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_full_movielens.csv')
train_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_train_movielens.csv')
val_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_val_movielens.csv')
test_ratings = pd.read_csv('processed_dataset/MovieLens-1M/ratings/ml_1m_test_movielens.csv')

In [4]:
# Combine user features into a single string for each user
users['user_features'] = 'occupation: ' + users['occupation'] + ' [SEP] age: ' + users['age'].astype(str) + ' [SEP] gender: ' + users['gender'].astype(str)

# Combine movie features into a single string for each movie
movies['movie_features'] = 'title: ' + movies['title'] + ' [SEP] genres: ' + movies['genres']

In [4]:
# Combine user features into a single string for each user
# users['user_features'] = '[USER_PROFILE] occupation: ' + users['occupation'] + ' [SEP] age: ' + users['age'].astype(str) + ' [SEP] gender: ' + users['gender'].astype(str)
users['user_features'] = '[USER_PROFILE] occupation: ' + users['occupation'] + ' [SEP] gender: ' + users['gender'].astype(str)

# Combine movie features into a single string for each movie
# movies['movie_features'] = '[MOVIE_DETAIL] title: ' + movies['title'] + ' genres: ' + movies['genres']
movies['movie_features'] = '[MOVIE_DETAIL] genres: ' + movies['genres']
# movies['movie_features'] = 'title: ' + movies['title'] + ' [SEP] genres: ' + movies['genres']

In [5]:
users

,user_id,gender,age,occupation,zip_code,user_features
0,1,Female,Under 18,K-12 student,48067,occupation: K-12 student [SEP] age: Under 18 [...
1,2,Male,56+,self-employed,70072,occupation: self-employed [SEP] age: 56+ [SEP]...
2,3,Male,25-34,scientist,55117,occupation: scientist [SEP] age: 25-34 [SEP] g...
3,4,Male,45-49,executive/managerial,02460,occupation: executive/managerial [SEP] age: 45...
4,5,Male,25-34,writer,55455,occupation: writer [SEP] age: 25-34 [SEP] gend...
...,...,...,...,...,...,...
6035,6036,Female,25-34,scientist,32603,occupation: scientist [SEP] age: 25-34 [SEP] g...
6036,6037,Female,45-49,academic/educator,76006,occupation: academic/educator [SEP] age: 45-49...
6037,6038,Female,56+,academic/educator,14706,occupation: academic/educator [SEP] age: 56+ [...
6038,6039,Female,45-49,other or not specified,01060,occupation: other or not specified [SEP] age: ...
6039,6040,Male,25-34,doctor/health care,11106,occupation: doctor/health care [SEP] age: 25-3...

In [6]:
movies

,item_id,title,genres,movie_features
0,1,Toy Story (1995),Animation|Children's|Comedy,title: Toy Story (1995) [SEP] genres: Animatio...
1,2,Jumanji (1995),Adventure|Children's|Fantasy,title: Jumanji (1995) [SEP] genres: Adventure|...
2,3,Grumpier Old Men (1995),Comedy|Romance,title: Grumpier Old Men (1995) [SEP] genres: C...
3,4,Waiting to Exhale (1995),Comedy|Drama,title: Waiting to Exhale (1995) [SEP] genres: ...
4,5,Father of the Bride Part II (1995),Comedy,title: Father of the Bride Part II (1995) [SEP...
...,...,...,...,...
3878,3948,Meet the Parents (2000),Comedy,title: Meet the Parents (2000) [SEP] genres: C...
3879,3949,Requiem for a Dream (2000),Drama,title: Requiem for a Dream (2000) [SEP] genres...
3880,3950,Tigerland (2000),Drama,title: Tigerland (2000) [SEP] genres: Drama
3881,3951,Two Family House (2000),Drama,title: Two Family House (2000) [SEP] genres: D...
3882,3952,"Contender, The (2000)",Drama|Thriller,"title: Contender, The (2000) [SEP] genres: Dra..."

In [7]:
# Create a dictionary for fast lookup
user_features_dict = users.set_index('user_id')['user_features'].to_dict()
movie_features_dict = movies.set_index('item_id')['movie_features'].to_dict()

# # Create lists of user and item texts
user_texts = [user_features_dict[userId] for userId in full_ratings['user_id'].unique()]
item_texts = [movie_features_dict[movieId] for movieId in full_ratings['item_id'].unique()]

# Create a mapping from userId and movieId to indices
user_id_to_idx = {userId: idx for idx, userId in enumerate(full_ratings['user_id'].unique())}
movie_id_to_idx = {movieId: idx for idx, movieId in enumerate(full_ratings['item_id'].unique())}

# Map userId and movieId in ratings_df to indices
train_ratings['user_idx'] = train_ratings['user_id'].map(user_id_to_idx)
train_ratings['movie_idx'] = train_ratings['item_id'].map(movie_id_to_idx)

# Map userId and movieId in ratings_val to indices
val_ratings['user_idx'] = val_ratings['user_id'].map(user_id_to_idx)
val_ratings['movie_idx'] = val_ratings['item_id'].map(movie_id_to_idx)

# Map userId and movieId in ratings_val to indices
test_ratings['user_idx'] = test_ratings['user_id'].map(user_id_to_idx)
test_ratings['movie_idx'] = test_ratings['item_id'].map(movie_id_to_idx)

# Extract user indices, item indices, and ratings
train_user_indices = torch.LongTensor(train_ratings['user_idx'].values).to(device)
train_item_indices = torch.LongTensor(train_ratings['movie_idx'].values).to(device)
train_labels = torch.FloatTensor(train_ratings['rating'].values).to(device)

# Extract user indices, item indices, and ratings for validation
val_user_indices = torch.LongTensor(val_ratings['user_idx'].values).to(device)
val_item_indices = torch.LongTensor(val_ratings['movie_idx'].values).to(device)
val_labels = torch.FloatTensor(val_ratings['rating'].values).to(device)

test_user_indices = torch.LongTensor(test_ratings['user_idx'].values).to(device)
test_item_indices = torch.LongTensor(test_ratings['movie_idx'].values).to(device)
test_labels = torch.FloatTensor(test_ratings['rating'].values).to(device)

In [8]:
train_ratings

        user_id  item_id  rating  timestamp  user_idx  movie_idx
0             1     3186       4  978300019      6033       1773
1             1     1022       5  978300055      6033        135
2             1     1721       4  978300055      6033        203
3             1     1270       5  978300055      6033        103
4             1     2340       3  978300103      6033       1649
...         ...      ...     ...        ...       ...        ...
797753     6040     2612       5  960971797         0       1909
797754     6040     2303       5  960971857         0        292
797755     6040     3504       4  960971857         0        224
797756     6040     1449       3  960971857         0       1396
797757     6040     3334       5  960971875         0        593

[797758 rows x 6 columns]

In [9]:
train_item_indices[0].item()

1773

In [10]:
item_texts[train_item_indices[0].item()]

'title: Girl, Interrupted (1999) [SEP] genres: Drama'

In [11]:
train_user_indices[0].item()

6033

In [12]:
user_texts[train_user_indices[0].item()]

'occupation: K-12 student [SEP] age: Under 18 [SEP] gender: Female'

In [13]:
train_labels[0].item()

4.0

In [14]:
# Create DataLoader for training data
train_dataset = TensorDataset(train_user_indices, train_item_indices, train_labels)
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)

# Create DataLoader for training data
val_dataset = TensorDataset(val_user_indices, val_item_indices, val_labels)
val_dataloader = DataLoader(val_dataset, batch_size=64, shuffle=True, drop_last=True)

# Create DataLoader for training data
test_dataset = TensorDataset(test_user_indices, test_item_indices, test_labels)
test_dataloader = DataLoader(test_dataset, batch_size=64, shuffle=True, drop_last=True)

In [9]:
class TwoTowerModel(pl.LightningModule):
    def __init__(self, user_model_name, item_model_name, embedding_size=384):
        super(TwoTowerModel, self).__init__()
        self.user_model = SentenceTransformer(user_model_name)
        self.item_model = SentenceTransformer(item_model_name)

        self.user_fc = nn.Linear(embedding_size, embedding_size)
        self.item_fc = nn.Linear(embedding_size, embedding_size)

        self.criterion = nn.MSELoss()
        self.epoch_losses = {'train_loss': [], 'val_loss': []}

    def forward(self, user_text, item_text):
        user_embedding = self.user_model.encode(user_text, convert_to_tensor=True).to(device)
        item_embedding = self.item_model.encode(item_text, convert_to_tensor=True).to(device)

        user_output = self.user_fc(user_embedding)
        item_output = self.item_fc(item_embedding)

        dot_product = torch.matmul(user_output.unsqueeze(1), item_output.unsqueeze(2)).squeeze()

        dot_product = 4 * torch.sigmoid(dot_product) + 1

        return dot_product

    def training_step(self, batch, batch_idx):
        users, items, ratings = batch

        users = [user_texts[i] for i in users.tolist()]
        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        users, items, ratings = batch

        users = [user_texts[i] for i in users.tolist()]
        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('val_loss', loss)
        return loss

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=1e-5)

class PrintLossesCallback(Callback):
    def on_train_epoch_end(self, trainer, pl_module):
        train_loss = trainer.callback_metrics.get('train_loss')
        if train_loss is not None:
            pl_module.epoch_losses['train_loss'].append(train_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Train Loss: {train_loss.item()}")

    def on_validation_epoch_end(self, trainer, pl_module):
        val_loss = trainer.callback_metrics.get('val_loss')
        if val_loss is not None:
            pl_module.epoch_losses['val_loss'].append(val_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Val Loss: {val_loss.item()}")

In [45]:
# model = TwoTowerModel(user_model_name='all-MiniLM-L6-v2', item_model_name='all-MiniLM-L6-v2')
# model = TwoTowerModel(user_model_name='paraphrase-MiniLM-L6-v2', item_model_name='paraphrase-MiniLM-L6-v2')
model = TwoTowerModel(user_model_name='paraphrase-MiniLM-L12-v2', item_model_name='paraphrase-MiniLM-L12-v2')

# Define the ModelCheckpoint callback
checkpoint_callback = ModelCheckpoint(
    monitor='val_loss',  # Metric to monitor
    dirpath='checkpoints/',  # Directory to save the checkpoints
    filename='no-history-best-checkpoint',  # Filename for the best model
    save_top_k=1,  # Save only the top 1 model
    mode='min'  # Mode to save the best model (min for validation loss)
)

trainer = pl.Trainer(max_epochs=5, log_every_n_steps=1, callbacks=[PrintLossesCallback()], enable_progress_bar=True)
trainer.fit(model, train_dataloader, val_dataloader)

# Print losses after training completes
print("Epoch losses:")
for epoch in range(trainer.max_epochs):
    train_loss = model.epoch_losses['train_loss'][epoch] if epoch < len(model.epoch_losses['train_loss']) else 'N/A'
    val_loss = model.epoch_losses['val_loss'][epoch] if epoch < len(model.epoch_losses['val_loss']) else 'N/A'
    print(f"Epoch {epoch + 1}: Train Loss: {train_loss}, Val Loss: {val_loss}")

D:\Anaconda\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type                | Params | Mode
-----------------------------------------------------------
0 | user_model | SentenceTransformer | 33.4 M | train
1 | item_model | SentenceTransformer | 33.4 M | train
2 | user_fc    | Linear              | 147 K  | train
3 | item_fc    | Linear              | 147 K  | train
4 | criterion  | MSELoss             | 0      | train
-----------------------------------------------------------
67.0 M    Trainable params
0         Non-trainable params
67.0 M    Total params
268.063   Total estimated model params size (MB)

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]

D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:475: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test dataloaders.
D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  5.26it/s]Epoch 1: Val Loss: 1.941399335861206

D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Epoch 0: 100%|██████████| 12464/12464 [17:15<00:00, 12.03it/s, v_num=5]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/1557 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1557 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 1/1557 [00:00<02:22, 10.93it/s]
Validation DataLoader 0:   0%|          | 2/1557 [00:00<02:17, 11.30it/s]
Validation DataLoader 0:   0%|          | 3/1557 [00:00<02:18, 11.23it/s]
Validation DataLoader 0:   0%|          | 4/1557 [00:00<02:18, 11.20it/s]
Validation DataLoader 0:   0%|          | 5/1557 [00:00<02:19, 11.11it/s]
Validation DataLoader 0:   0%|          | 6/1557 [00:00<02:17, 11.28it/s]
Validation DataLoader 0:   0%|          | 7/1557 [00:00<02:16, 11.32it/s]
Validation DataLoader 0:   1%|          | 8/1557 [00:00<02:17, 11.29it/s]
Validation DataLoader 0:   1%|          | 9/1557 [00:00<02:16, 11.33it/s]
Validation DataLoader 0:   1%|          | 10/1557 [00:00<02:16, 11.31it/s]
Validation DataLoader 0:   1%|          | 11/1557 [00:00<02:16, 11.30it/s]
Validation DataLoader 0:   1%|          | 12/1557 [00:01<02:17, 11.23it/s]
Validation DataLoader 0:   1%|          | 13/1557 [00:01<02:17, 11.22it/s]
Validation DataLoader 0:   1%|          | 14/1557 [00:01<02:17, 11.19it/s]
Validation DataLoader 0:   1%|          | 15/1557 [00:01<02:17, 11.22it/s]
Validation DataLoader 0:   1%|          | 16/1557 [00:01<02:17, 11.23it/s]
Validation DataLoader 0:   1%|          | 17/1557 [00:01<02:17, 11.19it/s]
Validation DataLoader 0:   1%|          | 18/1557 [00:01<02:17, 11.18it/s]
Validation DataLoader 0:   1%|          | 19/1557 [00:01<02:17, 11.17it/s]
Validation DataLoader 0:   1%|▏         | 20/1557 [00:01<02:17, 11.19it/s]
Validation DataLoader 0:   1%|▏         | 21/1557 [00:01<02:16, 11.23it/s]
Validation DataLoader 0:   1%|▏         | 22/1557 [00:01<02:17, 11.19it/s]
Validation DataLoader 0:   1%|▏         | 23/1557 [00:02<02:16, 11.23it/s]
Validation DataLoader 0:   2%|▏         | 24/1557 [00:02<02:16, 11.26it/s]
Validation DataLoader 0:   2%|▏         | 25/1557 [00:02<02:16, 11.24it/s]
Validation DataLoader 0:   2%|▏         | 26/1557 [00:02<02:16, 11.25it/s]
Validation DataLoader 0:   2%|▏         | 27/1557 [00:02<02:16, 11.22it/s]
Validation DataLoader 0:   2%|▏         | 28/1557 [00:02<02:15, 11.25it/s]
Validation DataLoader 0:   2%|▏         | 29/1557 [00:02<02:15, 11.26it/s]
Validation DataLoader 0:   2%|▏         | 30/1557 [00:02<02:15, 11.27it/s]
Validation DataLoader 0:   2%|▏         | 31/1557 [00:02<02:15, 11.26it/s]
Validation DataLoader 0:   2%|▏         | 32/1557 [00:02<02:15, 11.26it/s]
Validation DataLoader 0:   2%|▏         | 33/1557 [00:02<02:15, 11.27it/s]
Validation DataLoader 0:   2%|▏         | 34/1557 [00:03<02:15, 11.27it/s]
Validation DataLoader 0:   2%|▏         | 35/1557 [00:03<02:15, 11.27it/s]
Validation DataLoader 0:   2%|▏         | 36/1557 [00:03<02:14, 11.28it/s]
Validation DataLoader 0:   2%|▏         | 37/1557 [00:03<02:14, 11.28it/s]
Validation DataLoader 0:   2%|▏         | 38/1557 [00:03<02:14, 11.30it/s]
Validation DataLoader 0:   3%|▎         | 39/1557 [00:03<02:14, 11.29it/s]
Validation DataLoader 0:   3%|▎         | 40/1557 [00:03<02:14, 11.30it/s]
Validation DataLoader 0:   3%|▎         | 41/1557 [00:03<02:14, 11.30it/s]
Validation DataLoader 0:   3%|▎         | 42/1557 [00:03<02:14, 11.28it/s]
Validation DataLoader 0:   3%|▎         | 43/1557 [00:03<02:14, 11.28it/s]
Validation DataLoader 0:   3%|▎         | 44/1557 [00:03<02:13, 11.29it/s]
Validation DataLoader 0:   3%|▎         | 45/1557 [00:03<02:13, 11.30it/s]
Validation DataLoader 0:   3%|▎         | 46/1557 [00:04<02:13, 11.30it/s]
Validation DataLoader 0:   3%|▎         | 47/1557 [00:04<02:13, 11.29it/s]
Validation DataLoader 0:   3%|▎         | 48/1557 [00:04<02:13, 11.27it/s]
Validation DataLoader 0:   3%|▎         | 49/1557 [00:04<02:13, 11.29it/s]
Validation DataLoader 0:   3%|▎         | 50/1557 [00:04<02:13, 11.30it/s]
Validation DataLoader 0:   3%|▎         | 51/1557 [00:04<02:13, 11.30it/s]
Validation DataLoader 0:   3%|▎         | 52/1557 [00:04<02:13, 11.29it/s]
Validation DataLoader 0:   3%|▎         | 53/1557 [00:04<02:13, 11.29it/s]
Validation DataLoader 0:   3%|▎         | 54/1557 [00:04<02:13, 11.29it/s]
Validation DataLoader 0:   4%|▎         | 55/1557 [00:04<02:13, 11.29it/s]
Validation DataLoader 0:   4%|▎         | 56/1557 [00:04<02:13, 11.28it/s]
Validation DataLoader 0:   4%|▎         | 57/1557 [00:05<02:13, 11.26it/s]
Validation DataLoader 0:   4%|▎         | 58/1557 [00:05<02:13, 11.25it/s]
Validation DataLoader 0:   4%|▍         | 59/1557 [00:05<02:13, 11.26it/s]
Validation DataLoader 0:   4%|▍         | 60/1557 [00:05<02:12, 11.27it/s]
Validation DataLoader 0:   4%|▍         | 61/1557 [00:05<02:12, 11.28it/s]
Validation DataLoader 0:   4%|▍         | 62/1557 [00:05<02:12, 11.27it/s]
Validation DataLoader 0:   4%|▍         | 63/1557 [00:05<02:12, 11.28it/s]
Validation DataLoader 0:   4%|▍         | 64/1557 [00:05<02:12, 11.27it/s]
Validation DataLoader 0:   4%|▍         | 65/1557 [00:05<02:12, 11.27it/s]
Validation DataLoader 0:   4%|▍         | 66/1557 [00:05<02:12, 11.28it/s]
Validation DataLoader 0:   4%|▍         | 67/1557 [00:05<02:12, 11.28it/s]
Validation DataLoader 0:   4%|▍         | 68/1557 [00:06<02:12, 11.27it/s]
Validation DataLoader 0:   4%|▍         | 69/1557 [00:06<02:12, 11.23it/s]
Validation DataLoader 0:   4%|▍         | 70/1557 [00:06<02:12, 11.25it/s]
Validation DataLoader 0:   5%|▍         | 71/1557 [00:06<02:12, 11.25it/s]
Validation DataLoader 0:   5%|▍         | 72/1557 [00:06<02:12, 11.24it/s]
Validation DataLoader 0:   5%|▍         | 73/1557 [00:06<02:12, 11.24it/s]
Validation DataLoader 0:   5%|▍         | 74/1557 [00:06<02:11, 11.25it/s]
Validation DataLoader 0:   5%|▍         | 75/1557 [00:06<02:11, 11.25it/s]
Validation DataLoader 0:   5%|▍         | 76/1557 [00:06<02:11, 11.26it/s]
Validation DataLoader 0:   5%|▍         | 77/1557 [00:06<02:11, 11.26it/s]
Validation DataLoader 0:   5%|▌         | 78/1557 [00:06<02:11, 11.26it/s]
Validation DataLoader 0:   5%|▌         | 79/1557 [00:07<02:11, 11.26it/s]
Validation DataLoader 0:   5%|▌         | 80/1557 [00:07<02:11, 11.26it/s]
Validation DataLoader 0:   5%|▌         | 81/1557 [00:07<02:10, 11.27it/s]
Validation DataLoader 0:   5%|▌         | 82/1557 [00:07<02:11, 11.26it/s]
Validation DataLoader 0:   5%|▌         | 83/1557 [00:07<02:10, 11.26it/s]
Validation DataLoader 0:   5%|▌         | 84/1557 [00:07<02:10, 11.26it/s]
Validation DataLoader 0:   5%|▌         | 85/1557 [00:07<02:10, 11.26it/s]
Validation DataLoader 0:   6%|▌         | 86/1557 [00:07<02:10, 11.26it/s]
Validation DataLoader 0:   6%|▌         | 87/1557 [00:07<02:10, 11.26it/s]
Validation DataLoader 0:   6%|▌         | 88/1557 [00:07<02:10, 11.25it/s]
Validation DataLoader 0:   6%|▌         | 89/1557 [00:07<02:10, 11.25it/s]
Validation DataLoader 0:   6%|▌         | 90/1557 [00:07<02:10, 11.25it/s]
Validation DataLoader 0:   6%|▌         | 91/1557 [00:08<02:10, 11.25it/s]
Validation DataLoader 0:   6%|▌         | 92/1557 [00:08<02:10, 11.25it/s]
Validation DataLoader 0:   6%|▌         | 93/1557 [00:08<02:10, 11.26it/s]
Validation DataLoader 0:   6%|▌         | 94/1557 [00:08<02:09, 11.26it/s]
Validation DataLoader 0:   6%|▌         | 95/1557 [00:08<02:09, 11.26it/s]
Validation DataLoader 0:   6%|▌         | 96/1557 [00:08<02:09, 11.26it/s]
Validation DataLoader 0:   6%|▌         | 97/1557 [00:08<02:09, 11.26it/s]
Validation DataLoader 0:   6%|▋         | 98/1557 [00:08<02:09, 11.26it/s]
Validation DataLoader 0:   6%|▋         | 99/1557 [00:08<02:09, 11.26it/s]
Validation DataLoader 0:   6%|▋         | 100/1557 [00:08<02:09, 11.26it/s]
Validation DataLoader 0:   6%|▋         | 101/1557 [00:08<02:09, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 102/1557 [00:09<02:09, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 103/1557 [00:09<02:09, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 104/1557 [00:09<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 105/1557 [00:09<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 106/1557 [00:09<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 107/1557 [00:09<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 108/1557 [00:09<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 109/1557 [00:09<02:08, 11.28it/s]
Validation DataLoader 0:   7%|▋         | 110/1557 [00:09<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 111/1557 [00:09<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 112/1557 [00:09<02:08, 11.26it/s]
Validation DataLoader 0:   7%|▋         | 113/1557 [00:10<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 114/1557 [00:10<02:08, 11.27it/s]
Validation DataLoader 0:   7%|▋         | 115/1557 [00:10<02:08, 11.24it/s]
Validation DataLoader 0:   7%|▋         | 116/1557 [00:10<02:08, 11.24it/s]
Validation DataLoader 0:   8%|▊         | 117/1557 [00:10<02:08, 11.24it/s]
Validation DataLoader 0:   8%|▊         | 118/1557 [00:10<02:07, 11.24it/s]
Validation DataLoader 0:   8%|▊         | 119/1557 [00:10<02:07, 11.24it/s]
Validation DataLoader 0:   8%|▊         | 120/1557 [00:10<02:07, 11.23it/s]
Validation DataLoader 0:   8%|▊         | 121/1557 [00:10<02:07, 11.22it/s]
Validation DataLoader 0:   8%|▊         | 122/1557 [00:10<02:07, 11.22it/s]
Validation DataLoader 0:   8%|▊         | 123/1557 [00:10<02:07, 11.22it/s]
Validation DataLoader 0:   8%|▊         | 124/1557 [00:11<02:07, 11.22it/s]
Validation DataLoader 0:   8%|▊         | 125/1557 [00:11<02:07, 11.22it/s]
Validation DataLoader 0:   8%|▊         | 126/1557 [00:11<02:07, 11.22it/s]
Validation DataLoader 0:   8%|▊         | 127/1557 [00:11<02:07, 11.23it/s]
Validation DataLoader 0:   8%|▊         | 128/1557 [00:11<02:07, 11.23it/s]
Validation DataLoader 0:   8%|▊         | 129/1557 [00:11<02:07, 11.23it/s]
Validation DataLoader 0:   8%|▊         | 130/1557 [00:11<02:07, 11.23it/s]
Validation DataLoader 0:   8%|▊         | 131/1557 [00:11<02:06, 11.23it/s]
Validation DataLoader 0:   8%|▊         | 132/1557 [00:11<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▊         | 133/1557 [00:11<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▊         | 134/1557 [00:11<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▊         | 135/1557 [00:12<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▊         | 136/1557 [00:12<02:06, 11.23it/s]
Validation DataLoader 0:   9%|▉         | 137/1557 [00:12<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 138/1557 [00:12<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 139/1557 [00:12<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 140/1557 [00:12<02:06, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 141/1557 [00:12<02:05, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 142/1557 [00:12<02:05, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 143/1557 [00:12<02:05, 11.23it/s]
Validation DataLoader 0:   9%|▉         | 144/1557 [00:12<02:05, 11.23it/s]
Validation DataLoader 0:   9%|▉         | 145/1557 [00:12<02:05, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 146/1557 [00:12<02:05, 11.24it/s]
Validation DataLoader 0:   9%|▉         | 147/1557 [00:13<02:05, 11.24it/s]
Validation DataLoader 0:  10%|▉         | 148/1557 [00:13<02:05, 11.23it/s]
Validation DataLoader 0:  10%|▉         | 149/1557 [00:13<02:05, 11.24it/s]
Validation DataLoader 0:  10%|▉         | 150/1557 [00:13<02:05, 11.24it/s]
Validation DataLoader 0:  10%|▉         | 151/1557 [00:13<02:05, 11.24it/s]
Validation DataLoader 0:  10%|▉         | 152/1557 [00:13<02:05, 11.24it/s]
Validation DataLoader 0:  10%|▉         | 153/1557 [00:13<02:04, 11.24it/s]
Validation DataLoader 0:  10%|▉         | 154/1557 [00:13<02:05, 11.22it/s]
Validation DataLoader 0:  10%|▉         | 155/1557 [00:13<02:04, 11.23it/s]
Validation DataLoader 0:  10%|█         | 156/1557 [00:13<02:04, 11.23it/s]
Validation DataLoader 0:  10%|█         | 157/1557 [00:13<02:04, 11.23it/s]
Validation DataLoader 0:  10%|█         | 158/1557 [00:14<02:04, 11.23it/s]
Validation DataLoader 0:  10%|█         | 159/1557 [00:14<02:04, 11.23it/s]
Validation DataLoader 0:  10%|█         | 160/1557 [00:14<02:04, 11.23it/s]
Validation DataLoader 0:  10%|█         | 161/1557 [00:14<02:04, 11.23it/s]
Validation DataLoader 0:  10%|█         | 162/1557 [00:14<02:04, 11.24it/s]
Validation DataLoader 0:  10%|█         | 163/1557 [00:14<02:04, 11.24it/s]
Validation DataLoader 0:  11%|█         | 164/1557 [00:14<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 165/1557 [00:14<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 166/1557 [00:14<02:03, 11.25it/s]
Validation DataLoader 0:  11%|█         | 167/1557 [00:14<02:03, 11.25it/s]
Validation DataLoader 0:  11%|█         | 168/1557 [00:14<02:03, 11.25it/s]
Validation DataLoader 0:  11%|█         | 169/1557 [00:15<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 170/1557 [00:15<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 171/1557 [00:15<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 172/1557 [00:15<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 173/1557 [00:15<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 174/1557 [00:15<02:03, 11.24it/s]
Validation DataLoader 0:  11%|█         | 175/1557 [00:15<02:02, 11.24it/s]
Validation DataLoader 0:  11%|█▏        | 176/1557 [00:15<02:02, 11.24it/s]
Validation DataLoader 0:  11%|█▏        | 177/1557 [00:15<02:02, 11.24it/s]
Validation DataLoader 0:  11%|█▏        | 178/1557 [00:15<02:02, 11.24it/s]
Validation DataLoader 0:  11%|█▏        | 179/1557 [00:15<02:02, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 180/1557 [00:16<02:02, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 181/1557 [00:16<02:02, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 182/1557 [00:16<02:02, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 183/1557 [00:16<02:02, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 184/1557 [00:16<02:02, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 185/1557 [00:16<02:02, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 186/1557 [00:16<02:01, 11.25it/s]
Validation DataLoader 0:  12%|█▏        | 187/1557 [00:16<02:01, 11.24it/s]
Validation DataLoader 0:  12%|█▏        | 188/1557 [00:16<02:01, 11.25it/s]
Validation DataLoader 0:  12%|█▏        | 189/1557 [00:16<02:01, 11.25it/s]
Validation DataLoader 0:  12%|█▏        | 190/1557 [00:16<02:01, 11.25it/s]
Validation DataLoader 0:  12%|█▏        | 191/1557 [00:16<02:01, 11.25it/s]
Validation DataLoader 0:  12%|█▏        | 192/1557 [00:17<02:01, 11.25it/s]
Validation DataLoader 0:  12%|█▏        | 193/1557 [00:17<02:01, 11.25it/s]
Validation DataLoader 0:  12%|█▏        | 194/1557 [00:17<02:01, 11.24it/s]
Validation DataLoader 0:  13%|█▎        | 195/1557 [00:17<02:01, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 196/1557 [00:17<02:01, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 197/1557 [00:17<02:00, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 198/1557 [00:17<02:00, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 199/1557 [00:17<02:00, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 200/1557 [00:17<02:00, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 201/1557 [00:17<02:00, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 202/1557 [00:17<02:00, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 203/1557 [00:18<02:00, 11.25it/s]
Validation DataLoader 0:  13%|█▎        | 204/1557 [00:18<02:00, 11.24it/s]
Validation DataLoader 0:  13%|█▎        | 205/1557 [00:18<02:00, 11.24it/s]
Validation DataLoader 0:  13%|█▎        | 206/1557 [00:18<02:00, 11.24it/s]
Validation DataLoader 0:  13%|█▎        | 207/1557 [00:18<02:00, 11.24it/s]
Validation DataLoader 0:  13%|█▎        | 208/1557 [00:18<02:00, 11.24it/s]
Validation DataLoader 0:  13%|█▎        | 209/1557 [00:18<01:59, 11.24it/s]
Validation DataLoader 0:  13%|█▎        | 210/1557 [00:18<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▎        | 211/1557 [00:18<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▎        | 212/1557 [00:18<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▎        | 213/1557 [00:18<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▎        | 214/1557 [00:19<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 215/1557 [00:19<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 216/1557 [00:19<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 217/1557 [00:19<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 218/1557 [00:19<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 219/1557 [00:19<01:59, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 220/1557 [00:19<01:58, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 221/1557 [00:19<01:58, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 222/1557 [00:19<01:58, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 223/1557 [00:19<01:58, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 224/1557 [00:19<01:58, 11.24it/s]
Validation DataLoader 0:  14%|█▍        | 225/1557 [00:20<01:58, 11.24it/s]
Validation DataLoader 0:  15%|█▍        | 226/1557 [00:20<01:58, 11.24it/s]
Validation DataLoader 0:  15%|█▍        | 227/1557 [00:20<01:58, 11.24it/s]
Validation DataLoader 0:  15%|█▍        | 228/1557 [00:20<01:58, 11.24it/s]
Validation DataLoader 0:  15%|█▍        | 229/1557 [00:20<01:58, 11.24it/s]
Validation DataLoader 0:  15%|█▍        | 230/1557 [00:20<01:58, 11.24it/s]
Validation DataLoader 0:  15%|█▍        | 231/1557 [00:20<01:58, 11.23it/s]
Validation DataLoader 0:  15%|█▍        | 232/1557 [00:20<01:57, 11.23it/s]
Validation DataLoader 0:  15%|█▍        | 233/1557 [00:20<01:57, 11.23it/s]
Validation DataLoader 0:  15%|█▌        | 234/1557 [00:20<01:57, 11.23it/s]
Validation DataLoader 0:  15%|█▌        | 235/1557 [00:20<01:57, 11.23it/s]
Validation DataLoader 0:  15%|█▌        | 236/1557 [00:21<01:57, 11.23it/s]
Validation DataLoader 0:  15%|█▌        | 237/1557 [00:21<01:57, 11.24it/s]
Validation DataLoader 0:  15%|█▌        | 238/1557 [00:21<01:57, 11.24it/s]
Validation DataLoader 0:  15%|█▌        | 239/1557 [00:21<01:57, 11.24it/s]
Validation DataLoader 0:  15%|█▌        | 240/1557 [00:21<01:57, 11.24it/s]
Validation DataLoader 0:  15%|█▌        | 241/1557 [00:21<01:57, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 242/1557 [00:21<01:57, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 243/1557 [00:21<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 244/1557 [00:21<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 245/1557 [00:21<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 246/1557 [00:21<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 247/1557 [00:21<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 248/1557 [00:22<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 249/1557 [00:22<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 250/1557 [00:22<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 251/1557 [00:22<01:56, 11.24it/s]
Validation DataLoader 0:  16%|█▌        | 252/1557 [00:22<01:56, 11.23it/s]
Validation DataLoader 0:  16%|█▌        | 253/1557 [00:22<01:56, 11.23it/s]
Validation DataLoader 0:  16%|█▋        | 254/1557 [00:22<01:55, 11.23it/s]
Validation DataLoader 0:  16%|█▋        | 255/1557 [00:22<01:55, 11.24it/s]
Validation DataLoader 0:  16%|█▋        | 256/1557 [00:22<01:55, 11.23it/s]
Validation DataLoader 0:  17%|█▋        | 257/1557 [00:22<01:55, 11.23it/s]
Validation DataLoader 0:  17%|█▋        | 258/1557 [00:22<01:55, 11.23it/s]
Validation DataLoader 0:  17%|█▋        | 259/1557 [00:23<01:55, 11.23it/s]
Validation DataLoader 0:  17%|█▋        | 260/1557 [00:23<01:55, 11.23it/s]
Validation DataLoader 0:  17%|█▋        | 261/1557 [00:23<01:55, 11.23it/s]

`Trainer.fit` stopped: `max_epochs=5` reached.

Epoch 4: 100%|██████████| 12464/12464 [27:47<00:00,  7.47it/s, v_num=5]
Epoch losses:
Epoch 1: Train Loss: 1.115174412727356, Val Loss: 1.941399335861206
Epoch 2: Train Loss: 1.0392054319381714, Val Loss: 1.1585066318511963
Epoch 3: Train Loss: 1.3856589794158936, Val Loss: 1.1448918581008911
Epoch 4: Train Loss: 0.9124230146408081, Val Loss: 1.1453769207000732
Epoch 5: Train Loss: 0.9220023155212402, Val Loss: 1.1464678049087524

In [15]:
class ImprovedTwoTowerModel(pl.LightningModule):
    def __init__(self, user_model_name, item_model_name, embedding_size=384, hidden_units=64, dropout_rate=0.5):
        super(ImprovedTwoTowerModel, self).__init__()
        self.user_model = SentenceTransformer(user_model_name)
        self.item_model = SentenceTransformer(item_model_name)

        self.user_fc = nn.Sequential(
            nn.Linear(embedding_size, hidden_units),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_units, embedding_size)
        )
        self.item_fc = nn.Sequential(
            nn.Linear(embedding_size, hidden_units),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_units, embedding_size)
        )

        self.criterion = nn.MSELoss()
        self.epoch_losses = {'train_loss': [], 'val_loss': []}

    def forward(self, user_text, item_text):
        user_embedding = self.user_model.encode(user_text, convert_to_tensor=True).to(device)
        item_embedding = self.item_model.encode(item_text, convert_to_tensor=True).to(device)

        user_output = self.user_fc(user_embedding)
        item_output = self.item_fc(item_embedding)

        dot_product = torch.matmul(user_output.unsqueeze(1), item_output.unsqueeze(2)).squeeze()
        dot_product = 4 * torch.sigmoid(dot_product) + 1

        return dot_product

    def training_step(self, batch, batch_idx):
        users, items, ratings = batch

        users = [user_texts[i] for i in users.tolist()]
        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        users, items, ratings = batch

        users = [user_texts[i] for i in users.tolist()]
        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('val_loss', loss)
        return loss

    def full_predict(self, user_ids, item_ids):
        users = [user_texts[i] for i in user_ids.tolist()]
        items = [item_texts[i] for i in item_ids.tolist()]
        user_embedding = self.user_model.encode(users, convert_to_tensor=True).to(self.device)
        item_embeddings = torch.stack([self.item_model.encode(item_text, convert_to_tensor=True) for item_text in items]).to(self.device)

        user_output = self.user_fc(user_embedding)
        item_output = self.item_fc(item_embeddings)

        dot_product = torch.matmul(user_output, item_output.T)
        dot_product = 4 * torch.sigmoid(dot_product) + 1

        return dot_product

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=1e-5)

class PrintLossesCallback(Callback):
    def on_train_epoch_end(self, trainer, pl_module):
        train_loss = trainer.callback_metrics.get('train_loss')
        if train_loss is not None:
            pl_module.epoch_losses['train_loss'].append(train_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Train Loss: {train_loss.item()}")

    def on_validation_epoch_end(self, trainer, pl_module):
        val_loss = trainer.callback_metrics.get('val_loss')
        if val_loss is not None:
            pl_module.epoch_losses['val_loss'].append(val_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Val Loss: {val_loss.item()}")

In [16]:
# model = TwoTowerModel(user_model_name='all-MiniLM-L6-v2', item_model_name='all-MiniLM-L6-v2')
model = ImprovedTwoTowerModel(user_model_name='paraphrase-MiniLM-L6-v2', item_model_name='paraphrase-MiniLM-L6-v2')

# Define the ModelCheckpoint callback
checkpoint_callback = ModelCheckpoint(
    monitor='val_loss',  # Metric to monitor
    dirpath='checkpoints/',  # Directory to save the checkpoints
    filename='no-history-best-checkpoint',  # Filename for the best model
    save_top_k=1,  # Save only the top 1 model
    mode='min'  # Mode to save the best model (min for validation loss)
)

trainer = pl.Trainer(max_epochs=5, log_every_n_steps=1, callbacks=[PrintLossesCallback()], enable_progress_bar=True)
trainer.fit(model, train_dataloader, val_dataloader)

# Print losses after training completes
print("Epoch losses:")
for epoch in range(trainer.max_epochs):
    train_loss = model.epoch_losses['train_loss'][epoch] if epoch < len(model.epoch_losses['train_loss']) else 'N/A'
    val_loss = model.epoch_losses['val_loss'][epoch] if epoch < len(model.epoch_losses['val_loss']) else 'N/A'
    print(f"Epoch {epoch + 1}: Train Loss: {train_loss}, Val Loss: {val_loss}")

D:\Anaconda\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type                | Params | Mode
-----------------------------------------------------------
0 | user_model | SentenceTransformer | 22.7 M | train
1 | item_model | SentenceTransformer | 22.7 M | train
2 | user_fc    | Sequential          | 49.6 K | train
3 | item_fc    | Sequential          | 49.6 K | train
4 | criterion  | MSELoss             | 0      | train
-----------------------------------------------------------
45.5 M    Trainable params
0         Non-trainable params
45.5 M    Total params
182.103   Total estimated model params size (MB)

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]

D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:475: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test dataloaders.
D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  3.45it/s]Epoch 1: Val Loss: 1.6962825059890747

D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Epoch 0: 100%|██████████| 12464/12464 [11:38<00:00, 17.84it/s, v_num=0]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/1557 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1557 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 1/1557 [00:00<01:27, 17.86it/s]
Validation DataLoader 0:   0%|          | 2/1557 [00:00<01:26, 17.94it/s]
Validation DataLoader 0:   0%|          | 3/1557 [00:00<01:24, 18.46it/s]
Validation DataLoader 0:   0%|          | 4/1557 [00:00<01:23, 18.69it/s]
Validation DataLoader 0:   0%|          | 5/1557 [00:00<01:22, 18.82it/s]
Validation DataLoader 0:   0%|          | 6/1557 [00:00<01:22, 18.86it/s]
Validation DataLoader 0:   0%|          | 7/1557 [00:00<01:21, 18.96it/s]
Validation DataLoader 0:   1%|          | 8/1557 [00:00<01:21, 18.97it/s]
Validation DataLoader 0:   1%|          | 9/1557 [00:00<01:21, 19.00it/s]
Validation DataLoader 0:   1%|          | 10/1557 [00:00<01:21, 19.01it/s]
Validation DataLoader 0:   1%|          | 11/1557 [00:00<01:21, 19.03it/s]
Validation DataLoader 0:   1%|          | 12/1557 [00:00<01:21, 19.00it/s]
Validation DataLoader 0:   1%|          | 13/1557 [00:00<01:21, 19.04it/s]
Validation DataLoader 0:   1%|          | 14/1557 [00:00<01:21, 18.99it/s]
Validation DataLoader 0:   1%|          | 15/1557 [00:00<01:20, 19.05it/s]
Validation DataLoader 0:   1%|          | 16/1557 [00:00<01:20, 19.08it/s]
Validation DataLoader 0:   1%|          | 17/1557 [00:00<01:20, 19.10it/s]
Validation DataLoader 0:   1%|          | 18/1557 [00:00<01:20, 19.08it/s]
Validation DataLoader 0:   1%|          | 19/1557 [00:00<01:20, 19.10it/s]
Validation DataLoader 0:   1%|▏         | 20/1557 [00:01<01:20, 19.09it/s]
Validation DataLoader 0:   1%|▏         | 21/1557 [00:01<01:20, 19.12it/s]
Validation DataLoader 0:   1%|▏         | 22/1557 [00:01<01:20, 19.09it/s]
Validation DataLoader 0:   1%|▏         | 23/1557 [00:01<01:20, 19.12it/s]
Validation DataLoader 0:   2%|▏         | 24/1557 [00:01<01:20, 19.11it/s]
Validation DataLoader 0:   2%|▏         | 25/1557 [00:01<01:20, 19.12it/s]
Validation DataLoader 0:   2%|▏         | 26/1557 [00:01<01:20, 19.08it/s]
Validation DataLoader 0:   2%|▏         | 27/1557 [00:01<01:20, 19.08it/s]
Validation DataLoader 0:   2%|▏         | 28/1557 [00:01<01:20, 18.99it/s]
Validation DataLoader 0:   2%|▏         | 29/1557 [00:01<01:20, 18.94it/s]
Validation DataLoader 0:   2%|▏         | 30/1557 [00:01<01:20, 18.95it/s]
Validation DataLoader 0:   2%|▏         | 31/1557 [00:01<01:20, 18.97it/s]
Validation DataLoader 0:   2%|▏         | 32/1557 [00:01<01:20, 18.99it/s]
Validation DataLoader 0:   2%|▏         | 33/1557 [00:01<01:20, 18.99it/s]
Validation DataLoader 0:   2%|▏         | 34/1557 [00:01<01:20, 19.00it/s]
Validation DataLoader 0:   2%|▏         | 35/1557 [00:01<01:20, 19.02it/s]
Validation DataLoader 0:   2%|▏         | 36/1557 [00:01<01:19, 19.03it/s]
Validation DataLoader 0:   2%|▏         | 37/1557 [00:01<01:19, 19.05it/s]
Validation DataLoader 0:   2%|▏         | 38/1557 [00:01<01:19, 19.05it/s]
Validation DataLoader 0:   3%|▎         | 39/1557 [00:02<01:19, 19.07it/s]
Validation DataLoader 0:   3%|▎         | 40/1557 [00:02<01:19, 19.08it/s]
Validation DataLoader 0:   3%|▎         | 41/1557 [00:02<01:19, 19.08it/s]
Validation DataLoader 0:   3%|▎         | 42/1557 [00:02<01:19, 19.09it/s]
Validation DataLoader 0:   3%|▎         | 43/1557 [00:02<01:19, 19.11it/s]
Validation DataLoader 0:   3%|▎         | 44/1557 [00:02<01:19, 19.13it/s]
Validation DataLoader 0:   3%|▎         | 45/1557 [00:02<01:18, 19.15it/s]
Validation DataLoader 0:   3%|▎         | 46/1557 [00:02<01:18, 19.17it/s]
Validation DataLoader 0:   3%|▎         | 47/1557 [00:02<01:18, 19.18it/s]
Validation DataLoader 0:   3%|▎         | 48/1557 [00:02<01:18, 19.20it/s]
Validation DataLoader 0:   3%|▎         | 49/1557 [00:02<01:18, 19.19it/s]
Validation DataLoader 0:   3%|▎         | 50/1557 [00:02<01:18, 19.19it/s]
Validation DataLoader 0:   3%|▎         | 51/1557 [00:02<01:18, 19.20it/s]
Validation DataLoader 0:   3%|▎         | 52/1557 [00:02<01:18, 19.21it/s]
Validation DataLoader 0:   3%|▎         | 53/1557 [00:02<01:18, 19.22it/s]
Validation DataLoader 0:   3%|▎         | 54/1557 [00:02<01:18, 19.22it/s]
Validation DataLoader 0:   4%|▎         | 55/1557 [00:02<01:18, 19.21it/s]
Validation DataLoader 0:   4%|▎         | 56/1557 [00:02<01:18, 19.20it/s]
Validation DataLoader 0:   4%|▎         | 57/1557 [00:02<01:18, 19.22it/s]
Validation DataLoader 0:   4%|▎         | 58/1557 [00:03<01:17, 19.22it/s]
Validation DataLoader 0:   4%|▍         | 59/1557 [00:03<01:17, 19.22it/s]
Validation DataLoader 0:   4%|▍         | 60/1557 [00:03<01:17, 19.22it/s]
Validation DataLoader 0:   4%|▍         | 61/1557 [00:03<01:17, 19.22it/s]
Validation DataLoader 0:   4%|▍         | 62/1557 [00:03<01:17, 19.23it/s]
Validation DataLoader 0:   4%|▍         | 63/1557 [00:03<01:17, 19.24it/s]
Validation DataLoader 0:   4%|▍         | 64/1557 [00:03<01:17, 19.24it/s]
Validation DataLoader 0:   4%|▍         | 65/1557 [00:03<01:17, 19.24it/s]
Validation DataLoader 0:   4%|▍         | 66/1557 [00:03<01:17, 19.25it/s]
Validation DataLoader 0:   4%|▍         | 67/1557 [00:03<01:17, 19.25it/s]
Validation DataLoader 0:   4%|▍         | 68/1557 [00:03<01:17, 19.25it/s]
Validation DataLoader 0:   4%|▍         | 69/1557 [00:03<01:17, 19.21it/s]
Validation DataLoader 0:   4%|▍         | 70/1557 [00:03<01:17, 19.21it/s]
Validation DataLoader 0:   5%|▍         | 71/1557 [00:03<01:17, 19.21it/s]
Validation DataLoader 0:   5%|▍         | 72/1557 [00:03<01:17, 19.18it/s]
Validation DataLoader 0:   5%|▍         | 73/1557 [00:03<01:17, 19.16it/s]
Validation DataLoader 0:   5%|▍         | 74/1557 [00:03<01:17, 19.11it/s]
Validation DataLoader 0:   5%|▍         | 75/1557 [00:03<01:17, 19.08it/s]
Validation DataLoader 0:   5%|▍         | 76/1557 [00:03<01:17, 19.08it/s]
Validation DataLoader 0:   5%|▍         | 77/1557 [00:04<01:17, 19.08it/s]
Validation DataLoader 0:   5%|▌         | 78/1557 [00:04<01:17, 19.09it/s]
Validation DataLoader 0:   5%|▌         | 79/1557 [00:04<01:17, 19.10it/s]
Validation DataLoader 0:   5%|▌         | 80/1557 [00:04<01:17, 19.10it/s]
Validation DataLoader 0:   5%|▌         | 81/1557 [00:04<01:17, 19.06it/s]
Validation DataLoader 0:   5%|▌         | 82/1557 [00:04<01:17, 19.05it/s]
Validation DataLoader 0:   5%|▌         | 83/1557 [00:04<01:17, 19.04it/s]
Validation DataLoader 0:   5%|▌         | 84/1557 [00:04<01:17, 19.04it/s]
Validation DataLoader 0:   5%|▌         | 85/1557 [00:04<01:17, 19.05it/s]
Validation DataLoader 0:   6%|▌         | 86/1557 [00:04<01:17, 19.05it/s]
Validation DataLoader 0:   6%|▌         | 87/1557 [00:04<01:17, 19.05it/s]
Validation DataLoader 0:   6%|▌         | 88/1557 [00:04<01:17, 19.05it/s]
Validation DataLoader 0:   6%|▌         | 89/1557 [00:04<01:17, 19.05it/s]
Validation DataLoader 0:   6%|▌         | 90/1557 [00:04<01:16, 19.05it/s]
Validation DataLoader 0:   6%|▌         | 91/1557 [00:04<01:16, 19.06it/s]
Validation DataLoader 0:   6%|▌         | 92/1557 [00:04<01:16, 19.07it/s]
Validation DataLoader 0:   6%|▌         | 93/1557 [00:04<01:16, 19.08it/s]
Validation DataLoader 0:   6%|▌         | 94/1557 [00:04<01:16, 19.09it/s]
Validation DataLoader 0:   6%|▌         | 95/1557 [00:04<01:16, 19.09it/s]
Validation DataLoader 0:   6%|▌         | 96/1557 [00:05<01:16, 19.09it/s]
Validation DataLoader 0:   6%|▌         | 97/1557 [00:05<01:16, 19.09it/s]
Validation DataLoader 0:   6%|▋         | 98/1557 [00:05<01:16, 19.10it/s]
Validation DataLoader 0:   6%|▋         | 99/1557 [00:05<01:16, 19.10it/s]
Validation DataLoader 0:   6%|▋         | 100/1557 [00:05<01:16, 19.10it/s]
Validation DataLoader 0:   6%|▋         | 101/1557 [00:05<01:16, 19.11it/s]
Validation DataLoader 0:   7%|▋         | 102/1557 [00:05<01:16, 19.11it/s]
Validation DataLoader 0:   7%|▋         | 103/1557 [00:05<01:16, 19.12it/s]
Validation DataLoader 0:   7%|▋         | 104/1557 [00:05<01:15, 19.13it/s]
Validation DataLoader 0:   7%|▋         | 105/1557 [00:05<01:15, 19.13it/s]
Validation DataLoader 0:   7%|▋         | 106/1557 [00:05<01:15, 19.14it/s]
Validation DataLoader 0:   7%|▋         | 107/1557 [00:05<01:15, 19.14it/s]
Validation DataLoader 0:   7%|▋         | 108/1557 [00:05<01:15, 19.14it/s]
Validation DataLoader 0:   7%|▋         | 109/1557 [00:05<01:15, 19.14it/s]
Validation DataLoader 0:   7%|▋         | 110/1557 [00:05<01:15, 19.12it/s]
Validation DataLoader 0:   7%|▋         | 111/1557 [00:05<01:15, 19.09it/s]
Validation DataLoader 0:   7%|▋         | 112/1557 [00:05<01:15, 19.10it/s]
Validation DataLoader 0:   7%|▋         | 113/1557 [00:05<01:15, 19.10it/s]
Validation DataLoader 0:   7%|▋         | 114/1557 [00:05<01:15, 19.10it/s]
Validation DataLoader 0:   7%|▋         | 115/1557 [00:06<01:15, 19.10it/s]
Validation DataLoader 0:   7%|▋         | 116/1557 [00:06<01:15, 19.10it/s]
Validation DataLoader 0:   8%|▊         | 117/1557 [00:06<01:15, 19.10it/s]
Validation DataLoader 0:   8%|▊         | 118/1557 [00:06<01:15, 19.11it/s]
Validation DataLoader 0:   8%|▊         | 119/1557 [00:06<01:15, 19.11it/s]
Validation DataLoader 0:   8%|▊         | 120/1557 [00:06<01:15, 19.11it/s]
Validation DataLoader 0:   8%|▊         | 121/1557 [00:06<01:15, 19.11it/s]
Validation DataLoader 0:   8%|▊         | 122/1557 [00:06<01:15, 19.11it/s]
Validation DataLoader 0:   8%|▊         | 123/1557 [00:06<01:15, 19.11it/s]
Validation DataLoader 0:   8%|▊         | 124/1557 [00:06<01:14, 19.12it/s]
Validation DataLoader 0:   8%|▊         | 125/1557 [00:06<01:14, 19.12it/s]
Validation DataLoader 0:   8%|▊         | 126/1557 [00:06<01:14, 19.13it/s]
Validation DataLoader 0:   8%|▊         | 127/1557 [00:06<01:14, 19.13it/s]
Validation DataLoader 0:   8%|▊         | 128/1557 [00:06<01:14, 19.13it/s]
Validation DataLoader 0:   8%|▊         | 129/1557 [00:06<01:14, 19.14it/s]
Validation DataLoader 0:   8%|▊         | 130/1557 [00:06<01:14, 19.14it/s]
Validation DataLoader 0:   8%|▊         | 131/1557 [00:06<01:14, 19.14it/s]
Validation DataLoader 0:   8%|▊         | 132/1557 [00:06<01:14, 19.14it/s]
Validation DataLoader 0:   9%|▊         | 133/1557 [00:06<01:14, 19.15it/s]
Validation DataLoader 0:   9%|▊         | 134/1557 [00:06<01:14, 19.15it/s]
Validation DataLoader 0:   9%|▊         | 135/1557 [00:07<01:14, 19.15it/s]
Validation DataLoader 0:   9%|▊         | 136/1557 [00:07<01:14, 19.15it/s]
Validation DataLoader 0:   9%|▉         | 137/1557 [00:07<01:14, 19.15it/s]
Validation DataLoader 0:   9%|▉         | 138/1557 [00:07<01:14, 19.15it/s]
Validation DataLoader 0:   9%|▉         | 139/1557 [00:07<01:14, 19.15it/s]
Validation DataLoader 0:   9%|▉         | 140/1557 [00:07<01:13, 19.15it/s]
Validation DataLoader 0:   9%|▉         | 141/1557 [00:07<01:13, 19.14it/s]
Validation DataLoader 0:   9%|▉         | 142/1557 [00:07<01:13, 19.14it/s]
Validation DataLoader 0:   9%|▉         | 143/1557 [00:07<01:13, 19.14it/s]
Validation DataLoader 0:   9%|▉         | 144/1557 [00:07<01:13, 19.14it/s]
Validation DataLoader 0:   9%|▉         | 145/1557 [00:07<01:13, 19.14it/s]
Validation DataLoader 0:   9%|▉         | 146/1557 [00:07<01:13, 19.14it/s]
Validation DataLoader 0:   9%|▉         | 147/1557 [00:07<01:13, 19.14it/s]
Validation DataLoader 0:  10%|▉         | 148/1557 [00:07<01:13, 19.15it/s]
Validation DataLoader 0:  10%|▉         | 149/1557 [00:07<01:13, 19.15it/s]
Validation DataLoader 0:  10%|▉         | 150/1557 [00:07<01:13, 19.15it/s]
Validation DataLoader 0:  10%|▉         | 151/1557 [00:07<01:13, 19.15it/s]
Validation DataLoader 0:  10%|▉         | 152/1557 [00:07<01:13, 19.16it/s]
Validation DataLoader 0:  10%|▉         | 153/1557 [00:07<01:13, 19.16it/s]
Validation DataLoader 0:  10%|▉         | 154/1557 [00:08<01:13, 19.17it/s]
Validation DataLoader 0:  10%|▉         | 155/1557 [00:08<01:13, 19.17it/s]
Validation DataLoader 0:  10%|█         | 156/1557 [00:08<01:13, 19.17it/s]
Validation DataLoader 0:  10%|█         | 157/1557 [00:08<01:13, 19.17it/s]
Validation DataLoader 0:  10%|█         | 158/1557 [00:08<01:12, 19.18it/s]
Validation DataLoader 0:  10%|█         | 159/1557 [00:08<01:12, 19.17it/s]
Validation DataLoader 0:  10%|█         | 160/1557 [00:08<01:12, 19.17it/s]
Validation DataLoader 0:  10%|█         | 161/1557 [00:08<01:12, 19.18it/s]
Validation DataLoader 0:  10%|█         | 162/1557 [00:08<01:12, 19.18it/s]
Validation DataLoader 0:  10%|█         | 163/1557 [00:08<01:12, 19.17it/s]
Validation DataLoader 0:  11%|█         | 164/1557 [00:08<01:12, 19.17it/s]
Validation DataLoader 0:  11%|█         | 165/1557 [00:08<01:12, 19.17it/s]
Validation DataLoader 0:  11%|█         | 166/1557 [00:08<01:12, 19.18it/s]
Validation DataLoader 0:  11%|█         | 167/1557 [00:08<01:12, 19.18it/s]
Validation DataLoader 0:  11%|█         | 168/1557 [00:08<01:12, 19.18it/s]
Validation DataLoader 0:  11%|█         | 169/1557 [00:08<01:12, 19.19it/s]
Validation DataLoader 0:  11%|█         | 170/1557 [00:08<01:12, 19.19it/s]
Validation DataLoader 0:  11%|█         | 171/1557 [00:08<01:12, 19.19it/s]
Validation DataLoader 0:  11%|█         | 172/1557 [00:08<01:12, 19.19it/s]
Validation DataLoader 0:  11%|█         | 173/1557 [00:09<01:12, 19.18it/s]
Validation DataLoader 0:  11%|█         | 174/1557 [00:09<01:12, 19.19it/s]
Validation DataLoader 0:  11%|█         | 175/1557 [00:09<01:12, 19.19it/s]
Validation DataLoader 0:  11%|█▏        | 176/1557 [00:09<01:11, 19.19it/s]
Validation DataLoader 0:  11%|█▏        | 177/1557 [00:09<01:11, 19.19it/s]
Validation DataLoader 0:  11%|█▏        | 178/1557 [00:09<01:11, 19.19it/s]
Validation DataLoader 0:  11%|█▏        | 179/1557 [00:09<01:11, 19.19it/s]
Validation DataLoader 0:  12%|█▏        | 180/1557 [00:09<01:11, 19.19it/s]
Validation DataLoader 0:  12%|█▏        | 181/1557 [00:09<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 182/1557 [00:09<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 183/1557 [00:09<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 184/1557 [00:09<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 185/1557 [00:09<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 186/1557 [00:09<01:11, 19.21it/s]
Validation DataLoader 0:  12%|█▏        | 187/1557 [00:09<01:11, 19.21it/s]
Validation DataLoader 0:  12%|█▏        | 188/1557 [00:09<01:11, 19.21it/s]
Validation DataLoader 0:  12%|█▏        | 189/1557 [00:09<01:11, 19.21it/s]
Validation DataLoader 0:  12%|█▏        | 190/1557 [00:09<01:11, 19.21it/s]
Validation DataLoader 0:  12%|█▏        | 191/1557 [00:09<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 192/1557 [00:09<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 193/1557 [00:10<01:11, 19.20it/s]
Validation DataLoader 0:  12%|█▏        | 194/1557 [00:10<01:10, 19.20it/s]
Validation DataLoader 0:  13%|█▎        | 195/1557 [00:10<01:10, 19.20it/s]
Validation DataLoader 0:  13%|█▎        | 196/1557 [00:10<01:10, 19.21it/s]
Validation DataLoader 0:  13%|█▎        | 197/1557 [00:10<01:10, 19.21it/s]
Validation DataLoader 0:  13%|█▎        | 198/1557 [00:10<01:10, 19.21it/s]
Validation DataLoader 0:  13%|█▎        | 199/1557 [00:10<01:10, 19.21it/s]
Validation DataLoader 0:  13%|█▎        | 200/1557 [00:10<01:10, 19.21it/s]
Validation DataLoader 0:  13%|█▎        | 201/1557 [00:10<01:10, 19.22it/s]
Validation DataLoader 0:  13%|█▎        | 202/1557 [00:10<01:10, 19.22it/s]
Validation DataLoader 0:  13%|█▎        | 203/1557 [00:10<01:10, 19.22it/s]
Validation DataLoader 0:  13%|█▎        | 204/1557 [00:10<01:10, 19.22it/s]
Validation DataLoader 0:  13%|█▎        | 205/1557 [00:10<01:10, 19.22it/s]
Validation DataLoader 0:  13%|█▎        | 206/1557 [00:10<01:10, 19.22it/s]
Validation DataLoader 0:  13%|█▎        | 207/1557 [00:10<01:10, 19.23it/s]
Validation DataLoader 0:  13%|█▎        | 208/1557 [00:10<01:10, 19.23it/s]
Validation DataLoader 0:  13%|█▎        | 209/1557 [00:10<01:10, 19.23it/s]
Validation DataLoader 0:  13%|█▎        | 210/1557 [00:10<01:10, 19.23it/s]
Validation DataLoader 0:  14%|█▎        | 211/1557 [00:10<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▎        | 212/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▎        | 213/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▎        | 214/1557 [00:11<01:09, 19.24it/s]
Validation DataLoader 0:  14%|█▍        | 215/1557 [00:11<01:09, 19.24it/s]
Validation DataLoader 0:  14%|█▍        | 216/1557 [00:11<01:09, 19.24it/s]
Validation DataLoader 0:  14%|█▍        | 217/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▍        | 218/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▍        | 219/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▍        | 220/1557 [00:11<01:09, 19.22it/s]
Validation DataLoader 0:  14%|█▍        | 221/1557 [00:11<01:09, 19.22it/s]
Validation DataLoader 0:  14%|█▍        | 222/1557 [00:11<01:09, 19.22it/s]
Validation DataLoader 0:  14%|█▍        | 223/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▍        | 224/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  14%|█▍        | 225/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 226/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 227/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 228/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 229/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 230/1557 [00:11<01:09, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 231/1557 [00:12<01:08, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 232/1557 [00:12<01:08, 19.23it/s]
Validation DataLoader 0:  15%|█▍        | 233/1557 [00:12<01:08, 19.23it/s]
Validation DataLoader 0:  15%|█▌        | 234/1557 [00:12<01:08, 19.23it/s]
Validation DataLoader 0:  15%|█▌        | 235/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  15%|█▌        | 236/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  15%|█▌        | 237/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  15%|█▌        | 238/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  15%|█▌        | 239/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  15%|█▌        | 240/1557 [00:12<01:08, 19.25it/s]
Validation DataLoader 0:  15%|█▌        | 241/1557 [00:12<01:08, 19.25it/s]
Validation DataLoader 0:  16%|█▌        | 242/1557 [00:12<01:08, 19.25it/s]
Validation DataLoader 0:  16%|█▌        | 243/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 244/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 245/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 246/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 247/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 248/1557 [00:12<01:08, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 249/1557 [00:12<01:07, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 250/1557 [00:12<01:07, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 251/1557 [00:13<01:07, 19.24it/s]
Validation DataLoader 0:  16%|█▌        | 252/1557 [00:13<01:07, 19.25it/s]
Validation DataLoader 0:  16%|█▌        | 253/1557 [00:13<01:07, 19.25it/s]
Validation DataLoader 0:  16%|█▋        | 254/1557 [00:13<01:07, 19.25it/s]
Validation DataLoader 0:  16%|█▋        | 255/1557 [00:13<01:07, 19.25it/s]
Validation DataLoader 0:  16%|█▋        | 256/1557 [00:13<01:07, 19.25it/s]
Validation DataLoader 0:  17%|█▋        | 257/1557 [00:13<01:07, 19.26it/s]
Validation DataLoader 0:  17%|█▋        | 258/1557 [00:13<01:07, 19.26it/s]
Validation DataLoader 0:  17%|█▋        | 259/1557 [00:13<01:07, 19.26it/s]
Validation DataLoader 0:  17%|█▋        | 260/1557 [00:13<01:07, 19.26it/s]
Validation DataLoader 0:  17%|█▋        | 261/1557 [00:13<01:07, 19.26it/s]

`Trainer.fit` stopped: `max_epochs=5` reached.

Epoch 4: 100%|██████████| 12464/12464 [15:48<00:00, 13.14it/s, v_num=0]
Epoch losses:
Epoch 1: Train Loss: 0.9376359581947327, Val Loss: 1.6962825059890747
Epoch 2: Train Loss: 1.1455373764038086, Val Loss: 1.1595927476882935
Epoch 3: Train Loss: 0.8663498163223267, Val Loss: 1.115472435951233
Epoch 4: Train Loss: 1.3735228776931763, Val Loss: 1.0860795974731445
Epoch 5: Train Loss: 0.9129804968833923, Val Loss: 1.0652637481689453

In [ ]:
model.epoch_losses

# Evaluation

In [20]:
# Assuming the training part has been done already, load the best model checkpoint
# # best_model_path = './lightning_logs/paraphrase-MiniLM-L6-v2/not-binarized/no-history_5-epochs_lr-1e-5/checkpoints/epoch=4-step=93765.ckpt'  # Path where the best model is saved
# best_model_path = './lightning_logs/paraphrase-MiniLM-L6-v2/not-binarized/no-history_5-epochs_lr-1e-5_(new format - only genre for movies)/checkpoints/epoch=4-step=62320.ckpt'  # Path where the best model is saved
best_model_path = './lightning_logs/version_0/checkpoints/epoch=4-step=62320.ckpt'  # Path where the best model is saved

best_model = ImprovedTwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L6-v2', item_model_name='paraphrase-MiniLM-L6-v2').to(device)
# best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L12-v2', item_model_name='paraphrase-MiniLM-L12-v2').to(device)

# paraphrase-MiniLM-L12-v2

## Calculations

In [25]:
def get_top_n_items_without_history_unseen_items(model, userId, n):
    # Ensure the model is in evaluation mode
    model.eval()

    # Get the user text for the given userId
    user_text = user_features_dict[userId]

    # Encode the user text
    user_embedding = model.user_model.encode(user_text, convert_to_tensor=True).to(device)

    # Compute the scores (dot product between user embedding and each item embedding)
    user_output = model.user_fc(user_embedding).to(device)
    item_output = model.item_fc(full_items_embeddings).to(device)
    dot_product = torch.matmul(user_output, item_output.t()).squeeze()

    # Get items the user has seen in the training and validation data
    seen_items_train = train_ratings[train_ratings['user_id'] == userId]['item_id'].values
    seen_items_val = val_ratings[val_ratings['user_id'] == userId]['item_id'].values
    seen_items = set(np.concatenate((seen_items_train, seen_items_val)))
    # print(seen_items)
    # Get the top n + len(seen_items) item indices and their scores
    top_n_scores, top_n_indices = torch.topk(dot_product, n + len(seen_items))

    # Map indices back to item IDs
    top_n_item_ids = [list(movie_id_to_idx.keys())[list(movie_id_to_idx.values()).index(idx.item())] for idx in top_n_indices]
    # print(top_n_item_ids[:5])
    # Filter out seen items
    unseen_top_n_item_ids = [item for item in top_n_item_ids if item not in seen_items]
    # print(unseen_top_n_item_ids[:n])
    return unseen_top_n_item_ids[:n]

In [22]:
item_texts

['title: Godfather, The (1972) [SEP] genres: Action|Crime|Drama',
 "title: Babe: Pig in the City (1998) [SEP] genres: Children's|Comedy",
 'title: Silence of the Lambs, The (1991) [SEP] genres: Drama|Thriller',
 'title: Rain Man (1988) [SEP] genres: Drama',
 'title: Seven Samurai (The Magnificent Seven) (Shichinin no samurai) (1954) [SEP] genres: Action|Drama',
 'title: Walkabout (1971) [SEP] genres: Drama',
 'title: Burnt By the Sun (Utomlyonnye solntsem) (1994) [SEP] genres: Drama',
 'title: Places in the Heart (1984) [SEP] genres: Drama',
 'title: Ciao, Professore! (Io speriamo che me la cavo ) (1993) [SEP] genres: Drama',
 'title: No Way Out (1987) [SEP] genres: Thriller',
 'title: My Life in Pink (Ma vie en rose) (1997) [SEP] genres: Comedy|Drama',
 "title: Wizard of Oz, The (1939) [SEP] genres: Adventure|Children's|Drama|Musical",
 'title: Casablanca (1942) [SEP] genres: Drama|Romance|War',
 'title: Apple, The (Sib) (1998) [SEP] genres: Drama',
 "title: Schindler's List (1993) [SEP] genres: Drama|War",
 'title: Chinatown (1974) [SEP] genres: Film-Noir|Mystery|Thriller',
 'title: Cold Fever (Á köldum klaka) (1994) [SEP] genres: Comedy|Drama',
 'title: Shawshank Redemption, The (1994) [SEP] genres: Drama',
 'title: Not One Less (Yi ge dou bu neng shao) (1999) [SEP] genres: Drama',
 'title: Maya Lin: A Strong Clear Vision (1994) [SEP] genres: Documentary',
 'title: American Beauty (1999) [SEP] genres: Comedy|Drama',
 'title: Fargo (1996) [SEP] genres: Crime|Drama|Thriller',
 'title: Shakespeare in Love (1998) [SEP] genres: Comedy|Romance',
 'title: Fast, Cheap & Out of Control (1997) [SEP] genres: Documentary',
 'title: Saving Private Ryan (1998) [SEP] genres: Action|Drama|War',
 'title: To Live (Huozhe) (1994) [SEP] genres: Drama',
 'title: Sixth Sense, The (1999) [SEP] genres: Thriller',
 "title: Babe (1995) [SEP] genres: Children's|Comedy|Drama",
 'title: Sense and Sensibility (1995) [SEP] genres: Drama|Romance',
 'title: Hoop Dreams (1994) [SEP] genres: Documentary',
 'title: Run Lola Run (Lola rennt) (1998) [SEP] genres: Action|Crime|Romance',
 'title: L.A. Confidential (1997) [SEP] genres: Crime|Film-Noir|Mystery|Thriller',
 'title: Quiz Show (1994) [SEP] genres: Drama',
 'title: Citizen Ruth (1996) [SEP] genres: Comedy|Drama',
 "title: Microcosmos (Microcosmos: Le peuple de l'herbe) (1996) [SEP] genres: Documentary",
 'title: Apollo 13 (1995) [SEP] genres: Drama',
 'title: Welcome to the Dollhouse (1995) [SEP] genres: Comedy|Drama',
 'title: Thirty-Two Short Films About Glenn Gould (1993) [SEP] genres: Documentary',
 'title: Shall We Dance? (Shall We Dansu?) (1996) [SEP] genres: Comedy',
 'title: Fearless (1993) [SEP] genres: Drama',
 'title: Bound (1996) [SEP] genres: Crime|Drama|Romance|Thriller',
 'title: Pillow Book, The (1995) [SEP] genres: Drama|Romance',
 'title: Like Water for Chocolate (Como agua para chocolate) (1992) [SEP] genres: Drama|Romance',
 'title: Life Is Beautiful (La Vita è bella) (1997) [SEP] genres: Comedy|Drama',
 'title: Sling Blade (1996) [SEP] genres: Drama|Thriller',
 'title: Ed Wood (1994) [SEP] genres: Comedy|Drama',
 'title: Heavenly Creatures (1994) [SEP] genres: Drama|Fantasy|Romance|Thriller',
 'title: Farewell My Concubine (1993) [SEP] genres: Drama|Romance',
 'title: Good Will Hunting (1997) [SEP] genres: Drama',
 'title: Crying Game, The (1992) [SEP] genres: Drama|Romance|War',
 'title: Usual Suspects, The (1995) [SEP] genres: Crime|Thriller',
 'title: To Die For (1995) [SEP] genres: Comedy|Drama',
 'title: Crumb (1994) [SEP] genres: Documentary',
 'title: Bullets Over Broadway (1994) [SEP] genres: Comedy',
 'title: Philadelphia (1993) [SEP] genres: Drama',
 'title: Terminator 2: Judgment Day (1991) [SEP] genres: Action|Sci-Fi|Thriller',
 'title: Reservoir Dogs (1992) [SEP] genres: Crime|Thriller',
 'title: Postino, Il (The Postman) (1994) [SEP] genres: Drama|Romance',
 'title: Go (1999) [SEP] genres: Crime',
 'title: Apostle, The (1997) [SEP] genres: Drama',
 'title: Spanish Prisoner, The (1997) [SEP] genres: Drama|Thriller',
 'title: Simple Plan, A (1998) [SEP] genres: Crime|Thriller',
 'title: Taxi Driver (1976) [SEP] genres: Drama|Thriller',
 'title: Nell (1994) [SEP] genres: Drama',
 'title: Once Were Warriors (1994) [SEP] genres: Crime|Drama',
 'title: Doctor Zhivago (1965) [SEP] genres: Drama|Romance|War',
 'title: Full Monty, The (1997) [SEP] genres: Comedy',
 'title: Four Weddings and a Funeral (1994) [SEP] genres: Comedy|Romance',
 'title: Annie Hall (1977) [SEP] genres: Comedy|Romance',
 'title: Notorious (1946) [SEP] genres: Film-Noir|Romance|Thriller',
 'title: My Man Godfrey (1936) [SEP] genres: Comedy',
 'title: Harvey (1950) [SEP] genres: Comedy',
 'title: General, The (1927) [SEP] genres: Comedy',
 'title: Go West (1925) [SEP] genres: Comedy',
 'title: M*A*S*H (1970) [SEP] genres: Comedy|War',
 'title: Christmas Story, A (1983) [SEP] genres: Comedy|Drama',
 'title: Animal House (1978) [SEP] genres: Comedy',
 'title: Arsenic and Old Lace (1944) [SEP] genres: Comedy|Mystery|Thriller',
 'title: Manhattan (1979) [SEP] genres: Comedy|Drama|Romance',
 'title: Bringing Up Baby (1938) [SEP] genres: Comedy',
 'title: Cool Hand Luke (1967) [SEP] genres: Comedy|Drama',
 "title: Midsummer Night's Dream, A (1999) [SEP] genres: Comedy|Fantasy",
 'title: Airplane! (1980) [SEP] genres: Comedy',
 'title: Producers, The (1968) [SEP] genres: Comedy|Musical',
 "title: Mary Poppins (1964) [SEP] genres: Children's|Comedy|Musical",
 'title: Princess Bride, The (1987) [SEP] genres: Action|Adventure|Comedy|Romance',
 "title: Hard Day's Night, A (1964) [SEP] genres: Comedy|Musical",
 'title: Auntie Mame (1958) [SEP] genres: Comedy|Drama',
 'title: Wings of Desire (Der Himmel über Berlin) (1987) [SEP] genres: Comedy|Drama|Romance',
 'title: Grand Day Out, A (1992) [SEP] genres: Animation|Comedy',
 'title: His Girl Friday (1940) [SEP] genres: Comedy',
 'title: To Catch a Thief (1955) [SEP] genres: Comedy|Romance|Thriller',
 'title: Moonstruck (1987) [SEP] genres: Comedy',
 'title: Shall We Dance? (1937) [SEP] genres: Comedy|Musical|Romance',
 'title: Gay Divorcee, The (1934) [SEP] genres: Comedy|Musical|Romance',
 'title: Band Wagon, The (1953) [SEP] genres: Comedy|Musical',
 'title: Butch Cassidy and the Sundance Kid (1969) [SEP] genres: Action|Comedy|Western',
 'title: Notting Hill (1999) [SEP] genres: Comedy|Romance',
 'title: Galaxy Quest (1999) [SEP] genres: Adventure|Comedy|Sci-Fi',
 'title: American Graffiti (1973) [SEP] genres: Comedy|Drama',
 "title: Pollyanna (1960) [SEP] genres: Children's|Comedy|Drama",
 'title: Bananas (1971) [SEP] genres: Comedy|War',
 'title: Mister Roberts (1955) [SEP] genres: Comedy|Drama|War',
 'title: Back to the Future (1985) [SEP] genres: Comedy|Sci-Fi',
 'title: Groundhog Day (1993) [SEP] genres: Comedy|Romance',
 'title: Apartment, The (1960) [SEP] genres: Comedy|Drama',
 "title: Muppet Movie, The (1979) [SEP] genres: Children's|Comedy",
 'title: Charade (1963) [SEP] genres: Comedy|Mystery|Romance|Thriller',
 "title: You Can't Take It With You (1938) [SEP] genres: Comedy",
 'title: Beetlejuice (1988) [SEP] genres: Comedy|Fantasy',
 'title: Top Hat (1935) [SEP] genres: Comedy|Musical|Romance',
 'title: Little Shop of Horrors (1986) [SEP] genres: Comedy|Horror|Musical',
 'title: Around the World in 80 Days (1956) [SEP] genres: Adventure|Comedy',
 'title: Little Big Man (1970) [SEP] genres: Comedy|Drama|Western',
 'title: Strictly Ballroom (1992) [SEP] genres: Comedy|Romance',
 'title: Hudsucker Proxy, The (1994) [SEP] genres: Comedy|Romance',
 'title: Player, The (1992) [SEP] genres: Comedy|Drama',
 'title: Roman Holiday (1953) [SEP] genres: Comedy|Romance',
 'title: Return of the Pink Panther, The (1974) [SEP] genres: Comedy',
 'title: Sabrina (1954) [SEP] genres: Comedy|Romance',
 'title: Taming of the Shrew, The (1967) [SEP] genres: Comedy',
 'title: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963) [SEP] genres: Sci-Fi|War',
 'title: Star Wars: Episode IV - A New Hope (1977) [SEP] genres: Action|Adventure|Fantasy|Sci-Fi',
 'title: Close Encounters of the Third Kind (1977) [SEP] genres: Drama|Sci-Fi',
 "title: E.T. the Extra-Terrestrial (1982) [SEP] genres: Children's|Drama|Fantasy|Sci-Fi",
 'title: 2001: A Space Odyssey (1968) [SEP] genres: Drama|Mystery|Sci-Fi|Thriller',
 'title: Star Wars: Episode VI - Return of the Jedi (1983) [SEP] genres: Action|Adventure|Romance|Sci-Fi|War',
 'title: Cabaret (1972) [SEP] genres: Musical|War',
 "title: Peter Pan (1953) [SEP] genres: Animation|Children's|Fantasy|Musical",
 'title: My Fair Lady (1964) [SEP] genres: Musical|Romance',
 'title: King and I, The (1956) [SEP] genres: Musical',
 'title: American in Paris, An (1951) [SEP] genres: Musical|Romance',
 "title: Singin' in the Rain (1952) [SEP] genres: Musical|Romance",
 'title: Meet Me in St. Louis (1944) [SEP] genres: Musical',
 "title: Fantasia (1940) [SEP] genres: Animation|Children's|Musical",
 "title: Cinderella (1950) [SEP] genres: Animation|Children's|Musical",
 'title: Guys and Dolls (1955) [SEP] genres: Musical',
 "title: Lion King, The (1994) [SEP] genres: Animation|Children's|Musical",
 'title: Inspector General, The (1949) [SEP] genres: Musical',
 'title: West Side Story (1961) [SEP] genres: Musical|Romance',
 "title: Aladdin (1992) [SEP] genres: Animation|Children's|Comedy|Musical",
 'title: Oliver! (1968) [SEP] genres: Musical',
 'title: Grease (1978) [SEP] genres: Comedy|Musical|Romance',
 'title: Yellow Submarine (1968) [SEP] genres: Animation|Musical',
 "title: Muppet Treasure Island (1996) [SEP] genres: Adventure|Children's|Comedy|Musical",
 'title: Blues Brothers, The (1980) [SEP] genres: Action|Comedy|Musical',
 'title: Help! (1965) [SEP] genres: Comedy|Musical',
 'title: Victor/Victoria (1982) [SEP] genres: Comedy|Musical',
 "title: Muppet Christmas Carol, The (1992) [SEP] genres: Children's|Musical",
 'title: Gigi (1958) [SEP] genres: Musical',
 "title: Sleeping Beauty (1959) [SEP] genres: Animation|Children's|Musical",
 "title: James and the Giant Peach (1996) [SEP] genres: Animation|Children's|Musical",
 'title: Dirty Dancing (1987) [SEP] genres: Musical|Romance',
 'title: Funny Face (1957) [SEP] genres: Comedy|Musical',
 "title: Hunchback of Notre Dame, The (1996) [SEP] genres: Animation|Children's|Musical",
 "title: Lady and the Tramp (1955) [SEP] genres: Animation|Children's|Comedy|Musical|Romance",
 'title: Great Race, The (1965) [SEP] genres: Comedy|Musical',
 'title: Evita (1996) [SEP] genres: Drama|Musical',
 'title: Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les) (1964) [SEP] genres: Drama|Musical',
 "title: Pocahontas (1995) [SEP] genres: Animation|Children's|Musical|Romance",
 'title: Big Sleep, The (1946) [SEP] genres: Film-Noir|Mystery',
 'title: Rear Window (1954) [SEP] genres: Mystery|Thriller',
 'title: Maltese Falcon, The (1941) [SEP] genres: Film-Noir|Mystery',
 'title: Vertigo (1958) [SEP] genres: Mystery|Thriller',
 'title: Third Man, The (1949) [SEP] genres: Mystery|Thriller',
 'title: Dial M for Murder (1954) [SEP] genres: Mystery|Thriller',
 'title: Klute (1971) [SEP] genres: Drama|Mystery',
 'title: Suspicion (1941) [SEP] genres: Mystery|Thriller',
 'title: Thin Man, The (1934) [SEP] genres: Mystery',
 'title: Lady Vanishes, The (1938) [SEP] genres: Comedy|Mystery|Romance|Thriller',
 'title: Gaslight (1944) [SEP] genres: Mystery|Thriller',
 'title: Laura (1944) [SEP] genres: Crime|Film-Noir|Mystery',
 'title: Young Sherlock Holmes (1985) [SEP] genres: Action|Adventure|Mystery',
 'title: Sliding Doors (1998) [SEP] genres: Drama|Romance',
 'title: All About Eve (1950) [SEP] genres: Drama',
 'title: Seventh Seal, The (Sjunde inseglet, Det) (1957) [SEP] genres: Drama',
 'title: Citizen Kane (1941) [SEP] genres: Drama',
 'title: Gone with the Wind (1939) [SEP] genres: Drama|Romance|War',
 "title: St. Elmo's Fire (1985) [SEP] genres: Drama|Romance",
 'title: Jaws (1975) [SEP] genres: Action|Horror',
 'title: Forrest Gump (1994) [SEP] genres: Comedy|Romance|War',
 'title: Fish Called Wanda, A (1988) [SEP] genres: Comedy',
 'title: Wrong Trousers, The (1993) [SEP] genres: Animation|Comedy',
 'title: Ghostbusters (1984) [SEP] genres: Comedy|Horror',
 'title: Eat Drink Man Woman (1994) [SEP] genres: Comedy|Drama',
 'title: Monty Python and the Holy Grail (1974) [SEP] genres: Comedy',
 'title: Godzilla (1998) [SEP] genres: Action|Sci-Fi',
 'title: Faces (1968) [SEP] genres: Drama',
 'title: Manchurian Candidate, The (1962) [SEP] genres: Film-Noir|Thriller',
 'title: Outlaw Josey Wales, The (1976) [SEP] genres: Western',
 'title: Cider House Rules, The (1999) [SEP] genres: Drama',
 'title: Godfather: Part II, The (1974) [SEP] genres: Action|Crime|Drama',
 'title: Diner (1982) [SEP] genres: Comedy|Drama',
 "title: One Flew Over the Cuckoo's Nest (1975) [SEP] genres: Drama",
 "title: Who's Afraid of Virginia Woolf? (1966) [SEP] genres: Drama",
 'title: Bridge on the River Kwai, The (1957) [SEP] genres: Drama|War',
 'title: Insider, The (1999) [SEP] genres: Drama',
 'title: North by Northwest (1959) [SEP] genres: Drama|Thriller',
 'title: Stalag 17 (1953) [SEP] genres: Drama|War',
 'title: Killing Fields, The (1984) [SEP] genres: Drama|War',
 'title: Amadeus (1984) [SEP] genres: Drama',
 'title: To Kill a Mockingbird (1962) [SEP] genres: Drama',
 'title: Inherit the Wind (1960) [SEP] genres: Drama',
 'title: Titanic (1997) [SEP] genres: Drama|Romance',
 'title: Faculty, The (1998) [SEP] genres: Horror|Sci-Fi',
 'title: View to a Kill, A (1985) [SEP] genres: Action',
 'title: Bulworth (1998) [SEP] genres: Comedy',
 "title: Teenage Mutant Ninja Turtles (1990) [SEP] genres: Action|Children's|Fantasy",
 'title: On the Waterfront (1954) [SEP] genres: Crime|Drama',
 'title: Hustler, The (1961) [SEP] genres: Drama',
 'title: Spartacus (1960) [SEP] genres: Drama',
 'title: Right Stuff, The (1983) [SEP] genres: Drama',
 'title: Breaking Away (1979) [SEP] genres: Drama',
 'title: Lost Weekend, The (1945) [SEP] genres: Drama',
 'title: Man for All Seasons, A (1966) [SEP] genres: Drama',
 'title: Arachnophobia (1990) [SEP] genres: Action|Comedy|Sci-Fi|Thriller',
 'title: 13th Warrior, The (1999) [SEP] genres: Action|Horror|Thriller',
 "title: Astronaut's Wife, The (1999) [SEP] genres: Sci-Fi|Thriller",
 'title: 20 Dates (1998) [SEP] genres: Comedy',
 'title: American Pie (1999) [SEP] genres: Comedy',
 'title: Austin Powers: The Spy Who Shagged Me (1999) [SEP] genres: Comedy',
 'title: Arlington Road (1999) [SEP] genres: Thriller',
 'title: 10 Things I Hate About You (1999) [SEP] genres: Comedy|Romance',
 'title: Dog Day Afternoon (1975) [SEP] genres: Comedy|Crime|Drama',
 'title: Network (1976) [SEP] genres: Comedy|Drama',
 'title: 12 Angry Men (1957) [SEP] genres: Drama',
 'title: October Sky (1999) [SEP] genres: Drama',
 'title: Baby Geniuses (1999) [SEP] genres: Comedy',
 'title: Blair Witch Project, The (1999) [SEP] genres: Horror',
 'title: Bowfinger (1999) [SEP] genres: Comedy',
 'title: Beach, The (2000) [SEP] genres: Adventure|Drama',
 'title: Big Daddy (1999) [SEP] genres: Comedy',
 'title: Best Man, The (1999) [SEP] genres: Drama',
 'title: Bone Collector, The (1999) [SEP] genres: Thriller',
 'title: Being John Malkovich (1999) [SEP] genres: Comedy',
 'title: Best Laid Plans (1999) [SEP] genres: Crime|Drama',
 'title: Cutting Edge, The (1992) [SEP] genres: Drama',
 'title: Boat, The (Das Boot) (1981) [SEP] genres: Action|Drama|War',
 'title: Splendor in the Grass (1961) [SEP] genres: Drama',
 'title: Brokedown Palace (1999) [SEP] genres: Drama',
 'title: Civil Action, A (1998) [SEP] genres: Drama',
 "title: Cat from Outer Space, The (1978) [SEP] genres: Children's|Comedy|Sci-Fi",
 'title: Clan of the Cave Bear, The (1986) [SEP] genres: Drama',
 'title: Clerks (1994) [SEP] genres: Comedy',
 'title: Creepshow (1982) [SEP] genres: Horror',
 'title: Verdict, The (1982) [SEP] genres: Drama',
 'title: Grapes of Wrath, The (1940) [SEP] genres: Drama',
 'title: Apocalypse Now (1979) [SEP] genres: Drama|War',
 'title: Three Kings (1999) [SEP] genres: Drama|War',
 'title: Gandhi (1982) [SEP] genres: Drama',
 'title: Hamlet (1948) [SEP] genres: Drama',
 'title: Year of Living Dangerously (1982) [SEP] genres: Drama|Romance',
 "title: Gentleman's Agreement (1947) [SEP] genres: Drama",
 'title: Doctor Dolittle (1998) [SEP] genres: Comedy',
 'title: Deep End of the Ocean, The (1999) [SEP] genres: Drama',
 'title: Cruel Intentions (1999) [SEP] genres: Drama',
 'title: Double Jeopardy (1999) [SEP] genres: Action|Thriller',
 'title: Doors, The (1991) [SEP] genres: Drama|Musical',
 'title: Dick (1999) [SEP] genres: Comedy',
 'title: Desert Blue (1999) [SEP] genres: Drama',
 'title: Detroit Rock City (1999) [SEP] genres: Comedy',
 'title: Deep Blue Sea (1999) [SEP] genres: Action|Sci-Fi|Thriller',
 'title: Dead Calm (1989) [SEP] genres: Thriller',
 "title: Dudley Do-Right (1999) [SEP] genres: Children's|Comedy",
 'title: End of Days (1999) [SEP] genres: Action|Thriller',
 'title: Elizabeth (1998) [SEP] genres: Drama',
 'title: Entrapment (1999) [SEP] genres: Crime|Thriller',
 'title: Election (1999) [SEP] genres: Comedy',
 'title: Dreamlife of Angels, The (La Vie rêvée des anges) (1998) [SEP] genres: Drama',
 'title: Down in the Delta (1998) [SEP] genres: Drama',
 'title: Erin Brockovich (2000) [SEP] genres: Drama',
 'title: Anywhere But Here (1999) [SEP] genres: Drama',
 'title: Hud (1963) [SEP] genres: Drama|Western',
 'title: Stand by Me (1986) [SEP] genres: Adventure|Comedy|Drama',
 'title: GoodFellas (1990) [SEP] genres: Crime|Drama',
 'title: Eyes Wide Shut (1999) [SEP] genres: Drama',
 "title: Fantasia 2000 (1999) [SEP] genres: Animation|Children's|Musical",
 'title: Frances (1982) [SEP] genres: Drama',
 'title: Best Years of Our Lives, The (1946) [SEP] genres: Drama|War',
 'title: Parenthood (1989) [SEP] genres: Comedy|Drama',
 'title: In the Heat of the Night (1967) [SEP] genres: Drama|Mystery',
 'title: Midnight Cowboy (1969) [SEP] genres: Drama',
 'title: Instinct (1999) [SEP] genres: Drama|Thriller',
 'title: In the Mouth of Madness (1995) [SEP] genres: Horror|Thriller',
 'title: Ideal Husband, An (1999) [SEP] genres: Comedy',
 'title: House on Haunted Hill, The (1999) [SEP] genres: Horror',
 'title: Gods and Monsters (1998) [SEP] genres: Drama',
 'title: Happiness (1998) [SEP] genres: Comedy',
 'title: Haunting, The (1999) [SEP] genres: Horror|Thriller',
 'title: Last Picture Show, The (1971) [SEP] genres: Drama',
 'title: Of Human Bondage (1934) [SEP] genres: Drama',
 'title: This Is Spinal Tap (1984) [SEP] genres: Comedy|Drama|Musical',
 'title: Nashville (1975) [SEP] genres: Drama|Musical',
 'title: Love Letter, The (1999) [SEP] genres: Comedy|Romance',
 'title: Jakob the Liar (1999) [SEP] genres: Drama',
 'title: Magnolia (1999) [SEP] genres: Drama',
 'title: Lake Placid (1999) [SEP] genres: Horror|Thriller',
 'title: Last Night (1998) [SEP] genres: Thriller',
 'title: Jack Frost (1998) [SEP] genres: Comedy|Drama',
 'title: Little Voice (1998) [SEP] genres: Comedy',
 'title: Kingpin (1996) [SEP] genres: Comedy',
 'title: Witness (1985) [SEP] genres: Drama|Romance|Thriller',
 'title: Green Mile, The (1999) [SEP] genres: Drama|Thriller',
 'title: French Connection, The (1971) [SEP] genres: Action|Crime|Drama|Thriller',
 'title: Seven Beauties (Pasqualino Settebellezze) (1976) [SEP] genres: Comedy|Drama',
 'title: Mission to Mars (2000) [SEP] genres: Sci-Fi',
 'title: Mickey Blue Eyes (1999) [SEP] genres: Comedy|Romance',
 'title: Mosquito Coast, The (1986) [SEP] genres: Drama',
 'title: Monkey Shines (1988) [SEP] genres: Horror|Sci-Fi',
 'title: Messenger: The Story of Joan of Arc, The (1999) [SEP] genres: Drama|War',
 'title: On the Beach (1959) [SEP] genres: Drama',
 'title: East of Eden (1955) [SEP] genres: Drama',
 'title: Pulp Fiction (1994) [SEP] genres: Crime|Drama',
 'title: Affliction (1997) [SEP] genres: Drama',
 'title: Out of Africa (1985) [SEP] genres: Drama|Romance',

In [23]:
# Assuming full_items_embeddings is already defined
full_items_embeddings = torch.stack([best_model.item_model.encode(item_text, convert_to_tensor=True) for item_text in item_texts]).to(device)

## Type 0

In [26]:
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count

def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0

def evaluate_user_cf_model(model, test_data, train_data, val_data, all_items, k):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values

        y_score = [1 if item in test_items else 0 for item in recommended_items]

        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
        'Recall@{}'.format(k): avg_recall,
        'MRR@{}'.format(k): avg_mrr,
    }

all_items = movies['item_id'].unique()
# Evaluate the model
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_30872\183069761.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.6365923710611281, 'Recall@5': 0.0018854956498022657, 'MRR@5': 0.014489514348785874}
{'NDCG@10': 0.48542765700096663, 'Recall@10': 0.004081930479270502, 'MRR@10': 0.017798604541154207}

## Type 2

In [27]:
def evaluate_user_cf_model(model, test_data, train_data, val_data, all_items, k):
    ndcg_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values
        # print(user)
        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 2.5
            for item in recommended_items
        ]
        ndcg = ndcg_at_k(y_score, k)
        ndcg_scores.append(ndcg)

    avg_ndcg = np.nanmean(ndcg_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }

all_items = movies['item_id'].unique()
# Evaluate the model
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=10)
print(eval_result)

{'NDCG@5': 0.9979293080496994}
{'NDCG@10': 0.996027125675857}

## Type 3

In [28]:
def evaluate_user_cf_model(model, test_data, train_data, val_data, all_items, k):
    ndcg_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values

        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 0
            for item in recommended_items
        ]
        ndcg = ndcg_at_k(y_score, k)
        ndcg_scores.append(ndcg)

    avg_ndcg = np.nanmean(ndcg_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }

all_items = movies['item_id'].unique()

# Evaluate the model
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_30872\183069761.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.6337184640067162}
{'NDCG@10': 0.4830920780547607}

## Type 1

In [ ]:
def evaluate_user_cf_model(model, test_data, train_data, val_data, all_items, k):
    ndcg_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values
        print(user)
        # y_score = [
        #     user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 0
        #     for item in recommended_items
        # ]
        y_score = [
            1 if (item in test_items and user_test_data[user_test_data['item_id'] == item]['label'].values[0] == 1) else 0
            for item in recommended_items
        ]
        # y_score = [
        #     1 if (item in test_items and user_test_data[user_test_data['item'] == item]['label'].values[0] == 1) else 0
        #     for item in recommended_items
        # ]

        ndcg = ndcg_at_k(y_score, k)
        ndcg_scores.append(ndcg)

    avg_ndcg = np.nanmean(ndcg_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }

all_items = movies['item_id'].unique()
# Evaluate the model
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)